apiVersion: v1alpha1
kind: HostnameConfig
auto: "off"
hostname: sophons-alpha
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBVZk5u
        WFpCcTdzckR0eU5pTkhBeDVQaGRKZkJFMjF1aVpzT0tsbmZ6YzBRCno2ejY4VktU
        M01nLzN6eExDNktkMXhIcEhtcXBIL2xVdHdFVXZqS3ZOaDgKLS0tIDJvaGFBRHpD
        b2NkZnJDZVFXUUZMRGRUMFdOQk1vK091VmM3UTJvZndTeU0KS5IyicBZzhSyo0Pm
        r5I8oUaMizHkoQmC3RTKzaWefCNrJsl7/xlrtjY0WjxlOT5DzGL6fXAqqoglJ9zB
        cOVXMw==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5eVJQUHhvdnBwNS8wYWNT
        N1BEK2lBNUpPcUt6em5Fd0ZLY2pMZ2VoUlFRCnJKcll4dTZrV2ozWHBJbGNKanI2
        dmJveExjUkREVjJGZktvNjRaZmx5c28KLS0tIFQ0NVI1ejd6elI2NmVGSFVaWVAr
        WENwaE5PMzcrWFRBQndwenlyTld5dGcKHWsDzbF0aoQD7/mzMamnlI6HP2oHHpGx
        L0xW63vLTf3w2Qryvf9p6BwJD6shJV24PdMYCORN8S7riPETHa1VRA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-09-17T15:42:12Z"
  mac: ENC[AES256_GCM,data:bgRv+pSIArSnWTOZe1vpSO5GEnjv2WwQileI+aGaDwCI5ywxH3RqN5CiFP+FIb/JqU8Xwt+tXW8DKvFYr58Q5ftIIQfTTm3PZwC813idliPuzxS0SOreoTR7jQHl1zaaDa3o/R9Sc0FrAKXRkZ453AQeBxiZ8koZiN1C5dGRZg4=,iv:gkTa4jFk0LJ7RXPuM6JM8zRDij84eEt0lAj9VgHq/EE=,tag:Q/3F+80VheEKgzFMm0rm9Q==,type:str]
  version: 3.13.3
---
apiVersion: v1alpha1
kind: UnattendedInstallConfig
provisioning:
  diskSelector:
    match: disk.dev_path == "/dev/mmcblk0"
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBVZk5u
        WFpCcTdzckR0eU5pTkhBeDVQaGRKZkJFMjF1aVpzT0tsbmZ6YzBRCno2ejY4VktU
        M01nLzN6eExDNktkMXhIcEhtcXBIL2xVdHdFVXZqS3ZOaDgKLS0tIDJvaGFBRHpD
        b2NkZnJDZVFXUUZMRGRUMFdOQk1vK091VmM3UTJvZndTeU0KS5IyicBZzhSyo0Pm
        r5I8oUaMizHkoQmC3RTKzaWefCNrJsl7/xlrtjY0WjxlOT5DzGL6fXAqqoglJ9zB
        cOVXMw==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5eVJQUHhvdnBwNS8wYWNT
        N1BEK2lBNUpPcUt6em5Fd0ZLY2pMZ2VoUlFRCnJKcll4dTZrV2ozWHBJbGNKanI2
        dmJveExjUkREVjJGZktvNjRaZmx5c28KLS0tIFQ0NVI1ejd6elI2NmVGSFVaWVAr
        WENwaE5PMzcrWFRBQndwenlyTld5dGcKHWsDzbF0aoQD7/mzMamnlI6HP2oHHpGx
        L0xW63vLTf3w2Qryvf9p6BwJD6shJV24PdMYCORN8S7riPETHa1VRA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-09-17T15:42:12Z"
  mac: ENC[AES256_GCM,data:bgRv+pSIArSnWTOZe1vpSO5GEnjv2WwQileI+aGaDwCI5ywxH3RqN5CiFP+FIb/JqU8Xwt+tXW8DKvFYr58Q5ftIIQfTTm3PZwC813idliPuzxS0SOreoTR7jQHl1zaaDa3o/R9Sc0FrAKXRkZ453AQeBxiZ8koZiN1C5dGRZg4=,iv:gkTa4jFk0LJ7RXPuM6JM8zRDij84eEt0lAj9VgHq/EE=,tag:Q/3F+80VheEKgzFMm0rm9Q==,type:str]
  version: 3.13.3
---
apiVersion: v1alpha1
kind: KubeNodeConfig
labels:
  l2ad.metallb.sophons.cloud/internal-pools: "true"
  nwpolicy.sophons.cloud/dhcpv6: "true"
  egress.sophons.cloud/positron: "true"
  topology.kubernetes.io/region: ng
  topology.kubernetes.io/zone: ng-east-1
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBVZk5u
        WFpCcTdzckR0eU5pTkhBeDVQaGRKZkJFMjF1aVpzT0tsbmZ6YzBRCno2ejY4VktU
        M01nLzN6eExDNktkMXhIcEhtcXBIL2xVdHdFVXZqS3ZOaDgKLS0tIDJvaGFBRHpD
        b2NkZnJDZVFXUUZMRGRUMFdOQk1vK091VmM3UTJvZndTeU0KS5IyicBZzhSyo0Pm
        r5I8oUaMizHkoQmC3RTKzaWefCNrJsl7/xlrtjY0WjxlOT5DzGL6fXAqqoglJ9zB
        cOVXMw==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5eVJQUHhvdnBwNS8wYWNT
        N1BEK2lBNUpPcUt6em5Fd0ZLY2pMZ2VoUlFRCnJKcll4dTZrV2ozWHBJbGNKanI2
        dmJveExjUkREVjJGZktvNjRaZmx5c28KLS0tIFQ0NVI1ejd6elI2NmVGSFVaWVAr
        WENwaE5PMzcrWFRBQndwenlyTld5dGcKHWsDzbF0aoQD7/mzMamnlI6HP2oHHpGx
        L0xW63vLTf3w2Qryvf9p6BwJD6shJV24PdMYCORN8S7riPETHa1VRA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-09-17T15:42:12Z"
  mac: ENC[AES256_GCM,data:bgRv+pSIArSnWTOZe1vpSO5GEnjv2WwQileI+aGaDwCI5ywxH3RqN5CiFP+FIb/JqU8Xwt+tXW8DKvFYr58Q5ftIIQfTTm3PZwC813idliPuzxS0SOreoTR7jQHl1zaaDa3o/R9Sc0FrAKXRkZ453AQeBxiZ8koZiN1C5dGRZg4=,iv:gkTa4jFk0LJ7RXPuM6JM8zRDij84eEt0lAj9VgHq/EE=,tag:Q/3F+80VheEKgzFMm0rm9Q==,type:str]
  version: 3.13.3
---
# https://tailscale.com/docs/reference/best-practices/performance#linux-optimizations-for-subnet-routers-and-exit-nodes
apiVersion: v1alpha1
kind: EthernetConfig
name: end0
features:
  rx-gro-list: "off"
  rx-udp-gro-forwarding: "on"
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBVZk5u
        WFpCcTdzckR0eU5pTkhBeDVQaGRKZkJFMjF1aVpzT0tsbmZ6YzBRCno2ejY4VktU
        M01nLzN6eExDNktkMXhIcEhtcXBIL2xVdHdFVXZqS3ZOaDgKLS0tIDJvaGFBRHpD
        b2NkZnJDZVFXUUZMRGRUMFdOQk1vK091VmM3UTJvZndTeU0KS5IyicBZzhSyo0Pm
        r5I8oUaMizHkoQmC3RTKzaWefCNrJsl7/xlrtjY0WjxlOT5DzGL6fXAqqoglJ9zB
        cOVXMw==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5eVJQUHhvdnBwNS8wYWNT
        N1BEK2lBNUpPcUt6em5Fd0ZLY2pMZ2VoUlFRCnJKcll4dTZrV2ozWHBJbGNKanI2
        dmJveExjUkREVjJGZktvNjRaZmx5c28KLS0tIFQ0NVI1ejd6elI2NmVGSFVaWVAr
        WENwaE5PMzcrWFRBQndwenlyTld5dGcKHWsDzbF0aoQD7/mzMamnlI6HP2oHHpGx
        L0xW63vLTf3w2Qryvf9p6BwJD6shJV24PdMYCORN8S7riPETHa1VRA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-09-17T15:42:12Z"
  mac: ENC[AES256_GCM,data:bgRv+pSIArSnWTOZe1vpSO5GEnjv2WwQileI+aGaDwCI5ywxH3RqN5CiFP+FIb/JqU8Xwt+tXW8DKvFYr58Q5ftIIQfTTm3PZwC813idliPuzxS0SOreoTR7jQHl1zaaDa3o/R9Sc0FrAKXRkZ453AQeBxiZ8koZiN1C5dGRZg4=,iv:gkTa4jFk0LJ7RXPuM6JM8zRDij84eEt0lAj9VgHq/EE=,tag:Q/3F+80VheEKgzFMm0rm9Q==,type:str]
  version: 3.13.3
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  diskSelector:
    match: '''/dev/disk/by-id/usb-SanDisk_Extreme_55AE_323530333653343035343633-0:0'' in disk.symlinks'
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBVZk5u
        WFpCcTdzckR0eU5pTkhBeDVQaGRKZkJFMjF1aVpzT0tsbmZ6YzBRCno2ejY4VktU
        M01nLzN6eExDNktkMXhIcEhtcXBIL2xVdHdFVXZqS3ZOaDgKLS0tIDJvaGFBRHpD
        b2NkZnJDZVFXUUZMRGRUMFdOQk1vK091VmM3UTJvZndTeU0KS5IyicBZzhSyo0Pm
        r5I8oUaMizHkoQmC3RTKzaWefCNrJsl7/xlrtjY0WjxlOT5DzGL6fXAqqoglJ9zB
        cOVXMw==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5eVJQUHhvdnBwNS8wYWNT
        N1BEK2lBNUpPcUt6em5Fd0ZLY2pMZ2VoUlFRCnJKcll4dTZrV2ozWHBJbGNKanI2
        dmJveExjUkREVjJGZktvNjRaZmx5c28KLS0tIFQ0NVI1ejd6elI2NmVGSFVaWVAr
        WENwaE5PMzcrWFRBQndwenlyTld5dGcKHWsDzbF0aoQD7/mzMamnlI6HP2oHHpGx
        L0xW63vLTf3w2Qryvf9p6BwJD6shJV24PdMYCORN8S7riPETHa1VRA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-09-17T15:42:12Z"
  mac: ENC[AES256_GCM,data:bgRv+pSIArSnWTOZe1vpSO5GEnjv2WwQileI+aGaDwCI5ywxH3RqN5CiFP+FIb/JqU8Xwt+tXW8DKvFYr58Q5ftIIQfTTm3PZwC813idliPuzxS0SOreoTR7jQHl1zaaDa3o/R9Sc0FrAKXRkZ453AQeBxiZ8koZiN1C5dGRZg4=,iv:gkTa4jFk0LJ7RXPuM6JM8zRDij84eEt0lAj9VgHq/EE=,tag:Q/3F+80VheEKgzFMm0rm9Q==,type:str]
  version: 3.13.3
---
apiVersion: v1alpha1
kind: VLANConfig
name: end0.42
vlanID: 42
parent: end0
addresses:
  - address: 10.42.69.4/16
routes:
  - gateway: 10.42.0.1
# ---
# apiVersion: v1alpha1
# kind: DHCPv6Config
# name: end0.42
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBVZk5u
        WFpCcTdzckR0eU5pTkhBeDVQaGRKZkJFMjF1aVpzT0tsbmZ6YzBRCno2ejY4VktU
        M01nLzN6eExDNktkMXhIcEhtcXBIL2xVdHdFVXZqS3ZOaDgKLS0tIDJvaGFBRHpD
        b2NkZnJDZVFXUUZMRGRUMFdOQk1vK091VmM3UTJvZndTeU0KS5IyicBZzhSyo0Pm
        r5I8oUaMizHkoQmC3RTKzaWefCNrJsl7/xlrtjY0WjxlOT5DzGL6fXAqqoglJ9zB
        cOVXMw==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5eVJQUHhvdnBwNS8wYWNT
        N1BEK2lBNUpPcUt6em5Fd0ZLY2pMZ2VoUlFRCnJKcll4dTZrV2ozWHBJbGNKanI2
        dmJveExjUkREVjJGZktvNjRaZmx5c28KLS0tIFQ0NVI1ejd6elI2NmVGSFVaWVAr
        WENwaE5PMzcrWFRBQndwenlyTld5dGcKHWsDzbF0aoQD7/mzMamnlI6HP2oHHpGx
        L0xW63vLTf3w2Qryvf9p6BwJD6shJV24PdMYCORN8S7riPETHa1VRA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-09-17T15:42:12Z"
  mac: ENC[AES256_GCM,data:bgRv+pSIArSnWTOZe1vpSO5GEnjv2WwQileI+aGaDwCI5ywxH3RqN5CiFP+FIb/JqU8Xwt+tXW8DKvFYr58Q5ftIIQfTTm3PZwC813idliPuzxS0SOreoTR7jQHl1zaaDa3o/R9Sc0FrAKXRkZ453AQeBxiZ8koZiN1C5dGRZg4=,iv:gkTa4jFk0LJ7RXPuM6JM8zRDij84eEt0lAj9VgHq/EE=,tag:Q/3F+80VheEKgzFMm0rm9Q==,type:str]
  version: 3.13.3
