apiVersion: v1alpha1
kind: HostnameConfig
auto: "off"
hostname: sophons-caeneus
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBBeGQy
        R2VSdDJmK1AxcU9JOFU4ZFZyUy9hZlI4K2o3QlhmbmJ3NnRIMVJzClBRYXRQM3BI
        ZFZPS0dEMmpaVVp3aHFzSE9HOXo1STJ3VVNmSUF3R3JaZEEKLS0tIDB1SENEVjZS
        VHRnOHplWVdrclJXY2I5SkJqVDRaemNXSjQ2R3FUeTBGOEUKuSBHShEjhTPavre2
        vyhyvpM6D23FPTiyPn946QYdDhNlXEqnyhEDx+yQvhLAeVGubhJyYmuCzT4SzMc/
        eVhIXw==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTzNWblB4MGVBTmhKRHVa
        U0Qyakc5bWZ0cnk0N0Nzd1VrYkdVaTlEbUdZCmhZSTVHTUVvQU5Ic1NFTFlMd1JO
        QUdocnNoRHhodmM1R1hFU3pkZEltUmsKLS0tIDdYWUlIUC9UVEdLa29jRWJ6aUdr
        aEo1dHhhckpDUnl4dXJMLy8xMW5BUkEK0BllY94Ys/5OR9FFLXC3Edp0TEgdqJmh
        l9CO8rRBz5Q+hocDMmJlSswRHPFYC522eJCu2QMpqrCmPQ8DXizcAw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-09-17T15:42:13Z"
  mac: ENC[AES256_GCM,data:wtPd1IKMrt257+sV7T+6iG4v7D7SIXyCDClwbLt3vJBDbRSf4fwFJtghE2D1NdAhApJNO7+gY3+AkIiOvlNgfNhePFk3wAial55RQrckz+9jhVAs9qw3RHCfMhxAKe4EOhTHyK/LbnKwDbGpobsh6lujwMlXXcRZ+fZRMUiFbIE=,iv:a/424oU4LS0eG7m3NOs5gAoiMgTBegsNtclufSi+PZQ=,tag:YjELRXiR+Ue2sVqBHlZcxQ==,type:str]
  version: 3.13.3
---
machine:
  kubelet:
    extraMounts:
      - destination: /var/lib/garage/backup/big-boi
        type: bind
        source: /var/lib/garage/backup/big-boi
        options:
          - bind
          - rshared
          - rw
      - destination: /var/lib/garage/backup/less-big-boi
        type: bind
        source: /var/lib/garage/backup/less-big-boi
        options:
          - bind
          - rshared
          - rw
      - destination: /mnt/less-big-boi/media
        type: bind
        source: /mnt/less-big-boi/media
        options:
          - bind
          - rshared
          - rw
      - destination: /mnt/big-boi/time-machine
        type: bind
        source: /mnt/big-boi/time-machine
        options:
          - bind
          - rshared
          - rw
      - destination: /mnt/big-boi/everything-else
        type: bind
        source: /mnt/big-boi/everything-else
        options:
          - bind
          - rshared
          - rw
    extraConfig:
      mergeDefaultEvictionSettings: true
      evictionHard:
        nodefs.available: 0%
        nodefs.inodesFree: 0%
      # kubelet doesn't use cgroups to apply limits, so, hacks!
      systemReserved:
        ephemeral-storage: 1.5Ti
        cpu: 18000m
        memory: 80Gi
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBBeGQy
        R2VSdDJmK1AxcU9JOFU4ZFZyUy9hZlI4K2o3QlhmbmJ3NnRIMVJzClBRYXRQM3BI
        ZFZPS0dEMmpaVVp3aHFzSE9HOXo1STJ3VVNmSUF3R3JaZEEKLS0tIDB1SENEVjZS
        VHRnOHplWVdrclJXY2I5SkJqVDRaemNXSjQ2R3FUeTBGOEUKuSBHShEjhTPavre2
        vyhyvpM6D23FPTiyPn946QYdDhNlXEqnyhEDx+yQvhLAeVGubhJyYmuCzT4SzMc/
        eVhIXw==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTzNWblB4MGVBTmhKRHVa
        U0Qyakc5bWZ0cnk0N0Nzd1VrYkdVaTlEbUdZCmhZSTVHTUVvQU5Ic1NFTFlMd1JO
        QUdocnNoRHhodmM1R1hFU3pkZEltUmsKLS0tIDdYWUlIUC9UVEdLa29jRWJ6aUdr
        aEo1dHhhckpDUnl4dXJMLy8xMW5BUkEK0BllY94Ys/5OR9FFLXC3Edp0TEgdqJmh
        l9CO8rRBz5Q+hocDMmJlSswRHPFYC522eJCu2QMpqrCmPQ8DXizcAw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-09-17T15:42:13Z"
  mac: ENC[AES256_GCM,data:wtPd1IKMrt257+sV7T+6iG4v7D7SIXyCDClwbLt3vJBDbRSf4fwFJtghE2D1NdAhApJNO7+gY3+AkIiOvlNgfNhePFk3wAial55RQrckz+9jhVAs9qw3RHCfMhxAKe4EOhTHyK/LbnKwDbGpobsh6lujwMlXXcRZ+fZRMUiFbIE=,iv:a/424oU4LS0eG7m3NOs5gAoiMgTBegsNtclufSi+PZQ=,tag:YjELRXiR+Ue2sVqBHlZcxQ==,type:str]
  version: 3.13.3
---
apiVersion: v1alpha1
kind: LinkConfig
name: eth0
addresses:
  - address: 10.42.42.5/16
    # - address: 10.42.42.55/16
routes:
  - gateway: 10.42.0.1
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBBeGQy
        R2VSdDJmK1AxcU9JOFU4ZFZyUy9hZlI4K2o3QlhmbmJ3NnRIMVJzClBRYXRQM3BI
        ZFZPS0dEMmpaVVp3aHFzSE9HOXo1STJ3VVNmSUF3R3JaZEEKLS0tIDB1SENEVjZS
        VHRnOHplWVdrclJXY2I5SkJqVDRaemNXSjQ2R3FUeTBGOEUKuSBHShEjhTPavre2
        vyhyvpM6D23FPTiyPn946QYdDhNlXEqnyhEDx+yQvhLAeVGubhJyYmuCzT4SzMc/
        eVhIXw==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTzNWblB4MGVBTmhKRHVa
        U0Qyakc5bWZ0cnk0N0Nzd1VrYkdVaTlEbUdZCmhZSTVHTUVvQU5Ic1NFTFlMd1JO
        QUdocnNoRHhodmM1R1hFU3pkZEltUmsKLS0tIDdYWUlIUC9UVEdLa29jRWJ6aUdr
        aEo1dHhhckpDUnl4dXJMLy8xMW5BUkEK0BllY94Ys/5OR9FFLXC3Edp0TEgdqJmh
        l9CO8rRBz5Q+hocDMmJlSswRHPFYC522eJCu2QMpqrCmPQ8DXizcAw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-09-17T15:42:13Z"
  mac: ENC[AES256_GCM,data:wtPd1IKMrt257+sV7T+6iG4v7D7SIXyCDClwbLt3vJBDbRSf4fwFJtghE2D1NdAhApJNO7+gY3+AkIiOvlNgfNhePFk3wAial55RQrckz+9jhVAs9qw3RHCfMhxAKe4EOhTHyK/LbnKwDbGpobsh6lujwMlXXcRZ+fZRMUiFbIE=,iv:a/424oU4LS0eG7m3NOs5gAoiMgTBegsNtclufSi+PZQ=,tag:YjELRXiR+Ue2sVqBHlZcxQ==,type:str]
  version: 3.13.3
---
apiVersion: v1alpha1
kind: KubeNodeConfig
labels:
  l2ad.metallb.sophons.cloud/internal-pools: "true"
  egress.sophons.cloud/positron: "true"
  topology.kubernetes.io/region: ng
  # TODO: fully merge all of NG into one zone
  topology.kubernetes.io/zone: ng-east-1
  hugeloads.sophons.cloud/longhorn: "false"
  hugeloads.sophons.cloud/postgres: "false"
taints:
  caeneus.sophons.cloud: :NoSchedule
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBBeGQy
        R2VSdDJmK1AxcU9JOFU4ZFZyUy9hZlI4K2o3QlhmbmJ3NnRIMVJzClBRYXRQM3BI
        ZFZPS0dEMmpaVVp3aHFzSE9HOXo1STJ3VVNmSUF3R3JaZEEKLS0tIDB1SENEVjZS
        VHRnOHplWVdrclJXY2I5SkJqVDRaemNXSjQ2R3FUeTBGOEUKuSBHShEjhTPavre2
        vyhyvpM6D23FPTiyPn946QYdDhNlXEqnyhEDx+yQvhLAeVGubhJyYmuCzT4SzMc/
        eVhIXw==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTzNWblB4MGVBTmhKRHVa
        U0Qyakc5bWZ0cnk0N0Nzd1VrYkdVaTlEbUdZCmhZSTVHTUVvQU5Ic1NFTFlMd1JO
        QUdocnNoRHhodmM1R1hFU3pkZEltUmsKLS0tIDdYWUlIUC9UVEdLa29jRWJ6aUdr
        aEo1dHhhckpDUnl4dXJMLy8xMW5BUkEK0BllY94Ys/5OR9FFLXC3Edp0TEgdqJmh
        l9CO8rRBz5Q+hocDMmJlSswRHPFYC522eJCu2QMpqrCmPQ8DXizcAw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-09-17T15:42:13Z"
  mac: ENC[AES256_GCM,data:wtPd1IKMrt257+sV7T+6iG4v7D7SIXyCDClwbLt3vJBDbRSf4fwFJtghE2D1NdAhApJNO7+gY3+AkIiOvlNgfNhePFk3wAial55RQrckz+9jhVAs9qw3RHCfMhxAKe4EOhTHyK/LbnKwDbGpobsh6lujwMlXXcRZ+fZRMUiFbIE=,iv:a/424oU4LS0eG7m3NOs5gAoiMgTBegsNtclufSi+PZQ=,tag:YjELRXiR+Ue2sVqBHlZcxQ==,type:str]
  version: 3.13.3
---
apiVersion: v1alpha1
kind: SysctlConfig
params:
  # 64MiB
  vm.min_free_kbytes: 65536
  vm.swappiness: 200
  vm.watermark_scale_factor: 100
  kernel.unprivileged_userns_clone: 1
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBBeGQy
        R2VSdDJmK1AxcU9JOFU4ZFZyUy9hZlI4K2o3QlhmbmJ3NnRIMVJzClBRYXRQM3BI
        ZFZPS0dEMmpaVVp3aHFzSE9HOXo1STJ3VVNmSUF3R3JaZEEKLS0tIDB1SENEVjZS
        VHRnOHplWVdrclJXY2I5SkJqVDRaemNXSjQ2R3FUeTBGOEUKuSBHShEjhTPavre2
        vyhyvpM6D23FPTiyPn946QYdDhNlXEqnyhEDx+yQvhLAeVGubhJyYmuCzT4SzMc/
        eVhIXw==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTzNWblB4MGVBTmhKRHVa
        U0Qyakc5bWZ0cnk0N0Nzd1VrYkdVaTlEbUdZCmhZSTVHTUVvQU5Ic1NFTFlMd1JO
        QUdocnNoRHhodmM1R1hFU3pkZEltUmsKLS0tIDdYWUlIUC9UVEdLa29jRWJ6aUdr
        aEo1dHhhckpDUnl4dXJMLy8xMW5BUkEK0BllY94Ys/5OR9FFLXC3Edp0TEgdqJmh
        l9CO8rRBz5Q+hocDMmJlSswRHPFYC522eJCu2QMpqrCmPQ8DXizcAw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-09-17T15:42:13Z"
  mac: ENC[AES256_GCM,data:wtPd1IKMrt257+sV7T+6iG4v7D7SIXyCDClwbLt3vJBDbRSf4fwFJtghE2D1NdAhApJNO7+gY3+AkIiOvlNgfNhePFk3wAial55RQrckz+9jhVAs9qw3RHCfMhxAKe4EOhTHyK/LbnKwDbGpobsh6lujwMlXXcRZ+fZRMUiFbIE=,iv:a/424oU4LS0eG7m3NOs5gAoiMgTBegsNtclufSi+PZQ=,tag:YjELRXiR+Ue2sVqBHlZcxQ==,type:str]
  version: 3.13.3
