cluster:
  etcd:
    # listenSubnets defaults to advertisedSubnets if not set explicitly
    # enc!
    advertisedSubnets:
      - ENC[AES256_GCM,data:sHC5qkNEAawzkA4hvpSG/zPR/pb1Pg==,iv:l7iVBJeQiGQ62P5yB4sTNzf/CJp4W8bb/uI+xBSVq0Y=,tag:OapirmSkQDwgOiFbhjfaxw==,type:str]
      - ENC[AES256_GCM,data:LGWURkEleJvDVcIYGtXaRfDb39g6ad/hY9Ur3wWXTwo1PlewUFW5Zj4m8T9Qhk9b+Bw=,iv:zxcSEfhqnHHPUsU4d7+K/+eiM7S9FmGNfjL9uNb3GB8=,tag:8FGauuRjtkVYK75O0QOReg==,type:comment]
      - ENC[AES256_GCM,data:MbiiB3LB6xCTW1utqtk=,iv:qrFxutcsB6wIVPEHwYQlMEQW8sfgYviawn1H54srd3A=,tag:C87sItUCAZWUXWMXvwfnuA==,type:comment]
      - ENC[AES256_GCM,data:si8zwhBM04N7C70lQCalURa3tYiYdg==,iv:xurugMTRgezodmuJpAdRXYCCf/QG0afNONN8gu87YAc=,tag:/mF6b9ZUfkE5psj4JtHLZQ==,type:str]
      - ENC[AES256_GCM,data:he9ZTQpWlwmqGybxhUU0DY0+9KoL,iv:lPe0pDVc0OK778heG5A175BBvlMuSY0OgeKl8HHelBQ=,tag:iBFIbh1qmErrV1Zfiszq+Q==,type:str]
    # enc!
    listenSubnets:
      - ENC[AES256_GCM,data:vC+cyeefwAkDdA+n69vF0wGIlw==,iv:K/WbLhlnEEQYeTCNWhgdVIrG6tivWpcoQ/vrils188A=,tag:e15PwKZdUh/gkTW2Mz9ifg==,type:str]
      - ENC[AES256_GCM,data:csz7b6x450pP053DAmkeGTdGo5Trgw==,iv:hXZGfYQZxcTnakDFwhj+Kh5pT/RjgjWkYgxHdrpQAf8=,tag:NKsxin0A1493gn44EUpsuw==,type:str]
      - ENC[AES256_GCM,data:fuQTb9UcZ/wOq6l04Hf6Y2Pd0MkCcvRq5dZk9kM1h6fLQPS7OojTVjzHlknVZzvOP8o=,iv:zkWHoiBTmR00A7jgxcZDSuPUbs5ScYE9EK1CoxElVeM=,tag:xkxsiHQUE+lrOrgjAoCHQg==,type:comment]
      - ENC[AES256_GCM,data:iwwhNap3Eicsf44CY1s=,iv:M76+4U7CDBlWOvWLSb1xr1xG3OAjAJhsIwbXiRjI61Y=,tag:SNG6YpYr5YD7zzrkDrlDAw==,type:comment]
      - ENC[AES256_GCM,data:Kq6h5yzGQewkC+5uPml749rZB23FCA==,iv:n8Vyu+PYgiuO3yo2Vv795LFfDXFP5tNb/0DVoQaNh+A=,tag:Sk2jSvOC87nQ8cCqfVOp8g==,type:str]
      - ENC[AES256_GCM,data:BfUuUmaemKNGmkJP7XlEodiBzNKW,iv:hO/cBYqGR9IRT5dLpYTcaHyzRhYxqkuF+mXtoNGWnI0=,tag:ssg2wY32sOdCjpFzMtCCZg==,type:str]
    extraArgs:
      heartbeat-interval: 5000
      election-timeout: 50000
      listen-metrics-urls: http://0.0.0.0:2381
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBVQXE2
        ZHNQVDBTNlJnQ0xPQnNrcCtGUC9IRVB2NXpWcHVuZG1MWlVIZHpzCkQwZUczRU41
        V0gwL0diRFZmUWFOUWJ1ekdpdkdVcHgrYnNMcnFodG5qMjAKLS0tIGdFRytxeFVM
        ZVpPSm9Pc1RBbGtsU3ZxYUtJVTJSNjRjOUREaHV4YWErSU0Kvf9oIpSocrnB+Gq+
        thjc+S3A1NdP/C3/+JlBp6QMuFLp/TZ/0nsXALmUKK+cZ/XsZ2Z5jzrdobgTBxy2
        pRqfUQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcXp1MktHN1d0bVVjMXdy
        a2lVbUhFdGt1NzBXbVlaMUxrdytvTVFIOUdRCmxFblBNRXVoc0pmbGxJTDhxVEY0
        K3hoL3ZhaDB0aUkvL3pLcDJHbVBTTDgKLS0tIGdTM2YwQXJUaFNMMElCelJUend5
        clFBR2cyYlNqRy9kNGtqbVNJU1U4YkEKDHi8B5Xe5XgKPXFAFcum2aAmGstWI3TB
        PfQH/Q4XNsac6GiVLNvCmE22VAepD+LsFoDfLsa79eIP93IRNOpUxA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-09-20T03:52:42Z"
  mac: ENC[AES256_GCM,data:edZGZAHCrdppAoRyFPyRrxTczuIw8o+7hLqDNMhSUsNbVduDVWG0Y6sTcpM/iR+wMc4b2goTGgytNgWSPumbdxL4MyH2tIfCNnMSc2p6oiSeva2AzsfxjX9Zv/x9kvxZj9YltBtx+A7++pif1eLHl4TzjddmQg+yzNb05ywPW2w=,iv:J6mXGsNrCACGgKXpTkhYDuiAwuOaxJit9VO3GjTa9L4=,tag:1lLb5t9mfLacle2gxbOCfQ==,type:str]
  version: 3.13.3
---
apiVersion: v1alpha1
kind: KubeProxyConfig
enabled: false
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBVQXE2
        ZHNQVDBTNlJnQ0xPQnNrcCtGUC9IRVB2NXpWcHVuZG1MWlVIZHpzCkQwZUczRU41
        V0gwL0diRFZmUWFOUWJ1ekdpdkdVcHgrYnNMcnFodG5qMjAKLS0tIGdFRytxeFVM
        ZVpPSm9Pc1RBbGtsU3ZxYUtJVTJSNjRjOUREaHV4YWErSU0Kvf9oIpSocrnB+Gq+
        thjc+S3A1NdP/C3/+JlBp6QMuFLp/TZ/0nsXALmUKK+cZ/XsZ2Z5jzrdobgTBxy2
        pRqfUQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcXp1MktHN1d0bVVjMXdy
        a2lVbUhFdGt1NzBXbVlaMUxrdytvTVFIOUdRCmxFblBNRXVoc0pmbGxJTDhxVEY0
        K3hoL3ZhaDB0aUkvL3pLcDJHbVBTTDgKLS0tIGdTM2YwQXJUaFNMMElCelJUend5
        clFBR2cyYlNqRy9kNGtqbVNJU1U4YkEKDHi8B5Xe5XgKPXFAFcum2aAmGstWI3TB
        PfQH/Q4XNsac6GiVLNvCmE22VAepD+LsFoDfLsa79eIP93IRNOpUxA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-09-20T03:52:42Z"
  mac: ENC[AES256_GCM,data:edZGZAHCrdppAoRyFPyRrxTczuIw8o+7hLqDNMhSUsNbVduDVWG0Y6sTcpM/iR+wMc4b2goTGgytNgWSPumbdxL4MyH2tIfCNnMSc2p6oiSeva2AzsfxjX9Zv/x9kvxZj9YltBtx+A7++pif1eLHl4TzjddmQg+yzNb05ywPW2w=,iv:J6mXGsNrCACGgKXpTkhYDuiAwuOaxJit9VO3GjTa9L4=,tag:1lLb5t9mfLacle2gxbOCfQ==,type:str]
  version: 3.13.3
---
apiVersion: v1alpha1
kind: KubeAPIServerConfig
certExtraSANs:
  - 2001:cafe:43::2
  - kubeprism
  - kubeprism.kube-system
  - kubeprism.kube-system.svc
  - kubeprism.kube-system.svc.cluster.local
extraArgs:
  feature-gates: MutablePVNodeAffinity=true
  # https://github.com/kubernetes/kubernetes/pull/88567
  goaway-chance: ".01"
resources:
  requests:
    cpu: 300m
    memory: 1.5Gi
  limits:
    memory: 2Gi
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBVQXE2
        ZHNQVDBTNlJnQ0xPQnNrcCtGUC9IRVB2NXpWcHVuZG1MWlVIZHpzCkQwZUczRU41
        V0gwL0diRFZmUWFOUWJ1ekdpdkdVcHgrYnNMcnFodG5qMjAKLS0tIGdFRytxeFVM
        ZVpPSm9Pc1RBbGtsU3ZxYUtJVTJSNjRjOUREaHV4YWErSU0Kvf9oIpSocrnB+Gq+
        thjc+S3A1NdP/C3/+JlBp6QMuFLp/TZ/0nsXALmUKK+cZ/XsZ2Z5jzrdobgTBxy2
        pRqfUQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcXp1MktHN1d0bVVjMXdy
        a2lVbUhFdGt1NzBXbVlaMUxrdytvTVFIOUdRCmxFblBNRXVoc0pmbGxJTDhxVEY0
        K3hoL3ZhaDB0aUkvL3pLcDJHbVBTTDgKLS0tIGdTM2YwQXJUaFNMMElCelJUend5
        clFBR2cyYlNqRy9kNGtqbVNJU1U4YkEKDHi8B5Xe5XgKPXFAFcum2aAmGstWI3TB
        PfQH/Q4XNsac6GiVLNvCmE22VAepD+LsFoDfLsa79eIP93IRNOpUxA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-09-20T03:52:42Z"
  mac: ENC[AES256_GCM,data:edZGZAHCrdppAoRyFPyRrxTczuIw8o+7hLqDNMhSUsNbVduDVWG0Y6sTcpM/iR+wMc4b2goTGgytNgWSPumbdxL4MyH2tIfCNnMSc2p6oiSeva2AzsfxjX9Zv/x9kvxZj9YltBtx+A7++pif1eLHl4TzjddmQg+yzNb05ywPW2w=,iv:J6mXGsNrCACGgKXpTkhYDuiAwuOaxJit9VO3GjTa9L4=,tag:1lLb5t9mfLacle2gxbOCfQ==,type:str]
  version: 3.13.3
---
apiVersion: v1alpha1
kind: KubeSchedulerConfig
resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    memory: 256Mi
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBVQXE2
        ZHNQVDBTNlJnQ0xPQnNrcCtGUC9IRVB2NXpWcHVuZG1MWlVIZHpzCkQwZUczRU41
        V0gwL0diRFZmUWFOUWJ1ekdpdkdVcHgrYnNMcnFodG5qMjAKLS0tIGdFRytxeFVM
        ZVpPSm9Pc1RBbGtsU3ZxYUtJVTJSNjRjOUREaHV4YWErSU0Kvf9oIpSocrnB+Gq+
        thjc+S3A1NdP/C3/+JlBp6QMuFLp/TZ/0nsXALmUKK+cZ/XsZ2Z5jzrdobgTBxy2
        pRqfUQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcXp1MktHN1d0bVVjMXdy
        a2lVbUhFdGt1NzBXbVlaMUxrdytvTVFIOUdRCmxFblBNRXVoc0pmbGxJTDhxVEY0
        K3hoL3ZhaDB0aUkvL3pLcDJHbVBTTDgKLS0tIGdTM2YwQXJUaFNMMElCelJUend5
        clFBR2cyYlNqRy9kNGtqbVNJU1U4YkEKDHi8B5Xe5XgKPXFAFcum2aAmGstWI3TB
        PfQH/Q4XNsac6GiVLNvCmE22VAepD+LsFoDfLsa79eIP93IRNOpUxA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-09-20T03:52:42Z"
  mac: ENC[AES256_GCM,data:edZGZAHCrdppAoRyFPyRrxTczuIw8o+7hLqDNMhSUsNbVduDVWG0Y6sTcpM/iR+wMc4b2goTGgytNgWSPumbdxL4MyH2tIfCNnMSc2p6oiSeva2AzsfxjX9Zv/x9kvxZj9YltBtx+A7++pif1eLHl4TzjddmQg+yzNb05ywPW2w=,iv:J6mXGsNrCACGgKXpTkhYDuiAwuOaxJit9VO3GjTa9L4=,tag:1lLb5t9mfLacle2gxbOCfQ==,type:str]
  version: 3.13.3
---
apiVersion: v1alpha1
kind: KubeControllerManagerConfig
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    memory: 512Mi
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBVQXE2
        ZHNQVDBTNlJnQ0xPQnNrcCtGUC9IRVB2NXpWcHVuZG1MWlVIZHpzCkQwZUczRU41
        V0gwL0diRFZmUWFOUWJ1ekdpdkdVcHgrYnNMcnFodG5qMjAKLS0tIGdFRytxeFVM
        ZVpPSm9Pc1RBbGtsU3ZxYUtJVTJSNjRjOUREaHV4YWErSU0Kvf9oIpSocrnB+Gq+
        thjc+S3A1NdP/C3/+JlBp6QMuFLp/TZ/0nsXALmUKK+cZ/XsZ2Z5jzrdobgTBxy2
        pRqfUQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcXp1MktHN1d0bVVjMXdy
        a2lVbUhFdGt1NzBXbVlaMUxrdytvTVFIOUdRCmxFblBNRXVoc0pmbGxJTDhxVEY0
        K3hoL3ZhaDB0aUkvL3pLcDJHbVBTTDgKLS0tIGdTM2YwQXJUaFNMMElCelJUend5
        clFBR2cyYlNqRy9kNGtqbVNJU1U4YkEKDHi8B5Xe5XgKPXFAFcum2aAmGstWI3TB
        PfQH/Q4XNsac6GiVLNvCmE22VAepD+LsFoDfLsa79eIP93IRNOpUxA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-09-20T03:52:42Z"
  mac: ENC[AES256_GCM,data:edZGZAHCrdppAoRyFPyRrxTczuIw8o+7hLqDNMhSUsNbVduDVWG0Y6sTcpM/iR+wMc4b2goTGgytNgWSPumbdxL4MyH2tIfCNnMSc2p6oiSeva2AzsfxjX9Zv/x9kvxZj9YltBtx+A7++pif1eLHl4TzjddmQg+yzNb05ywPW2w=,iv:J6mXGsNrCACGgKXpTkhYDuiAwuOaxJit9VO3GjTa9L4=,tag:1lLb5t9mfLacle2gxbOCfQ==,type:str]
  version: 3.13.3
---
apiVersion: v1alpha1
kind: KubeAuthenticationConfig
configuration:
  anonymous:
    conditions:
      - path: /livez
      - path: /readyz
      - path: /healthz
      - path: /openid/v1/jwks
      - path: /.well-known/openid-configuration
    enabled: true
  jwt:
    - issuer:
        # url must not conflict with issuer configured in --service-account-issuer.
        url: https://ic.vrtx.sh/.identity
        audiences:
          - kubernetes
      claimMappings:
        # username represents an option for the username attribute.
        # This is the only required attribute.
        username:
          # Mutually exclusive with username.expression.
          claim: sub
          # if username.claim is set, username.prefix is required.
          # Explicitly set it to "" if no prefix is desired.
          prefix: ""
      userValidationRules:
        # expression is a CEL expression that evaluates to a boolean.
        # all the expressions must evaluate to true for the user to be valid.
        - expression: user.username.startsWith('woodpecker:')
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBVQXE2
        ZHNQVDBTNlJnQ0xPQnNrcCtGUC9IRVB2NXpWcHVuZG1MWlVIZHpzCkQwZUczRU41
        V0gwL0diRFZmUWFOUWJ1ekdpdkdVcHgrYnNMcnFodG5qMjAKLS0tIGdFRytxeFVM
        ZVpPSm9Pc1RBbGtsU3ZxYUtJVTJSNjRjOUREaHV4YWErSU0Kvf9oIpSocrnB+Gq+
        thjc+S3A1NdP/C3/+JlBp6QMuFLp/TZ/0nsXALmUKK+cZ/XsZ2Z5jzrdobgTBxy2
        pRqfUQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcXp1MktHN1d0bVVjMXdy
        a2lVbUhFdGt1NzBXbVlaMUxrdytvTVFIOUdRCmxFblBNRXVoc0pmbGxJTDhxVEY0
        K3hoL3ZhaDB0aUkvL3pLcDJHbVBTTDgKLS0tIGdTM2YwQXJUaFNMMElCelJUend5
        clFBR2cyYlNqRy9kNGtqbVNJU1U4YkEKDHi8B5Xe5XgKPXFAFcum2aAmGstWI3TB
        PfQH/Q4XNsac6GiVLNvCmE22VAepD+LsFoDfLsa79eIP93IRNOpUxA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-09-20T03:52:42Z"
  mac: ENC[AES256_GCM,data:edZGZAHCrdppAoRyFPyRrxTczuIw8o+7hLqDNMhSUsNbVduDVWG0Y6sTcpM/iR+wMc4b2goTGgytNgWSPumbdxL4MyH2tIfCNnMSc2p6oiSeva2AzsfxjX9Zv/x9kvxZj9YltBtx+A7++pif1eLHl4TzjddmQg+yzNb05ywPW2w=,iv:J6mXGsNrCACGgKXpTkhYDuiAwuOaxJit9VO3GjTa9L4=,tag:1lLb5t9mfLacle2gxbOCfQ==,type:str]
  version: 3.13.3
---
apiVersion: v1alpha1
kind: KubeTalosAPIAccessConfig
allowedRoles:
  - os:etcd:backup
allowedKubernetesNamespaces:
  - kube-system
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBVQXE2
        ZHNQVDBTNlJnQ0xPQnNrcCtGUC9IRVB2NXpWcHVuZG1MWlVIZHpzCkQwZUczRU41
        V0gwL0diRFZmUWFOUWJ1ekdpdkdVcHgrYnNMcnFodG5qMjAKLS0tIGdFRytxeFVM
        ZVpPSm9Pc1RBbGtsU3ZxYUtJVTJSNjRjOUREaHV4YWErSU0Kvf9oIpSocrnB+Gq+
        thjc+S3A1NdP/C3/+JlBp6QMuFLp/TZ/0nsXALmUKK+cZ/XsZ2Z5jzrdobgTBxy2
        pRqfUQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcXp1MktHN1d0bVVjMXdy
        a2lVbUhFdGt1NzBXbVlaMUxrdytvTVFIOUdRCmxFblBNRXVoc0pmbGxJTDhxVEY0
        K3hoL3ZhaDB0aUkvL3pLcDJHbVBTTDgKLS0tIGdTM2YwQXJUaFNMMElCelJUend5
        clFBR2cyYlNqRy9kNGtqbVNJU1U4YkEKDHi8B5Xe5XgKPXFAFcum2aAmGstWI3TB
        PfQH/Q4XNsac6GiVLNvCmE22VAepD+LsFoDfLsa79eIP93IRNOpUxA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-09-20T03:52:42Z"
  mac: ENC[AES256_GCM,data:edZGZAHCrdppAoRyFPyRrxTczuIw8o+7hLqDNMhSUsNbVduDVWG0Y6sTcpM/iR+wMc4b2goTGgytNgWSPumbdxL4MyH2tIfCNnMSc2p6oiSeva2AzsfxjX9Zv/x9kvxZj9YltBtx+A7++pif1eLHl4TzjddmQg+yzNb05ywPW2w=,iv:J6mXGsNrCACGgKXpTkhYDuiAwuOaxJit9VO3GjTa9L4=,tag:1lLb5t9mfLacle2gxbOCfQ==,type:str]
  version: 3.13.3
