apiVersion: v1alpha1
kind: HostnameConfig
auto: "off"
hostname: sophons-prime
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBZaXpQ
        d1JLMmxvUnZrMVhZMkpQeTlnL0l3RHBuRU5aQ2F2RWtiMDIvcm5zCldpUlgyeklZ
        RGxsYjZGNFRhdWlIVjd2MXZUU002U05xdDFmeVJYUmZ0OTAKLS0tIEZReGkzZi81
        MGgwaXFqVTEwVzVncDhIOGRpdk5vd2lkTEEwaDFJUThoTVEKRuS9HwKm58jadqRT
        3tnVnFkAebny1i29XxiUkxPZa14EyX2041bVjZsRydMybecxU/CgMcqfUmqYED+t
        jhNyWg==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncER5N2VwYzVmSXEvaDBj
        bDRaTzc1UG5tVC9MQjV5V3ZEOEovQW0wR1NNClJFbnNzelpBTTdnbUtHN0ozVHVi
        ajBEZnVKU2Y2SmlZSmFZS2FjZHdCUkUKLS0tIFI0b3NsY0lDTTMycUpBMzR4OU9a
        elFOUUk0Y1VES3h0YlZnVVVpRTVneVkKrr5hKcv+2hm234XiI15XtVeMkF73fiHs
        GKLwiTFCKoBxZRjyg+AvqXbDERy6EMfOPiEUauK5+Jqec67hpmM0SQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-09-17T15:42:13Z"
  mac: ENC[AES256_GCM,data:xpX86g3j4muTUSC6Jrz44dNSi2MjzclRArKvhNLywNCF5RMvwg1BULXP5DD3Oc9YG6hT2A/iacdPy+kEQ+TU136FiYOu0YlweQbjBp38bVv15u8BIJlN6/ZfcduC/zbeq4zuHVrNVKylyFpCjusINRtimcRVXVyWyEke5yIiIIo=,iv:q+uy80B0aOGnd9Wq5x3SBqrY8B4KrXSr+jJepFxhPu4=,tag:OEaRRHteYg4eztnIVuc8zw==,type:str]
  version: 3.13.3
---
machine:
  kubelet:
    extraConfig:
      mergeDefaultEvictionSettings: true
      evictionSoft:
        memory.available: 150Mi
      evictionSoftGracePeriod:
        memory.available: 30s
      evictionHard:
        memory.available: 100Mi
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBZaXpQ
        d1JLMmxvUnZrMVhZMkpQeTlnL0l3RHBuRU5aQ2F2RWtiMDIvcm5zCldpUlgyeklZ
        RGxsYjZGNFRhdWlIVjd2MXZUU002U05xdDFmeVJYUmZ0OTAKLS0tIEZReGkzZi81
        MGgwaXFqVTEwVzVncDhIOGRpdk5vd2lkTEEwaDFJUThoTVEKRuS9HwKm58jadqRT
        3tnVnFkAebny1i29XxiUkxPZa14EyX2041bVjZsRydMybecxU/CgMcqfUmqYED+t
        jhNyWg==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncER5N2VwYzVmSXEvaDBj
        bDRaTzc1UG5tVC9MQjV5V3ZEOEovQW0wR1NNClJFbnNzelpBTTdnbUtHN0ozVHVi
        ajBEZnVKU2Y2SmlZSmFZS2FjZHdCUkUKLS0tIFI0b3NsY0lDTTMycUpBMzR4OU9a
        elFOUUk0Y1VES3h0YlZnVVVpRTVneVkKrr5hKcv+2hm234XiI15XtVeMkF73fiHs
        GKLwiTFCKoBxZRjyg+AvqXbDERy6EMfOPiEUauK5+Jqec67hpmM0SQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-09-17T15:42:13Z"
  mac: ENC[AES256_GCM,data:xpX86g3j4muTUSC6Jrz44dNSi2MjzclRArKvhNLywNCF5RMvwg1BULXP5DD3Oc9YG6hT2A/iacdPy+kEQ+TU136FiYOu0YlweQbjBp38bVv15u8BIJlN6/ZfcduC/zbeq4zuHVrNVKylyFpCjusINRtimcRVXVyWyEke5yIiIIo=,iv:q+uy80B0aOGnd9Wq5x3SBqrY8B4KrXSr+jJepFxhPu4=,tag:OEaRRHteYg4eztnIVuc8zw==,type:str]
  version: 3.13.3
---
apiVersion: v1alpha1
kind: UnattendedInstallConfig
provisioning:
  diskSelector:
    match: disk.dev_path == "/dev/mmcblk0"
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBZaXpQ
        d1JLMmxvUnZrMVhZMkpQeTlnL0l3RHBuRU5aQ2F2RWtiMDIvcm5zCldpUlgyeklZ
        RGxsYjZGNFRhdWlIVjd2MXZUU002U05xdDFmeVJYUmZ0OTAKLS0tIEZReGkzZi81
        MGgwaXFqVTEwVzVncDhIOGRpdk5vd2lkTEEwaDFJUThoTVEKRuS9HwKm58jadqRT
        3tnVnFkAebny1i29XxiUkxPZa14EyX2041bVjZsRydMybecxU/CgMcqfUmqYED+t
        jhNyWg==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncER5N2VwYzVmSXEvaDBj
        bDRaTzc1UG5tVC9MQjV5V3ZEOEovQW0wR1NNClJFbnNzelpBTTdnbUtHN0ozVHVi
        ajBEZnVKU2Y2SmlZSmFZS2FjZHdCUkUKLS0tIFI0b3NsY0lDTTMycUpBMzR4OU9a
        elFOUUk0Y1VES3h0YlZnVVVpRTVneVkKrr5hKcv+2hm234XiI15XtVeMkF73fiHs
        GKLwiTFCKoBxZRjyg+AvqXbDERy6EMfOPiEUauK5+Jqec67hpmM0SQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-09-17T15:42:13Z"
  mac: ENC[AES256_GCM,data:xpX86g3j4muTUSC6Jrz44dNSi2MjzclRArKvhNLywNCF5RMvwg1BULXP5DD3Oc9YG6hT2A/iacdPy+kEQ+TU136FiYOu0YlweQbjBp38bVv15u8BIJlN6/ZfcduC/zbeq4zuHVrNVKylyFpCjusINRtimcRVXVyWyEke5yIiIIo=,iv:q+uy80B0aOGnd9Wq5x3SBqrY8B4KrXSr+jJepFxhPu4=,tag:OEaRRHteYg4eztnIVuc8zw==,type:str]
  version: 3.13.3
---
apiVersion: v1alpha1
kind: KubeNodeConfig
labels:
  egress.sophons.cloud/positron: "true"
  topology.kubernetes.io/region: ng
  # TODO: fully merge all of NG into one zone
  topology.kubernetes.io/zone: ng-east-1
  hugeloads.sophons.cloud/postgres: "false"
taints:
  prime.sophons.cloud: :NoSchedule
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBZaXpQ
        d1JLMmxvUnZrMVhZMkpQeTlnL0l3RHBuRU5aQ2F2RWtiMDIvcm5zCldpUlgyeklZ
        RGxsYjZGNFRhdWlIVjd2MXZUU002U05xdDFmeVJYUmZ0OTAKLS0tIEZReGkzZi81
        MGgwaXFqVTEwVzVncDhIOGRpdk5vd2lkTEEwaDFJUThoTVEKRuS9HwKm58jadqRT
        3tnVnFkAebny1i29XxiUkxPZa14EyX2041bVjZsRydMybecxU/CgMcqfUmqYED+t
        jhNyWg==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncER5N2VwYzVmSXEvaDBj
        bDRaTzc1UG5tVC9MQjV5V3ZEOEovQW0wR1NNClJFbnNzelpBTTdnbUtHN0ozVHVi
        ajBEZnVKU2Y2SmlZSmFZS2FjZHdCUkUKLS0tIFI0b3NsY0lDTTMycUpBMzR4OU9a
        elFOUUk0Y1VES3h0YlZnVVVpRTVneVkKrr5hKcv+2hm234XiI15XtVeMkF73fiHs
        GKLwiTFCKoBxZRjyg+AvqXbDERy6EMfOPiEUauK5+Jqec67hpmM0SQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-09-17T15:42:13Z"
  mac: ENC[AES256_GCM,data:xpX86g3j4muTUSC6Jrz44dNSi2MjzclRArKvhNLywNCF5RMvwg1BULXP5DD3Oc9YG6hT2A/iacdPy+kEQ+TU136FiYOu0YlweQbjBp38bVv15u8BIJlN6/ZfcduC/zbeq4zuHVrNVKylyFpCjusINRtimcRVXVyWyEke5yIiIIo=,iv:q+uy80B0aOGnd9Wq5x3SBqrY8B4KrXSr+jJepFxhPu4=,tag:OEaRRHteYg4eztnIVuc8zw==,type:str]
  version: 3.13.3
---
apiVersion: v1alpha1
kind: KernelModuleConfig
name: snd-usb-audio
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBZaXpQ
        d1JLMmxvUnZrMVhZMkpQeTlnL0l3RHBuRU5aQ2F2RWtiMDIvcm5zCldpUlgyeklZ
        RGxsYjZGNFRhdWlIVjd2MXZUU002U05xdDFmeVJYUmZ0OTAKLS0tIEZReGkzZi81
        MGgwaXFqVTEwVzVncDhIOGRpdk5vd2lkTEEwaDFJUThoTVEKRuS9HwKm58jadqRT
        3tnVnFkAebny1i29XxiUkxPZa14EyX2041bVjZsRydMybecxU/CgMcqfUmqYED+t
        jhNyWg==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncER5N2VwYzVmSXEvaDBj
        bDRaTzc1UG5tVC9MQjV5V3ZEOEovQW0wR1NNClJFbnNzelpBTTdnbUtHN0ozVHVi
        ajBEZnVKU2Y2SmlZSmFZS2FjZHdCUkUKLS0tIFI0b3NsY0lDTTMycUpBMzR4OU9a
        elFOUUk0Y1VES3h0YlZnVVVpRTVneVkKrr5hKcv+2hm234XiI15XtVeMkF73fiHs
        GKLwiTFCKoBxZRjyg+AvqXbDERy6EMfOPiEUauK5+Jqec67hpmM0SQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-09-17T15:42:13Z"
  mac: ENC[AES256_GCM,data:xpX86g3j4muTUSC6Jrz44dNSi2MjzclRArKvhNLywNCF5RMvwg1BULXP5DD3Oc9YG6hT2A/iacdPy+kEQ+TU136FiYOu0YlweQbjBp38bVv15u8BIJlN6/ZfcduC/zbeq4zuHVrNVKylyFpCjusINRtimcRVXVyWyEke5yIiIIo=,iv:q+uy80B0aOGnd9Wq5x3SBqrY8B4KrXSr+jJepFxhPu4=,tag:OEaRRHteYg4eztnIVuc8zw==,type:str]
  version: 3.13.3
---
apiVersion: v1alpha1
kind: SysctlConfig
params:
  # 64MiB
  vm.min_free_kbytes: 65536
  vm.swappiness: 200
  vm.watermark_scale_factor: 250
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBZaXpQ
        d1JLMmxvUnZrMVhZMkpQeTlnL0l3RHBuRU5aQ2F2RWtiMDIvcm5zCldpUlgyeklZ
        RGxsYjZGNFRhdWlIVjd2MXZUU002U05xdDFmeVJYUmZ0OTAKLS0tIEZReGkzZi81
        MGgwaXFqVTEwVzVncDhIOGRpdk5vd2lkTEEwaDFJUThoTVEKRuS9HwKm58jadqRT
        3tnVnFkAebny1i29XxiUkxPZa14EyX2041bVjZsRydMybecxU/CgMcqfUmqYED+t
        jhNyWg==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncER5N2VwYzVmSXEvaDBj
        bDRaTzc1UG5tVC9MQjV5V3ZEOEovQW0wR1NNClJFbnNzelpBTTdnbUtHN0ozVHVi
        ajBEZnVKU2Y2SmlZSmFZS2FjZHdCUkUKLS0tIFI0b3NsY0lDTTMycUpBMzR4OU9a
        elFOUUk0Y1VES3h0YlZnVVVpRTVneVkKrr5hKcv+2hm234XiI15XtVeMkF73fiHs
        GKLwiTFCKoBxZRjyg+AvqXbDERy6EMfOPiEUauK5+Jqec67hpmM0SQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-09-17T15:42:13Z"
  mac: ENC[AES256_GCM,data:xpX86g3j4muTUSC6Jrz44dNSi2MjzclRArKvhNLywNCF5RMvwg1BULXP5DD3Oc9YG6hT2A/iacdPy+kEQ+TU136FiYOu0YlweQbjBp38bVv15u8BIJlN6/ZfcduC/zbeq4zuHVrNVKylyFpCjusINRtimcRVXVyWyEke5yIiIIo=,iv:q+uy80B0aOGnd9Wq5x3SBqrY8B4KrXSr+jJepFxhPu4=,tag:OEaRRHteYg4eztnIVuc8zw==,type:str]
  version: 3.13.3
---
apiVersion: v1alpha1
kind: VLANConfig
name: end0.42
vlanID: 42
parent: end0
addresses:
  - address: 10.42.42.2/16
routes:
  - gateway: 10.42.0.1
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBZaXpQ
        d1JLMmxvUnZrMVhZMkpQeTlnL0l3RHBuRU5aQ2F2RWtiMDIvcm5zCldpUlgyeklZ
        RGxsYjZGNFRhdWlIVjd2MXZUU002U05xdDFmeVJYUmZ0OTAKLS0tIEZReGkzZi81
        MGgwaXFqVTEwVzVncDhIOGRpdk5vd2lkTEEwaDFJUThoTVEKRuS9HwKm58jadqRT
        3tnVnFkAebny1i29XxiUkxPZa14EyX2041bVjZsRydMybecxU/CgMcqfUmqYED+t
        jhNyWg==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncER5N2VwYzVmSXEvaDBj
        bDRaTzc1UG5tVC9MQjV5V3ZEOEovQW0wR1NNClJFbnNzelpBTTdnbUtHN0ozVHVi
        ajBEZnVKU2Y2SmlZSmFZS2FjZHdCUkUKLS0tIFI0b3NsY0lDTTMycUpBMzR4OU9a
        elFOUUk0Y1VES3h0YlZnVVVpRTVneVkKrr5hKcv+2hm234XiI15XtVeMkF73fiHs
        GKLwiTFCKoBxZRjyg+AvqXbDERy6EMfOPiEUauK5+Jqec67hpmM0SQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-09-17T15:42:13Z"
  mac: ENC[AES256_GCM,data:xpX86g3j4muTUSC6Jrz44dNSi2MjzclRArKvhNLywNCF5RMvwg1BULXP5DD3Oc9YG6hT2A/iacdPy+kEQ+TU136FiYOu0YlweQbjBp38bVv15u8BIJlN6/ZfcduC/zbeq4zuHVrNVKylyFpCjusINRtimcRVXVyWyEke5yIiIIo=,iv:q+uy80B0aOGnd9Wq5x3SBqrY8B4KrXSr+jJepFxhPu4=,tag:OEaRRHteYg4eztnIVuc8zw==,type:str]
  version: 3.13.3
---
# https://tailscale.com/docs/reference/best-practices/performance#linux-optimizations-for-subnet-routers-and-exit-nodes
apiVersion: v1alpha1
kind: EthernetConfig
name: end0
features:
  rx-gro-list: "off"
  rx-udp-gro-forwarding: "on"
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBZaXpQ
        d1JLMmxvUnZrMVhZMkpQeTlnL0l3RHBuRU5aQ2F2RWtiMDIvcm5zCldpUlgyeklZ
        RGxsYjZGNFRhdWlIVjd2MXZUU002U05xdDFmeVJYUmZ0OTAKLS0tIEZReGkzZi81
        MGgwaXFqVTEwVzVncDhIOGRpdk5vd2lkTEEwaDFJUThoTVEKRuS9HwKm58jadqRT
        3tnVnFkAebny1i29XxiUkxPZa14EyX2041bVjZsRydMybecxU/CgMcqfUmqYED+t
        jhNyWg==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncER5N2VwYzVmSXEvaDBj
        bDRaTzc1UG5tVC9MQjV5V3ZEOEovQW0wR1NNClJFbnNzelpBTTdnbUtHN0ozVHVi
        ajBEZnVKU2Y2SmlZSmFZS2FjZHdCUkUKLS0tIFI0b3NsY0lDTTMycUpBMzR4OU9a
        elFOUUk0Y1VES3h0YlZnVVVpRTVneVkKrr5hKcv+2hm234XiI15XtVeMkF73fiHs
        GKLwiTFCKoBxZRjyg+AvqXbDERy6EMfOPiEUauK5+Jqec67hpmM0SQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-09-17T15:42:13Z"
  mac: ENC[AES256_GCM,data:xpX86g3j4muTUSC6Jrz44dNSi2MjzclRArKvhNLywNCF5RMvwg1BULXP5DD3Oc9YG6hT2A/iacdPy+kEQ+TU136FiYOu0YlweQbjBp38bVv15u8BIJlN6/ZfcduC/zbeq4zuHVrNVKylyFpCjusINRtimcRVXVyWyEke5yIiIIo=,iv:q+uy80B0aOGnd9Wq5x3SBqrY8B4KrXSr+jJepFxhPu4=,tag:OEaRRHteYg4eztnIVuc8zw==,type:str]
  version: 3.13.3
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  maxSize: 100GiB
  grow: false
# ---
# apiVersion: v1alpha1
# kind: SwapVolumeConfig
# name: swap-1GiB
# provisioning:
#   diskSelector:
#     match: system_disk
#   minSize: 1GiB
#   maxSize: 1GiB
#   grow: false
# ---
# apiVersion: v1alpha1
# kind: ZswapConfig
# # The maximum percent of memory that zswap can use.
# maxPoolPercent: 69
# # Enable the shrinker feature: kernel might move
# shrinkerEnabled: true
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBZaXpQ
        d1JLMmxvUnZrMVhZMkpQeTlnL0l3RHBuRU5aQ2F2RWtiMDIvcm5zCldpUlgyeklZ
        RGxsYjZGNFRhdWlIVjd2MXZUU002U05xdDFmeVJYUmZ0OTAKLS0tIEZReGkzZi81
        MGgwaXFqVTEwVzVncDhIOGRpdk5vd2lkTEEwaDFJUThoTVEKRuS9HwKm58jadqRT
        3tnVnFkAebny1i29XxiUkxPZa14EyX2041bVjZsRydMybecxU/CgMcqfUmqYED+t
        jhNyWg==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncER5N2VwYzVmSXEvaDBj
        bDRaTzc1UG5tVC9MQjV5V3ZEOEovQW0wR1NNClJFbnNzelpBTTdnbUtHN0ozVHVi
        ajBEZnVKU2Y2SmlZSmFZS2FjZHdCUkUKLS0tIFI0b3NsY0lDTTMycUpBMzR4OU9a
        elFOUUk0Y1VES3h0YlZnVVVpRTVneVkKrr5hKcv+2hm234XiI15XtVeMkF73fiHs
        GKLwiTFCKoBxZRjyg+AvqXbDERy6EMfOPiEUauK5+Jqec67hpmM0SQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-09-17T15:42:13Z"
  mac: ENC[AES256_GCM,data:xpX86g3j4muTUSC6Jrz44dNSi2MjzclRArKvhNLywNCF5RMvwg1BULXP5DD3Oc9YG6hT2A/iacdPy+kEQ+TU136FiYOu0YlweQbjBp38bVv15u8BIJlN6/ZfcduC/zbeq4zuHVrNVKylyFpCjusINRtimcRVXVyWyEke5yIiIIo=,iv:q+uy80B0aOGnd9Wq5x3SBqrY8B4KrXSr+jJepFxhPu4=,tag:OEaRRHteYg4eztnIVuc8zw==,type:str]
  version: 3.13.3
