apiVersion: v1alpha1
kind: HostnameConfig
auto: "off"
hostname: sophons-theta
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBPSzM5
        Slh4SFlSNUNQc0lhYk1TUVdVL05QQmoweFBnV3RSWjBjU3B2QkdnCm5Udi90Y3px
        bHdrZEFBV1B0Uk8vZzNJdFhBdGVmYk5zYjBqc3lyaGFXQzQKLS0tIGtDLzZKYSs1
        UDZyY1M3R2gxVm9jOVhEc2Yzbnhxa1VnV3BGSGRyRjBLK2sK0+9tdwYvg3WsEQY/
        4SFiO4BAv3lPUy5mZtCBMLH+CB6HanjTfZQHJCcm511TxdAy1HVKW+8e7rw8BYT6
        jBkUFA==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZ2lQNWZmcXEvN0VtZmF1
        d0NSZ2wvSENqRXcwUTQyU0kwRkNJNmV3MWlRCmlvSmo0aGhmWWxXWUp3RjNGcCtz
        Y2VaRlNxVXZGcnpQSnZCd1JrUytQNmcKLS0tIEpyVGdETDJPQzAwZ2ZCZThTelBK
        ZU9OYU1GNlBTaHlsQ0g2S1JERnA0SmMKZeyOsrfYtly05s6dGscnOXezSMjnHo5N
        SvcW06rOHMARBDKuyafoxex81wyZ13A8GdVlLhyk4LHFWXjB4QCzXA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-09-17T15:42:14Z"
  mac: ENC[AES256_GCM,data:/Y4Qmn/+IBGi0HpboThL+KCaAm3E1kAUsd9WrN3mtI46aFyXWj0upNZ0QtceaQdAVxUFtUAC29u3l2D44dHDg7vnfvhm2UyK/g2fqUiZbPb3Ug5S1t6nfdG/jTy+LFys01unkodkpx7zzIO6QWwAsvDCuKibvRrl5FZXvenLHiQ=,iv:ayhU1Pp0jaTu/rYf0f4RIQUMG7SpZGcYmMNVozBj49c=,tag:MiE5gsUjNrsEOPmwqwuM5A==,type:str]
  version: 3.13.3
---
apiVersion: v1alpha1
kind: UnattendedInstallConfig
provisioning:
  diskSelector:
    match: disk.dev_path == "/dev/vda"
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBPSzM5
        Slh4SFlSNUNQc0lhYk1TUVdVL05QQmoweFBnV3RSWjBjU3B2QkdnCm5Udi90Y3px
        bHdrZEFBV1B0Uk8vZzNJdFhBdGVmYk5zYjBqc3lyaGFXQzQKLS0tIGtDLzZKYSs1
        UDZyY1M3R2gxVm9jOVhEc2Yzbnhxa1VnV3BGSGRyRjBLK2sK0+9tdwYvg3WsEQY/
        4SFiO4BAv3lPUy5mZtCBMLH+CB6HanjTfZQHJCcm511TxdAy1HVKW+8e7rw8BYT6
        jBkUFA==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZ2lQNWZmcXEvN0VtZmF1
        d0NSZ2wvSENqRXcwUTQyU0kwRkNJNmV3MWlRCmlvSmo0aGhmWWxXWUp3RjNGcCtz
        Y2VaRlNxVXZGcnpQSnZCd1JrUytQNmcKLS0tIEpyVGdETDJPQzAwZ2ZCZThTelBK
        ZU9OYU1GNlBTaHlsQ0g2S1JERnA0SmMKZeyOsrfYtly05s6dGscnOXezSMjnHo5N
        SvcW06rOHMARBDKuyafoxex81wyZ13A8GdVlLhyk4LHFWXjB4QCzXA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-09-17T15:42:14Z"
  mac: ENC[AES256_GCM,data:/Y4Qmn/+IBGi0HpboThL+KCaAm3E1kAUsd9WrN3mtI46aFyXWj0upNZ0QtceaQdAVxUFtUAC29u3l2D44dHDg7vnfvhm2UyK/g2fqUiZbPb3Ug5S1t6nfdG/jTy+LFys01unkodkpx7zzIO6QWwAsvDCuKibvRrl5FZXvenLHiQ=,iv:ayhU1Pp0jaTu/rYf0f4RIQUMG7SpZGcYmMNVozBj49c=,tag:MiE5gsUjNrsEOPmwqwuM5A==,type:str]
  version: 3.13.3
---
apiVersion: v1alpha1
kind: KubeNodeConfig
labels:
  egress.sophons.cloud/ci-ipv6: "true"
  topology.kubernetes.io/region: nl
  topology.kubernetes.io/zone: nl-east-1
  hugeloads.sophons.cloud/garage: "true"
  cluster.garage.sophons.cloud/global: "true"
  weed.sophons.cloud/cluster: global
  weed.sophons.cloud/master: "true"
  weed.sophons.cloud/volume: "true"
  weed.sophons.cloud/filer: "true"
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBPSzM5
        Slh4SFlSNUNQc0lhYk1TUVdVL05QQmoweFBnV3RSWjBjU3B2QkdnCm5Udi90Y3px
        bHdrZEFBV1B0Uk8vZzNJdFhBdGVmYk5zYjBqc3lyaGFXQzQKLS0tIGtDLzZKYSs1
        UDZyY1M3R2gxVm9jOVhEc2Yzbnhxa1VnV3BGSGRyRjBLK2sK0+9tdwYvg3WsEQY/
        4SFiO4BAv3lPUy5mZtCBMLH+CB6HanjTfZQHJCcm511TxdAy1HVKW+8e7rw8BYT6
        jBkUFA==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZ2lQNWZmcXEvN0VtZmF1
        d0NSZ2wvSENqRXcwUTQyU0kwRkNJNmV3MWlRCmlvSmo0aGhmWWxXWUp3RjNGcCtz
        Y2VaRlNxVXZGcnpQSnZCd1JrUytQNmcKLS0tIEpyVGdETDJPQzAwZ2ZCZThTelBK
        ZU9OYU1GNlBTaHlsQ0g2S1JERnA0SmMKZeyOsrfYtly05s6dGscnOXezSMjnHo5N
        SvcW06rOHMARBDKuyafoxex81wyZ13A8GdVlLhyk4LHFWXjB4QCzXA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-09-17T15:42:14Z"
  mac: ENC[AES256_GCM,data:/Y4Qmn/+IBGi0HpboThL+KCaAm3E1kAUsd9WrN3mtI46aFyXWj0upNZ0QtceaQdAVxUFtUAC29u3l2D44dHDg7vnfvhm2UyK/g2fqUiZbPb3Ug5S1t6nfdG/jTy+LFys01unkodkpx7zzIO6QWwAsvDCuKibvRrl5FZXvenLHiQ=,iv:ayhU1Pp0jaTu/rYf0f4RIQUMG7SpZGcYmMNVozBj49c=,tag:MiE5gsUjNrsEOPmwqwuM5A==,type:str]
  version: 3.13.3
---
apiVersion: v1alpha1
kind: LinkConfig
name: enp7s0
addresses:
  # enc!
  - address: ENC[AES256_GCM,data:lkZVlzy5cd9HYEzbljtsSQ==,iv:1HeQTY5Br1sfptg6cydxhubZJJy86qviCGxR/7wrWfA=,tag:+11Yh7lQJUoFz8aHW4IV2A==,type:str]
  # enc!
  - address: ENC[AES256_GCM,data:a9B9vyqXJBqGcoji/N5fMHGxdhi38Ws=,iv:5GErNmem7wMKfaP/U3Y8+/aPfAHRKDmWJtoJQroc+JI=,tag:Xui4+O+gC2L0jnPNc4eCJQ==,type:str]
routes:
  - metric: 150
    # enc!
    gateway: ENC[AES256_GCM,data:wPB3ngDZjk49nJg=,iv:NVu+WKnPPsDVqSpbvZzNXtN726B6P7fTfh8TzgY7848=,tag:MlntWSk5R1v3ItSa2sX1/w==,type:str]
  - gateway: fe80::1
    metric: 100
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBPSzM5
        Slh4SFlSNUNQc0lhYk1TUVdVL05QQmoweFBnV3RSWjBjU3B2QkdnCm5Udi90Y3px
        bHdrZEFBV1B0Uk8vZzNJdFhBdGVmYk5zYjBqc3lyaGFXQzQKLS0tIGtDLzZKYSs1
        UDZyY1M3R2gxVm9jOVhEc2Yzbnhxa1VnV3BGSGRyRjBLK2sK0+9tdwYvg3WsEQY/
        4SFiO4BAv3lPUy5mZtCBMLH+CB6HanjTfZQHJCcm511TxdAy1HVKW+8e7rw8BYT6
        jBkUFA==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZ2lQNWZmcXEvN0VtZmF1
        d0NSZ2wvSENqRXcwUTQyU0kwRkNJNmV3MWlRCmlvSmo0aGhmWWxXWUp3RjNGcCtz
        Y2VaRlNxVXZGcnpQSnZCd1JrUytQNmcKLS0tIEpyVGdETDJPQzAwZ2ZCZThTelBK
        ZU9OYU1GNlBTaHlsQ0g2S1JERnA0SmMKZeyOsrfYtly05s6dGscnOXezSMjnHo5N
        SvcW06rOHMARBDKuyafoxex81wyZ13A8GdVlLhyk4LHFWXjB4QCzXA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-09-17T15:42:14Z"
  mac: ENC[AES256_GCM,data:/Y4Qmn/+IBGi0HpboThL+KCaAm3E1kAUsd9WrN3mtI46aFyXWj0upNZ0QtceaQdAVxUFtUAC29u3l2D44dHDg7vnfvhm2UyK/g2fqUiZbPb3Ug5S1t6nfdG/jTy+LFys01unkodkpx7zzIO6QWwAsvDCuKibvRrl5FZXvenLHiQ=,iv:ayhU1Pp0jaTu/rYf0f4RIQUMG7SpZGcYmMNVozBj49c=,tag:MiE5gsUjNrsEOPmwqwuM5A==,type:str]
  version: 3.13.3
---
# https://tailscale.com/docs/reference/best-practices/performance#linux-optimizations-for-subnet-routers-and-exit-nodes
apiVersion: v1alpha1
kind: EthernetConfig
name: enp7s0
features:
  rx-gro-list: "off"
  rx-udp-gro-forwarding: "on"
# ---
# apiVersion: v1alpha1
# kind: VolumeConfig
# name: EPHEMERAL
# provisioning:
#   maxSize: 100GiB
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBPSzM5
        Slh4SFlSNUNQc0lhYk1TUVdVL05QQmoweFBnV3RSWjBjU3B2QkdnCm5Udi90Y3px
        bHdrZEFBV1B0Uk8vZzNJdFhBdGVmYk5zYjBqc3lyaGFXQzQKLS0tIGtDLzZKYSs1
        UDZyY1M3R2gxVm9jOVhEc2Yzbnhxa1VnV3BGSGRyRjBLK2sK0+9tdwYvg3WsEQY/
        4SFiO4BAv3lPUy5mZtCBMLH+CB6HanjTfZQHJCcm511TxdAy1HVKW+8e7rw8BYT6
        jBkUFA==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZ2lQNWZmcXEvN0VtZmF1
        d0NSZ2wvSENqRXcwUTQyU0kwRkNJNmV3MWlRCmlvSmo0aGhmWWxXWUp3RjNGcCtz
        Y2VaRlNxVXZGcnpQSnZCd1JrUytQNmcKLS0tIEpyVGdETDJPQzAwZ2ZCZThTelBK
        ZU9OYU1GNlBTaHlsQ0g2S1JERnA0SmMKZeyOsrfYtly05s6dGscnOXezSMjnHo5N
        SvcW06rOHMARBDKuyafoxex81wyZ13A8GdVlLhyk4LHFWXjB4QCzXA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-09-17T15:42:14Z"
  mac: ENC[AES256_GCM,data:/Y4Qmn/+IBGi0HpboThL+KCaAm3E1kAUsd9WrN3mtI46aFyXWj0upNZ0QtceaQdAVxUFtUAC29u3l2D44dHDg7vnfvhm2UyK/g2fqUiZbPb3Ug5S1t6nfdG/jTy+LFys01unkodkpx7zzIO6QWwAsvDCuKibvRrl5FZXvenLHiQ=,iv:ayhU1Pp0jaTu/rYf0f4RIQUMG7SpZGcYmMNVozBj49c=,tag:MiE5gsUjNrsEOPmwqwuM5A==,type:str]
  version: 3.13.3
