apiVersion: v1alpha1
kind: HostnameConfig
auto: "off"
hostname: sophons-voltzahl
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBldGRI
        aG1oc1NPWnM0b29mSEEvd3N0YVBsdmpSb0ZHYk54ZjY2azVDVVRzCmlsMC9BTWRz
        bUlkWllUZ1NSNXlMV2kzN0lkM3VCMi8xcUVmblZjSVo3VWcKLS0tIE03akhwYWVL
        QlRERko2TnltRTlTVW9maEdhSUx0MU5YMEVCcDV4bjVzY1EKc8nUaH0bs9Iz8oG9
        VgNDfInhF4wMlaiiTFMOwNTryWCMURPc33Obxonfh5qwt25uFhueKRMO1XOTulgA
        yi12Jw==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFQXg0VWFEaTVvSmVMZFFo
        Slc5bGszUE10WVNPdkovWmRHTmR6dXdOQUQ0CllvUkpXUHRPZmNmS1czWXR6bGJt
        Zmt6dXVTL2Z0bXROeWVZSXR2Wkp5cGMKLS0tIFpvRDNWdXB5d2FGUitqdDBmQnkr
        T0lONzhlOVUyMFpjYUZrS00rTUg0Y0EKoXX74L18IjF8jvIkZGsyHDJ2p4TmhY1w
        3xYWBtBP40Q8U/PEswn65NQUYksVwCKFZpDGKlxcWeB8D0Z+KUqpOA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-09-17T15:42:14Z"
  mac: ENC[AES256_GCM,data:eKXgYbXRZ6ygRY9yCKC3ttvmPUBHw1pVWG1gfnCy/MeDb8rhNn/JS3N/VnIYwW7GgCDN3nE5A3h1iWrKBpxLfYgZ7zp9OTlXvxORG6te8TcwPpU44oPT/OOJGPMr4ZvZ3fOLUgQ3mskVJL/gTgdII+JHyU0b5vgivhpQhlrzDv0=,iv:/TR5mjfUVtxlUdwNW5jSDzeI8YajEfeJC/3wWRpJktw=,tag:M0ceEx7DTTkgG3Fs7zeCCA==,type:str]
  version: 3.13.3
---
apiVersion: v1alpha1
kind: UnattendedInstallConfig
provisioning:
  diskSelector:
    match: disk.dev_path == "/dev/vda"
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBldGRI
        aG1oc1NPWnM0b29mSEEvd3N0YVBsdmpSb0ZHYk54ZjY2azVDVVRzCmlsMC9BTWRz
        bUlkWllUZ1NSNXlMV2kzN0lkM3VCMi8xcUVmblZjSVo3VWcKLS0tIE03akhwYWVL
        QlRERko2TnltRTlTVW9maEdhSUx0MU5YMEVCcDV4bjVzY1EKc8nUaH0bs9Iz8oG9
        VgNDfInhF4wMlaiiTFMOwNTryWCMURPc33Obxonfh5qwt25uFhueKRMO1XOTulgA
        yi12Jw==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFQXg0VWFEaTVvSmVMZFFo
        Slc5bGszUE10WVNPdkovWmRHTmR6dXdOQUQ0CllvUkpXUHRPZmNmS1czWXR6bGJt
        Zmt6dXVTL2Z0bXROeWVZSXR2Wkp5cGMKLS0tIFpvRDNWdXB5d2FGUitqdDBmQnkr
        T0lONzhlOVUyMFpjYUZrS00rTUg0Y0EKoXX74L18IjF8jvIkZGsyHDJ2p4TmhY1w
        3xYWBtBP40Q8U/PEswn65NQUYksVwCKFZpDGKlxcWeB8D0Z+KUqpOA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-09-17T15:42:14Z"
  mac: ENC[AES256_GCM,data:eKXgYbXRZ6ygRY9yCKC3ttvmPUBHw1pVWG1gfnCy/MeDb8rhNn/JS3N/VnIYwW7GgCDN3nE5A3h1iWrKBpxLfYgZ7zp9OTlXvxORG6te8TcwPpU44oPT/OOJGPMr4ZvZ3fOLUgQ3mskVJL/gTgdII+JHyU0b5vgivhpQhlrzDv0=,iv:/TR5mjfUVtxlUdwNW5jSDzeI8YajEfeJC/3wWRpJktw=,tag:M0ceEx7DTTkgG3Fs7zeCCA==,type:str]
  version: 3.13.3
---
apiVersion: v1alpha1
kind: KubeNodeConfig
labels:
  egress.sophons.cloud/ci-ipv6: "true"
  topology.kubernetes.io/region: de
  topology.kubernetes.io/zone: de-east-1
  hugeloads.sophons.cloud/garage: "true"
  cluster.garage.sophons.cloud/global: "true"
  weed.sophons.cloud/cluster: global
  weed.sophons.cloud/master: "true"
  weed.sophons.cloud/volume: "true"
  weed.sophons.cloud/filer: "true"
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBldGRI
        aG1oc1NPWnM0b29mSEEvd3N0YVBsdmpSb0ZHYk54ZjY2azVDVVRzCmlsMC9BTWRz
        bUlkWllUZ1NSNXlMV2kzN0lkM3VCMi8xcUVmblZjSVo3VWcKLS0tIE03akhwYWVL
        QlRERko2TnltRTlTVW9maEdhSUx0MU5YMEVCcDV4bjVzY1EKc8nUaH0bs9Iz8oG9
        VgNDfInhF4wMlaiiTFMOwNTryWCMURPc33Obxonfh5qwt25uFhueKRMO1XOTulgA
        yi12Jw==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFQXg0VWFEaTVvSmVMZFFo
        Slc5bGszUE10WVNPdkovWmRHTmR6dXdOQUQ0CllvUkpXUHRPZmNmS1czWXR6bGJt
        Zmt6dXVTL2Z0bXROeWVZSXR2Wkp5cGMKLS0tIFpvRDNWdXB5d2FGUitqdDBmQnkr
        T0lONzhlOVUyMFpjYUZrS00rTUg0Y0EKoXX74L18IjF8jvIkZGsyHDJ2p4TmhY1w
        3xYWBtBP40Q8U/PEswn65NQUYksVwCKFZpDGKlxcWeB8D0Z+KUqpOA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-09-17T15:42:14Z"
  mac: ENC[AES256_GCM,data:eKXgYbXRZ6ygRY9yCKC3ttvmPUBHw1pVWG1gfnCy/MeDb8rhNn/JS3N/VnIYwW7GgCDN3nE5A3h1iWrKBpxLfYgZ7zp9OTlXvxORG6te8TcwPpU44oPT/OOJGPMr4ZvZ3fOLUgQ3mskVJL/gTgdII+JHyU0b5vgivhpQhlrzDv0=,iv:/TR5mjfUVtxlUdwNW5jSDzeI8YajEfeJC/3wWRpJktw=,tag:M0ceEx7DTTkgG3Fs7zeCCA==,type:str]
  version: 3.13.3
---
apiVersion: v1alpha1
kind: KubeAPIServerConfig
extraArgs:
  # bias to keep more connnections on this guy?
  goaway-chance: ".000001"
resources:
  requests:
    # 10 (arm64) CORES WHOOOHOOOOO (my wallet will never recover from this)
    cpu: 500m
    memory: 2Gi
  limits:
    memory: 3Gi
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBldGRI
        aG1oc1NPWnM0b29mSEEvd3N0YVBsdmpSb0ZHYk54ZjY2azVDVVRzCmlsMC9BTWRz
        bUlkWllUZ1NSNXlMV2kzN0lkM3VCMi8xcUVmblZjSVo3VWcKLS0tIE03akhwYWVL
        QlRERko2TnltRTlTVW9maEdhSUx0MU5YMEVCcDV4bjVzY1EKc8nUaH0bs9Iz8oG9
        VgNDfInhF4wMlaiiTFMOwNTryWCMURPc33Obxonfh5qwt25uFhueKRMO1XOTulgA
        yi12Jw==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFQXg0VWFEaTVvSmVMZFFo
        Slc5bGszUE10WVNPdkovWmRHTmR6dXdOQUQ0CllvUkpXUHRPZmNmS1czWXR6bGJt
        Zmt6dXVTL2Z0bXROeWVZSXR2Wkp5cGMKLS0tIFpvRDNWdXB5d2FGUitqdDBmQnkr
        T0lONzhlOVUyMFpjYUZrS00rTUg0Y0EKoXX74L18IjF8jvIkZGsyHDJ2p4TmhY1w
        3xYWBtBP40Q8U/PEswn65NQUYksVwCKFZpDGKlxcWeB8D0Z+KUqpOA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-09-17T15:42:14Z"
  mac: ENC[AES256_GCM,data:eKXgYbXRZ6ygRY9yCKC3ttvmPUBHw1pVWG1gfnCy/MeDb8rhNn/JS3N/VnIYwW7GgCDN3nE5A3h1iWrKBpxLfYgZ7zp9OTlXvxORG6te8TcwPpU44oPT/OOJGPMr4ZvZ3fOLUgQ3mskVJL/gTgdII+JHyU0b5vgivhpQhlrzDv0=,iv:/TR5mjfUVtxlUdwNW5jSDzeI8YajEfeJC/3wWRpJktw=,tag:M0ceEx7DTTkgG3Fs7zeCCA==,type:str]
  version: 3.13.3
---
# https://tailscale.com/docs/reference/best-practices/performance#linux-optimizations-for-subnet-routers-and-exit-nodes
apiVersion: v1alpha1
kind: EthernetConfig
name: enp7s0
features:
  rx-gro-list: "off"
  rx-udp-gro-forwarding: "on"
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBldGRI
        aG1oc1NPWnM0b29mSEEvd3N0YVBsdmpSb0ZHYk54ZjY2azVDVVRzCmlsMC9BTWRz
        bUlkWllUZ1NSNXlMV2kzN0lkM3VCMi8xcUVmblZjSVo3VWcKLS0tIE03akhwYWVL
        QlRERko2TnltRTlTVW9maEdhSUx0MU5YMEVCcDV4bjVzY1EKc8nUaH0bs9Iz8oG9
        VgNDfInhF4wMlaiiTFMOwNTryWCMURPc33Obxonfh5qwt25uFhueKRMO1XOTulgA
        yi12Jw==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFQXg0VWFEaTVvSmVMZFFo
        Slc5bGszUE10WVNPdkovWmRHTmR6dXdOQUQ0CllvUkpXUHRPZmNmS1czWXR6bGJt
        Zmt6dXVTL2Z0bXROeWVZSXR2Wkp5cGMKLS0tIFpvRDNWdXB5d2FGUitqdDBmQnkr
        T0lONzhlOVUyMFpjYUZrS00rTUg0Y0EKoXX74L18IjF8jvIkZGsyHDJ2p4TmhY1w
        3xYWBtBP40Q8U/PEswn65NQUYksVwCKFZpDGKlxcWeB8D0Z+KUqpOA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-09-17T15:42:14Z"
  mac: ENC[AES256_GCM,data:eKXgYbXRZ6ygRY9yCKC3ttvmPUBHw1pVWG1gfnCy/MeDb8rhNn/JS3N/VnIYwW7GgCDN3nE5A3h1iWrKBpxLfYgZ7zp9OTlXvxORG6te8TcwPpU44oPT/OOJGPMr4ZvZ3fOLUgQ3mskVJL/gTgdII+JHyU0b5vgivhpQhlrzDv0=,iv:/TR5mjfUVtxlUdwNW5jSDzeI8YajEfeJC/3wWRpJktw=,tag:M0ceEx7DTTkgG3Fs7zeCCA==,type:str]
  version: 3.13.3
---
apiVersion: v1alpha1
kind: LinkConfig
name: enp7s0
addresses:
  # enc!
  - address: ENC[AES256_GCM,data:WkR/v+uvg6Pava+zK4g=,iv:iiOxtQZ1aq/kw0tEoCMY8sj3ySF6giBc3dK2hGWa3tM=,tag:7IiF1UDoe42/NFU4MpSm3g==,type:str]
  # enc!
  - address: ENC[AES256_GCM,data:AXolneOS2VRlYu2ooHNDdGeeze3QUw==,iv:rI+d4ToMj/0FBy7v9cFj500UT0mqQyllNyatLuSEq2M=,tag:BawH1hWvXg1WvD0pKRB7iA==,type:str]
routes:
  - metric: 150
    # enc!
    gateway: ENC[AES256_GCM,data:rndFcTpqgBx1ew==,iv:9RA4Mh4bDiNd4EnS1oJJK0ZtB+DH0uh8qyK/0vxk3PU=,tag:LjPBVCliX0raX/6IlGOrLw==,type:str]
  - gateway: fe80::1
    metric: 100
# ---
# apiVersion: v1alpha1
# kind: VolumeConfig
# name: EPHEMERAL
# provisioning:
#   maxSize: 100GiB
# ---
# apiVersion: v1alpha1
# kind: ExtensionServiceConfig
# name: tailscale
# environment:
#   # - TS_ROUTES=10.41.6.0/24,2001:cafe:41:6::/64,fdf6:9420:fade:67::5/128
#   - TS_ROUTES=10.41.6.0/24,2001:cafe:41:6::/64
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBldGRI
        aG1oc1NPWnM0b29mSEEvd3N0YVBsdmpSb0ZHYk54ZjY2azVDVVRzCmlsMC9BTWRz
        bUlkWllUZ1NSNXlMV2kzN0lkM3VCMi8xcUVmblZjSVo3VWcKLS0tIE03akhwYWVL
        QlRERko2TnltRTlTVW9maEdhSUx0MU5YMEVCcDV4bjVzY1EKc8nUaH0bs9Iz8oG9
        VgNDfInhF4wMlaiiTFMOwNTryWCMURPc33Obxonfh5qwt25uFhueKRMO1XOTulgA
        yi12Jw==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFQXg0VWFEaTVvSmVMZFFo
        Slc5bGszUE10WVNPdkovWmRHTmR6dXdOQUQ0CllvUkpXUHRPZmNmS1czWXR6bGJt
        Zmt6dXVTL2Z0bXROeWVZSXR2Wkp5cGMKLS0tIFpvRDNWdXB5d2FGUitqdDBmQnkr
        T0lONzhlOVUyMFpjYUZrS00rTUg0Y0EKoXX74L18IjF8jvIkZGsyHDJ2p4TmhY1w
        3xYWBtBP40Q8U/PEswn65NQUYksVwCKFZpDGKlxcWeB8D0Z+KUqpOA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-09-17T15:42:14Z"
  mac: ENC[AES256_GCM,data:eKXgYbXRZ6ygRY9yCKC3ttvmPUBHw1pVWG1gfnCy/MeDb8rhNn/JS3N/VnIYwW7GgCDN3nE5A3h1iWrKBpxLfYgZ7zp9OTlXvxORG6te8TcwPpU44oPT/OOJGPMr4ZvZ3fOLUgQ3mskVJL/gTgdII+JHyU0b5vgivhpQhlrzDv0=,iv:/TR5mjfUVtxlUdwNW5jSDzeI8YajEfeJC/3wWRpJktw=,tag:M0ceEx7DTTkgG3Fs7zeCCA==,type:str]
  version: 3.13.3
