kind: Deployment
replicas: 2
leaderElection:
  enabled: true

deschedulerPolicy:
  metricsProviders:
    - source: KubernetesMetrics
    - source: Prometheus
      prometheus:
        url: http://vmsingle-klusterstalker.victoriametrics-system.svc.cluster.local:8428/prometheus
  profiles:
    - name: default
      pluginConfig:
        - name: DefaultEvictor
          args:
            podProtections:
              defaultDisabled:
                - "PodsWithLocalStorage"
              extraEnabled:
                - "PodsWithPVC"
        - name: RemoveDuplicates
        - name: RemovePodsHavingTooManyRestarts
          args:
            podRestartThreshold: 100
            includingInitContainers: true
        - name: RemovePodsViolatingNodeAffinity
          args:
            nodeAffinityType:
              - requiredDuringSchedulingIgnoredDuringExecution
        - name: RemovePodsViolatingNodeTaints
        - name: RemovePodsViolatingInterPodAntiAffinity
        - name: RemovePodsViolatingTopologySpreadConstraint
        - name: LowNodeUtilization
          args:
            thresholds:
              cpu: 50
              memory: 40
              pods: 50
            targetThresholds:
              cpu: 95
              memory: 80
              pods: 80
      plugins:
        balance:
          enabled:
            - RemoveDuplicates
            - RemovePodsViolatingTopologySpreadConstraint
            - LowNodeUtilization
        deschedule:
          enabled:
            - RemovePodsHavingTooManyRestarts
            - RemovePodsViolatingNodeTaints
            - RemovePodsViolatingNodeAffinity
            - RemovePodsViolatingInterPodAntiAffinity

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
                - descheduler
        topologyKey: "kubernetes.io/hostname"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi

securityContext:
  seccompProfile:
    type: RuntimeDefault

serviceMonitor:
  enabled: true
