kind: Deployment
replicas: 2
leaderElection:
  enabled: true

deschedulerPolicy:
  metricsProviders:
    - source: KubernetesMetrics
    - source: Prometheus
      prometheus:
        url: http://mimir-mirage.monitoring-system:9009/prometheus
  profiles:
    - name: default
      pluginConfig:
        - name: DefaultEvictor
          args:
            nodeFit: true
            podProtections:
              defaultDisabled:
                - "PodsWithLocalStorage"
              # extraEnabled:
              #   - "PodsWithPVC"
        - name: RemoveDuplicates
        - name: RemovePodsHavingTooManyRestarts
          args:
            podRestartThreshold: 100
            includingInitContainers: true
        - name: RemovePodsViolatingNodeAffinity
          args:
            nodeAffinityType:
              - requiredDuringSchedulingIgnoredDuringExecution
              - preferredDuringSchedulingIgnoredDuringExecution
        - name: RemovePodsViolatingNodeTaints
          args:
            excludedTaints:
              - node.cilium.io/agent-not-ready
        - name: RemovePodsViolatingInterPodAntiAffinity
        - name: RemovePodsViolatingTopologySpreadConstraint
        - name: LowNodeUtilization
          args:
            thresholds:
              cpu: 40
              memory: 40
              pods: 40
            targetThresholds:
              cpu: 70
              memory: 70
              pods: 80
            metricsUtilization:
              source: KubernetesMetrics
      plugins:
        balance:
          enabled:
            - RemoveDuplicates
            - RemovePodsViolatingTopologySpreadConstraint
            - LowNodeUtilization
        deschedule:
          enabled:
            - RemovePodsHavingTooManyRestarts
            - RemovePodsViolatingNodeTaints
            - RemovePodsViolatingNodeAffinity
            - RemovePodsViolatingInterPodAntiAffinity

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
                - descheduler
        topologyKey: "kubernetes.io/hostname"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi

securityContext:
  seccompProfile:
    type: RuntimeDefault

serviceMonitor:
  enabled: true
