apiVersion: batch/v1
kind: CronJob
metadata:
  name: talos-backup
  namespace: kube-system
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure

          containers:
            - name: talos-backup
              image: ghcr.io/siderolabs/talos-backup:v0.1.0-beta.3-4-gff85670
              command:
                - /talos-backup
              workingDir: /tmp

              envFrom:
                - secretRef:
                    name: etcdeez-access-key
              env:
                - name: AWS_REGION
                  value: eu-central-003
                - name: CUSTOM_S3_ENDPOINT
                  value: https://s3.eu-central-003.backblazeb2.com
                - name: BUCKET
                  value: sophons-etcd
                - name: CLUSTER_NAME
                  value: "sophons"
                # AGE_X25519_PUBLIC_KEY supports multiple recipients as comma-separated keys
                - name: AGE_X25519_PUBLIC_KEY
                  value: "age18rlk0e9zffpfn49cdjyjy2gdemu0ayn4rn3vdwfrml4nf8wvjq6qe009d6"
                # If enabled, snapshot will be compressed with zstd algorithm
                - name: ENABLE_COMPRESSION
                  value: "true"

              securityContext:
                runAsUser: 1000
                runAsGroup: 1000
                allowPrivilegeEscalation: false
                runAsNonRoot: true
                capabilities:
                  drop:
                    - ALL
                seccompProfile:
                  type: RuntimeDefault

              volumeMounts:
                - mountPath: /tmp
                  name: tmp
                - mountPath: /var/run/secrets/talos.dev
                  name: talos-secrets

          volumes:
            - emptyDir: {}
              name: tmp
            - name: talos-secrets
              secret:
                secretName: talos-backup-secrets
---
apiVersion: talos.dev/v1alpha1
kind: ServiceAccount
metadata:
  name: talos-backup-secrets
  namespace: kube-system
spec:
  roles:
    - os:etcd:backup
---
apiVersion: v1
kind: Secret
metadata:
  name: talos-backup-secrets
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: talos-backup-secrets
---

