# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.35.2/service.json
apiVersion: v1
kind: Service
metadata:
  name: promstack
  namespace: monitoring-system
spec:
  ports:
    - name: grpc
      port: 10901
    - name: http
      port: 10902
  selector: {}
