configMapGenerator:
  - name: litestream-env
    literals:
      - LITESTREAM_RETENTION=168h # 7d
      - LITESTREAM_SYNC_INTERVAL=1s
      - LITESTREAM_SNAPSHOT_INTERVAL=1h
      - LITESTREAM_VALIDATION_INTERVAL=12
      - LITESTREAM_LOGGING_LEVEL=info
      - LITESTREAM_PROMETHEUS_ADDRESS=:9090
