# yaml-language-server: $schema=https://github.com/kubernetes-sigs/external-dns/raw/refs/tags/v0.21.0/charts/external-dns/values.schema.json
logLevel: debug
extraArgs:
  txt-wildcard-replacement: "w-c"
  cloudflare-proxied: true
  # Don't want wildcard DNS records when creating wildcard SSL certs
  ignore-ingress-tls-spec: true

policy: sync
provider:
  name: cloudflare
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cf-dns-api-token
        key: CLOUDFLARE_API_TOKEN
  - name: GOMEMLIMIT
    valueFrom:
      resourceFieldRef:
        resource: limits.memory

txtPrefix: ed-%{record_type}.
sources: [crd, service]
managedRecordTypes: [A, AAAA, CNAME, TXT]

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    memory: 128Mi

serviceMonitor:
  enabled: true
