# yaml-language-server: $schema=https://github.com/kubernetes-sigs/external-dns/raw/refs/tags/v0.21.0/charts/external-dns/values.schema.json
logLevel: debug
extraArgs:
  txt-prefix: "_ed-%{record_type}."
  cloudflare-proxied: true
  # Don't want wildcard DNS records when creating wildcard SSL certs
  ignore-ingress-tls-spec: true

policy: sync
provider:
  name: cloudflare
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cf-dns-api-token
        key: CLOUDFLARE_API_TOKEN
  - name: GOMEMLIMIT
    valueFrom:
      resourceFieldRef:
        resource: limits.memory

sources:
  - crd
  - service

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    memory: 128Mi

serviceMonitor:
  enabled: true
