# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.34.1/namespace.json
apiVersion: v1
kind: Namespace
metadata:
  name: flux-system
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: flux-operator
  namespace: flux-system
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  inputs:
    - version: "0.60.0"
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: OCIRepository
      metadata:
        name: << inputs.provider.name >>
        namespace: << inputs.provider.namespace >>
      spec:
        interval: 1h
        url: oci://ghcr.io/controlplaneio-fluxcd/charts/flux-operator
        layerSelector:
          mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
          operation: copy
        ref:
          semver: << inputs.version | quote >>
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: << inputs.provider.name >>
        namespace: << inputs.provider.namespace >>
      spec:
        interval: 1h
        releaseName: << inputs.provider.name >>
        serviceAccountName: << inputs.provider.name >>
        chartRef:
          kind: OCIRepository
          name: << inputs.provider.name >>
        values:
          resources:
            requests:
              cpu: 25m
            limits:
              cpu: null
              memory: 300Mi

          serviceMonitor:
            enabled: true

        postRenderers:
          - kustomize:
              patches:
                - target:
                    kind: Deployment
                    name: flux-operator
                  patch: |-
                    - op: add
                      path: /spec/template/spec/tolerations
                      value:
                        - key: caeneus.sophons.cloud
                          operator: Exists
                        - key: CriticalAddonsOnly
                          operator: Exists
                    - op: add
                      path: /spec/template/spec/containers/0/env/-
                      value:
                        name: KUBERNETES_SERVICE_HOST
                        value: 2001:cafe:43::2
                    - op: add
                      path: /spec/template/spec/containers/0/env/-
                      value:
                        name: GOGC
                        value: "10"
                    - op: add
                      path: /spec/template/spec/containers/0/env/-
                      value:
                        name: GOMEMLIMIT
                        valueFrom:
                          resourceFieldRef:
                            resource: limits.memory
---
apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    fluxcd.controlplane.io/reconcileEvery: 1h
    fluxcd.controlplane.io/reconcileArtifactEvery: 10m
    fluxcd.controlplane.io/reconcileTimeout: 5m
spec:
  cluster:
    size: small
  distribution:
    version: 2.9.5
    registry: ghcr.io/fluxcd
  sync:
    kind: OCIRepository
    interval: 1m
    url: oci://oci.sphns.run/p/cluster/manifests
    ref: latest
    path: sophons
    pullSecret: flux-oci-pull
  components:
    - source-watcher
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
    - image-reflector-controller
    - image-automation-controller
  kustomize:
    patches:
      - target:
          kind: Deployment
        patch: |-
          - op: replace
            path: /spec/template/spec/nodeSelector
            value:
              kubernetes.io/os: linux
          - op: add
            path: /spec/template/spec/tolerations
            value:
              - key: caeneus.sophons.cloud
                operator: Exists
              - key: CriticalAddonsOnly
                operator: Exists
          - op: replace
            path: /spec/template/spec/nodeSelector
            value:
              kubernetes.io/os: linux
          - op: add
            path: /spec/template/spec/affinity
            value:
              nodeAffinity:
                preferredDuringSchedulingIgnoredDuringExecution:
                  - preference:
                      matchExpressions:
                        - key: kubernetes.io/hostname
                          operator: In
                          values: [sophons-caeneus]
                    weight: 67
          - op: add
            path: /spec/template/spec/containers/0/env/-
            value:
              name: KUBERNETES_SERVICE_HOST
              value: 2001:cafe:43::2
          - op: add
            path: /spec/template/spec/containers/0/env/-
            value:
              name: GOGC
              value: "10"
          - op: replace
            path: /spec/template/spec/containers/0/resources/requests
            value:
              cpu: 15m
              memory: 48Mi

      - target:
          kind: Deployment
          name: (kustomize|helm)-controller
        patch: |-
          - op: replace
            path: /spec/template/spec/containers/0/resources/requests
            value:
              cpu: 30m
              memory: 100Mi

      - target:
          kind: Deployment
          name: source-controller
        patch: |-
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --feature-gates=ObjectLevelWorkloadIdentity=true
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --default-service-account=source-controller

      - target:
          kind: Deployment
          name: kustomize-controller
        patch: |-
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --sops-age-secret=flux-sops-age

      - target:
          kind: Kustomization
        patch: |-
          - op: add
            path: /spec/decryption
            value:
              provider: sops
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: forwardauth-authelia
  namespace: flux-system
spec:
  chain:
    middlewares:
      - name: forwardauth-authelia
        namespace: authelia
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nlamirault/schema-hub/main/schemas/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: flux-operator-web
  namespace: flux-system
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "FluxCD Operator"
    gethomepage.dev/name: Flux Operator
    gethomepage.dev/app: flux-operator
    gethomepage.dev/icon: flux-operator.svg
    gethomepage.dev/group: Admin
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
      sectionName: websecure

  hostnames:
    - flux.sophons.cloud

  rules:
    - filters:
        # TODO: oidc in flux web directly
        - type: ExtensionRef
          extensionRef:
            group: traefik.io
            kind: Middleware
            name: forwardauth-authelia
      backendRefs:
        - name: flux-operator
          port: 9080
