crds:
  enabled: false

defaultRules:
  create: true
  rules:
    etcd: false
    alertmanager: false
    prometheus: false
    prometheusOperator: false
    windows: false
    kubeProxy: false

    configReloaders: true
    general: true
    k8sContainerCpuUsageSecondsTotal: true
    k8sContainerMemoryCache: true
    k8sContainerMemoryRss: true
    k8sContainerMemorySwap: true
    k8sContainerResource: true
    k8sContainerMemoryWorkingSetBytes: true
    k8sPodOwner: true
    kubeApiserverAvailability: true
    kubeApiserverBurnrate: false
    kubeApiserverHistogram: false
    kubeApiserverSlos: false
    kubeControllerManager: true
    kubelet: true
    kubePrometheusGeneral: false
    kubePrometheusNodeRecording: false
    kubernetesApps: false
    kubernetesResources: false
    kubernetesStorage: false
    kubernetesSystem: true
    kubeStateMetrics: true
    kubeSchedulerAlerting: true
    kubeSchedulerRecording: true
    network: true
    node: true
    nodeExporterAlerting: true
    nodeExporterRecording: true

prometheusOperator:
  enabled: false
prometheus:
  enabled: false
alertmanager:
  enabled: false
  forceDeployDashboards: true
nodeExporter:
  enabled: false
  forceDeployDashboards: true
kubeStateMetrics:
  enabled: false

kubernetesServiceMonitors:
  enabled: false
kubeApiServer:
  enabled: true # needed for dashboard deployment
kubelet:
  enabled: false
kubeControllerManager:
  enabled: false
coreDns:
  enabled: false
kubeDns:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
windowsMonitoring:
  enabled: false

grafana:
  enabled: false
  forceDeployDashboards: true
  defaultDashboardsEnabled: true
