apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: birb
  namespace: woodpecker-system
spec:
  endpoints:
    - dnsName: ic.vrtx.sh
      recordType: CNAME
      targets:
        - cfd-traefik.sophons.cloud
    - dnsName: ci.sophons.cloud
      recordType: CNAME
      targets:
        - cfd-traefik.sophons.cloud
