# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.36.1/persistentvolumeclaim.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cache-lib-docker
  namespace: woodpecker-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 67Gi
  storageClassName: local-path
---
# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.36.1/persistentvolume-v1.json
apiVersion: v1
kind: PersistentVolume
metadata:
  name: woodpecker-system-cache-docker
spec:
  claimRef:
    namespace: woodpecker-system
    name: cache-docker
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""
  local:
    path: /var/lib/garage/backup/less-big-boi/woodpecker-cache-docker
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - sophons-caeneus
---
# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.36.1/persistentvolumeclaim-v1.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cache-docker
  namespace: woodpecker-system
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 100Gi
  volumeName: woodpecker-system-cache-docker
