[tool_alias]
zli = "github:project-zot/zot"

[tools]
helm = "3.21.0"
kubectl = "1.34.1"
"aqua:sarub0b0/kubetui" = "1.7.1"
kustomize = "5.8.1"
age = "1.2.1"
sops = "3.11.0"
talosctl = "1.13.4"
"ubi:cozystack/talm" = "0.16.2"
cosign = "3.0.2"
watchexec = "2.3.2"
cilium-cli = "0.19.2"
etcd = "3.5.24"
yq = "4.45.4"
"pipx:b2" = "4.4.2"
bun = "1.3.5"
"npm:@karakeep/cli" = "latest"
jj = "0.35.0"
cilium-hubble = "1.19.3"
"aqua:cloudnative-pg/cloudnative-pg/kubectl-cnpg" = "1.27.1"
ripsecrets = "0.1.11"
pre-commit = "4.4.0"
"aqua:juanfont/headscale" = "0.27.1"
rust = "1.92.0"
aws-cli = { version = "2.33.27", symlink_bins = "true" }
"cargo:stu" = "0.7.6"
"aqua:utkuozdemir/pv-migrate" = "2.2.1"
mc = "RELEASE.2025-08-13T08-35-41Z"
argocd = "3.3.2"
regctl = "0.11.2"
regsync = "0.11.2"
"aqua:ViRb3/wgcf" = "2.2.30"
"go:github.com/simulot/immich-go" = "0.31.0"


[tools.zli]
version = "2.1.17"
platforms.linux-x64 = { asset_pattern = "zli-linux-amd64" }
platforms.linux-arm64 = { asset_pattern = "zli-linux-arm64" }

[env]
'_'.file = ["{{config_root}}/.env"]
'_'.path = ["{{config_root}}/bin"]

REPO_ROOT = "{{config_root}}"
KUBECONFIG = "{{config_root}}/kubeconfig"
TALOSCONFIG = "{{config_root}}/talosconfig"
HEADSCALE_CLI_ADDRESS = "gghs.vrtx.sh:443"
TALOS_VERSION = "v1.13.4"

[settings]
npm.bun = true

[tasks.b2]
run = "docker run --rm -it -e B2_APPLICATION_KEY -e B2_APPLICATION_KEY_ID backblazeit/b2:4.4.2"

[tasks.'helm:kustomized']
dir = "{{ cwd }}"
usage = """
arg "<command>"
flag "-n --namespace <namespace>"
flag "-f --values <values>"
arg "<rest>" var=#true
"""
run = """
eval "rest=(${usage_rest?})"
helm --namespace {{ usage.namespace }} {{ usage.command }} \
  --post-renderer kustomizer --post-renderer-args $(dirname "{{ usage.values }}") \
  --values "{{ usage.values }}" "${rest[@]}"
"""

[tasks.'helm:diff:kustomized']
dir = "{{ cwd }}"
usage = """
arg "<command>"
flag "-n --namespace <namespace>"
flag "-f --values <values>"
arg "<rest>" var=#true
"""
run = """
eval "rest=(${usage_rest?})"
helm --namespace {{ usage.namespace }} diff {{ usage.command }} \
  --post-renderer kustomizer --post-renderer-args $(dirname "{{ usage.values }}") \
  --values "{{ usage.values }}" "${rest[@]}"
"""
