# yaml-language-server: $schema=https://raw.githubusercontent.com/nlamirault/schema-hub/main/schemas/cilium.io/ciliumclusterwidenetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: iperftreefiddy
spec:
  description: "Allow iperf3"
  nodeSelector:
    matchLabels:
      sophons.cloud/iperftreefiddy: "true"
  ingress:
    - toPorts:
        - ports:
            - port: "5201"
              protocol: TCP
            - port: "5201"
              protocol: UDP
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nlamirault/schema-hub/main/schemas/cilium.io/ciliumclusterwidenetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: dhcpv6
spec:
  description: "Allow DHCPv6 responses"
  nodeSelector:
    matchLabels:
      nwpolicy.sophons.cloud/dhcpv6: "true"
  ingress:
    - toPorts:
        - ports:
            - port: "546"
              protocol: UDP
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nlamirault/schema-hub/main/schemas/cilium.io/ciliumclusterwidenetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: fayawall
spec:
  description: "Default node firewall"
  nodeSelector:
    matchLabels:
      sophons.cloud/fayawall: "true"
  ingress:
    - fromEntities:
        - cluster
        - health
        - kube-apiserver

    - fromCIDRSet:
        - cidrGroupRef: private-ranges

    - toPorts:
        - ports:
            # etcd-client
            - port: "2379"
              protocol: TCP
            # etcd-peer
            - port: "2380"
              protocol: TCP
            # health checks?
            # cilium binds to the internalip for these
            # - port: "4240"
            #   protocol: TCP
            # geneve
            # - port: "6081"
            #   protocol: UDP
            # apiserver
            - port: "6443"
              protocol: TCP
            # vxlan
            # - port: "8472"
            #   protocol: UDP
            # tailscale
            - port: "41641"
              protocol: UDP
            # talos
            - port: "50000"
              protocol: TCP
            # wireguards
            - port: "51867"
              protocol: UDP
            - port: "51868"
              protocol: UDP
            - port: "51869"
              protocol: UDP
            - port: "51870"
              protocol: UDP

    - icmps:
        - fields:
            - type: EchoRequest
              family: IPv4
            - type: EchoRequest
              family: IPv6
            - type: EchoReply
              family: IPv4
            - type: EchoReply
              family: IPv6
