apiVersion: cilium.io/v2
kind: CiliumCIDRGroup
metadata:
  name: private-ranges
spec:
  externalCIDRs:
    - 10.0.0.0/8
    - 10.67.0.0/16
    - fdf6:9420:fade::/48
    - 100.64.0.0/10
    - fd7a:115c:a1e0::/48
