# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1/daemonset.json
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cilium-host-node-cidr
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: cilium-host-node-cidr
  template:
    metadata:
      name: cilium-host-node-cidr
      labels:
        app: cilium-host-node-cidr
    spec:
      hostNetwork: true
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: Exists
        - key: "node-role.kubernetes.io/control-plane"
          operator: Exists
      containers:
        - name: cilium-host-node-cidr
          image: alpine:3.22
          imagePullPolicy: Always
          command:
            - /bin/sh
            - -c
            - |
              apk update
              apk add iproute2

              handle_error() {
                echo "$1"
                sleep "$SLEEP_TIME"
              }

              echo "Watching cilium_host IP addresses..."

              while :; do
                # Extract all IPv4 addresses from cilium_host
                ip_addresses=$(ip -4 addr show dev cilium_host |grep inet | awk '{print $2}')
                ip6_addresses=$(ip -6 addr show dev cilium_host |grep inet6 | awk '{print $2}')

                # Check if any of the IP addresses match the NODE_CIDR_MASK_SIZE
                echo "$ip_addresses" | grep -q "/${NODE_CIDR_MASK_SIZE}" || {

                  # Extract the /32 IP address if NODE_CIDR_MASK_SIZE was not found
                  pod_ip=$(echo "$ip_addresses" | grep "/32" | cut -d/ -f1)

                  if [ -z "$pod_ip" ]; then
                    handle_error "Couldn't extract cilium pod IP address from cilium_host interface"
                    continue
                  fi

                  # Add secondary IP address with the proper NODE_CIDR_MASK_SIZE
                  echo "cilium_host IP is $pod_ip"
                  ip addr add "${pod_ip}/${NODE_CIDR_MASK_SIZE}" dev cilium_host

                  echo "Added new cilium_host IP address with mask /${NODE_CIDR_MASK_SIZE}"
                  ip addr show dev cilium_host
                }

                # Check if any of the IP addresses match the NODE_V6_CIDR_MASK_SIZE
                echo "$ip6_addresses" | grep -q "/${NODE_V6_CIDR_MASK_SIZE}" || {

                  # Extract the /128 IP address if NODE_V6_CIDR_MASK_SIZE was not found
                  pod_ip=$(echo "$ip6_addresses" | grep "/128" | cut -d/ -f1)

                  if [ -z "$pod_ip" ]; then
                    handle_error "Couldn't extract cilium pod IPv6 address from cilium_host interface"
                    continue
                  fi

                  # Replace IP address with the proper NODE_V6_CIDR_MASK_SIZE
                  echo "cilium_host IP is $pod_ip/128, replacing with: ${pod_ip}/${NODE_V6_CIDR_MASK_SIZE}"
                  ip -6 addr del "${pod_ip}/128" dev cilium_host && \
                  ip -6 addr add "${pod_ip}/${NODE_V6_CIDR_MASK_SIZE}" dev cilium_host

                  echo "Added new cilium_host IP address with mask /${NODE_V6_CIDR_MASK_SIZE}"
                  ip -6 addr show dev cilium_host
                }

                sleep "$SLEEP_TIME"
              done
          env:
            # The node cidr mask size (IPv4) to allocate pod IPs
            - name: NODE_CIDR_MASK_SIZE
              value: "24"
            - name: NODE_V6_CIDR_MASK_SIZE
              value: "64"
            - name: SLEEP_TIME
              value: "30"
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
