apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: harbor
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:18.1-minimal-trixie

  # TODO: Eventually the cluster breaks because of one problem or the other,
  # and the WAL streaming may also backup the problem :)
  instances: 2
  failoverDelay: 60

  affinity:
    nodeSelector:
      hugeloads.sophons.cloud/postgres: "true"
      topology.kubernetes.io/region: ng
    enablePodAntiAffinity: true # Default value
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required

  postgresql:
    synchronous:
      method: any
      number: 1
      failoverQuorum: true
      dataDurability: preferred
    parameters:
      shared_buffers: "64MB"
      max_wal_size: "256MB"
      min_wal_size: "64MB"
      wal_keep_size: "512MB"
      max_slot_wal_keep_size: "512MB"
      wal_receiver_timeout: 120s
      wal_sender_timeout: 120s

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 256Mi

  storage:
    storageClass: longhorn-local
    size: 5Gi

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: pgbooze
        serverName: v2
