tempo:
  tag: 2.10.8
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 512Mi
  extraEnv:
    - name: GOGC
      value: "5"
    - name: GOMEMLIMIT
      valueFrom:
        resourceFieldRef:
          resource: limits.memory
  extraEnvFrom:
    - secretRef:
        name: stalker-access-key
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: [ALL]
    readOnlyRootFilesystem: true
    seccompProfile:
      type: RuntimeDefault

  retention: 24h
  memBallastSizeMbs: 0
  reportingEnabled: false
  multitenancyEnabled: false
  streamOverHttpEnabled: true

  overrides:
    per_tenant_override_config: /runtime/runtime.yaml

  metricsGenerator:
    enabled: true
    remoteWriteUrl: http://mimir-mirage:9009/api/v1/push
    storage:
      path: /tmp/tempo/blocks
    traces_storage:
      path: /tmp/tempo/traces

  querier:
    trace_by_id:
      query_timeout: 30s
    search:
      query_timeout: 60s
  storage:
    trace:
      backend: s3
      s3:
        bucket: monitoring
        prefix: tempo/
        endpoint: s3-global-nogw.garage:3900
        insecure: true
        forcepathstyle: true
        enable_dual_stack: true
      wal:
        path: /tmp/tempo/wal
  extraVolumeMounts:
    - mountPath: /tmp
      name: tmp
    - mountPath: /runtime
      name: tempo-runtime

persistence:
  enabled: false
priorityClassName: system-node-critical
tolerations:
  - key: caeneus.sophons.cloud
    operator: Exists
affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
            - key: topology.kubernetes.io/region
              operator: In
              values: [ng]
        weight: 69
      - preference:
          matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: [sophons-voltzahl]
        weight: 42

serviceMonitor:
  enabled: true

extraVolumes:
  - name: tmp
    emptyDir: {}
  - name: tempo-runtime
    configMap:
      name: tempo-runtime
