namePrefix: mimir-mirage-

resources:
  - statefulset.yaml
  - ../config
  - ../../../garage/access-keys/stalker
components:
  - ../../../../common/litestream
  - ../../../../common/litestream/juicefs-defaults
  - ../../../../common/litestream/templ-config
