# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.34.1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: gitea-config
  namespace: gitea
type: Opaque
# enc!
stringData:
  oauth2: ENC[AES256_GCM,data:FOfvxucUrvhAm5RhKKS/LGuDpoe4xCbGyDvMofOAskZWvAjiZtYRLEcI3g0Fvf2sv8ekILnpgZjS,iv:9MWCEnHlgM6Air5T1bqLQSsuiCFBtCY8nZ2DBWPm0A0=,tag:2WkfV5uk/lHYlMXqJrP3LQ==,type:str]
  server: ENC[AES256_GCM,data:2+xOmNmNsr/Gf3T+D5dNrw+F1Kb+PRejQyi81wlaGLgBkKp6QhG5Scpg53oFd7CRRNXWeaJcCeOT9bHukQ==,iv:PlrP9lR9Ter4rSOE0+ZuVE/JVFUaRvY+v2UdM1TMa+0=,tag:fb5XDv3UCRgvWnrPIpfuuQ==,type:str]
  security: ENC[AES256_GCM,data:2PXHXjv1TfypanvmRn0K8ckcIypPaE20poERyD9O8+D52kXDYyurXeX7JOGeNYyfH49ETpEvct/d7TyXW+JB/fcWSgvqKTLnTHegDl6usyuNgOBJAa+mvVGz6p+dLf3LXKazReKa06SY2KRTOwGDwNm8kENTIHPUHEbxGuISOSNbrWxmO44rL4rVoHgGmVfCedrzwEqzKLpS8bSNoEtIsVe8JSZOngweEgJDf9beU5fTQixGIiuhuMSzPjLfXtUgIOOi2YAgQkNO,iv:G8I62WiRkgwyJrY+6Yt5/INkyx5UnpYLIRGRe6RzLK4=,tag:j9uJa+JTuZy8iVyRu/o8Wg==,type:str]
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBWN2V0
        L2VKZC9LTlFGOVk4Y0tYMnorYXlmM1FZMmdta1ZmK3RtRllGaVhBClp5cjMxdTJW
        UHIrbEZBanMzUHJCRUhtbCtWRWNvMHlaZ01CRmM5Nmk4cHcKLS0tIGwva081aUNn
        ZHZnOTFQYUo0TU8zZ2xVS1p2TTB3SFNSK0dzYnY3T1dLc28Ka8yfq9r+daXmu+Qe
        JMCLoxDdbtJHKYmwvk+4/7G27Imp9pUp9usnFWKSSf+s0pnGH4LeVva5JiGjzL5L
        eShfYw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbXpRU1R2NE9LU3V5M1Nv
        Z0RMQ1ZSbHVqR1pQYUVEd1NOdG0wRkVGWVVNCi9rclMxOVBwODlUVWphWU14RTNG
        aUxXbitlekxiblFQeEJ2bWN3K0pRUVkKLS0tIEVpa0lxV1MvSDRzbU9BRVkwMUFs
        TEZ1UVFiTEhEYk1ZN0FnMGxNVGdZbFUKXLtpCE3GN1a3YcNWRVP7B/fN4pN54v6s
        K8Kony6qiT3ONmJ6rnZ9MuTOGUBiztORvTniz8mwqs3q1MHtMbcnzA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-20T00:56:21Z"
  mac: ENC[AES256_GCM,data:HXcT4mGTATe91FWLLy73YlbpS+nIepiHCneQCQzSMCdbh3Db/HLPsguEPvu//ZXAJ0D5jf4KrssnTJcpMGh/IukAv8NshCIQMv4y3tKTIJC0XGoUuj3vQpZwJ04HG3vnoCjzRvR6VydbEch4+/APZ3TAXbcLfrA8iI5lQ0AOve8=,iv:eo1DZ1amkLDGHvb2k0v9fcLaoag7zcuYnGyg+XY2YPE=,tag:GhdF3G8UqaHOzOwyc3+0zw==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.34.1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: gitea-runner
  namespace: gitea
type: Opaque
# enc!
stringData:
  GITEA_RUNNER_REGISTRATION_TOKEN: ENC[AES256_GCM,data:RqFjsiuXx58JJDFySvdYbZgduoey/yqsZZfgDH2zTY/olT1jw98JOIAy6KfOYlIDSvcDqMe0Ja79T5J0A92dF2yNtj8=,iv:s2W78MDSqr2N/2LiwjlHL9CFuFYSDfBDi6lMzXPkC7U=,tag:gS6Np/Fd1yVigUrVCFUGkw==,type:str]
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBWN2V0
        L2VKZC9LTlFGOVk4Y0tYMnorYXlmM1FZMmdta1ZmK3RtRllGaVhBClp5cjMxdTJW
        UHIrbEZBanMzUHJCRUhtbCtWRWNvMHlaZ01CRmM5Nmk4cHcKLS0tIGwva081aUNn
        ZHZnOTFQYUo0TU8zZ2xVS1p2TTB3SFNSK0dzYnY3T1dLc28Ka8yfq9r+daXmu+Qe
        JMCLoxDdbtJHKYmwvk+4/7G27Imp9pUp9usnFWKSSf+s0pnGH4LeVva5JiGjzL5L
        eShfYw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbXpRU1R2NE9LU3V5M1Nv
        Z0RMQ1ZSbHVqR1pQYUVEd1NOdG0wRkVGWVVNCi9rclMxOVBwODlUVWphWU14RTNG
        aUxXbitlekxiblFQeEJ2bWN3K0pRUVkKLS0tIEVpa0lxV1MvSDRzbU9BRVkwMUFs
        TEZ1UVFiTEhEYk1ZN0FnMGxNVGdZbFUKXLtpCE3GN1a3YcNWRVP7B/fN4pN54v6s
        K8Kony6qiT3ONmJ6rnZ9MuTOGUBiztORvTniz8mwqs3q1MHtMbcnzA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-20T00:56:21Z"
  mac: ENC[AES256_GCM,data:HXcT4mGTATe91FWLLy73YlbpS+nIepiHCneQCQzSMCdbh3Db/HLPsguEPvu//ZXAJ0D5jf4KrssnTJcpMGh/IukAv8NshCIQMv4y3tKTIJC0XGoUuj3vQpZwJ04HG3vnoCjzRvR6VydbEch4+/APZ3TAXbcLfrA8iI5lQ0AOve8=,iv:eo1DZ1amkLDGHvb2k0v9fcLaoag7zcuYnGyg+XY2YPE=,tag:GhdF3G8UqaHOzOwyc3+0zw==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
