namespace: pihole
labels:
  - pairs:
      app.kubernetes.io/name: pihole
    includeSelectors: true
    includeTemplates: true

resources:
  - role.yaml
  - service.yaml
  - rolebinding.yaml
  - statefulset.yaml
  - serviceaccount.yaml
components:
  - ../../common/tailscale
  - ../../common/tailscale/auth

configMapGenerator:
  - name: pihole
    files:
      - config/adlists.list
      - config/blacklist.txt
      - config/dnsmasq.conf
