namespace: pihole
labels:
  - pairs:
      app.kubernetes.io/name: pihole
    includeSelectors: true
    includeTemplates: true

resources:
  - primary
  - secondary
  - role.yaml
  - rolebinding.yaml
  - serviceaccount.yaml
  - poddisruptionbudget.yaml
components:
  - ../../common/tailscale
  - ../../common/tailscale/auth

images:
  - name: ghcr.io/pi-hole/pihole
    newTag: 2026.07.2

configMapGenerator:
  - name: pihole
    files:
      - config/adlists.list
      - config/blacklist.txt
      - config/configure.sh
    envs: [.env]
