# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.34.1/rolebinding.json
# Copyright (c) Tailscale Inc & AUTHORS
# SPDX-License-Identifier: BSD-3-Clause
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale
  namespace: pihole
subjects:
  - kind: ServiceAccount
    name: pihole
roleRef:
  kind: Role
  name: tailscale
  apiGroup: rbac.authorization.k8s.io
