# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.34.1/statefulset-apps-v1.json
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: necronomicon
  labels:
    app.kubernetes.io/instance: necronomicon
spec:
  replicas: 2
  serviceName: necronomicon-cluster-dns
  selector:
    matchLabels:
      app.kubernetes.io/instance: necronomicon
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: necronomicon
    spec:
      hostUsers: false
      serviceAccountName: pihole

      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/instance: necronomicon
          maxSkew: 1
          minDomains: 2
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule

      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: topology.kubernetes.io/region
                    operator: In
                    values: [ng]
              weight: 100

      securityContext:
        seccompProfile:
          type: RuntimeDefault

      # dnsPolicy: None
      # dnsConfig:
      #   nameservers:
      #     - 1.1.1.1
      #     - 9.9.9.9
      # hostAliases:
      #   - ip: 10.43.0.69
      #     hostnames:
      #       - hs.vrtx.sh
      #   - ip: 2001:cafe:43::69
      #     hostnames:
      #       - hs.vrtx.sh

      containers:
        - name: pihole
          image: ghcr.io/pi-hole/pihole:2026.04.1

          ports:
            - containerPort: 53
              protocol: TCP
              name: dns-tcp
            - containerPort: 53
              protocol: UDP
              name: dns-udp
            - containerPort: 80
              protocol: TCP
              name: http

          env:
            - name: TZ
              value: Africa/Lagos
            - name: PIHOLE_UID
              value: "1000"
            - name: PIHOLE_GID
              value: "1000"
            - name: FTLCONF_webserver_api_password
              value: ""
            - name: FTLCONF_dns_listeningMode
              value: "ALL"
            - name: FTLCONF_dns_upstreams
              value: "1.1.1.1;1.0.0.1;9.9.9.9;149.112.112.112"
            - name: FTLCONF_misc_dnsmasq_lines
              valueFrom:
                configMapKeyRef:
                  key: dnsmasq.conf
                  name: pihole

          volumeMounts:
            - mountPath: /etc/pihole
              name: pihole
            - mountPath: /etc/pihole/adlists.list
              name: pihole-config
              subPath: adlists.list
              readOnly: true
            - mountPath: /etc/pihole/blacklist.txt
              name: pihole-config
              subPath: blacklist.txt
              readOnly: true

          startupProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  dig -p $(pihole-FTL --config dns.port) +short +norecurse +retry=0 @127.0.0.1 pi.hole || exit 1
            timeoutSeconds: 5
            failureThreshold: 20
            initialDelaySeconds: 30

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  dig -p $(pihole-FTL --config dns.port) +short +norecurse +retry=0 @127.0.0.1 pi.hole || exit 1
            timeoutSeconds: 5
            failureThreshold: 5

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  dig -p $(pihole-FTL --config dns.port) +short +norecurse +retry=0 @127.0.0.1 pi.hole || exit 1
            timeoutSeconds: 5
            failureThreshold: 5
            initialDelaySeconds: 60

          resources:
            requests:
              cpu: 150m
              memory: 256Mi
            limits:
              memory: 256Mi

      initContainers:
        - name: tailscale
          image: ghcr.io/tailscale/tailscale
          restartPolicy: Always

          ports:
            - containerPort: 9002
              name: ts-metrics

          envFrom:
            - configMapRef:
                name: tailscale-config
            - secretRef:
                name: tailscale-auth

          env:
            - name: GOMEMLIMIT
              value: 100MiB
            - name: TS_EXTRA_ARGS
              value: $(TS_BASE_ARGS)
            - name: TS_TAILSCALED_EXTRA_ARGS
              value: $(TSD_BASE_ARGS)
            - name: TS_KUBE_SECRET
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: TS_AUTH_ONCE
              value: "true"
            - name: TS_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: TS_USERSPACE
              value: "false"
            - name: TS_DEBUG_FIREWALL_MODE
              value: nftables
            # - name: TS_DEST_IP
            #   value: "127.0.0.1"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid

          volumeMounts:
            - mountPath: /tmp
              name: tmp
              subPath: ts

          securityContext:
            privileged: true
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ALL]
              add: [NET_ADMIN]

          startupProbe:
            httpGet:
              path: /healthz
              port: ts-metrics
            failureThreshold: 15
            initialDelaySeconds: 10

          livenessProbe:
            httpGet:
              path: /healthz
              port: ts-metrics
            failureThreshold: 5

          readinessProbe:
            httpGet:
              path: /healthz
              port: ts-metrics
            failureThreshold: 5

          resources:
            requests:
              cpu: 75m
              memory: 64Mi
            limits:
              memory: 128Mi

      volumes:
        - name: pihole
          emptyDir: {}
        - name: pihole-config
          configMap:
            name: pihole
        - name: tmp
          emptyDir: {}
---
# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.34.1/statefulset-apps-v1.json
# TODO: For some reason, i can't LB to the necronomicon pods so these act as a proxy in my home network
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: darkhold
  labels:
    app.kubernetes.io/instance: darkhold
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: darkhold
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: darkhold
    spec:
      hostUsers: false
      serviceAccountName: pihole
      imagePullSecrets:
        - name: harbor-pull-cred

      tolerations:
        - key: orunmila.sophons.cloud/ase-orun
          operator: Exists

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/region
                    operator: In
                    values: [ng]

        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: darkhold
                topologyKey: kubernetes.io/hostname
              weight: 10

      securityContext:
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: pihole-proxy
          # image: poci.sphns.run/proxy-docker.io/library/alpine:3.22.2
          image: docker.io/library/alpine:3.23.3
          command:
            - ash
            - -c
            - |
              set -xeuo pipefail
              cleanup() {
                echo "stopping..."
                kill -TERM $udp_pid
                kill -TERM $tcp_pid
              }
              trap "cleanup" SIGTERM

              dns_name="$(hostname | sed s/darkhold/necronomicon/).necronomicon-cluster-dns.pihole.svc"
              apk add --no-cache sed socat bind-tools

              socat_config=fork,reuseaddr
              socat "udp-recvfrom:53,$socat_config" "udp-sendto:$dns_name:53" &
              udp_pid=$!

              socat "tcp-listen:53,$socat_config,max-children=32,backlog=128" "tcp:$dns_name:53" &
              tcp_pid=$!

              wait

          ports:
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
              hostPort: 53
            - name: dns-udp
              containerPort: 53
              protocol: UDP
              hostPort: 53

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  (ps aux | grep socat) || exit 1
            initialDelaySeconds: 30
            failureThreshold: 5

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  dig +short +norecurse +retry=0 @127.0.0.1 pi.hole || exit 1
            initialDelaySeconds: 30
            failureThreshold: 5

          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              memory: 64Mi

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
