# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.34.1/statefulset-apps-v1.json
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: necronomicon
  labels:
    app.kubernetes.io/instance: necronomicon
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: necronomicon
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: necronomicon
    spec:
      hostUsers: false
      serviceAccountName: pihole
      imagePullSecrets:
        - name: harbor-pull-cred

      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/instance: necronomicon
              topologyKey: kubernetes.io/hostname

      securityContext:
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: pihole
          image: poci.sphns.run/proxy-ghcr.io/pi-hole/pihole:2025.11.0

          ports:
            - containerPort: 53
              protocol: TCP
              name: dns-tcp
            - containerPort: 53
              protocol: UDP
              name: dns-udp
            - containerPort: 80
              protocol: TCP
              name: http

          env:
            - name: TZ
              value: Africa/Lagos
            - name: PIHOLE_UID
              value: "1000"
            - name: PIHOLE_GID
              value: "1000"
            - name: FTLCONF_webserver_api_password
              value: ""
            - name: FTLCONF_dns_listeningMode
              value: "ALL"
            - name: FTLCONF_dns_upstreams
              value: "1.1.1.1;1.0.0.1;9.9.9.9;149.112.112.112"

          volumeMounts:
            - mountPath: /etc/pihole
              name: pihole
            - mountPath: /etc/pihole/adlists.list
              name: pihole-config
              subPath: adlists.list
              readOnly: true
            - mountPath: /etc/pihole/blacklist.txt
              name: pihole-config
              subPath: blacklist.txt
              readOnly: true

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  dig -p $(pihole-FTL --config dns.port) +short +norecurse +retry=0 @127.0.0.1 pi.hole || exit 1
            timeoutSeconds: 5
            failureThreshold: 5
            initialDelaySeconds: 60 # might download adlists on boot

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  dig -p $(pihole-FTL --config dns.port) +short +norecurse +retry=0 @127.0.0.1 pi.hole || exit 1
            timeoutSeconds: 5
            failureThreshold: 5
            initialDelaySeconds: 60

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 256Mi

        - name: tailscale
          image: poci.sphns.run/proxy-ghcr.io/tailscale/tailscale:v1.90.8

          ports:
            - containerPort: 9002
              name: ts-metrics

          envFrom:
            - secretRef:
                name: tailscale-base-config
            - secretRef:
                name: tailscale-auth

          env:
            - name: GOMEMLIMIT
              value: 100MiB
            - name: TS_EXTRA_ARGS
              value: $(TS_BASE_ARGS)
            - name: TS_TAILSCALED_EXTRA_ARGS
              value: $(TSD_BASE_ARGS)
            - name: TS_KUBE_SECRET
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: TS_AUTH_ONCE
              value: "true"
            - name: TS_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: TS_USERSPACE
              value: "false"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid

          volumeMounts:
            - mountPath: /tmp
              name: tmp
              subPath: ts

          securityContext:
            privileged: true
            readOnlyRootFilesystem: true

          livenessProbe:
            httpGet:
              path: /healthz
              port: ts-metrics
            failureThreshold: 5
            initialDelaySeconds: 60

          readinessProbe:
            httpGet:
              path: /healthz
              port: ts-metrics
            failureThreshold: 5
            initialDelaySeconds: 60

          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              memory: 128Mi

      volumes:
        - name: pihole
          emptyDir:
            sizeLimit: 512Mi
        - name: pihole-config
          configMap:
            name: pihole
        - name: tmp
          emptyDir:
            sizeLimit: 128Mi
---
# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.34.1/statefulset-apps-v1.json
# TODO: For some reason, i can't LB to the necronomicon pods so these act as a proxy in my home network
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: darkhold
  labels:
    app.kubernetes.io/instance: darkhold
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: darkhold
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: darkhold
    spec:
      hostUsers: false
      serviceAccountName: pihole
      imagePullSecrets:
        - name: harbor-pull-cred

      tolerations:
        - key: orunmila.sophons.cloud/ase-orun
          operator: Exists

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/region
                    operator: In
                    values: [ng]

        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: darkhold
                topologyKey: kubernetes.io/hostname
              weight: 10

      securityContext:
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: pihole-proxy
          image: poci.sphns.run/proxy-docker.io/library/alpine:3.22.2
          command:
            - ash
            - -c
            - |
              set -xeuo pipefail
              cleanup() {
                echo "stopping..."
                kill -TERM $udp_pid
                kill -TERM $tcp_pid
              }
              trap "cleanup" SIGTERM

              dns_name=necronomicon-cluster-dns.pihole.svc
              apk add --no-cache sed socat bind-tools

              socat_config=fork,reuseaddr
              socat "udp-recvfrom:53,$socat_config" "udp-sendto:$dns_name:53" &
              udp_pid=$!

              socat "tcp-listen:53,$socat_config,max-children=32,backlog=128" "tcp:$dns_name:53" &
              tcp_pid=$!

              wait

          ports:
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
              hostPort: 53
            - name: dns-udp
              containerPort: 53
              protocol: UDP
              hostPort: 53

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  (ps aux | grep socat) || exit 1
            initialDelaySeconds: 30
            failureThreshold: 5

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  dig +short +norecurse +retry=0 @127.0.0.1 pi.hole || exit 1
            initialDelaySeconds: 30
            failureThreshold: 5

          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              memory: 64Mi
