# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.34.1/daemonset-apps-v1.json
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cloudflared
  namespace: traefik
  labels:
    app.kubernetes.io/name: cloudflared
    app.kubernetes.io/instance: traefik
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudflared
      app.kubernetes.io/instance: traefik
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cloudflared
        app.kubernetes.io/instance: traefik
    spec:
      tolerations:
        - key: orunmila.sophons.cloud/ase-orun
          operator: Exists
        - key: caeneus.sophons.cloud
          operator: Exists

      # securityContext:
      #   sysctls:
      #     # allows icmp traffic (ping, traceroute) to resources behind cloudflared.
      #     # TODO: apply this at the node level?
      #     - name: net.ipv4.ping_group_range
      #       value: "65532 65532"

      hostNetwork: true # use host network to avoid issue with mtu linked below
      dnsPolicy: ClusterFirstWithHostNet
      hostAliases:
        - ip: 10.43.0.10
          hostnames:
            - traefik.traefik.svc.cluster.local
        - ip: 2001:cafe:43::69
          hostnames:
            - traefik.traefik.svc.cluster.local
      containers:
        # https://developers.cloudflare.com/cloudflare-one/networks/connectors/cloudflare-tunnel/deployment-guides/kubernetes/
        - image: cloudflare/cloudflared:2026.2.0
          name: cloudflared
          env:
            - name: GOMEMLIMIT
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
          command:
            - cloudflared
            - tunnel
            - --no-autoupdate
            - --loglevel
            - info
            - --metrics
            - 0.0.0.0:2000
            # https://github.com/cilium/cilium/issues/37529
            # - --protocol
            # - http2
            - --config
            - /.cloudflared/config.yaml
            - run
          ports:
            - containerPort: 2000
              name: cfd-metrics
              protocol: TCP
          volumeMounts:
            - name: cloudflared
              mountPath: /.cloudflared
              readOnly: true
          livenessProbe:
            httpGet:
              # Cloudflared has a /ready endpoint which returns 200 if and only if
              # it has an active connection to Cloudflare's network.
              path: /ready
              port: cfd-metrics
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: cloudflared
          secret:
            secretName: cloudflared
