# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.34.1/daemonset-apps-v1.json
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: traefik-cloudflared
  namespace: traefik
  labels:
    app.kubernetes.io/name: cloudflared
    app.kubernetes.io/instance: traefik
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudflared
      app.kubernetes.io/instance: traefik
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cloudflared
        app.kubernetes.io/instance: traefik
    spec:
      tolerations:
        - key: orunmila.sophons.cloud/ase-orun
          operator: Exists
        - key: caeneus.sophons.cloud
          operator: Exists

      securityContext:
        sysctls:
          # allows icmp traffic (ping, traceroute) to resources behind cloudflared.
          - name: net.ipv4.ping_group_range
            value: "65532 65532"

      # hostNetwork: true # use host network to avoid issue with mtu linked below
      # dnsPolicy: ClusterFirstWithHostNet
      hostAliases:
        - ip: 10.43.0.10
          hostnames:
            - traefik.traefik.svc.cluster.local
        - ip: 2001:cafe:43::69
          hostnames:
            - traefik.traefik.svc.cluster.local
      containers:
        # https://developers.cloudflare.com/cloudflare-one/networks/connectors/cloudflare-tunnel/deployment-guides/kubernetes/
        - image: docker.io/cloudflare/cloudflared:latest
          imagePullPolicy: Always
          name: cloudflared
          env:
            - name: GOGC
              value: "10"
            - name: GOMEMLIMIT
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              memory: 72Mi
          command:
            - cloudflared
            - tunnel
            - --no-autoupdate
            - --loglevel
            - info
            - --metrics
            - 0.0.0.0:2000
            # https://github.com/cilium/cilium/issues/37529
            # - --protocol
            # - http2
            - --config
            - /.cloudflared/config.yaml
            - run
          ports:
            - containerPort: 2000
              name: cfd-metrics
              protocol: TCP
          volumeMounts:
            - name: cloudflared
              mountPath: /.cloudflared
              readOnly: true
          livenessProbe:
            httpGet:
              # Cloudflared has a /ready endpoint which returns 200 if and only if
              # it has an active connection to Cloudflare's network.
              path: /ready
              port: cfd-metrics
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: cloudflared
          secret:
            secretName: cloudflared
---
# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.35.2/daemonset-apps-v1.json
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: traefik-haproxy
  namespace: traefik
  labels:
    app.kubernetes.io/name: haproxy
    app.kubernetes.io/instance: traefik
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: haproxy
      app.kubernetes.io/instance: traefik
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: haproxy
        app.kubernetes.io/instance: traefik
    spec:
      priorityClassName: system-node-critical
      securityContext:
        sysctls:
          - name: net.ipv4.ip_forward
            value: "1"
          - name: net.ipv6.conf.all.forwarding
            value: "1"

        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        seccompProfile:
          type: RuntimeDefault

      hostAliases:
        - ip: 10.43.0.10
          hostnames:
            - traefik.traefik.svc.cluster.local
        - ip: 2001:cafe:43::69
          hostnames:
            - traefik.traefik.svc.cluster.local

      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: CriticalAddonsOnly
          operator: Exists
        - key: caeneus.sophons.cloud
          operator: Exists

      volumes:
        - name: haproxy
          configMap:
            name: traefik-haproxy
        - name: certs
          secret:
            secretName: gateway-tls

      containers:
        - name: haproxy
          image: docker.io/library/haproxy
          args: [-V, -f, /usr/local/etc/haproxy/haproxy.cfg]
          ports:
            - name: tcp-ssh
              containerPort: 22
              hostPort: 22
              protocol: TCP
            - name: tcp-http
              containerPort: 80
              hostPort: 80
              protocol: TCP
            - name: tcp-https
              containerPort: 443
              hostPort: 443
              protocol: TCP
            - name: udp-https
              containerPort: 443
              hostPort: 443
              protocol: UDP
            - name: metrics
              containerPort: 9069
              protocol: TCP

          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics

          readinessProbe:
            httpGet:
              path: /healthz
              port: metrics

          volumeMounts:
            - mountPath: /usr/local/etc/haproxy
              name: haproxy
              readOnly: true
            - mountPath: /usr/local/etc/haproxy/certs
              name: certs
              readOnly: true

          resources:
            requests:
              cpu: 75m
              memory: 32Mi
            limits:
              memory: 72Mi

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ALL]
              add: [NET_BIND_SERVICE]
