# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.34.1/deployment-apps-v1.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anubis
  namespace: traefik
  labels:
    app.kubernetes.io/name: anubis
    app.kubernetes.io/instance: traefik
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: anubis
      app.kubernetes.io/instance: traefik
  template:
    metadata:
      labels:
        app.kubernetes.io/name: anubis
        app.kubernetes.io/instance: traefik
    spec:
      hostUsers: false
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: topology.kubernetes.io/region
                    operator: NotIn
                    values: [ng]
              weight: 100

      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

      volumes:
        - name: config
          configMap:
            name: anubis-config

      containers:
        - name: anubis
          image: ghcr.io/techarohq/anubis:v1.27.0@sha256:8828275668b7bc675679f100970f9714f731388fbbf66ae94de8aca952e3fc4a

          env:
            - name: GOGC
              value: "10"
            - name: GOMEMLIMIT
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory
            - name: POLICY_FNAME
              value: /etc/anubis/config/policy.yaml
            - name: BIND
              value: :8080
            - name: DIFFICULTY
              value: "5"
            - name: ED25519_PRIVATE_KEY_HEX
              valueFrom:
                secretKeyRef:
                  name: traefik-secrets
                  key: ANUBIS_ED25519_PRIVATE_KEY_HEX
            - name: SERVE_ROBOTS_TXT
              value: "true"
            - name: TARGET
              value: " " # Redirect mode
            - name: PUBLIC_URL
              # The `Redirect` function in the golang stdlib will "helpfully" prefix
              # a relative path with the request URL. This doesn't complicate my genius plan whatsoever.
              # https://cs.opensource.google/go/go/+/refs/tags/go1.27.1:src/net/http/server.go;l=2419
              value: /.
            - name: CUSTOM_REAL_IP_HEADER
              value: X-Real-Ip
            - name: COOKIE_HTTP_ONLY
              value: "true"
            - name: COOKIE_DYNAMIC_DOMAIN
              value: "true"

          ports:
            - containerPort: 8080
              name: anubis
            - containerPort: 9090
              name: metrics

          volumeMounts:
            - mountPath: /etc/anubis/config
              name: config
              readOnly: true

          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ALL]
---
# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.34.1/deployment-apps-v1.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddns
  namespace: traefik
  labels:
    app.kubernetes.io/name: ddns
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ddns
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ddns
    spec:
      serviceAccountName: ddns
      hostUsers: false
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/region
                    operator: In
                    values: [ng]

      hostAliases:
        - ip: 10.42.0.1
          hostnames: [unifi.local]

      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

      volumes:
        - name: tmp
          emptyDir: {}
        - name: bunny-edge-dns
          configMap:
            name: bunny-edge-dns

      containers:
        - name: deno
          image: ghcr.io/denoland/deno
          args:
            - run
            - --allow-env
            - --allow-net
            - --allow-read
            - /bunny/ddns.worker.ts

          env:
            - name: DENO_DIR
              value: "/tmp/.deno_cache"

            - name: ISP_NAME
              value: Starlink
            - name: UNIFI_BASE_URL
              value: "https://unifi.local"
            - name: UNIFI_GATEWAY
              value: positron
            - name: UNIFI_CA_CRT
              valueFrom:
                configMapKeyRef:
                  name: positron-ca
                  key: ca.crt
            - name: UNIFI_USERNAME
              valueFrom:
                secretKeyRef:
                  name: traefik-secrets
                  key: UNIFI_USERNAME
            - name: UNIFI_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: traefik-secrets
                  key: UNIFI_PASSWORD

            - name: DNS_ZONE_ID
              value: "852605"
            - name: DNS_RECORD_IDS
              value: "23427427,23807643"
            - name: BUNNY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: traefik-secrets
                  key: BUNNY_API_KEY

          ports:
            - containerPort: 8080
              name: ddns

          volumeMounts:
            - mountPath: /tmp
              name: tmp
            - mountPath: /bunny
              name: bunny-edge-dns
              readOnly: true

          resources:
            requests:
              cpu: 1m
              memory: 16Mi
            limits:
              memory: 48Mi

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ALL]
