apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: default-cache
  namespace: traefik
spec:
  plugin:
    cacheify:
      path: /cache/default
      maxExpiry: 900 # 15mins
      cleanup: 300 # 5 mins
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: default-compression
  namespace: traefik
spec:
  compress: {}
    # encodings: [gzip, br, zstd] # Already the default order
