# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.34.1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-token
  namespace: traefik
type: Opaque
stringData:
  # enc!
  TUNNEL_TOKEN: ENC[AES256_GCM,data:w7j3iBH633GCRh8IkmqJUEz9XYnMYm13KghC09Jj9K0L7K+n2B/6G/n6L2V9QeU93RahDsCy0K4LdqOFYzv6b5nCJ2r6oj06diNwv74XC+6m66EQ4Ib4yHJJZfQJPle1WOQX2N/5VPMqVIFVGjGTHJqdeMVpN7G6u0ACl8BsLEsZLKxGMPLXzWlC1BrzPKLdeE7uoH7xiyj2TgFHnmCXDAP880Wjqi6SXOs0u4n8lZVhj1gvPcmMOQ==,iv:ASNsU17VQd92M0SjXGZCnO7RibtOCCfixqZDhHmzqfI=,tag:kt6HChrdd8TsSX+cFNs5Rw==,type:str]
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBWc0JF
        ZkhFeWhoK2tPNWhoYjRJTE5iZmVGQkV1UVdMUlI4OXcxY2E5dUVRCmQwdEVJZHhZ
        a3RXY0tqQ0xBVmJCaVlWRmFRMzFVdE9FaEdGS0dITFBYVk0KLS0tIEc3Rld4dThq
        NTFaRU9HY0c0Q0tGUGk1d2VHYnhKdjg5eWQ0aTFqT0pYZ0EKJY5r9wvw0e7wTJqc
        6qkfQK36GUwnmph1TkCZL8oTIjCPYYtCQyBTK4kx1YQ5BfkqlynIyiJ5DtEm3nZw
        wTZP5w==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsTUdFM1NjZkN2MXlVYXFL
        dERSMkFNcWoxRVZFUU41NnN5RVpwdjRHOEZFCnFqUGZvMW9MdGNXR3Nwb2RYd091
        aWhmeGlJaEpndEU4QjZIbWMvMWdnQWcKLS0tIEpvYjZxanl2QkRXT1NOY21yMEQ1
        TXI4UU1MNit1cUtscjZTUmlLU1RMdXcKahS90SPyzN8thKMUwyfLCxYG79hj52pl
        OwyYB3jKQfLS83Mr/2hpc099MK1EaracTAh0ECY/d8BcbdaBS+O10w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-31T18:48:50Z"
  mac: ENC[AES256_GCM,data:6k9iXcVHoQS7d9r33W/fgYVhPNFd9aZYg4KhgIJs3izd/gjx8K4sNqEsxU34rggHynO64wvuQ/7Jut6od0XJV1BSj2bw7r8NseiZaMJ+KdDeOWdBnsnUeeU0ZkmWUegxsWSjhocDQdhbV3E6CLq/3H2SNnfCzGlOVSc+C9d3fLY=,iv:yOTZMETi6g5S40K2FZRvvHjeDHXiQI2wWqThj2FFRWA=,tag:liINnPzai4yPtX6wnRMZwQ==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
