# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.34.1/service-v1.json
apiVersion: v1
kind: Service
metadata:
  name: cloudflared-metrics
  namespace: traefik
  labels:
    app.kubernetes.io/name: cloudflared
    app.kubernetes.io/instance: traefik
spec:
  clusterIP: None
  ports:
    - name: cfd-metrics
      protocol: TCP
      port: 2000
  selector:
    app.kubernetes.io/name: cloudflared
    app.kubernetes.io/instance: traefik
