apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: traefik-haproxy
  namespace: traefik
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: haproxy
      app.kubernetes.io/instance: traefik
  endpoints:
    - port: metrics
