apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: anubis
  namespace: traefik
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: anubis
      app.kubernetes.io/instance: traefik
  endpoints:
    - port: metrics
