# yaml-language-server: $schema=https://github.com/traefik/traefik-helm-chart/raw/refs/tags/v39.0.2/traefik/values.schema.json

cfIPs: &cfIPs
  - 127.0.0.0/8 # lokalhost
  - ::1/128
  - 10.41.0.0/16 # kluster
  - 2001:cafe:41::/56
  - 173.245.48.0/20 # Cloudflare
  - 103.21.244.0/22
  - 103.22.200.0/22
  - 103.31.4.0/22
  - 141.101.64.0/18
  - 108.162.192.0/18
  - 190.93.240.0/20
  - 188.114.96.0/20
  - 197.234.240.0/22
  - 198.41.128.0/17
  - 162.158.0.0/15
  - 104.16.0.0/13
  - 104.24.0.0/14
  - 172.64.0.0/13
  - 131.0.72.0/22
  - 2400:cb00::/32
  - 2606:4700::/32
  - 2803:f800::/32
  - 2405:b500::/32
  - 2405:8100::/32
  - 2a06:98c0::/29
  - 2c0f:f248::/32

logs:
  general:
    # TODO: prob just scan git logs for ssh attempts
    # TCP/UDP connection logs only happen at the debug level
    level: INFO
    noColor: true
  access:
    enabled: true

metrics:
  prometheus:
    enabled: true

ingressRoute:
  dashboard:
    enabled: true

ports:
  traefik:
    port: 8080
    expose:
      default: true
      internal: true
      kaos: true

  web:
    port: 80
    hostPort: 80
    expose:
      internal: true
      kaos: true
      starlink: true
      theta: true
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
      middlewares:
        - default-compression@file
    # middlewares: []
    # - crowdsec-crowdsec-bouncer@kubernetescrd

    proxyProtocol:
      trustedIPs: *cfIPs

    forwardedHeaders:
      trustedIPs: *cfIPs

  websecure:
    port: 443
    hostPort: 443
    expose:
      internal: true
      kaos: true
      starlink: true
      theta: true
    transport:
      respondingTimeouts:
        # uploading blobs to gitea etc can take a while
        # thanks [fuck-all]mbps upload internet.
        readTimeout: 300
    # middlewares: []
    # - crowdsec-crowdsec-bouncer@kubernetescrd

    proxyProtocol:
      trustedIPs: *cfIPs

    forwardedHeaders:
      trustedIPs: *cfIPs

  ssh:
    port: 22
    hostPort: 22
    expose:
      default: true
      internal: true
      kaos: true
      starlink: true
      theta: true

service:
  enabled: true
  type: ClusterIP
  spec:
    # TODO: https://github.com/cilium/cilium/issues/44060
    # trafficDistribution: PreferSameNode # not supported by cilium
    ipFamilies: ["IPv4", "IPv6"]
    ipFamilyPolicy: RequireDualStack
    clusterIP: 10.43.0.69
    clusterIPs:
      - 10.43.0.69
      - 2001:cafe:43::69

  additionalServices:
    internal:
      single: true
      type: LoadBalancer
      annotations:
        metallb.io/address-pool: internal
        external-dns.alpha.kubernetes.io/hostname: >
          traefik-internal.sophons.cloud
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
      spec:
        # trafficDistribution: PreferSameNode
        externalTrafficPolicy: Local
    kaos:
      single: true
      type: LoadBalancer
      annotations:
        metallb.io/address-pool: kaos
        external-dns.alpha.kubernetes.io/hostname: >
          traefik-kaos.sophons.cloud
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
      spec:
        # trafficDistribution: PreferSameNode
        externalTrafficPolicy: Local
    starlink:
      single: true
      type: LoadBalancer
      annotations:
        metallb.io/address-pool: starlink
        external-dns.alpha.kubernetes.io/hostname: >
          traefik-starlink.sophons.cloud,
          traefik-star-theta.sophons.cloud,
          traefik-sango-star-theta.sophons.cloud
      spec:
        # trafficDistribution: PreferSameNode
        ipFamilies: ["IPv6"]
        externalTrafficPolicy: Local
    theta:
      single: true
      type: LoadBalancer
      annotations:
        metallb.io/address-pool: theta
        external-dns.alpha.kubernetes.io/hostname: >
          traefik-theta.sophons.cloud,
          traefik-star-theta.sophons.cloud,
          traefik-sango-star-theta.sophons.cloud
      spec:
        # trafficDistribution: PreferSameNode
        ipFamilies: ["IPv6"]
        externalTrafficPolicy: Local

providers:
  kubernetesCRD:
    nativeLBByDefault: true
    allowCrossNamespace: true
  kubernetesIngress:
    nativeLBByDefault: true
    # allowCrossNamespace: true
  kubernetesGateway:
    enabled: true
    nativeLBByDefault: true
    # allowCrossNamespace: true
    experimentalChannel: true
  file:
    enabled: true
    content: |
      http:
        middlewares:
          redirect-to-https:
            redirectScheme:
              scheme: https
              permanent: true
          default-compression:
            compress:
              encodings: [br, zstd, gzip]
              defaultEncoding: br

        routers:
          headplane:
            entryPoints: [web, websecure]
            service: headplane
            rule: Host(`hs.vrtx.sh`) && PathPrefix(`/admin`)
            middlewares: [default-compression]
          headscale:
            entryPoints: [web, websecure]
            service: headscale
            rule: Host(`hs.vrtx.sh`)
          headscale-grpc:
            entryPoints: [websecure]
            service: headscale-grpc
            rule: Host(`gghs.vrtx.sh`)

        services:
          headplane:
            loadBalancer:
              servers:
                - url: http://headscale-proxy-headless.headscale.svc.cluster.local:3000
              passHostHeader: true
              serversTransport: headscale@file
          headscale:
            loadBalancer:
              servers:
                - url: http://headscale-proxy-headless.headscale.svc.cluster.local:8080
              passHostHeader: true
              serversTransport: headscale@file
          headscale-grpc:
            loadBalancer:
              servers:
                - url: h2c://headscale-proxy-headless.headscale.svc.cluster.local:50051
              passHostHeader: true
              serversTransport: headscale-grpc@file
        
        serversTransports:
          headscale:
            serverName: hs.vrtx.sh
          headscale-grpc:
            serverName: gghs.vrtx.sh

      tls:
        stores:
          default:
            defaultCertificate:
              certFile: /etc/traefik/gateway-tls/tls.crt
              keyFile: /etc/traefik/gateway-tls/tls.key

        certificates:
          - certFile: /etc/traefik/gateway-tls/tls.crt
            keyFile: /etc/traefik/gateway-tls/tls.key

gateway:
  listeners:
    traefik: # HTTP listener that matches entryPoint `traefik`
      port: 8080
      protocol: HTTP
      namespacePolicy:
        from: All
    web: # HTTP listener that matches entryPoint `web`
      port: 80
      protocol: HTTP
      namespacePolicy:
        from: All
    websecure: # HTTPS listener that matches entryPoint `websecure`
      port: 443
      mode: Terminate
      protocol: HTTPS
      namespacePolicy:
        from: All
      certificateRefs:
        - kind: Secret
          group: ""
          name: gateway-tls
    ssh: # TCP listener that matches entryPoint `ssh`
      port: 22
      protocol: TCP
      namespacePolicy:
        from: All

priorityClassName: system-node-critical
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 0
deployment:
  kind: DaemonSet

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "750m"
    memory: "768Mi"

volumes:
  - type: secret
    name: gateway-tls
    mountPath: /etc/traefik/gateway-tls

tolerations:
  - key: orunmila.sophons.cloud/ase-orun
    operator: Exists
  - key: caeneus.sophons.cloud
    operator: Exists

experimental:
  # Fun fact, using plugins essentially introduce a hard dependency
  # on Traefik's plugin servers.
  # Loved figuring this one out
  plugins:
    souin:
      moduleName: "github.com/darkweak/souin"
      version: "v1.7.8"
    crowdsec-bouncer-traefik-plugin:
      moduleName: "github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
      version: "v1.4.6"
  # Fun fact, there's a config to crash on failure to load them ya big dum
  abortOnPluginFailure: true

securityContext:
  capabilities:
    add: ["NET_BIND_SERVICE"]

podSecurityContext:
  sysctls:
    # allows icmp traffic (ping, traceroute) to resources behind cloudflared.
    - name: net.ipv4.ping_group_range
      value: "65532 65532"

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: '{{ template "traefik.name" . }}'
            app.kubernetes.io/instance: '{{ .Release.Name }}-{{ include "traefik.namespace" . }}'
        topologyKey: kubernetes.io/hostname
