# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.34.1/storageclass-storage-v1.json
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: weedfs
provisioner: seaweedfs-csi-driver
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  replication: "100" # 2 copies, 1 per zone
  volumeServerAccess: publicUrl
  collection: weedfs
  dataLocality: write_preferlocaldc
  parentDir: "/pvcs"
---
# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.34.1/storageclass-storage-v1.json
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: weedfs-no-repl
provisioner: seaweedfs-csi-driver
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  replication: "000" # 1 copy, what could go wrong?
  volumeServerAccess: publicUrl
  collection: weedfs-no-repl
  dataLocality: write_preferlocaldc
  parentDir: "/pvcs--no-repl"
