seaweedfsFiler: weedfs-seaweedfs-filer-client:8888
storageClassName: ""
dataLocality: write_preferlocaldc
cacheCapacityMB: 4096

csiProvisioner:
  image: registry.k8s.io/sig-storage/csi-provisioner:v6.2.0
csiResizer:
  image: registry.k8s.io/sig-storage/csi-resizer:v2.1.0
csiAttacher:
  enabled: true
  image: registry.k8s.io/sig-storage/csi-attacher:v4.11.0

controller:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 128Mi

mountService:
  tolerations:
    - key: caeneus.sophons.cloud
      operator: Exists
  resources:
    requests:
      cpu: 150m
      memory: 128Mi
    limits:
      cpu: 750m
      memory: 1Gi

node:
  updateStrategy:
    type: OnDelete # no support for seamless upgrades
  tolerations:
    - key: caeneus.sophons.cloud
      operator: Exists
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 128Mi

  injectTopologyInfoFromNodeLabel:
    enabled: false # Manually handled with k8s 1.35's automatic labels
