namespace: backup-system
resources:
  - cronjob.yaml

configMapGenerator:
  - name: rclone-garage-config
    literals:
      - RCLONE_CONFIG_GARAGE_TYPE=s3
      - RCLONE_CONFIG_GARAGE_ENDPOINT=http://s3-global.garage:3900
      - RCLONE_CONFIG_GARAGE_REGION=global
      - RCLONE_CONFIG_GARAGE_ENV_AUTH=true

secretGenerator:
  - name: global-garage-access-key
    env: .env
