tolerations:
  - key: prime.sophons.cloud
    operator: Exists
  - key: caeneus.sophons.cloud
    operator: Exists

extraEnv:
  - name: GOGC
    value: "10"
  - name: GOMEMLIMIT
    valueFrom:
      resourceFieldRef:
        resource: limits.memory
  - name: PING_TIMEOUT
    value: 500ms

priorityClassName: system-node-critical

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    memory: 64Mi
