# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.34.1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: cf-dns-api-token
  namespace: cert-manager
type: Opaque
stringData:
  # enc!
  api-token: ENC[AES256_GCM,data:jtxcbF7eOwEK5ybSf6dOzp7oYprkgYy/b2dPzgz698KzX8mAXl2Kqg==,iv:52hwsHJB6Dsu56Igo/ejcq1dKaJRPSU1B0UHROn0imQ=,tag:Jt7gLdNuHwVJM2Umv0MqjQ==,type:str]
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBuRzRQ
        ZWVuL1FZNWxFaXNvaUo1VHR6SHUyWE03TjduZ2VBd3BKQmRxRlhRClpHdUlyaE0r
        NzdNTnlsYllERnBPdGErNXVXcmlLTzBFazhUK1ZndkQ4bkUKLS0tIEQzeEQxNFNI
        T014RmxnMXBvQ05KYjArRWZlYWFFbjBQZkNKSXBZYW5zWnMKZNpM5mZ5RoqhritR
        vQ3tbIGMSeGU/dg7WqjkUU2NunFs2VnctLDgYacyBPQF56hJmCYamInt+F0WfVMk
        N2bR0g==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1YVlRWkxuaHlnUU53V1Ry
        a1J0MUdyYVZZNHIyN3BiS0FYd2V0NllNeFY0CmFYTDA2TmRXUnYyMkRGakZ0RVJC
        bnB4TWpiZ25mTWRFVDVXYjBxdjllY2cKLS0tIGV0YUhsTC92QmovaXFlTCsvYmhV
        ZDBrWnlqVG44WnpOc01YcC9UOW5WakEKsugdZm13PRQH6F3FTudksjF0KHWRT6J+
        /RZbNBd3BzhqcmUttHyjYB7FEUQyLUio9WV9Mqx5UfZKX4YdEBw/eA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-20T00:56:48Z"
  mac: ENC[AES256_GCM,data:g4upLa4sgGUZjUPufcotQ8CkhJcg2z1glvvmGdaO20tp81RpkSAOTvJkUcEpTm47e32lqrnjBn0n1wj5fiUENVcm8XlMzu6fXaOZF7fBOGwq7QPkFmxMEWT7VVVsRC2JILZaQmOEfFVevEpQaKzNTOGw5f9SjOD9I7dQllRe1AA=,iv:CDKSgdTDYFO+Fco3UwuhTKBTiw4AnKKtpSdlxdSmfA4=,tag:TSVMRvkJ3BvzDwC8PLq1kA==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.34.1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: letsencrypt-staging-issuer-key
  namespace: cert-manager
type: Opaque
stringData:
  # enc!
  tls.key: ENC[AES256_GCM,data:qj8tqfVZj6PzP6OhY6gq5ndBZarmbHLZW+4A0kaGY0M91IhiiMKS2WQHSIYl43XtLvG/rs3UFhJ5v5/uzxgrCVhvsDxqwTNGXfLr3FEOyU5wNIdMRoVQ+Jgm+rgTUZoHPk+aLf5/PdzT1D8FizGbTj9euhcs/WF93RMmFg+aYHjJ9pPkgkbW6AOmu16jXh/26TZ4sb/UbRxcQFxfWJ7dX8Ar6+Z62sJS6dHhRcFAGbBsAgHrAz8TPV98Po42KF+DZnti0p7xL2FjZkFshSimSZlJlunMWDGIM08WLvOXKcPYT77Na8WZsANUkRiYDTfTa1LaKhbGmOwGqYtPfPIgR28mK6VzMCWarIRWeE1/b1dUPchgG5tZCBdVOl97Z8lq0sDl9Xnjai7jv6hF7e8kWTPPIwTLzqsinl0578UvyxlHxnG3B+cdyFtkxlfWdiAq6KWwCQSbKDpHpzgzo+Vic7egs2cUpY1xMZdXUIfsR9U8ZOgq6Vh/lCj1DwbDEELrdci8+fbzZd3UZ/1XknZE3ewIyKXfGY2HkLhnmY4Bvk33Q0P39GR6gAXYpvZbO8T+F+sgSRXI23Oq0RIEV/SuNgpyyiNxmGLM3wFSp8t8UPg2lBU01mPEU62f2+eKzZpXHS+OCfGp88trGr1YRAo70te9Ogc/50UNcdKxjaiyO5Zv9BtanehjL5Sj2cKdHfE550HkW6Wru6kyA9lzKMYoJqPpKQVtuZLbTjx97XhZcHTVi8uRTIyurtlbGKGw0N/p1pjHwa+nTNb5fLz3xiwzvCB9dTM4qwZQHx7P3YiOwZhAvkQNPuwESMrkccZwSVdhgwOjjaxXIr9wDb/Od4L3qd9q3ELkBhMw6iuzfc9b9LuVX7AVh8Nlpzqy8CkGZJ+4udnpnFQXxp+Lsd2INkoJ831dcrP2qwosAspgMEK98xkFXDY2Xc6QfXQVVvqM/lOl1SqeFKjYsS+ej4szU3B/X2im7nwIJfzpvwsl6aQRPXXWgDH9ax6h4V6LgNZ1rWAB7cNlM5VajZlpVN1m0+kC5FmZHZVzoQSEuPqIs+X05RGozH5rTJwuH0cb77saN41iMGTOgkojAr+MoxZPEaXhvnyq11Mbg3iv6s9x2x82Z8uSz7ur+LGuzpEjzc2I9XsIVITjge1DkfVcVBRIpmiiXJyS4OUYE/s1oshTAnVUQ+jrTwsbTYLEUy21YPs1LvIuzbfCCBFgfUH2uVNvjESz6lU/QlCuHxCM6wbQ/YYYrrhYL9ZhbjW/8hGU0Ds/GnrWIvfM0psJI3Px2KD/TKjwWmhu1ald5WqA+xiKc5F9nD9JwVEn3ADuJaDMNUVOfdUQbQHsUg0mj2I1tSP0625Xqdr2yTuNtIsXRmIdgGXrPtoDslbu4yuP1m+nl3mX1nBmyrAjhcso24vtkmjyymz+slcSusZ/q/sfz96suofFS04OZEd+tzC+Mzdwp1uN2wlZwffjjCDjfh0aKVP9jWjpa1JjjoQtX5nADOkmzOCqiHpPje49tKx6IXQmhbahC8kK3ab52hOZVXXvhMCMgR/9PFaYcmLT81bxdpPEnnN9ndqTuPKJbiyf3wLLdagFnDLr4VOg/E20qJY9TSx0jhPNSl6JrFzZqo0wZ/F2Afl1CBZrWXR0P2eq3plLzvUMQmCJ1GyoXDGJGHP+NCfKJgbCEJFt7oapXfjY6XK4FLzGAlQ5IrcKBR0rHYhhGWNLnP/D/gFjnUMMjWDFQoM9asaO+L0ug7QuLM1z3pOD75sPaGPlRzRh8YbtyQcPmInBT3cSeE1BQyPlyICP+1ljAcOPan2HN16r5eDqesqhb4ORqIzOCQovk9lZp4Z9rumRufF5XKobCzYRC8PYCqVOgA/K0aN4Fp9PjvNvHx1SmSr/RsV3suPy+RN+36zXfzrWvPJLx9Up9S6pfGKkcKs45MgGZ8RTrcPlt0c1MYItZ81PYlCFf0eztk4J78vRHW5bHJ08jPFcxHawNNKykoUzEu7APwLNz/gn1mQ0k85cUJBtbor4DK0KkRmHGzt6oExhKdzUsW13GUX9wxixxRetFIGc2P51Plbe0PkYitGJQ+ub/W3eHa0wX4NjpcIXZd9AiT2u9oYdeeqNTGwmfm9veDJUBK2DDyy/4TMGftASuETfLAMCDDvoq+paEB72IGiFpHGz5aUfiHsiL2mOAgo2tF65Vwlu4ttkn6HyUT3Dncog6JG/p2Ud32i/PVuSX4XbcEs=,iv:J1Fd2tkU3te37z6/mcDdZy8C+yPkVuvTpID/zcOrnHo=,tag:QSa1V+tCFjzRjlYLHiQYvQ==,type:str]
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBuRzRQ
        ZWVuL1FZNWxFaXNvaUo1VHR6SHUyWE03TjduZ2VBd3BKQmRxRlhRClpHdUlyaE0r
        NzdNTnlsYllERnBPdGErNXVXcmlLTzBFazhUK1ZndkQ4bkUKLS0tIEQzeEQxNFNI
        T014RmxnMXBvQ05KYjArRWZlYWFFbjBQZkNKSXBZYW5zWnMKZNpM5mZ5RoqhritR
        vQ3tbIGMSeGU/dg7WqjkUU2NunFs2VnctLDgYacyBPQF56hJmCYamInt+F0WfVMk
        N2bR0g==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1YVlRWkxuaHlnUU53V1Ry
        a1J0MUdyYVZZNHIyN3BiS0FYd2V0NllNeFY0CmFYTDA2TmRXUnYyMkRGakZ0RVJC
        bnB4TWpiZ25mTWRFVDVXYjBxdjllY2cKLS0tIGV0YUhsTC92QmovaXFlTCsvYmhV
        ZDBrWnlqVG44WnpOc01YcC9UOW5WakEKsugdZm13PRQH6F3FTudksjF0KHWRT6J+
        /RZbNBd3BzhqcmUttHyjYB7FEUQyLUio9WV9Mqx5UfZKX4YdEBw/eA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-20T00:56:48Z"
  mac: ENC[AES256_GCM,data:g4upLa4sgGUZjUPufcotQ8CkhJcg2z1glvvmGdaO20tp81RpkSAOTvJkUcEpTm47e32lqrnjBn0n1wj5fiUENVcm8XlMzu6fXaOZF7fBOGwq7QPkFmxMEWT7VVVsRC2JILZaQmOEfFVevEpQaKzNTOGw5f9SjOD9I7dQllRe1AA=,iv:CDKSgdTDYFO+Fco3UwuhTKBTiw4AnKKtpSdlxdSmfA4=,tag:TSVMRvkJ3BvzDwC8PLq1kA==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.34.1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: letsencrypt-prod-issuer-key
  namespace: cert-manager
type: Opaque
stringData:
  # enc!
  tls.key: ENC[AES256_GCM,data:PG8nbvZ2kL7TPGcRl6cP8SncVn9Haav0utzVkZEbjLcD79ihi0e9ar2N53vnrB/eAu6BVACOzez2oqe50XmKJRghXooy9fxmT8/PqPZf9CbkfPAET/5D6CRFwQeygrNk8kthwGhviJBQUrIYVMeOt8bgude22tLxlMbjgf56odfeU+zqz6E/HJkrKpIGeLxN3gzezqLFtm8USbbY0BGmh0trB1B6jM68wpMhT/fPgKxCDChAeIEePsmRxqPzoeS2+sgKNaXGUgjzLLU+vKhk1gIy8tdtI899ctSCw8Hgw7tc5My5xufX7k9J4kEI6hGwQyPdQS4aGu5h4La0VQ5gWtJUuXkMdJ5FMQVXRmlT1a7KWsCGQGvkkA/tkEQ3cYPa1s9OQz+whHQY1HhSiazWXiWmJBJEw02/G9JrNWvBrg2mbhoGnuAnyZWM+sV//xudzQnt8uT/oz7meHjbevk8UsDb4ccaUwTSiavnld0GiGmnMidOCrXYa3dnt0g0ZawkC/MeLdM0hos5/iCWeTKuw9ZtMzE6E4+ESmL8eCTa2vlfaByYNlKVFikOAY0HAsHRDQoueCTCWU4LWV5i2/pUs0LzKdgBWgQNUWP2UNgg12yz9QYmxLVBLDk/zaW6cZrjS0I8BvcuwO9VgiPcyUxHteP52RXrr4oPKhSFkmofPE2lbBfeMgMz2i+aqE9udas6zZFcSD9Lo9gIJHTj3FUvoLjhTPfRooet3DSrDOjmMugjuC51BdHwXQJx19gql0fN9noLZVpALqjIVVKkEh1xyT4R7ZDiXluScPOZ5G5KnInC4wrYEEVNmrAlw6SuiJ1qawdHRPZHdUpofiQiW/B8tlirDq6oW3Enk1cpHsXEGpEEH+W4DHjK9bn23v9RkKneXpEuLAYDm9gloFjo3/8otFRtmdijPhE235ZZG4Kabwq2S2psaQLaP4T78C+TuYbTLDNZgU2ac6+a/uMvaW8GGsFDrULR7/IrrENB7TpcPNe7eaEM/JUMHrHY94uwvH7lt7vA7/VYqiSSw95pNo+9fnJSanL+johpW3TWPrHlGjOU3M3Vfzyc3q+dSeJh/n9HhyXU7GY9JwGek4ZfIybPq2TZevlaHNKtJ7xIGHKBc3vLwOJ/EeZNJz+strtLb5i/vonZvVqGjWvX75A83cm4dUXHOuTcD2RTt+J+m9vwlk/E04LU+ifWxkWczXktkBV367JQ0AXl+n4mII5GaGpkfFV95xx0sp9rnc48n4aK1pp392icP3AYb2Cbhdp1edlAh6CDHKFLTog3DbOt7OvUfJNWx8b9jp0pgm7vYYTlSAwf1hRNDlwDLGe/A97twhCZxm1JYkx+FUS03PBU3dpNI9zAi2aBYjRLddi1walqCZZ1qaJi1GnHfRCpM5mSa3+T1T0zlPhjEtvrHhom4mfdQOLa0XUEtCXMnr0Y+YPUVtqooZRyVPO850ZVDmAvZFn2ZHh9zE9g8FL17n028hdyOFZLgZyJIqXEE7WWkHZtcincSP2yrvAynJrI4pgUzhPm5cqv4DxsFpWmn3k6LAxlCjKAXhBduciYW28uzbVV8GGqZE4KWJFLJIMqarelgOHg6EPfSO4tXICiRl1f4hYmGbSju0C7onryJvTthYfETCraMuS+E6hpBAmlofABU6p/UiRhfsMABJ17WFzC7Hsb2H9tG+YLZ5hKhNBJ08XHBSE0DsPr5FZfndlTUte9ZVF3Sx261lscLDCgfxlEdZ6BKvI2PSZnks2VClB1XvIuBiTR2bskFTthXUsD6AStAx79lnk69XN+LFac48bcU60nVvOFl28AfvVqDBDxgqJW18/jJvLip4w3GA1I1kcpplnvODgJeI8dWC12puW/NoJTJHtj6BBGsxsr0nhULnSqYwnNaYfYP4LlWuRV/Eqp+PS3bAkrn+vf936YqtERa5usWe4tB14qPmovheib7V5793qpuGktreX1iYJbYq8uLrCx6HV3XugcAjOjtvMFZu2hX3GqbVafON+cvRBUpa8dilJG1uvfFDqy73tyu7i6JD5WJJVNmxsMuGD+yJo89mzHIDGdULFxOroim8Xr4116Zw5e4RKBtk7JEgkOGbHUeVdbDWsIzfmCCLFHVz9yT2cbAlRsjUHWNQAJ8CQG4RUNy22EddUVlyMz3zcqlBIRbk8FaHhTPVHw0B37i0/wFj/nzCUpDRKGeRRwRSLIwozDEk2snUn/lixfMQQVTqQEAQc=,iv:UJbzZHQFV26NZGOV3LgQXcSRFXSEWWxAq9txalAamUY=,tag:GarX+UfCYKPhPrCZBuXqVQ==,type:str]
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBuRzRQ
        ZWVuL1FZNWxFaXNvaUo1VHR6SHUyWE03TjduZ2VBd3BKQmRxRlhRClpHdUlyaE0r
        NzdNTnlsYllERnBPdGErNXVXcmlLTzBFazhUK1ZndkQ4bkUKLS0tIEQzeEQxNFNI
        T014RmxnMXBvQ05KYjArRWZlYWFFbjBQZkNKSXBZYW5zWnMKZNpM5mZ5RoqhritR
        vQ3tbIGMSeGU/dg7WqjkUU2NunFs2VnctLDgYacyBPQF56hJmCYamInt+F0WfVMk
        N2bR0g==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1YVlRWkxuaHlnUU53V1Ry
        a1J0MUdyYVZZNHIyN3BiS0FYd2V0NllNeFY0CmFYTDA2TmRXUnYyMkRGakZ0RVJC
        bnB4TWpiZ25mTWRFVDVXYjBxdjllY2cKLS0tIGV0YUhsTC92QmovaXFlTCsvYmhV
        ZDBrWnlqVG44WnpOc01YcC9UOW5WakEKsugdZm13PRQH6F3FTudksjF0KHWRT6J+
        /RZbNBd3BzhqcmUttHyjYB7FEUQyLUio9WV9Mqx5UfZKX4YdEBw/eA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-20T00:56:48Z"
  mac: ENC[AES256_GCM,data:g4upLa4sgGUZjUPufcotQ8CkhJcg2z1glvvmGdaO20tp81RpkSAOTvJkUcEpTm47e32lqrnjBn0n1wj5fiUENVcm8XlMzu6fXaOZF7fBOGwq7QPkFmxMEWT7VVVsRC2JILZaQmOEfFVevEpQaKzNTOGw5f9SjOD9I7dQllRe1AA=,iv:CDKSgdTDYFO+Fco3UwuhTKBTiw4AnKKtpSdlxdSmfA4=,tag:TSVMRvkJ3BvzDwC8PLq1kA==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
