# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.34.1/deployment-apps-v1.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bluesky-pds
  namespace: bluesky
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bluesky-pds
      app.kubernetes.io/instance: pds
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bluesky-pds
        app.kubernetes.io/instance: pds
    spec:
      serviceAccountName: bluesky-pds

      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

      containers:
        - name: bluesky-pds
          image: "ghcr.io/bluesky-social/pds:0.4.208"
          # command: ["sleep", "10000"]
          env:
            - name: PDS_HOSTNAME
              value: pds.vrtx.sh
            - name: PDS_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: bluesky-pds
                  key: jwtSecret
            - name: PDS_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bluesky-pds
                  key: adminPassword
            - name: PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX
              valueFrom:
                secretKeyRef:
                  name: bluesky-pds
                  key: plcRotationKey
            - name: PDS_EMAIL_SMTP_URL
              valueFrom:
                secretKeyRef:
                  name: bluesky-pds
                  key: emailSmtpUrl
            - name: PDS_BLOBSTORE_S3_BUCKET
              value: pds
            - name: PDS_BLOBSTORE_S3_REGION
              value: global
            - name: PDS_BLOBSTORE_S3_ENDPOINT
              value: ps3-global.sphns.run
            - name: PDS_BLOBSTORE_S3_UPLOAD_TIMEOUT_MS
              value: "60000"
            - name: PDS_BLOBSTORE_S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: bluesky-pds
                  key: s3AccessKey
            - name: PDS_BLOBSTORE_S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: bluesky-pds
                  key: s3SecretKey
            # The fine folks at bsky set up seperate sqlite databases,
            # as they should have, to reduce contention. We are now going to
            # ruin all of their hard work by putting sqlite inside sqlite :tm:
            - name: PDS_DATA_DIRECTORY
              value: "/fs/mnt/pds"
            - name: PDS_DID_PLC_URL
              value: "https://plc.directory"
            - name: PDS_BSKY_APP_VIEW_URL
              value: "https://api.bsky.app"
            - name: PDS_BSKY_APP_VIEW_DID
              value: "did:web:api.bsky.app"
            - name: PDS_REPORT_SERVICE_URL
              value: "https://mod.bsky.app"
            - name: PDS_REPORT_SERVICE_DID
              value: "did:plc:ar7c4by46qjdydhdevvrndac"
            - name: PDS_CRAWLERS
              value: "https://bsky.network"
            - name: LOG_ENABLED
              value: "true"
            - name: PDS_EMAIL_FROM_ADDRESS
              value: "bsky@vrtx.sh"

          ports:
            - name: pds-port
              containerPort: 3000
              protocol: TCP

          volumeMounts:
            - name: fs
              mountPath: /fs
              mountPropagation: HostToContainer
            # - name: data
            #   mountPath: /pds
            # - name: blobstore
            #   mountPath: /blobstore

          livenessProbe:
            httpGet:
              path: /xrpc/_health
              port: pds-port

          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 512Mi
      initContainers:
        - name: litestream-legacy-restore-fsdb
          image: docker.io/litestream/litestream:0.3.13
          args:
            - restore
            - -config=/etc/litestream/litestream-legacy.yaml
            # - -if-replica-exists
            - /fs/fs.db

          envFrom:
            - secretRef:
                name: litestream-ps3-global-access-key
          env:
            - name: GOMEMLIMIT
              value: 120MiB
            - name: LITESTREAM_LOGGING_LEVEL
              value: debug

          volumeMounts:
            - name: fs
              mountPath: "/fs"
            - name: litestream
              mountPath: "/etc/litestream"
              readOnly: true
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ALL]

        # - name: format-fsdb
        #   image: docker.io/juicedata/mount:ce-v1.3.1
        #   command:
        #     - sh
        #     - -c
        #     - |
        #       set -e
        #       juicefs format --storage sqlite3 --bucket /fs/fs.db sqlite3:///fs/fs.db fsdb \
        #         --no-update --trash-days=0
        #   volumeMounts:
        #     - name: fs
        #       mountPath: "/fs"
        #   securityContext:
        #     readOnlyRootFilesystem: true
        #     allowPrivilegeEscalation: false
        #     capabilities:
        #       drop: [ALL]

        - name: litestream-legacy-replicate
          image: docker.io/litestream/litestream:0.3.13
          args: ["replicate", "-config=/etc/litestream/litestream-legacy.yaml"]
          restartPolicy: Always
          envFrom:
            - secretRef:
                name: litestream-ps3-global-access-key
          env:
            - name: GOMEMLIMIT
              value: 120MiB
            - name: LITESTREAM_SYNC_INTERVAL
              value: "1s"
            - name: LITESTREAM_SNAPSHOT_INTERVAL
              value: 30m
            - name: LITESTREAM_RETENTION
              value: 6h

          ports:
            - name: ls-metrics
              containerPort: 9090

          volumeMounts:
            - name: fs
              mountPath: "/fs"
            - name: litestream
              mountPath: "/etc/litestream"
              readOnly: true

          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]

          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              memory: 128Mi

        - name: mount-fsdb
          image: docker.io/juicedata/mount:ce-v1.3.1
          command:
            - juicefs
            - mount
            - --check-storage
            - sqlite3:///fs/fs.db
            - /fs/mnt
          restartPolicy: Always
          volumeMounts:
            - name: fs
              mountPath: "/fs"
              mountPropagation: Bidirectional
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            runAsNonRoot: false
            privileged: true
            capabilities:
              add: [SYS_RESOURCE]
            seccompProfile:
              type: RuntimeDefault

        - name: wait-for-mount
          image: docker.io/library/busybox:1.37.0
          command:
            - sh
            - -c
            - |
              until mountpoint -q /fs/mnt; do
                sleep 1 &
                wait $!
              done
          volumeMounts:
            - name: fs
              mountPath: /fs
              mountPropagation: HostToContainer
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]

      volumes:
        - name: fs
          emptyDir: {}
        - name: litestream
          configMap:
            name: litestream
