namespace: bluesky
labels:
  - pairs:
      app.kubernetes.io/name: bluesky-pds
      app.kubernetes.io/instance: pds
      app.kubernetes.io/version: "0.4.193"

resources:
  - service.yaml
  - httproute.yaml
  - dnsendpoint.yaml
  - statefulset.yaml
  - serviceaccount.yaml
  - ../garage/access-keys/infinity-and-beyond
components:
  - ../../common/litestream
  - ../../common/litestream/templ-config

secretGenerator:
  - name: pds-config
    env: .env
  - name: pds-actor-keys
    files:
      - vrtx.key=config/vrtx.sops.key
