# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.34.1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: bluesky-pds
  namespace: bluesky
type: Opaque
# enc!
stringData:
  jwtSecret: ENC[AES256_GCM,data:B9UFCxErS8X3/+M+lvGYUJNapfzBCu/CeMdyR1zrpIw=,iv:vr1iS5U88sPXjyOmM/W1htP91LBRYVr1dPfUG3AoP5Y=,tag:VjkbC+Epj4t7NjUJxAcluQ==,type:str]
  adminPassword: ENC[AES256_GCM,data:5LVO3Tv+pdH1O8P3femPAO/7TBEzaMUmB3r+OJ+O6vE=,iv:tsjZ2nWrHhjwWMGq5pkIOOhyd/n2axVuZKKaforKL2M=,tag:hVU6SiylJZdwwS+nOfT8WQ==,type:str]
  plcRotationKey: ENC[AES256_GCM,data:BbKWSnaiQetXX/PBVWkZpoE2KN4aWAA/9MiraRDvVTu/x/8V03C5op/p92OIhAvsO0L43zo8syWis9VXNs9JEQ==,iv:sQKaTqfQDoFZ49Jfo8YQmIjB9i34u8dvMgJ8rKrRyjc=,tag:45mJI/A2ItX+wRU5ymfFiw==,type:str]
  emailSmtpUrl: ENC[AES256_GCM,data:c/y4zc6yL2r+9eN8WfBrzBqgldOKFDH8vI5ausuMKjQJz9tRBOcpjttAuJTwWV+zqnYIMN2tKp+AL5JJje7rE+wYiWEo5LDJiUpJ65fH4karhhFZpcDh4evBrokKcTY=,iv:P6wcV23S8cG87MpgDkLF1/JVOZTWJLyhyZMUNSCI92o=,tag:4/zZNZRoPUQRGIwjDDNFwA==,type:str]
  s3AccessKey: ENC[AES256_GCM,data:QiYDP7zeqWVfvWOY6mD2ubP1vEavjuGT0QI=,iv:MkagcyXMAgBhUMbLugJ9xMZYtURGHcsWTQ9UryEkpzU=,tag:2loDcfxYJcjh6kuuZ0aW6w==,type:str]
  s3SecretKey: ENC[AES256_GCM,data:phmRd72XG1ao2koRzJzjpvcY5/yylPUgJnktawD4fLPvS43hCc5fUrEoaKBGNI47pFQ76SPFwifHEXYkR/JZ7A==,iv:GGz/+HZB3LJWio3uiPmnqG93WokwUu2sfW8Kn/c4oUQ=,tag:E8pw2pXV9oi+ym+JNhAceQ==,type:str]
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyA1RkEy
        L3BKZURSME9Td3N2K3M4aXZBbVVIYTEySHBUQ1g0d2NaSEM1RWlRCk1ZUlAzaE9y
        OVlQNFdVVnBzd3hpbEU4andFbStiOUc1YzR3N2R3bzQxaWMKLS0tIFpGK24vditx
        ckVhaEcxTVNtMno0L3hnV0UrWnRYK09FZGFGYXZWNXVlVTQK2T3uaBI6Q5F2tWxE
        qETVY+0ITGTlHmzEb56Z530Jh6qTvvgA4cw2elfB1cHfyBkP0nlHAUXDYze3t1Bv
        gwedMA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4dTJheCtmZ3NKenZISmtT
        VWw5WUpuam9aOXhVUVIxbktNZ2U5Y0NtbHk0CjlvajJhMnNDVzdpMkkzUFhQUGFY
        dEZEbzdEdzBsUk5xZTh0UW5vbDgwV1UKLS0tIGhqQzI4L2F2MlMzZEVGR2VkWkph
        YmduT2pFd25EK0pzUGk5MWhCYTJVMHMK19o6qCEtK5Lmy7KKmirOe4+7EBE8BOzO
        5moooZHoi8dp/89yrjxW/QQxBzLtCRpskTSbHd564/+fRX6FU5tL6g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-25T13:09:20Z"
  mac: ENC[AES256_GCM,data:gf5u5i3BG394MPrKMis/nZ8iJc8qKpdtz8cJKpsFWC64wHNsVkUE8xUwg8W10BLmqaAMaeXKWIllpNF7+kYvp7pJNLdjoyWftoZrfNxwVThWpsZerMglyOoNjANuD8SPtCfWIK55pUr4f/i9PCbNS8LUv6Jhc+gLYnIr+TXeKHA=,iv:Gg/+1sVAKIZweRiB+xtCylRvzV0C9fwMZDX07L+2K+M=,tag:NuFZ9rH4FCbaZd00Z7dFLw==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
