# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.34.1/serviceaccount.json
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bluesky-pds
  namespace: bluesky
