apiVersion: cloudflared-operator.vrtx.sh/v1alpha1
kind: CfdTunnel
metadata:
  name: grafana
  namespace: monitoring-system
spec:
  serviceMonitor: {}
  dns:
    externalDNS:
      kind:
        generated:
          endpoints:
            - dnsName: klustermntr.sophons.cloud

  accountId: 93814820f122031e8f5004eb893430f0
  apiToken:
    secretRef:
      name: cf-dns-api-token
      namespace: default
    key: api-token

  serviceRef:
    name: grafana
  ingress:
    - service: https://traefik.traefik.svc.cluster.local
  originRequestConfig: |
    matchSNItoHost: true
    http2Origin: true

  podSpecOverrides:
    tolerations:
      - key: caeneus.sophons.cloud
        operator: Exists
  containerOverrides:
    name: cloudflared
    env:
      - name: GOGC
        value: "50"
    resources:
      requests:
        cpu: 25m
        memory: 32Mi
      limits:
        memory: 64Mi
