# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.34.1/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: grafana
  namespace: grafana
# enc!
stringData:
  oauthClientSecret: ENC[AES256_GCM,data:wpb0sMwKgFtLWBe5z9PdrbQ5BNYhcT7vEOC0ixccrUjBtuYs8IID3z4K9okOGx7hl60sv6NYam5klzvT4JaB+A==,iv:5RwBeg5pshqFqBVWpQNOQHCLWM82XzefRbF5458y1+E=,tag:qBP/oIgLjM+6CV0Us95k6g==,type:str]
  adminUser: ENC[AES256_GCM,data:xsIWzEZtv2HV4Q==,iv:53BhF0viKTKttETeoFq90w01I25tngipqLX26BWLDns=,tag:yzvY2SoJxOAkliREyg1zuA==,type:str]
  adminPassword: ENC[AES256_GCM,data:1+BnogvXhw7ytEnQxXFi1AiM/ZwE2mlEmK3qSNWwpoM=,iv:9i9hyd/hx7hCgm/hcfoFfSSvllMBLojeZPFUirPVXQI=,tag:JkHn9J+HI3Ay8aRX9DKSBA==,type:str]
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBBVFdW
        bFFyb3hTZEtnRXhQaEFWeTJpdWRIK3hmcHFBZmpHK0pzUzJEa1U4Clhzb2RDS3Vh
        UkIzR3p3eUFvYWdheTk0QmRmQk9BelNFZ3h5OGdkVmRDL00KLS0tIGhWN3dzeXNa
        cFFPdE5BZjd6eDlvR0hXWmc4Y05oN2YwMjdJb01sOHNXMG8Kd1615paTuWb9+hXy
        qW+oQZ8IJ/1n2Ob33r9wzcCBoea6Ha7Jzg25oK0UmDkyebDg6Gqk8wyYH60zyq1u
        QVreYw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGOCtVb201aHdhT1NWc0E5
        RzN5cUVEaXRxRXRwYXZHVEVjeDZ1RzBOUmprCjVwNFQzZmJQRTNza1BhNWZLY0JI
        SlVWd05pY2dtTmxnYTNraHhVWXZCSGcKLS0tIGQ1NlJDdGdOOU1IWTRFTDh1NGxG
        VW9lSGhuenRWVFNhcU50R1NweHF1OGsKp+P9MwiMgl8dJr6vU+wUHyAyZzQYM6MO
        slA85zKRRa6qoxsqu9JJOlNr2QjwrCpIl16TDn5HgXyVEVFqhzq0qQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-31T18:37:00Z"
  mac: ENC[AES256_GCM,data:tqyU4sNy9WzKRXs0rTUQbqBAxcK7gQlSnB5Tal+Qp4N5cxr63XYxl+wa9fsgrK0ap52XwhEsvGXqs9SJfOxNl8O5vj3m27c4EQRSrryL37UysgHCVII/iGWSh3nFHHCEcdh9S6gNUddNzflj7Sxfz12BU1XgoY8qWXumimSq608=,iv:eii1l2F1+sreaGteJhVOc4qsHvapgoyf7OWA3SKXNNo=,tag:4NMC4aa0XFZ6I8AFi1idWQ==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
