# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.34.1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: trisolaris-harbor-access-key
  namespace: harbor
type: Opaque
# enc!
stringData:
  REGISTRY_STORAGE_S3_ACCESSKEY: ENC[AES256_GCM,data:dWsLNqJshDUwiZ/m7kfJRaJQIPTkHfhb3w==,iv:m7uJINwQ60NJ4VOBHg/FlaNpEtICDfYHR0X2ZSls0pc=,tag:l/Jtp7Cizwqc6EXV+yWTEA==,type:str]
  REGISTRY_STORAGE_S3_SECRETKEY: ENC[AES256_GCM,data:WNTwaVN9aUX45Hc8neB2Cq0vAmFaGi6dCJ/7n4HOQw==,iv:3nu4U2eVn6A6vCI4KkHByker4YqoRg4TnLi7rGDgWMU=,tag:H2S9IWicfOHR63tx4hMkUw==,type:str]
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyAxN2xB
        NnFmUWh4bkN0ZUZiS1dmcEJ2c1l6MkZpVElVaGhBb2NNbEpqc0dnCnFtM0FidDA4
        TTJTbjJpOVVvbTVrV2ZpMWx6U21xTUdSNU1FdTVneEp3VnMKLS0tIDBLL0luQW9z
        V3hNVThSTE1sYWhXOU82NGRyMHVFc2dmdVBUT2tjRlN1L2sKNTtaBLgUTJ4qZUds
        K2FjQ5or0YI8TZQge14XKzOA/B/2ABf+VYNvL76wEBRaWWhhQamDzTkFQrB2Q7cR
        eF9V9w==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZcFhsLzZIZndaNnJVZEhx
        aXJCdXZkWVp6M3lmTVpQR1BrL3ZpbVo5ZW5RCkNvL2QvQ3FhU0NiQ1l6dGdrU0VD
        M0pwakZ5L1lBUzFiS1JqL21qYmdnZlkKLS0tIGFYaWlZQ1BGTmdnZ1hwV2lzQTVO
        WjBvemtuQ1FPV05JR0RSekZvSVpDVWsKyuK/wE92BulEgWRpbdbhkKOxAyMrtHM2
        t0ozW4Y4yrkQ9dFcmndx9e00i4j/bb7UZv8d72yjjBGxWkixHeN8Dw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-20T00:56:25Z"
  mac: ENC[AES256_GCM,data:B6RrpCXxpJ5XUv48t366mqFWILAhrKQHENIcyzPqlWqcy7hIDIiUzXHq+2bbYNPRyC6HSKd1aEGAORr7QTzpFi3zr+saVL3RdvUOeUDjfXlOOiyFT8vmLDBE94CM79HZie9945jAl/WBV0YxDt+zeWWNR6gfzye5VX7mlOaPZos=,iv:0O4p3hypLvMMLhn20ck6hSIbinW48GUxTn5/JuBhC4k=,tag:Rw+dtcCNFec8+sfp9VWNQg==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
