apiVersion: operator.victoriametrics.com/v1
kind: VLSingle
metadata:
  name: klusterstalker
  namespace: victoriametrics-system
spec:
  retentionPeriod: "7d"
  extraArgs:
    enableTCP6: "true"

  tolerations:
    - key: oduduwa.sophons.cloud/ase-orun
      operator: Exists
    - key: caeneus.sophons.cloud
      operator: Exists

  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 512Mi

  extraEnvs:
    - name: GOMEMLIMIT
      value: 512MiB

  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop: [ALL]
    seccompProfile:
      type: RuntimeDefault

  storage:
    storageClassName: weedfs-no-repl
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi

  # volumes:
  #   - name: data
  #     emptyDir: {}
  #   - name: litestream
  #     configMap:
  #       name: litestream-juicefs
  # volumeMounts:
  #   - name: data
  #     mountPath: /fs
  #     mountPropagation: HostToContainer
  # storageDataPath: /fs/mnt/victorialogs

  # initContainers:
  #   - name: cleanup-emptydir
  #     image: docker.io/library/busybox:1.37.0
  #     command:
  #       - sh
  #       - -c
  #       - |
  #         set -e
  #         rm -rf /fs/meta.db*
  #         rm -rf /fs/.*meta.db*
  #     volumeMounts:
  #       - name: data
  #         mountPath: /fs
  #     securityContext:
  #       readOnlyRootFilesystem: true
  #       allowPrivilegeEscalation: false
  #       capabilities:
  #         drop: [ALL]
  #       seccompProfile:
  #         type: RuntimeDefault

  #   - name: litestream-restore-meta
  #     image: docker.io/litestream/litestream:0.5.9
  #     args:
  #       - restore
  #       - -config=/etc/litestream/litestream.yaml
  #       - -parallelism=6
  #       - /fs/meta.db

  #     envFrom:
  #       - secretRef:
  #           name: juicestream-cluster-s3-global-access-key
  #     env:
  #       - name: VOLUME_NAME
  #         value: vl-klusterstalker-v2
  #       - name: GOMEMLIMIT
  #         valueFrom:
  #           resourceFieldRef:
  #             resource: limits.memory
  #       - name: LITESTREAM_LOGGING_LEVEL
  #         value: debug

  #     volumeMounts:
  #       - name: data
  #         mountPath: "/fs"
  #       - name: litestream
  #         mountPath: "/etc/litestream"
  #         readOnly: true
  #     securityContext:
  #       allowPrivilegeEscalation: false
  #       readOnlyRootFilesystem: true
  #       capabilities:
  #         drop: [ALL]
  #       seccompProfile:
  #         type: RuntimeDefault

  #     resources:
  #       requests:
  #         cpu: 25m
  #         memory: 64Mi
  #       limits:
  #         memory: 128Mi

  #   - name: litestream-replicate
  #     restartPolicy: Always
  #     image: docker.io/litestream/litestream:0.5.9
  #     args: ["replicate", "-config=/etc/litestream/litestream.yaml"]
  #     envFrom:
  #       - secretRef:
  #           name: juicestream-cluster-s3-global-access-key
  #     env:
  #       - name: VOLUME_NAME
  #         value: vl-klusterstalker-v2
  #       - name: GOMEMLIMIT
  #         valueFrom:
  #           resourceFieldRef:
  #             resource: limits.memory

  #     ports:
  #       - name: ls-metrics
  #         containerPort: 9090

  #     volumeMounts:
  #       - name: data
  #         mountPath: "/fs"
  #       - name: litestream
  #         mountPath: "/etc/litestream"
  #         readOnly: true

  #     securityContext:
  #       readOnlyRootFilesystem: true
  #       allowPrivilegeEscalation: false
  #       capabilities:
  #         drop: [ALL]
  #       seccompProfile:
  #         type: RuntimeDefault

  #     resources:
  #       requests:
  #         cpu: 50m
  #         memory: 64Mi
  #       limits:
  #         memory: 256Mi

  #   - name: mount-fsdb
  #     restartPolicy: Always
  #     image: docker.io/juicedata/mount:ce-v1.3.1
  #     command:
  #       - juicefs
  #       - mount
  #       - --check-storage
  #       - --backup-meta=0 # litestream does this
  #       - sqlite3:///fs/meta.db
  #       - /fs/mnt

  #     env:
  #       - name: GOMEMLIMIT
  #         valueFrom:
  #           resourceFieldRef:
  #             resource: limits.memory
  #     envFrom:
  #       - secretRef:
  #           name: steroids-ps3-global-access-key

  #     volumeMounts:
  #       - name: data
  #         mountPath: "/fs"
  #         mountPropagation: Bidirectional
  #     startupProbe:
  #       exec:
  #         command:
  #           - mountpoint
  #           - -q
  #           - /fs/mnt
  #       failureThreshold: 60
  #       periodSeconds: 1
  #     securityContext:
  #       runAsUser: 0
  #       runAsGroup: 0
  #       runAsNonRoot: false
  #       privileged: true # required for Bidirectional
  #       capabilities:
  #         drop: [ALL]
  #         add: [SYS_RESOURCE, SYS_ADMIN]
  #       seccompProfile:
  #         type: RuntimeDefault
  #     resources:
  #       requests:
  #         cpu: 150m
  #         memory: 128Mi
  #       # limits:
  #       #   memory: 300Mi

  #   - name: chown-mount
  #     image: docker.io/library/busybox:1.37.0
  #     command: [chown, 1000:1000, /fs/mnt]
  #     volumeMounts:
  #       - name: data
  #         mountPath: /fs
  #         mountPropagation: HostToContainer
  #     securityContext:
  #       runAsUser: 0
  #       runAsGroup: 0
  #       runAsNonRoot: false
  #       readOnlyRootFilesystem: true
  #       allowPrivilegeEscalation: false
  #       capabilities:
  #         drop: [ALL]
  #         add: [CHOWN]
  #       seccompProfile:
  #         type: RuntimeDefault
---
apiVersion: operator.victoriametrics.com/v1
kind: VLAgent
metadata:
  name: klusterstalker
  namespace: victoriametrics-system
spec:
  extraArgs:
    enableTCP6: "true"

  priorityClassName: system-node-critical
  tolerations:
    - operator: Exists

  resources:
    requests:
      cpu: 100m
      memory: 32Mi
    limits:
      cpu: 300m
      memory: 128Mi

  extraEnvs:
    - name: GOMEMLIMIT
      value: 120MiB

  k8sCollector:
    enabled: true
  remoteWrite:
    - url: "http://vlsingle-klusterstalker.victoriametrics-system.svc.cluster.local:9428/internal/insert"
  syslogSpec:
    tcpListeners:
      - listenPort: 29514
