commonLabels:
  cluster.garage.sophons.cloud: global

garage:
  kubernetesSkipCrd: true
  existingRpcSecret: garage
  existingConfigMap: global-garage-config

persistence:
  enabled: true
  meta:
    storageClass: local-path
  data:
    storageClass: local-path

image:
  repository: dxflrs/garage

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    memory: 1Gi

priorityClassName: system-node-critical

securityContext:
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault

deployment:
  kind: StatefulSet
  replicaCount: 4

tolerations:
  - key: prime.sophons.cloud
    operator: Exists
  - key: caeneus.sophons.cloud
    operator: Exists

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: garage
            app.kubernetes.io/instance: global-gateway
        mismatchLabelKeys: [controller-revision-hash]
        topologyKey: kubernetes.io/hostname
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: garage
            app.kubernetes.io/instance: global
        topologyKey: kubernetes.io/hostname

monitoring:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  tracing:
    sink: "http://zero-order-alloy.monitoring-system:4317"
