apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: internal
  namespace: metallb-system
spec:
  addresses:
    - 10.42.100.0/24
  autoAssign: false
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBCR3A2
        ZEdHdUt2bzlmdnVmOHI0RlFrR3NxTU52eVh3Y215d2c0aWFLOURFCnlZWHJSNDk0
        MVVzejVRODNRZ0IxalYxdWtkZzY0NTNoeUVjK2ljTm4yUUkKLS0tIHVUTEtsNWww
        d2JVS3J5ZWZaaFptL3VqQ2xzbnlsT2d5NmoraXlHWG5RTVkKiawUI7x9V9V8pdDV
        8o6O0yXHpmhOWcaXCa80q4o1uC0rFaoKDycX7vjFuldL+gn48m7RSnqZlibiVxuo
        VsPD9w==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaallsU2owZlpaWktJd3dy
        bC9TUXQweXpYT1JEMHBUbCt6ckk1RW9MOFJRCi9jVVlwNGVqd054SFVqSFo1cXZB
        dE56bWNzOHdwS3YydThwU2pVdHBzbVUKLS0tIG1BdCtDdzlDRG9xb0dHaTJsU3pC
        azR6S2pWUVFiUHVKVnFBcGFISDVwNEUKQATFKAi4g7D7m48Fsss3OQ0BZzv5iscG
        csTHd7oD0n0WYvgTBcqvEfmQSFaPnCyS/25U9lc/U0TVimMKwH50Pg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-09-15T00:10:40Z"
  mac: ENC[AES256_GCM,data:xPAQM40iotFRrPUZtSGIVuVOXJILlf2898F1xELB5wbKSSU9Y3w3LZLFbUMWUGXgHkryHnMn+xeaLSy7KS0QxeegZnJ1/9a0r4lVkS6GvHS45zLhhGq7qf4fjaKNsrNl7DRRdyetF2oRBC2a++6wu6D0NqtA2XouyE+AlLxj5fA=,iv:OpS18L8Uw063aE1/Q02A6rXS4X9kDP6iPSMw9etr4AM=,tag:+soX4wxTTGt42GQG2KikWQ==,type:str]
  version: 3.13.3
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: prime
  namespace: metallb-system
spec:
  addresses:
    - 10.42.102.0/24
  autoAssign: false
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBCR3A2
        ZEdHdUt2bzlmdnVmOHI0RlFrR3NxTU52eVh3Y215d2c0aWFLOURFCnlZWHJSNDk0
        MVVzejVRODNRZ0IxalYxdWtkZzY0NTNoeUVjK2ljTm4yUUkKLS0tIHVUTEtsNWww
        d2JVS3J5ZWZaaFptL3VqQ2xzbnlsT2d5NmoraXlHWG5RTVkKiawUI7x9V9V8pdDV
        8o6O0yXHpmhOWcaXCa80q4o1uC0rFaoKDycX7vjFuldL+gn48m7RSnqZlibiVxuo
        VsPD9w==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaallsU2owZlpaWktJd3dy
        bC9TUXQweXpYT1JEMHBUbCt6ckk1RW9MOFJRCi9jVVlwNGVqd054SFVqSFo1cXZB
        dE56bWNzOHdwS3YydThwU2pVdHBzbVUKLS0tIG1BdCtDdzlDRG9xb0dHaTJsU3pC
        azR6S2pWUVFiUHVKVnFBcGFISDVwNEUKQATFKAi4g7D7m48Fsss3OQ0BZzv5iscG
        csTHd7oD0n0WYvgTBcqvEfmQSFaPnCyS/25U9lc/U0TVimMKwH50Pg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-09-15T00:10:40Z"
  mac: ENC[AES256_GCM,data:xPAQM40iotFRrPUZtSGIVuVOXJILlf2898F1xELB5wbKSSU9Y3w3LZLFbUMWUGXgHkryHnMn+xeaLSy7KS0QxeegZnJ1/9a0r4lVkS6GvHS45zLhhGq7qf4fjaKNsrNl7DRRdyetF2oRBC2a++6wu6D0NqtA2XouyE+AlLxj5fA=,iv:OpS18L8Uw063aE1/Q02A6rXS4X9kDP6iPSMw9etr4AM=,tag:+soX4wxTTGt42GQG2KikWQ==,type:str]
  version: 3.13.3
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: nat-ula
  namespace: metallb-system
spec:
  addresses:
    - fd67::69/128
  autoAssign: false
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBCR3A2
        ZEdHdUt2bzlmdnVmOHI0RlFrR3NxTU52eVh3Y215d2c0aWFLOURFCnlZWHJSNDk0
        MVVzejVRODNRZ0IxalYxdWtkZzY0NTNoeUVjK2ljTm4yUUkKLS0tIHVUTEtsNWww
        d2JVS3J5ZWZaaFptL3VqQ2xzbnlsT2d5NmoraXlHWG5RTVkKiawUI7x9V9V8pdDV
        8o6O0yXHpmhOWcaXCa80q4o1uC0rFaoKDycX7vjFuldL+gn48m7RSnqZlibiVxuo
        VsPD9w==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaallsU2owZlpaWktJd3dy
        bC9TUXQweXpYT1JEMHBUbCt6ckk1RW9MOFJRCi9jVVlwNGVqd054SFVqSFo1cXZB
        dE56bWNzOHdwS3YydThwU2pVdHBzbVUKLS0tIG1BdCtDdzlDRG9xb0dHaTJsU3pC
        azR6S2pWUVFiUHVKVnFBcGFISDVwNEUKQATFKAi4g7D7m48Fsss3OQ0BZzv5iscG
        csTHd7oD0n0WYvgTBcqvEfmQSFaPnCyS/25U9lc/U0TVimMKwH50Pg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-09-15T00:10:40Z"
  mac: ENC[AES256_GCM,data:xPAQM40iotFRrPUZtSGIVuVOXJILlf2898F1xELB5wbKSSU9Y3w3LZLFbUMWUGXgHkryHnMn+xeaLSy7KS0QxeegZnJ1/9a0r4lVkS6GvHS45zLhhGq7qf4fjaKNsrNl7DRRdyetF2oRBC2a++6wu6D0NqtA2XouyE+AlLxj5fA=,iv:OpS18L8Uw063aE1/Q02A6rXS4X9kDP6iPSMw9etr4AM=,tag:+soX4wxTTGt42GQG2KikWQ==,type:str]
  version: 3.13.3
