apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: internal
  namespace: metallb-system
spec:
  ipAddressPools:
    - internal
    - starlink
  nodeSelectors:
    - matchLabels:
        kubernetes.io/hostname: sophons-beta
    - matchLabels:
        kubernetes.io/hostname: sophons-kaos
  interfaces:
    - end0.42
    - enp1s0
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: kaos
  namespace: metallb-system
spec:
  ipAddressPools:
    - kaos
  nodeSelectors:
    - matchLabels:
        kubernetes.io/hostname: sophons-kaos
  interfaces:
    - enp1s0
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: prime
  namespace: metallb-system
spec:
  ipAddressPools:
    - prime
  nodeSelectors:
    - matchLabels:
        kubernetes.io/hostname: sophons-prime
  interfaces:
    - end0.42
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: theta
  namespace: metallb-system
spec:
  ipAddressPools:
    - theta
  nodeSelectors:
    - matchLabels:
        kubernetes.io/hostname: sophons-theta
