apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: internal
  namespace: metallb-system
spec:
  ipAddressPools:
    - internal
    - starlink
  nodeSelectors:
    - matchLabels:
        kubernetes.io/hostname: sophons-prime
    - matchLabels:
        kubernetes.io/hostname: sophons-beta
  interfaces:
    - end0.42
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: theta
  namespace: metallb-system
spec:
  ipAddressPools:
    - theta
  nodeSelectors:
    - matchLabels:
        kubernetes.io/hostname: sophons-theta
