apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: internal
  namespace: metallb-system
spec:
  ipAddressPools:
    - nat-ula
    - internal
  nodeSelectors:
    - matchLabels:
        l2ad.metallb.sophons.cloud/internal-pools: "true"
  interfaces:
    - eth0
    - end0.42
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: prime
  namespace: metallb-system
spec:
  ipAddressPools:
    - prime
  nodeSelectors:
    - matchLabels:
        kubernetes.io/hostname: sophons-prime
  interfaces:
    - end0.42
