# yaml-language-server: $schema=https://github.com/metallb/metallb/raw/refs/heads/main/charts/metallb/values.schema.json

speaker:
  tolerations:
    - key: prime.sophons.cloud
      operator: Exists
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                  - sophons-oduduwa
                  - sophons-caeneus
