namespace: victoriametrics-system
resources:
  - ../../../../system/juicefs-csi-driver/format

replacements:
  - sourceValue: mkfs-vm-klusterstalker
    targets:
      - select:
          name: mkfs
          kind: Job
        fieldPaths:
          - metadata.name

patches:
  - patch: |-
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: mkfs
      spec:
        template:
          spec:
            initContainers:
              - name: litestream-restore-meta
                env:
                  - name: VOLUME_NAME
                    value: vm-klusterstalker-v2
              - name: fail-if-exists
              - name: litestream-replicate
                env:
                  - name: VOLUME_NAME
                    value: vm-klusterstalker-v2
            containers:
              - name: format
                env:
                  - name: VOLUME_NAME
                    value: vm-klusterstalker-v2
