apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: authelia
  namespace: authelia
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Authzzz
    gethomepage.dev/group: Admin
    gethomepage.dev/icon: authelia.svg
    gethomepage.dev/name: Authelia
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
      sectionName: web
    - name: traefik-gateway
      namespace: traefik
      sectionName: websecure

  hostnames:
    - auth.sophons.cloud

  rules:
    - backendRefs:
        - name: authelia
          port: 80
