apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: forwardauth-authelia
  namespace: authelia
spec:
  forwardAuth:
    address: "http://authelia.authelia.svc.cluster.local/api/authz/forward-auth"
    trustForwardHeader: true
    authResponseHeaders:
      - "Remote-User"
      - "Remote-Name"
      - "Remote-Email"
      - "Remote-Groups"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: chain-authelia-auth
  namespace: authelia
spec:
  chain:
    middlewares:
      - name: forwardauth-authelia
        namespace: authelia
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oidc-enable-response-caching
  namespace: authelia
spec:
  headers:
    customResponseHeaders:
      Cache-Control: "public, max-age=604800, stale-while-revalidate=86400, stale-if-error=86400"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oidc-cache
  namespace: authelia
spec:
  plugin:
    souin:
      default_cache:
        mode: bypass_response
        ttl: 604800s # 7d
        stale: 86400s # 1d
