# yaml-language-server: $schema=https://raw.githubusercontent.com/authelia/chartrepo/refs/tags/authelia-0.10.54/charts/authelia/values.schema.json
persistence:
  enabled: false

ingress:
  enabled: false
  traefikCRD:
    enabled: true
    disableIngressRoute: true

pod:
  kind: StatefulSet
  replicas: 1
  selectors:
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
                - key: topology.kubernetes.io/region
                  operator: In
                  values: [de, nl]
            weight: 100

  securityContext:
    pod:
      runAsUser: 1000
      runAsGroup: 1000
      runAsNonRoot: true
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
      seccompProfile:
        type: RuntimeDefault
    container:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop: [ALL]

  initContainers:
    - name: litestream-replicate
      restartPolicy: Always
      image: docker.io/litestream/litestream
      command: [bash, /etc/litestream/entrypoint.sh]
      envFrom:
        - configMapRef:
            name: litestream-env
        - secretRef:
            name: infinity-and-beyond-access-key
      env:
        - name: GOGC
          value: "25"
        - name: GOMEMLIMIT
          valueFrom:
            resourceFieldRef:
              resource: limits.memory
        - name: LITESTREAM_DBS
          value: db.sqlite3,redka.sqlite3
        - name: LITESTREAM_DBS_DIR
          value: /db
        - name: LITESTREAM_DBS_PATTERN
          value: "*.sqlite3"
        - name: LITESTREAM_ENDPOINT
          value: https://ps3-global.sphns.run
        - name: LITESTREAM_BUCKET
          value: litestream-ad-infinitum
        - name: LITESTREAM_REPLICA_PATH
          value: ng/authelia

      ports:
        - name: ls-metrics
          containerPort: 9090

      startupProbe:
        exec:
          command: [bash, /etc/litestream/restore-probe.sh]
        initialDelaySeconds: 15
        periodSeconds: 5
        failureThreshold: 30

      volumeMounts:
        - name: tmp
          subPath: db
          mountPath: /db
        - name: litestream-config
          mountPath: /etc/litestream
          readOnly: true
        - name: tmp
          subPath: litestream
          mountPath: /tmp

      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop: [ALL]

      resources:
        requests:
          cpu: 50m
          memory: 48Mi
        limits:
          memory: 100Mi
    - name: redka-redis
      restartPolicy: Always
      image: docker.io/nalgeon/redka:1.0.1
      args: ["/db/redka.sqlite3"]
      env:
        - name: GOGC
          value: "25"
        - name: GOMEMLIMIT
          valueFrom:
            resourceFieldRef:
              resource: limits.memory

      ports:
        - name: redis
          containerPort: 6379

      startupProbe:
        exec:
          command: [sh, -c, "valkey-cli PING || exit 1"]

      livenessProbe:
        exec:
          command: [sh, -c, "valkey-cli PING || exit 1"]

      volumeMounts:
        - name: tmp
          subPath: db
          mountPath: /db
        - name: tmp
          subPath: redka
          mountPath: /tmp

      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop: [ALL]

      resources:
        requests:
          cpu: 50m
          memory: 32Mi
        limits:
          memory: 64Mi

  extraVolumeMounts:
    - name: tmp
      subPath: db
      mountPath: /db
    - name: authelia-users
      mountPath: /auth

  extraVolumes:
    - name: tmp
      emptyDir: {}
    - name: authelia-users
      configMap:
        name: authelia-users
    - name: litestream
      configMap:
        name: litestream
    - name: litestream-config
      configMap:
        name: litestream-config

configMap:
  log:
    level: info
  telemetry:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  authentication_backend:
    password_reset:
      disable: true
    password_change:
      disable: true
    refresh_interval: always
    file:
      enabled: true
      path: /auth/users.yaml
      watch: true
      password:
        algorithm: "argon2"
        argon2:
          variant: "argon2id"
          iterations: 3
          memory: 65536
          parallelism: 4
          key_length: 32
          salt_length: 16
      extra_attributes:
        sshpubkey:
          multi_valued: true
          value_type: "string"

  storage:
    local:
      enabled: true
      path: /db/db.sqlite3

  session:
    redis:
      enabled: true
      host: localhost
      password:
        disabled: true
    cookies:
      - domain: sophons.cloud
        subdomain: auth
      - domain: sphns.run
        subdomain: auth
      - domain: vrtx.sh
        subdomain: auth
      - domain: kaos.nexus
        subdomain: auth
    expiration: 24 hours
    inactivity: 30 minutes
    remember_me: 1 month

  notifier:
    smtp:
      enabled: true
      address: "smtp://in-v3.mailjet.com:588"
      username: "1744ca110f7f119167b0b2a29123845d"
      timeout: "15 seconds"
      sender: "Authelia <auth@vrtx.sh>"
      ## HELO/EHLO Identifier. Some SMTP Servers may reject the default of localhost.
      identifier: "vrtx.sh"
      ## {title} is replaced by the text from the notifier
      subject: "{title}"
      startup_check_address: "noreply@vrtx.sh"

  identity_providers:
    oidc:
      enabled: true
      jwks:
        - key:
            path: /secrets/authelia/oidc.jwk.rs256.pem
      claims_policies:
        karakeep:
          id_token: [email]
        headscale:
          id_token: [email, groups]
        grafana:
          id_token: [email, name, groups, preferred_username]
        forgejo:
          custom_claims:
            sshpubkey: {}

      scopes:
        sshpubkey:
          claims:
            - sshpubkey

      clients:
        - client_name: Karakeep
          client_id: "sphns_q1F-KFdfxuwpzFejpdac311zzc65t0eiT.X1Vu3mE5"
          client_secret:
            path: "/secrets/authelia/oidc.client.karakeep.digest"
          redirect_uris:
            - https://holding.sophons.cloud/api/auth/callback/custom
            - https://hoarder.sophons.cloud/api/auth/callback/custom
          # workaround because karakeep doesn't actually implement oidc correctly:
          # https://www.authelia.com/integration/openid-connect/clients/karakeep/#configuration-escape-hatch
          claims_policy: karakeep
          scopes:
            - openid
            - profile
            - email
          response_types:
            - code
          grant_types:
            - authorization_code

        - client_name: Forgejo
          client_id: "sphns_cufg6XmWtrPDXfNi_lOfqr2pHP2wdVkF_OKNeIrKye"
          client_secret:
            path: "/secrets/authelia/oidc.client.gitea.digest"
          claims_policy: forgejo
          require_pkce: true
          pkce_challenge_method: "S256"
          redirect_uris:
            - https://tig.vrtx.sh/user/oauth2/authelia/callback
          scopes:
            - openid
            - email
            - profile
            - groups
            - sshpubkey
          response_types:
            - code
          grant_types:
            - authorization_code

        - client_name: Headscale
          client_id: "sphns_NOVzB7ZaA_wjYbmD_GnTrX2SiUKFZmTL7zSEASd~tG"
          client_secret:
            path: "/secrets/authelia/oidc.client.headscale.digest"
          require_pkce: true
          pkce_challenge_method: "S256"
          # https://www.authelia.com/integration/openid-connect/clients/headscale/#configuration-escape-hatch
          claims_policy: headscale
          redirect_uris:
            - https://hs.vrtx.sh/oidc/callback
            - https://hs.vrtx.sh/admin/oidc/callback
          scopes:
            - openid
            - profile
            - groups
            - email
          response_types:
            - code
          grant_types:
            - authorization_code

        - client_name: Grafana
          client_id: "sphns_8Y0WEhOcipKfGgjYQNF6x9imgEMZSrn1wZFPcBd-.4"
          client_secret:
            path: "/secrets/authelia/oidc.client.grafana.digest"
          require_pkce: true
          pkce_challenge_method: "S256"
          # https://www.authelia.com/integration/openid-connect/clients/grafana/#configuration-escape-hatch
          claims_policy: grafana
          redirect_uris:
            - https://klustermntr.sophons.cloud/login/generic_oauth
          scopes:
            - openid
            - offline_access
            - profile
            - groups
            - email
          response_types:
            - code
          grant_types:
            - authorization_code
            - refresh_token

        - client_name: Zot
          client_id: "sphns_gPmWD8eBveVFwKTcvK8R1.Q-QfoGqLBSpXSNeTVQ35"
          client_secret:
            path: "/secrets/authelia/oidc.client.zot.digest"
          redirect_uris:
            - https://zenlesszonezot.sophons.cloud/zot/auth/callback/oidc
            - https://z3.sphns.run/zot/auth/callback/oidc
          scopes:
            - openid
            - offline_access
            - profile
            - groups
            - email
          response_types:
            - code
          grant_types:
            - authorization_code
            - refresh_token

        - client_name: Immich
          client_id: "sphns_1wobcPby2p5DszRCkyiWPEE9fqhPXDYyERcSPDpoxj"
          client_secret:
            path: "/secrets/authelia/oidc.client.immich.digest"
          redirect_uris:
            - https://gimmich.sophons.cloud/auth/login
            - https://gimmich.sophons.cloud/user-settings
            - app.immich:///oauth-callback
          scopes:
            - openid
            - profile
            - groups
            - email
          response_types:
            - code
          grant_types:
            - authorization_code
          token_endpoint_auth_method: client_secret_post

secret:
  existingSecret: authelia
  additionalSecrets:
    authelia:
      items:
        - key: oidc.jwk.rs256.pem
        - key: oidc.client.karakeep.digest
        - key: oidc.client.gitea.digest
        - key: oidc.client.headscale.digest
        - key: oidc.client.grafana.digest
        - key: oidc.client.zot.digest
        - key: oidc.client.immich.digest
