# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.34.1/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: grafana
  namespace: grafana
# enc!
stringData:
  oauthClientSecret: ENC[AES256_GCM,data:qmm018nGNQuaevcQLglEruJY4ofLZaJdvIBJRSfntPzsuvk+Tx0vBoPe+dIpUuzaMQsS0YK6c/YwpfFUM5Ihiw==,iv:Xoq3Iow8vAPoGzm6Ai7ZR4cemyvLQUiyAfLHpvdTtas=,tag:qLyBTutf7UuRGIyr5s0nwg==,type:str]
  adminUser: ENC[AES256_GCM,data:tFftb7zwobMkvA==,iv:Kan/hno4hwRHX/hs4OeI474IQjbawRu2xncX5dk1T24=,tag:GQyhI2mQ9E7yfVnxGs5OCA==,type:str]
  adminPassword: ENC[AES256_GCM,data:A+ZHL+mLRwDCA+NlmKU1KWdy0OKuyxhWhF9iW5SYVDE=,iv:M5vVTfvnRIjrqJ/HVwzq3SHHjAd5XJWfvskjljuQRIs=,tag:/qj6ZyECDcLSu7OQk7ucIQ==,type:str]
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBpNGVw
        NlRVRlBmdVZBN3d2QmtwVmtXa25wblMwQ2d3S0VMT2paYWYxSGdBCnpmeUlkOHds
        U2ZQbGI5S3kyQjhlNU1qNW9JK0Z5UHpxemJHMkpKd3FzZG8KLS0tIEticHhBcjlo
        SDFEeU13YlpER3NBK3oxYWdxSXdJRmt4a1FYWlYrcnk0Y2cK5WNObtw33Nl7uphz
        OJdeNSSz56UmgEBakldgaRAz8aPOsSZR2ztyYowAJ/KzCh726T+Y48iCkJmUai01
        FzFr3w==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzdlhoblN0dm5GenlTNi83
        Ylp6KzkwdEdMZkZZUndzOXBqcDFzOHg5OFE4CmNzcTNGbjFYdkYvVkp6SXNvQTkx
        OHVqWVZqNWU5bjVDZm5IelV2R05KYXMKLS0tIDhFakdWOEtOdzNFVVhNMjZ2dmtz
        KzIrd3F0RW9PL0NJeW9nbDBuMmp5aXcKAdqbJtZNZjOEsT5gxuevWUsT3CCMD8TZ
        y8Lc+wySQSLJIZBOaHmbsTds2teV0q1K/QlgC1K8wjyfn58uUYRd3w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-03T00:02:24Z"
  mac: ENC[AES256_GCM,data:QUC90/8MeHyudtuoKeAFv7zofAWm9hoH4wptYUS4J+0A7Xin1HW5FS9LITRWR5uFO0J/afq+NHVeZ1S6IiVops+UiCuKuTgX/JyucrOhQHntNdSQJnqmOu6fC04jJXetsA/rVyJy4n0ILduStssHHFojg+BoOrH324LRoOylIC0=,iv:SdkRUY6i1+bWNT5aeXXa8RgkHFph2hbUerzFo+mgUUE=,tag:pkynt7/6bXqzEDNN4Wjp0w==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
