apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

secretGenerator:
  - name: tailscale-auth
    env: .env

patches:
  - target:
      kind: ConfigMap
      name: tailscale-config
    patch: |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: tailscale-config
      data:
        TS_KUBE_SECRET: ""
        TS_STATE_DIR: ""
        TS_AUTH_ONCE: "false"
