apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

secretGenerator:
  - name: tailscale-auth
    envs: [.env]

configMapGenerator:
  - name: tailscale-config
    behavior: merge
    literals:
      - TS_KUBE_SECRET=""
      - TS_STATE_DIR=""
      - TS_AUTH_ONCE="false"
