# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.35.2/deployment-apps-v1.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mimir-mirage
  namespace: monitoring-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector: {}
  template:
    spec:
      priorityClassName: system-node-critical
      tolerations:
        - key: caeneus.sophons.cloud
          operator: Exists
      nodeSelector:
        topology.kubernetes.io/region: ng
      terminationGracePeriodSeconds: 900 # 15 minutes

      volumes:
        - name: tmp
          emptyDir: {}
        # - name: seaweedfs-cache
        #   hostPath:
        #     path: /var/lib/garage/weedfs/cache
        - name: config
          configMap:
            name: mimir-mirage-config
        - name: runtime-config
          configMap:
            name: mimir-mirage-runtime-config
        - name: litestream-config
          configMap:
            name: litestream-juicefs
        - name: juicefs-cache
          hostPath:
            path: /var/lib/garage/juicefs/cache

      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        seccompProfile:
          type: RuntimeDefault

      initContainers:
        - name: litestream-replicate
          restartPolicy: Always
          image: docker.io/litestream/litestream:0.5.11
          command:
            - sh
            - -c
            - |-
              set -xeu

              rm -f $META_PATH
              LITESTREAM_LOGGING_LEVEL=debug litestream restore \
                -config=/etc/litestream/litestream.yaml -if-replica-exists \
                $META_PATH

              exec litestream replicate -config=/etc/litestream/litestream.yaml
          envFrom:
            - configMapRef:
                name: litestream-env-juicefs
            - secretRef:
                name: weed-s3-access-key
          env:
            - name: GOGC
              value: "10"
            - name: GOMEMLIMIT
              value: 120MiB
            - name: META_PATH
              value: /fs/meta.db
            - name: VOLUME_NAME
              value: mimir-mirage

          ports:
            - name: ls-metrics
              containerPort: 9090

          startupProbe:
            httpGet:
              path: /metrics
              port: ls-metrics
            initialDelaySeconds: 10
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /metrics
              port: ls-metrics

          volumeMounts:
            - name: tmp
              subPath: fs
              mountPath: /fs
            - name: litestream-config
              mountPath: /etc/litestream
              readOnly: true

          securityContext:
            runAsUser: 0
            runAsGroup: 0
            runAsNonRoot: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
            seccompProfile:
              type: RuntimeDefault

          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              memory: 128Mi

        - name: juice-mount
          restartPolicy: Always
          # NOTE: the fix for 0% available inodes blocking caching exists
          # in juicefs main, but the docker image hasn't been updated in months
          # this image is pinned to a commit including the fix
          image: pz3.sphns.run/library/juicedata/mount:ce-6541bca
          command:
            - sh
            - -c
            - |-
              set -xeu
              juicefs format --no-update \
                --storage=s3 --bucket=$LITESTREAM_ENDPOINT/$LITESTREAM_BUCKET \
                sqlite3://$META_PATH $VOLUME_NAME
              juicefs config --capacity=4 --dir-stats=true --trash-days=0 \
                sqlite3://$META_PATH

              exec juicefs mount -o async_dio,allow_other --buffer-size=64M \
                --backup-meta=12h --metrics 0.0.0.0:9567 \
                --cache-large-write --cache-expire 1d --free-space-ratio 0.05 \
                --get-timeout 120s --put-timeout 120s --max-uploads 6 --max-downloads 10 \
                sqlite3://$META_PATH /fs/mnt

          env:
            - name: GOGC
              value: "10"
            - name: GOMEMLIMIT
              value: "350MiB"
            - name: META_PATH
              value: /fs/meta.db
            - name: VOLUME_NAME
              value: mimir-mirage
          envFrom:
            - configMapRef:
                name: litestream-env-juicefs
            - secretRef:
                name: weed-s3-access-key

          ports:
            - name: jfs-metrics
              containerPort: 9567

          volumeMounts:
            - name: tmp
              subPath: fs
              mountPath: /fs
              mountPropagation: Bidirectional
            - name: juicefs-cache
              mountPath: /var/jfsCache

          startupProbe:
            exec:
              command: [mountpoint, -q, /fs/mnt]
            initialDelaySeconds: 10
            failureThreshold: 6

          securityContext:
            runAsUser: 0
            runAsGroup: 0
            runAsNonRoot: false
            privileged: true # required for Bidirectional
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              cpu: 250m
              memory: 128Mi
            limits:
              memory: 768Mi

        # - name: weed-mount
        #   image: docker.io/chrislusf/seaweedfs:4.19
        #   restartPolicy: Always

        #   env:
        #     - name: DATA_CENTER
        #       valueFrom:
        #         fieldRef:
        #           fieldPath: metadata.labels['topology.kubernetes.io/region']
        #     - name: GOGC
        #       value: "10"
        #     - name: GOMEMLIMIT
        #       value: 512MiB

        #   command:
        #     - sh
        #     - -c
        #     - |
        #       set -xeuo pipefail
        #       if mountpoint -q /tmp/fs; then
        #         umount /tmp/fs || umount -f /tmp/fs
        #       fi

        #       exec weed -logtostderr=true mount -dirAutoCreate=true -umask=000 \
        #         -asyncDio -dir=/tmp/fs -cacheDir=/var/cache/seaweedfs/mimirpv -cacheDirWrite=/tmp/write-cache \
        #         -cacheMetaTtlSec=60 -cacheCapacityMB=4096 -cacheSymlink -metadataFlushSeconds=30 \
        #         -filer=weedfs-seaweedfs-filer-client.weed-system:8888 -filer.path=/buckets/monitoring/mimirpv \
        #         -concurrentReaders=16 -concurrentWriters=16 -dataCenter=$DATA_CENTER -collectionQuotaMB=8192 \
        #         -volumeServerAccess=publicUrl -collection=monitoring -replication=000

        #   startupProbe:
        #     exec:
        #       command: [mountpoint, -q, /tmp/fs]
        #     initialDelaySeconds: 5
        #     periodSeconds: 5
        #     failureThreshold: 5

        #   volumeMounts:
        #     - mountPath: /tmp
        #       name: tmp
        #       mountPropagation: Bidirectional
        #     - mountPath: /var/cache/seaweedfs
        #       name: seaweedfs-cache

        #   resources:
        #     requests:
        #       cpu: 150m
        #       memory: 256Mi
        #     limits:
        #       cpu: 1000m
        #       memory: 1Gi # higher limit to avoid getting shot in the head by OOMkilla
        #       # prob mem leak

        #   securityContext:
        #     runAsUser: 0
        #     runAsGroup: 0
        #     runAsNonRoot: false
        #     privileged: true
        #     readOnlyRootFilesystem: true
        #     capabilities:
        #       drop: [ALL]
        #       add: [SYS_ADMIN]

      containers:
        - name: mimir
          image: docker.io/grafana/mimir
          args: [-config.file=/etc/mimir/mimir.yaml]
          env:
            - name: GOGC
              value: "10"
            - name: GOMEMLIMIT
              value: 1200MiB
          envFrom:
            - secretRef:
                name: weed-s3-access-key

          ports:
            - containerPort: 9009
              protocol: TCP
              name: prometheus

          livenessProbe:
            httpGet:
              path: /
              port: prometheus
            timeoutSeconds: 5
            initialDelaySeconds: 15
            failureThreshold: 10

          readinessProbe:
            httpGet:
              path: /ready
              port: prometheus
            timeoutSeconds: 5
            initialDelaySeconds: 10

          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]

          volumeMounts:
            - name: config
              mountPath: /etc/mimir
              readOnly: true
            - name: runtime-config
              mountPath: /etc/mimir/runtime
              readOnly: true
            - name: tmp
              mountPath: /data
              subPath: fs/mnt
              mountPropagation: HostToContainer
            - name: tmp
              mountPath: /tmp
              subPath: mimir-tmp

          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              memory: 1.25Gi
