namespace: monitoring-system

labels:
  - pairs:
      app.kubernetes.io/instance: mirage
      app.kubernetes.io/name: mimir
    includeSelectors: true
    includeTemplates: true
  - pairs:
      app.kubernetes.io/version: 2.17.9
    includeTemplates: true

images:
  - name: docker.io/grafana/mimir
    newTag: 2.17.9

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: mimir-mirage-config
    files:
      - config/mimir.yaml
  - name: mimir-mirage-runtime-config
    options:
      disableNameSuffixHash: true
    files:
      - mimir.yaml=config/mimir.runtime.yaml
