namespace: monitoring-system
configurations:
  - kustomizeconfig.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: Kustomize
  - pairs:
      app.kubernetes.io/instance: mirage
      app.kubernetes.io/name: mimir
    includeSelectors: true
    includeTemplates: true
  - pairs:
      app.kubernetes.io/version: 3.1.0
    includeTemplates: true

images:
  - name: docker.io/grafana/mimir
    newTag: 3.1.5

configMapGenerator:
  - name: mimir-dashboards
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "true"
    files:
      - https://github.com/grafana/mimir/raw/refs/tags/mimir-3.1.0/operations/mimir-mixin-compiled/dashboards/mimir-overview.json

resources:
  - prefixed
  - service.yaml
  - servicemonitor.yaml
