apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mimir-mirage
  namespace: monitoring-system
spec:
  jobLabel: app.kubernetes.io/name
  selector: {}
  endpoints:
    - port: prometheus
