# yaml-language-server: $schema=https://github.com/immich-app/immich-charts/raw/refs/tags/immich-0.13.1/charts/immich/values.schema.json
defaultPodOptions:
  nodeSelector:
    kubernetes.io/hostname: sophons-caeneus
  tolerations:
    - key: caeneus.sophons.cloud
      operator: Exists

  securityContext:
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0
    seccompProfile:
      type: RuntimeDefault

controllers:
  main:
    containers:
      main:
        image:
          tag: v3.1.0
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ALL]

valkey:
  enabled: true

  controllers:
    main:
      containers:
        main:
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534

          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              memory: 64Mi

  persistence:
    data:
      enabled: true
      size: 1Gi
      accessMode: ReadWriteOnce
      type: persistentVolumeClaim
      storageClass: local-path

immich:
  metrics:
    enabled: true

  persistence:
    library:
      existingClaim: immich-media-less-big-boi

server:
  enabled: true

  controllers:
    main:
      strategy: Recreate

      containers:
        main:
          ports:
            - containerPort: 2283
              hostPort: 2283
              name: http
              protocol: TCP

          env:
            CPU_CORES: "4"
            IMMICH_LOG_LEVEL: debug
            IMMICH_TRUSTED_PROXIES: 10.41.0.0/16,::ffff:10.41.0.0/112,::ffff:0a29:0000/112,2001:cafe:41::/56
            IMMICH_ALLOW_SETUP: "false"
            DB_HOSTNAME:
              valueFrom:
                secretKeyRef:
                  name: gimmich-postgres-app
                  key: host
            DB_USERNAME:
              valueFrom:
                secretKeyRef:
                  name: gimmich-postgres-app
                  key: user
            DB_PASSWORD:
              valueFrom:
                secretKeyRef:
                  name: gimmich-postgres-app
                  key: password
            DB_DATABASE_NAME:
              valueFrom:
                secretKeyRef:
                  name: gimmich-postgres-app
                  key: dbname

          resources:
            requests:
              cpu: 250m
              memory: 1Gi
            limits:
              memory: 5Gi

          securityContext:
            allowPrivilegeEscalation: true
            privileged: true

  persistence:
    dev-dri:
      type: hostPath
      hostPath: /dev/dri
      hostPathType: Directory
      advancedMounts:
        main:
          main:
            - path: /dev/dri

    # dev-dri-card0:
    #   type: hostPath
    #   hostPath: /dev/dri/by-path/pci-0000:09:00.0-card
    #   hostPathType: CharDevice
    #   advancedMounts:
    #     main:
    #       main:
    #         - path: /dev/dri/card0

    # dev-dri-renderd128:
    #   type: hostPath
    #   hostPath: /dev/dri/by-path/pci-0000:09:00.0-render
    #   hostPathType: CharDevice
    #   advancedMounts:
    #     main:
    #       main:
    #         - path: /dev/dri/renderD128

    # dev-kfd:
    #   type: hostPath
    #   hostPath: /dev/kfd
    #   hostPathType: CharDevice
    #   advancedMounts:
    #     main:
    #       main:
    #         - path: /dev/kfd

machine-learning:
  enabled: true

  controllers:
    main:
      strategy: Recreate

      containers:
        main:
          image:
            repository: ghcrd.sphns.run/immich-app/immich-machine-learning
            pullPolicy: IfNotPresent

          env:
            MACHINE_LEARNING_REQUEST_THREADS: "4"
            MACHINE_LEARNING_MODEL_INTER_OP_THREADS: "2"
            MACHINE_LEARNING_MODEL_INTRA_OP_THREADS: "3"
            # MACHINE_LEARNING_DEVICE_ID: "1" # 0 is the igpu
            # MACHINE_LEARNING_DEVICE_IDS: "1" # 0 is the igpu
            # HIP_VISIBLE_DEVICES: "1"
            # ROCR_VISIBLE_DEVICES: "1"
            # HSA_USE_SVM: "0"
            # HSA_OVERRIDE_GFX_VERSION: "11.0.0"

          resources:
            requests:
              cpu: 350m
              memory: 512Mi
            limits:
              memory: 4Gi

          securityContext:
            allowPrivilegeEscalation: true
            privileged: true

  persistence:
    cache:
      enabled: true
      size: 10Gi
      type: persistentVolumeClaim
      storageClass: local-path
      accessMode: ReadWriteOnce

    dev-dri:
      type: hostPath
      hostPath: /dev/dri
      hostPathType: Directory
      advancedMounts:
        main:
          main:
            - path: /dev/dri

    # dev-dri-card0:
    #   type: hostPath
    #   hostPath: /dev/dri/by-path/pci-0000:09:00.0-card
    #   hostPathType: CharDevice
    #   advancedMounts:
    #     main:
    #       main:
    #         - path: /dev/dri/card0

    # dev-dri-renderd128:
    #   type: hostPath
    #   hostPath: /dev/dri/by-path/pci-0000:09:00.0-render
    #   hostPathType: CharDevice
    #   advancedMounts:
    #     main:
    #       main:
    #         - path: /dev/dri/renderD128

    dev-kfd:
      type: hostPath
      hostPath: /dev/kfd
      hostPathType: CharDevice
      advancedMounts:
        main:
          main:
            - path: /dev/kfd
