- Gits and tigs:
    - Forgejo:
        - abbr: GT
          href: https://tig.vrtx.sh/vrtx
    - Github:
        - abbr: GH
          href: https://github.com/tehlordvortex
    - Codeberg:
        - abbr: CB
          href: https://codeberg.org/vrtxdotsh
