- kubernetes:
    cluster:
      show: true
      cpu: true
      memory: true
      showLabel: true
      label: "sophons"
    nodes:
      show: false

- search:
    provider: duckduckgo
    target: _blank
    # url: https://www.ecosia.org/search?q=
    # suggestionUrl: https://ac.ecosia.org/autocomplete?type=list&q= # Optional
    # showSearchSuggestions: true # Optional
