apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: headscale
  namespace: headscale
spec:
  endpoints:
    - dnsName: hs.vrtx.sh
      recordType: CNAME
      targets:
        - traefik-sango-star-theta.sophons.cloud
    - dnsName: gghs.vrtx.sh
      recordType: CNAME
      targets:
        - traefik-sango-noproxy.sophons.cloud
      providerSpecific:
        - name: "external-dns.alpha.kubernetes.io/cloudflare-proxied"
          value: "false"
