namespace: headscale
labels:
  - pairs:
      app.kubernetes.io/name: headscale
    includeSelectors: true
    includeTemplates: true
  - pairs:
      app.kubernetes.io/version: 0.28.1
    includeTemplates: true

resources:
  - service.yaml
  - cfdtunnel.yaml
  # These are now managed with the file provider so Traefik
  # retains routing config even if it can't reach the kube api-server
  # - grpcroute.yaml
  # - httproute.yaml
  - statefulset.yaml
  - ../garage/access-keys/infinity-and-beyond
components:
  - ../../common/litestream
  - ../../common/litestream/templ-config

secretGenerator:
  - name: headscale
    env: .env

configMapGenerator:
  - name: headscale
    files:
      - config/headscale.yaml
      - config/headplane.yaml
