# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.34.1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: headscale
  namespace: headscale
type: Opaque
# enc!
stringData:
  noise_private.key: ENC[AES256_GCM,data:Je4sO/KAoS2xPIL70/Bb3fL/SHNcqpEtuBCgki1yx/nzqJiXaveQHdQZzgbdjdxDpQzU7VyxXR6a1bMGmsCn2TuQLPlwIm8V,iv:ZQ/ae+lp6eycgpcNS0UdCYZDQR3P4ZEY0b8tPnb12DM=,tag:mcJ+lP+LtpURoKo8lTionQ==,type:str]
  derp_server_private.key: ENC[AES256_GCM,data:SE7Ud14HkkmAZAi0tHxrVjTwXHUIlbXm/GDCNFQ/1JiGtoGtVUJbXJ1TG7+jcTQAN2AlvMlVmNVG7Lv8j1GGYd0vTgRhY68k,iv:ZP5ukpPkFoTH8JO0ha9vaZbvDwXIGM7I4XNmgkqTOKM=,tag:GfD6at77VIsMIVwghHHilA==,type:str]
  oidc_client.secret: ENC[AES256_GCM,data:SwRkQzb40nUhPaYr+dY8O/z+Fp7sVxd6m/7twtejkMRmqTjamUkO23srnuy+fu25KYB01W4/c3V+/AVaxHyVRg==,iv:/pgtzsSriKL2kb5raAZahs/TC4DdTki4p6KrLH/IfV0=,tag:oCvNoxVhCkT3nokC6Eb/Lw==,type:str]
  cookie.secret: ENC[AES256_GCM,data:qbQO9u1hnJtphEHt2VcUn0bB4FzfMWx3shB0qCHUPg4=,iv:f14N2NtnxukleuBOXyYGHDXpOrwlibdr2hvvjNyqxtc=,tag:30qn2Mtubm5DH3TVibTLbQ==,type:str]
  headscale_api.key: ENC[AES256_GCM,data:HllJNOnOtBKLU1in1nM+QrOCjRrhjzXl0EkvXXUxP1++CrWdrYb7yw==,iv:FpuNnY/zj9u5b8NzuW1AfhiO29IvezTIAieoq4kqWmE=,tag:yd9hKvSgNR+uaisaJiqhGg==,type:str]
  agent_preauth.key: ENC[AES256_GCM,data:HI56xt1cggG4LooJQN0xi9aVJO598RxZxtAeOpmBE6FQMB6fI0cOPAZh40O8RU9Q,iv:nIdxbNfDH6fDCHR582tWG7ulWZn5cVigziqmexcMiTo=,tag:OHVtncexu2ZUZP9tp3ldAA==,type:str]
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyAzZW05
        RElWT1k1WkVmakpLbTVRUEVtVmJOZnlHbEtqRUVNK3pVU1hKRDIwCmNCSW9GRmZr
        eXY4MlZFUmkyTHU0dDNTZmI5M3JJa2kyVUg5akxMcmhoWmcKLS0tIGVHRU5ZcW01
        YmZlS2s3NVJydUFhMEdOelY3SzFtajJqYzIrODUxQVg5RkkKTUvHkgfHcqV+3DyE
        fWxpJvUCZazJEFaQJPmGurk1fQNvDmU3JYJiVBJRKWeXVlE5oKuDFJedtrQKXViM
        qfGBBQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5dDhqTWs2b0VGTE9ORFls
        NGhIQkorVVFuSkEvbkU3UGRZOVFjcUM4UlNrCkN2d2hSQ2pjV29ZbWh1WDJsWEFN
        bzJta1ZIRDMvUXJJVktTN05nVmN4eHcKLS0tIEtUOS8zMUlzY0c0Z3pVdWJxR0s1
        bERXdEpiUlQ4bVdPUGsrQWdUMk5GMjAKPbc1YVaxQTua8EY9lAdjp448vrxGK1w5
        BuGRYkfAm8+womEztJSB5csa7totYpKI04uQapSV/vijUNu8z654aA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-23T20:26:01Z"
  mac: ENC[AES256_GCM,data:QEYlb6IqbM54YzRZoXy7JumUNFXMfE5FvjqHDesdNuHIywtM3J/ZuwXjc+77Yfyk6FbUhXJw+rFsXKYJalSVPT1HcadOwfc14e1PlgFHGQ7K1YaLvEcGZ6/wLLIXaq3bk/giErM5PZvOiIy1eeKfQzmosbcu6EH0tciOvUbA49E=,iv:mxxA7YVBXGaSBJKqaAGShMSxlhi/WlQgu+SIcrGrEio=,tag:5+s08TGEgPC1a57+W0+veQ==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
