# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.34.1/statefulset-apps-v1.json
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: headscale
  namespace: headscale
spec:
  replicas: 1

  selector: {}
  template:
    spec:
      priorityClassName: system-node-critical

      tolerations:
        - key: orunmila.sophons.cloud/ase-orun
          operator: Exists
        - key: node.cilium.io/agent-not-ready
          operator: Exists

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    # only nodes with some kind of always publicly routable ip
                    values:
                      - sophons-theta
                      - sophons-voltzahl
                      - sophons-oduduwa

          preferredDuringSchedulingIgnoredDuringExecution:
            # - preference:
            #     matchExpressions:
            #       - key: node-role.kubernetes.io/control-plane
            #         operator: DoesNotExist
            #   weight: 100
            - preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - sophons-voltzahl
              weight: 100

      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault

      # do not depend on cluster DNS
      dnsConfig:
        nameservers:
          - 1.1.1.1
          - 1.0.0.1
          - 9.9.9.9
      dnsPolicy: None
      hostAliases:
        - ip: 10.43.0.69
          hostnames:
            - auth.sophons.cloud
            - ps3-global.sphns.run
        - ip: 2001:cafe:43::69
          hostnames:
            - auth.sophons.cloud
            - ps3-global.sphns.run

      containers:
        - name: headscale
          image: ghcr.io/juanfont/headscale:v0.28.0
          args: ["serve"]

          env:
            - name: GOMEMLIMIT
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory

          ports:
            - containerPort: 8080
              name: hs-http
            - containerPort: 8081
              name: hs-metrics
            - containerPort: 50051
              name: hs-grpc

          volumeMounts:
            - name: tmp
              mountPath: /var/lib/headscale
              subPath: lib-headscale
            - name: tmp
              mountPath: /var/run/headscale
              subPath: run-headscale
            - name: config
              mountPath: "/etc/headscale/config.yaml"
              subPath: headscale.yaml
              readOnly: true
            - name: secret
              mountPath: "/etc/headscale/noise_private.key"
              subPath: noise_private.key
              readOnly: true
            - name: secret
              mountPath: /etc/headscale/oidc_client.secret
              subPath: oidc_client.secret
              readOnly: true

          readinessProbe:
            exec:
              command: ["headscale", "health"]
            timeoutSeconds: 5
            failureThreshold: 5
            initialDelaySeconds: 15

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 256Mi

          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]

        - name: headplane
          image: ghcr.io/tale/headplane:0.6.3

          ports:
            - containerPort: 3000
              name: hp-http

          env:
            - name: GOMEMLIMIT
              value: 120MiB
            - name: HEADPLANE_LOAD_ENV_OVERRIDES
              value: "true"
            - name: HEADPLANE_SERVER__COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: headscale
                  key: cookie.secret
            - name: HEADPLANE_INTEGRATION__AGENT__PRE_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: headscale
                  key: agent_preauth.key
            - name: HEADPLANE_OIDC__HEADSCALE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: headscale
                  key: headscale_api.key

          volumeMounts:
            - name: tmp
              mountPath: /var/lib/headplane
              subPath: lib-headplane
            - name: tmp
              mountPath: /var/lib/headplane/agent
              subPath: lib-headplane-agent
            - name: config
              mountPath: "/etc/headplane/config.yaml"
              subPath: headplane.yaml
              readOnly: true
            - name: config
              mountPath: "/etc/headscale/config.yaml"
              subPath: headscale.yaml
              readOnly: true
            - name: secret
              mountPath: /etc/headscale/oidc_client.secret
              subPath: oidc_client.secret

          livenessProbe:
            httpGet:
              path: /admin/healthz
              port: hp-http
            timeoutSeconds: 5
            failureThreshold: 5
            initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              path: /admin/healthz
              port: hp-http
            timeoutSeconds: 5
            failureThreshold: 5
            initialDelaySeconds: 15

          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 256Mi

      initContainers:
        - name: litestream
          restartPolicy: Always
          image: docker.io/litestream/litestream
          command: [bash, /etc/litestream/entrypoint.sh]
          envFrom:
            - configMapRef:
                name: litestream-env
            - secretRef:
                name: infinity-and-beyond-access-key
          env:
            - name: GOGC
              value: "25"
            - name: GOMEMLIMIT
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory
            - name: LITESTREAM_ENDPOINT
              value: https://ps3-global.sphns.run
            - name: LITESTREAM_BUCKET
              value: litestream-ad-infinitum
            - name: LITESTREAM_REPLICA_PATH
              value: ng/headscale
            - name: LITESTREAM_CONFIG
              value: |-
                dbs:
                  - path: /var/lib/headscale/hs.db
                    replica:
                      url: "[[replica_url hs.db]]"
                  - path: /var/lib/headplane/hp_persist.db
                    replica:
                      url: "[[replica_url hp_persist.db]]"

          ports:
            - name: ls-metrics
              containerPort: 9090

          startupProbe:
            exec:
              command: [bash, /etc/litestream/restore-probe.sh]
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 30

          volumeMounts:
            - name: tmp
              mountPath: "/var/lib/headscale"
              subPath: lib-headscale
            - name: tmp
              mountPath: "/var/lib/headplane"
              subPath: lib-headplane
            - name: litestream-config
              mountPath: /etc/litestream
              readOnly: true
            - name: tmp
              subPath: litestream
              mountPath: /tmp

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ALL]

          resources:
            requests:
              cpu: 50m
              memory: 48Mi
            limits:
              memory: 100Mi

        - name: update-cf-dns
          image: docker.io/library/alpine:3.22
          command:
            - ash
            - -c
            - |
              set -xeu
              apk add curl

              if [ "$NODE_NAME" = "sophons-oduduwa" ]; then
                alias acurl="curl -4"
              else
                alias acurl="curl"
              fi

              # while :; do
              acurl -fsSL -XPOST -H "authorization: bearer $CLOUDFLARE_API_TOKEN" \
                https://neckhook.sphns.workers.dev/trigger
                # wget -qS -O /dev/null --post-data "" \
                #   --header "authorization: bearer $CLOUDFLARE_API_TOKEN" \
                #   https://neckhook.sphns.workers.dev/trigger
                # sleep 300 & # 5 minutes
                # wait $!
              # done
          env:
            - name: CLOUDFLARE_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: headscale
                  key: neckhook_cf.token
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName

          volumeMounts:
            - name: tmp
              mountPath: "/var/cache/apk"
              subPath: cache-apk

          securityContext:
            runAsNonRoot: false
            runAsGroup: 0
            runAsUser: 0
            capabilities:
              drop: [ALL]

          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              memory: 48Mi

      volumes:
        # - name: tls
        #   secret:
        #     secretName: gateway-tls
        - name: config
          configMap:
            name: headscale
        - name: secret
          secret:
            secretName: headscale
        - name: litestream-config
          configMap:
            name: litestream-config
        - name: tmp
          emptyDir: {}
