# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1/namespace.json
apiVersion: v1
kind: Namespace
metadata:
  name: karakeep
  labels:
    pod-security.kubernetes.io/enforce: privileged
