# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.34.1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: hoarder-access-key
  namespace: karakeep
type: Opaque
stringData:
  # enc!
  OLD_ASSET_STORE_S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:QMXSAZpPCcbfZeTuxYE3nOU7ZmZQY5OcCw==,iv:s5IbJ5B3retIil46sRHFtqE/bXSHBOQPomtLE0T5uwA=,tag:L1p1pjXXqKrqV9As0fi9OQ==,type:str]
  # enc!
  ASSET_STORE_S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:AIq48o0bT7WsWVgAYohleUYvrEtkfC+/q74=,iv:qPNlg8lj5H2u36veIdVVLba4rUtzFD1rdwqj5muqSWk=,tag:+k4Yq6VrfSMqmx1uNiNcbw==,type:str]
  # enc!
  OLD_ASSET_STORE_S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:6fROFnpYWKV6lFvRm2z+wbiFbNiRH/RE6k4put2kZA==,iv:zGyn64JS6x2hqmcO1jh7TMr26UrRH6FalBuCb0hzrNk=,tag:opB2oTOUw/L7HVZzMh1+eA==,type:str]
  # enc!
  ASSET_STORE_S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:uDyq5SXvoZOmZT1Q6mA1cxSvhLtmQf8I0oi/jT28zhiNzC5deCftbNzg5zbBxI2NrMn2PWURO7mG2B0SU7MsOQ==,iv:FOSM+yAZYLnKsaZ07VJaKbHBJ8UidLfEA7FoadMNHyc=,tag:Ju/kBcwWX9Vx0u9lAZ0URQ==,type:str]
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBJUmpy
        di92aW9xWWdEbW1FYkgvTkxBWlIvKzJUTUZPUWl2U0JsaTRjdzFFCjd1V2cwV3JB
        OXRYaERVZmFJR0dUM0hnVGRoNXBta1hHRXRUK2htSU03ZEEKLS0tIHBkRmpMMk0x
        a05EbUgwcWkwRDcySFpRWHFueEZEakoySTU1RlJDQkNrb1UKHNU12OdnsrBRMVHU
        n8mPvCHzqvb3Q9KysJgSyb58WWv4pIMABxus2JsjQ8fa31Zwi2Nxmg7PIFg1QVJq
        lNlHbA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFMEdxUjc5S0p1TVZlZjEr
        MW1TVGZaeWVTRVd3NmpZTzJTQ0NqRHl5V0hRCi9WeHF5aU16LzNkQnY4OHFBaFBU
        Qjd3enhWYy95Qk0yS3dYeWQ2a1RsVU0KLS0tIDI1NldkOHBXT3NUNmJwdEovTmx0
        MWxjK2pMaUJjM0tGNnJMN2p4cUcxVmsKXzovXdMycjRPSSlPnOWfpXaX3MWPt27P
        kHqdS2f1Hznw1ffJNxb3HCBQX/WZ44vjyq9YTa9YHTGoxIKsyP7lqQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-23T02:02:54Z"
  mac: ENC[AES256_GCM,data:xvus8Vehs8yqYFd2GJwhe8P8n7GE89AcUdi4X9OdCthwljsflICQ5K5S0BrVKQqPB8HXjzlWd5XAOaRfZqj7dSGHi4IUD2LS/6GK2Ly7WIe6m1JONmoThGc98XwDqO+qsuV4KpNOHWEeMoYcTaa5VGIUJDLMx00H93MhIiScrFo=,iv:KUlEw0OkHlyvdP87HexBFZoyW3cArJxkO9cJstu3j9g=,tag:DcL0xVtSvZdvrV1P3p85pg==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.34.1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: karakeep-oauth
  namespace: karakeep
type: Opaque
stringData:
  # enc!
  OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:QfhQjHntoOwImQgT7Mwh+AJD7KZeYa1zZKDN3PkbNogqE2rHlSjbq5nGteakVxdMYQXg0zsL3smkhe1Xa67yfA==,iv:mMcZxRDvF5x7Zmb5phO4A1otwgDUmJBv7eral4oAALk=,tag:0s+0MKHRj2DjtlKYshzljg==,type:str]
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBJUmpy
        di92aW9xWWdEbW1FYkgvTkxBWlIvKzJUTUZPUWl2U0JsaTRjdzFFCjd1V2cwV3JB
        OXRYaERVZmFJR0dUM0hnVGRoNXBta1hHRXRUK2htSU03ZEEKLS0tIHBkRmpMMk0x
        a05EbUgwcWkwRDcySFpRWHFueEZEakoySTU1RlJDQkNrb1UKHNU12OdnsrBRMVHU
        n8mPvCHzqvb3Q9KysJgSyb58WWv4pIMABxus2JsjQ8fa31Zwi2Nxmg7PIFg1QVJq
        lNlHbA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFMEdxUjc5S0p1TVZlZjEr
        MW1TVGZaeWVTRVd3NmpZTzJTQ0NqRHl5V0hRCi9WeHF5aU16LzNkQnY4OHFBaFBU
        Qjd3enhWYy95Qk0yS3dYeWQ2a1RsVU0KLS0tIDI1NldkOHBXT3NUNmJwdEovTmx0
        MWxjK2pMaUJjM0tGNnJMN2p4cUcxVmsKXzovXdMycjRPSSlPnOWfpXaX3MWPt27P
        kHqdS2f1Hznw1ffJNxb3HCBQX/WZ44vjyq9YTa9YHTGoxIKsyP7lqQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-23T02:02:54Z"
  mac: ENC[AES256_GCM,data:xvus8Vehs8yqYFd2GJwhe8P8n7GE89AcUdi4X9OdCthwljsflICQ5K5S0BrVKQqPB8HXjzlWd5XAOaRfZqj7dSGHi4IUD2LS/6GK2Ly7WIe6m1JONmoThGc98XwDqO+qsuV4KpNOHWEeMoYcTaa5VGIUJDLMx00H93MhIiScrFo=,iv:KUlEw0OkHlyvdP87HexBFZoyW3cArJxkO9cJstu3j9g=,tag:DcL0xVtSvZdvrV1P3p85pg==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
