#
# IMPORTANT NOTE
#
# This chart inherits from the bjw-s library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/tree/main/charts/library/common
#
applicationProtocol: https
applicationHost: hoarder.sophons.cloud

secrets:
  karakeep:
    enabled: false
  meilesearch:
    enabled: false

ingress:
  karakeep:
    enabled: false

controllers:
  karakeep:
    statefulset:
      volumeClaimTemplates: []
    pod:
      terminationGracePeriodSeconds: 180
      hostUsers: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: topology.kubernetes.io/region
                    operator: In
                    values:
                      - ng
              weight: 100
    containers:
      karakeep:
        image:
          tag: 0.33.1
        # Next.js is a plague :(
        resources:
          requests:
            cpu: 150m
            memory: 300Mi
          limits:
            memory: 1.5Gi

        envFrom:
          - secretRef:
              name: karakeep

        env:
          DISABLE_SIGNUPS: "true"
          DB_WAL_MODE: "true"
          BROWSER_WEB_URL: ws://karakeep-chrome:3000
          ASSET_STORE_S3_ENDPOINT: https://ps3-global.sphns.run
          ASSET_STORE_S3_REGION: global
          ASSET_STORE_S3_BUCKET: karakeep
          ASSET_STORE_S3_FORCE_PATH_STYLE: "true"
          ASSET_STORE_S3_ACCESS_KEY_ID:
            valueFrom:
              secretKeyRef:
                name: hoarder-access-key
                key: AWS_ACCESS_KEY_ID
          ASSET_STORE_S3_SECRET_ACCESS_KEY:
            valueFrom:
              secretKeyRef:
                name: hoarder-access-key
                key: AWS_SECRET_ACCESS_KEY
          OAUTH_WELLKNOWN_URL: https://auth.sophons.cloud/.well-known/openid-configuration
          OAUTH_CLIENT_ID: sphns_q1F-KFdfxuwpzFejpdac311zzc65t0eiT.X1Vu3mE5
          OAUTH_PROVIDER_NAME: Authelia
          OAUTH_ALLOW_DANGEROUS_EMAIL_ACCOUNT_LINKING: "true"
          # 15s
          OAUTH_TIMEOUT: "15000"
          OPENAI_API_KEY: clankerstudio
          # lmstudio on kaos
          OPENAI_BASE_URL: http://100.64.0.26:11433/v1
          OPENAI_PROXY_URL: http://localhost:8080
          OPENAI_REASONING_EFFORT: none
          INFERENCE_TEXT_MODEL: google/gemma-4-12b-qat
          INFERENCE_IMAGE_MODEL: google/gemma-4-12b-qat
          INFERENCE_CONTEXT_LENGTH: "12288"
          INFERENCE_MAX_OUTPUT_TOKENS: "4096"
          EMBEDDING_DIMENSIONS: "768"
          EMBEDDING_TEXT_MODEL: google/embeddinggemma-300m-qat
          INFERENCE_ENABLE_AUTO_TAGGING: "true"
          INFERENCE_ENABLE_AUTO_SUMMARIZATION: "true"
          # 2.5 minutes
          # INFERENCE_JOB_TIMEOUT_SEC: "150"
          # turns out its disabled by default for a reason whoopsie
          # CRAWLER_FULL_PAGE_ARCHIVE: "true"
          # 3 minutes
          CRAWLER_JOB_TIMEOUT_SEC: "300"
          CRAWLER_SCREENSHOT_TIMEOUT_SEC: "30"
          CRAWLER_MONOLITH_TIMEOUT_SEC: "180"
          HTML_CONTENT_SIZE_INLINE_THRESHOLD_BYTES: "1024"

          EVENT_LOGS_ENABLED: "true"

        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ALL]

    initContainers:
      0-tailscale:
        image:
          repository: ghcr.io/tailscale/tailscale
          tag: latest # required, replaced
        restartPolicy: Always
        envFrom:
          - configMapRef:
              name: tailscale-config
          - secretRef:
              name: tailscale-auth
        env:
          - name: GOGC
            value: "10"
          - name: GOMEMLIMIT
            valueFrom:
              resourceFieldRef:
                resource: limits.memory
          - name: TS_EXTRA_ARGS
            value: $(TS_BASE_ARGS)
          - name: TS_TAILSCALED_EXTRA_ARGS
            value: $(TSD_BASE_ARGS)
          - name: TS_HOSTNAME
            value: karakeep
          - name: TS_OUTBOUND_HTTP_PROXY_LISTEN
            value: localhost:8080
        ports:
          - name: ts-metrics
            containerPort: 9002

        resources:
          requests:
            cpu: 25m
            memory: 48Mi
          limits:
            memory: 100Mi
            devic.es/tun: 1

        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ALL]

        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthz
                port: ts-metrics

          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthz
                port: ts-metrics

      1-litestream:
        restartPolicy: Always
        image:
          repository: docker.io/litestream/litestream
          tag: latest # required, replaced
        command: [bash, /etc/litestream/entrypoint.sh]
        envFrom:
          - configMapRef:
              name: litestream-env
          - secretRef:
              name: infinity-and-beyond-access-key
        env:
          - name: GOGC
            value: "10"
          - name: GOMEMLIMIT
            valueFrom:
              resourceFieldRef:
                resource: limits.memory
          - name: LITESTREAM_ENDPOINT
            value: https://ps3-global.sphns.run
          - name: LITESTREAM_BUCKET
            value: litestream-ad-infinitum
          - name: LITESTREAM_REPLICA_PATH
            value: ng/karakeep
          - name: LITESTREAM_SNAPSHOT_INTERVAL
            value: 24h
          - name: LITESTREAM_CONFIG
            value: |-
              shutdown-sync-timeout: 150s
              levels:
                - interval: 15m  # L1
                - interval: 1.5h # L2
                - interval: 6h   # L3

              dbs:
                - path: /data/db.db
                  replica:
                    url: "[[replica_url db.db]]"
                - path: /data/queue.db
                  replica:
                    url: "[[replica_url queue.db]]"

        ports:
          - name: ls-metrics
            containerPort: 9090

        probes:
          startup:
            enabled: true
            custom: true
            spec:
              exec:
                command: [bash, /etc/litestream/restore-probe.sh]
              initialDelaySeconds: 10
              periodSeconds: 5
              failureThreshold: 30

        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ALL]

        resources:
          requests:
            cpu: 50m
            memory: 48Mi
          limits:
            memory: 100Mi
  chrome:
    pod:
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 10.43.14.40 # necronomicon-0
          - 10.43.203.219 # necronomicon-1
      hostUsers: false
      nodeSelector:
        kubernetes.io/hostname: sophons-caeneus
      tolerations:
        - key: caeneus.sophons.cloud
          operator: Exists
      securityContext:
        seccompProfile:
          type: RuntimeDefault

    containers:
      chrome:
        image:
          repository: ghcrd.sphns.run/browserless/chromium
          tag: v2.46.0
        args: null
        env:
          - name: ENABLE_DEBUGGER
            value: "false"
          - name: TIMEOUT
            # 5 minutes
            value: "300000"
          - name: CONCURRENT
            value: "4"
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /active
                port: 3000
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /active
                port: 3000
        securityContext:
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          capabilities:
            add: null
            drop: [ALL]
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: null
            memory: 1.5Gi
service:
  chrome:
    ports:
      http: null
      ws:
        port: 3000
persistence:
  tmp:
    type: emptyDir
    advancedMounts:
      karakeep:
        karakeep:
          - path: /data
            subPath: data
          - path: /tmp
            subPath: karakeep
          - path: /run
            subPath: run
        0-tailscale:
          - path: /tmp
            subPath: tailscale
        1-litestream:
          - path: /data
            subPath: data
          - path: /tmp
            subPath: litestream
      chrome:
        chrome:
          - path: /tmp
            subPath: chrome
  litestream-config:
    type: configMap
    name: litestream-config
    advancedMounts:
      karakeep:
        1-litestream:
          - path: /etc/litestream

meilisearch:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In
                values:
                  - ng
          weight: 100
  auth:
    existingMasterKeySecret: karakeep
  resources:
    requests:
      cpu: 50m
      memory: 32Mi
    limits:
      cpu: 250m
      memory: 256Mi
  securityContext:
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault
  persistence:
    enabled: false
