apiVersion: cloudflared-operator.vrtx.sh/v1alpha1
kind: CfdTunnel
metadata:
  name: weedfs-admin
  namespace: weed-system
spec:
  dns:
    externalDNS:
      kind:
        generated:
          endpoints:
            - dnsName: weed.sophons.cloud

  accountId: 93814820f122031e8f5004eb893430f0
  apiToken:
    secretRef:
      name: cf-dns-api-token
      namespace: default
    key: api-token

  serviceRef:
    name: weedfs-seaweedfs-admin
  ingress:
    - service: https://traefik.traefik.svc.cluster.local
  originRequestConfig: |
    matchSNItoHost: true
    http2Origin: true

  containerOverrides:
    name: cloudflared
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        memory: 32Mi
