# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.35.2/deployment-apps-v1.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weedfs-filer-config-reloader
  namespace: weed-system
  labels:
    app.kubernetes.io/weedname: seaweedfs
    app.kubernetes.io/instance: weedfs
    app.kubernetes.io/component: filer-config-reloader
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/weedname: seaweedfs
      app.kubernetes.io/instance: weedfs
      app.kubernetes.io/component: filer-config-reloader

  template:
    metadata:
      labels:
        app.kubernetes.io/weedname: seaweedfs
        app.kubernetes.io/instance: weedfs
        app.kubernetes.io/component: filer-config-reloader

    spec:
      tolerations:
        - operator: Exists

      volumes:
        - name: filer-config
          configMap:
            name: weed-filer

      containers:
        - name: config-reloader
          image: docker.io/library/alpine:edge
          imagePullPolicy: Always

          env:
            - name: FILER
              value: http://weedfs-seaweedfs-filer-client:8888
          command:
            - sh
            - -c
            - |
              set -euo pipefail
              filename=/etc/seaweedfs/filer.conf

              apk add --no-cache inotify-tools curl

              put_config() {
                curl -fsS -X PUT --upload-file $filename "$FILER$filename"
              }

              watch_config() {
                inotifywait -q -m -e close_write $filename |
                  while read -r filename event; do put_config; done
              }

              put_config
              watch_config &
              pid=$!
              trap "kill $pid" SIGTERM
              wait

          securityContext:
            privileged: false
            runAsNonRoot: false
            runAsUser: 0
            runAsGroup: 0
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]

          volumeMounts:
            - name: filer-config
              mountPath: /etc/seaweedfs
              readOnly: true

          resources:
            requests:
              memory: 16Mi
            limits:
              memory: 64Mi
