apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: weedfs-admin
  namespace: weed-system
spec:
  endpoints:
    - dnsName: weed.sophons.cloud
      recordType: CNAME
      targets:
        - cfd-traefik.sophons.cloud
