namespace: weed-system
resources:
  - service.yaml
  - httproute.yaml
  - middleware.yaml
  - dnsendpoint.yaml
  - storageclass.yaml
  - ciliumlocalredirectpolicy.yaml

secretGenerator:
  - name: weed-s3
    options:
      disableNameSuffixHash: true
    files:
      - seaweedfs_s3_config=config/s3.sops.json
