global:
  monitoring:
    enabled: true
  enableReplication: true
  replicationPlacement: "200"

admin:
  enabled: true
  port: 23646
  grpcPort: 33646 # For worker connections

  containerSecurityContext:
    enabled: true
    privileged: false
    allowPrivilegeEscalation: false
    capabilities:
      drop: [ALL]

  podSecurityContext:
    enabled: true
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    seccompProfile:
      type: RuntimeDefault

master:
  nodeSelector: |
    weed.sophons.cloud/cluster: global
    weed.sophons.cloud/master: "true"

  volumeSizeLimitMB: 1024
  data:
    type: emptyDir
  logs:
    type: null

  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      memory: 200Mi

  containerSecurityContext:
    enabled: true
    privileged: false
    allowPrivilegeEscalation: false
    capabilities:
      drop: [ALL]

  podSecurityContext:
    enabled: true
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    seccompProfile:
      type: RuntimeDefault

  extraEnvironmentVars:
    GOMEMLIMIT:
      resourceFieldRef:
        resource: limits.memory

volume:
  enabled: false
  replicas: 0
  nodeSelector: |
    weed.sophons.cloud/cluster: global
    weed.sophons.cloud/volume: "true"
  tolerations: |
    - key: orunmila.sophons.cloud/ase-orun
      operator: Exists

  readMode: redirect
  dataDirs:
    - name: data-uno
      type: persistentVolumeClaim
      storageClass: local-path
      size: 32Gi
      maxVolumes: 24

  idx:
    type: persistentVolumeClaim
    storageClass: local-path
    size: 4Gi

  logs: null

  resources:
    requests:
      cpu: 150m
      memory: 64Mi
    limits:
      memory: 400Mi

  extraEnvironmentVars:
    GOMEMLIMIT:
      resourceFieldRef:
        resource: limits.memory

  containerSecurityContext:
    enabled: true
    privileged: false
    allowPrivilegeEscalation: false
    capabilities:
      drop: [ALL]

  podSecurityContext:
    enabled: true
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: Always
    seccompProfile:
      type: RuntimeDefault

volumes:
  nl-east-1:
    dataCenter: nl-east-1
    replicas: 1
    nodeSelector: |
      weed.sophons.cloud/cluster: global
      weed.sophons.cloud/volume: "true"
      topology.kubernetes.io/zone: nl-east-1
  de-east-1:
    dataCenter: de-east-1
    replicas: 1
    nodeSelector: |
      weed.sophons.cloud/cluster: global
      weed.sophons.cloud/volume: "true"
      topology.kubernetes.io/zone: de-east-1
  ng-west-1:
    dataCenter: ng-west-1
    replicas: 1
    nodeSelector: |
      weed.sophons.cloud/cluster: global
      weed.sophons.cloud/volume: "true"
      topology.kubernetes.io/zone: ng-west-1

filer:
  loggingOverrideLevel: 0 # noisy filer generates data for logs/metrics, which generates logs in filer, which...
  tolerations: |
    - key: orunmila.sophons.cloud/ase-orun
      operator: Exists
    # - key: caeneus.sophons.cloud
    #   operator: Exists
  replicas: 3
  # encryptVolumeData: true
  # redirectOnRead: true

  data:
    type: persistentVolumeClaim
    storageClass: local-path
    size: 8Gi

  logs:
    type: null

  s3:
    enabled: true
    enableAuth: true
    existingConfigSecret: weed-s3

  resources:
    requests:
      cpu: 150m
      memory: 100Mi
    limits:
      memory: 172Mi

  extraEnvironmentVars:
    GOMEMLIMIT:
      resourceFieldRef:
        resource: limits.memory

  topologySpreadConstraints: |
    - labelSelector:
        matchLabels:
          app.kubernetes.io/name: seaweedfs
          app.kubernetes.io/instance: weedfs
          app.kubernetes.io/component: filer
      maxSkew: 1
      minDomains: 3
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
    - labelSelector:
        matchLabels:
          app.kubernetes.io/name: seaweedfs
          app.kubernetes.io/instance: weedfs
          app.kubernetes.io/component: filer
      maxSkew: 1
      minDomains: 3
      topologyKey: topology.kubernetes.io/region
      whenUnsatisfiable: DoNotSchedule

  containerSecurityContext:
    enabled: true
    privileged: false
    allowPrivilegeEscalation: false
    capabilities:
      drop: [ALL]

  podSecurityContext:
    enabled: true
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: Always
    seccompProfile:
      type: RuntimeDefault

worker:
  enabled: true
  nodeSelector: |
    weed.sophons.cloud/cluster: global

  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 300Mi

  extraEnvironmentVars:
    GOMEMLIMIT:
      resourceFieldRef:
        resource: limits.memory

  containerSecurityContext:
    enabled: true
    privileged: false
    allowPrivilegeEscalation: false
    capabilities:
      drop: [ALL]

  podSecurityContext:
    enabled: true
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    seccompProfile:
      type: RuntimeDefault
