# docs.siderolabs.com/talos/v1.11/platform-specific-installations/local-platforms/docker#docker
# docker run --rm -it
#   --name tutorial
#   --hostname talos-cp
#   --read-only
#   --privileged
#   --security-opt seccomp=unconfined
#   --mount type=tmpfs,destination=/run
#   --mount type=tmpfs,destination=/system
#   --mount type=tmpfs,destination=/tmp
#   --mount type=volume,destination=/system/state
#   --mount type=volume,destination=/var
#   --mount type=volume,destination=/etc/cni
#   --mount type=volume,destination=/etc/kubernetes
#   --mount type=volume,destination=/usr/libexec/kubernetes
#   --mount type=volume,destination=/opt
#   -e PLATFORM=container
#   ghcr.io/siderolabs/talos:v1.11.5

services:
  talos:
    restart: always
    stop_grace_period: 15m
    image: ghcr.io/siderolabs/talos:${TALOS_VERSION}
    privileged: true
    sysctls:
      net.ipv4.ip_forward: 1
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv6.conf.all.forwarding: 1
    security_opt:
      - seccomp=unconfined
    cpus: 8
    mem_limit: 12G
    read_only: true
    tmpfs:
      - /run
      - /system
      - /tmp
    volumes:
      - system-state:/system/state
      - var:/var
      - etc-cni:/etc/cni
      - etc-kubernetes:/etc/kubernetes
      - usr-libexec-kubernetes:/usr/libexec/kubernetes
      - opt:/opt
      - /run/media/vrtx/big-boi/backups/backups/garage:/var/lib/garage/backup/big-boi
      - /run/media/vrtx/less-big-boi/backups/garage:/var/lib/garage/backup/less-big-boi
      - /run/media/vrtx/big-boi/time-machine:/mnt/big-boi/time-machine
      - /run/media/vrtx/big-boi/everything-else:/mnt/big-boi/everything-else
      - /run/media/vrtx/less-big-boi/media:/mnt/less-big-boi/media
    environment:
      - PLATFORM=container
      - TALOSSKU=8CPU-8192RAM
    devices:
      - /dev/net/tun
      - /dev/dri
      - /dev/kfd
    networks:
      # default: {}
      lab:
        ipv4_address: 10.42.42.5
        # ipv6_address: ${V6_ADDR}
    # network_mode: service:tailscale

  # tailscale:
  #   hostname: sophons-caeneus
  #   image: tailscale/tailscale:v1.88.2
  #   restart: always
  #   sysctls:
  #     net.ipv4.ip_forward: 1
  #     net.ipv6.conf.all.disable_ipv6: 0
  #     net.ipv6.conf.all.forwarding: 1
  #   cap_add:
  #     - net_admin
  #     - sys_module
  #   environment:
  #     - TS_HOSTNAME=sophons-caeneus
  #     - TS_AUTHKEY=$TS_AUTHKEY
  #     - TS_EXTRA_ARGS=--login-server=https://hs.vrtx.sh --ssh --accept-routes=true --snat-subnet-routes=false
  #     - TS_AUTH_ONCE=true
  #     - TS_STATE_DIR=/var/lib/tailscale
  #     - TS_USERSPACE=false
  #     - TS_ROUTES=${TS_ROUTES}
  #   volumes:
  #     - tailscale-state:/var/lib/tailscale
  #   devices:
  #     - /dev/net/tun
  #   networks:
  #     lab:
  #       ipv4_address: 10.42.42.5

volumes:
  tailscale-state:
  system-state:
  var:
  etc-cni:
  etc-kubernetes:
  usr-libexec-kubernetes:
  opt:

networks:
  # default:
  #   enable_ipv6: true
  #   ipam:
  #     config:
  #       - subnet: 2001:dada:2::/64

  lab:
    driver: ipvlan
    driver_opts:
      parent: lab1
    # enable_ipv6: false
    ipam:
      config:
        - subnet: 10.42.0.0/16
        # - subnet: ${V6_SUBNET}
        #   gateway: ${V6_GATEWAY}
