apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: generic-device-plugin
  namespace: kube-system
  labels:
    app.kubernetes.io/name: generic-device-plugin
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: generic-device-plugin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: generic-device-plugin
    spec:
      priorityClassName: system-node-critical
      tolerations:
        - operator: "Exists"
          effect: "NoExecute"
        - operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: generic-device-plugin
          image: ghcr.io/squat/generic-device-plugin
          args:
            - --log-level
            - debug
            - --domain
            - devic.es
            - --device
            - |
              name: tun
              groups:
                - paths:
                    - path: /dev/net/tun
                  count: 16
            - --device
            - |
              name: fuse
              groups:
                - count: 16
                  paths:
                    - path: /dev/fuse
          resources:
            requests:
              cpu: 25m
              memory: 8Mi
            limits:
              memory: 32Mi
          ports:
            - containerPort: 8080
              name: http
          securityContext:
            privileged: true
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
            - name: dev
              mountPath: /dev
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: dev
          hostPath:
            path: /dev
