apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: homepage
  namespace: homepage
spec:
  endpoints:
    - dnsName: home.sophons.cloud
      recordType: CNAME
      targets:
        - traefik-star-theta.sophons.cloud
