namespace: homepage
resources:
  - service.yaml
  - httproute.yaml
  - deployment.yaml
  - clusterrole.yaml
  - serviceaccount.yaml
  - traefikservice.yaml

secretGenerator:
  - name: homepage
    env: .env

configMapGenerator:
  - name: homepage
    files:
      - config/widgets.yaml
      - config/bookmarks.yaml
      - config/kubernetes.yaml
    literals:
      - custom.js=""
      - custom.css=""
      - docker.yaml=""
      - proxmox.yaml=""
      - services.yaml=""
      - settings.yaml=""
