namespace: ntfy
resources:
  - service.yaml
  - cfdtunnel.yaml
  - httproute.yaml
  - statefulset.yaml
  - ../garage/access-keys/infinity-and-beyond

components:
  - ../../common/litestream
  - ../../common/litestream/templ-config

secretGenerator:
  - name: ntfy
    env: .env

  - name: ntfy-config
    files:
      - server.yaml=config/server.sops.yaml
