namespace: argocd-system
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v3.2.3/manifests/core-install.yaml
  - secret.sops.yaml

patches:
  - patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: argocd-system
    target:
      group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      version: v1
  - patch: |-
      - op: add
        path: /spec/template/spec/tolerations
        value:
          - key: caeneus.sophons.cloud
            operator: Exists
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: GOMEMLIMIT
          valueFrom:
            resourceFieldRef:
              resource: limits.memory
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 512Mi
    target:
      kind: StatefulSet
      name: argocd-application-controller
