# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.34.1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: argocd-server-tls
  namespace: argocd-system
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: default/gateway-tls
# https://argo-cd.readthedocs.io/en/stable/operator-manual/tls/#tls-certificates-used-by-argocd-server
# whee! this doesn't have to be tls so isn't subject to: https://github.com/emberstack/kubernetes-reflector/issues/298
type: Opaque
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBVbm44
        MU9xTTFBaWM1c0pnWjI2dXVDejdmTUtKOXNOZVAxeGVkZVZnN2tvCmdUSUVqVkdm
        MTNnUVl1aThaL29lRXFwNGV2NjJObGxaWkM2NmNvM295cDQKLS0tIFBSMVViRENL
        R0ozNWRuQ3pKa3NXU3FNSmtFWjR4NEtXVVVBWTQwOTZVZ1EKgu5iVulUrx+mYmyB
        15MeuBR/BRxIQUZ6ZLhxacHVHNAXRZiITumykj9afdPopd53IA+wYReZmAy3L7S1
        zvMxDA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQN2d0eDczdzV6UFE3SlJF
        SzJUM0lBclUxd3ZybXFnMEJ3YWRvWE9vdENrCkpyN3BnUitMT2IyYkdzSnV3a09G
        Vk5Oa3k5WVNEUUw0OUZyRFNlRlRTOTQKLS0tIDQzVzNXbkJxNGs5ZVJoRlYwYW1E
        VENZTU5xRFZESlJiMG1vSTRJQm8vMmcK/awDLjMboqZb1n0b2HJWoPesRcwwANJU
        P46QXiVPjrV1EAcCTN65T6W22jDzFszyM4BuJqQVsow066BJeOQbMg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-23T01:17:49Z"
  mac: ENC[AES256_GCM,data:jAgmrR3QhoDzga86uawmOO/pbOI6Q2acnCzWzvLIZsLJpjrNREZ5tAHIgYjxjSB+yMhbDqNBaAgIse85f1GWlje9lYoc23dojS+VPoVPJfo9U/hryBdE2jDlAoOc2kHzTXiJjpVobuHDvpUDCjSMJVMOoFK3WYJXHztm0jIp9hQ=,iv:WDzldzhiB3mZAs75IPnouDUvz5o2+c7Qg44p/R5kCRI=,tag:pFJyDFM6Ji+75BemHrlWNw==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
