namespace: traefik
resources:
  - daemonset.yaml
  # - syslogngflow.yaml
  - secrets.sops.yaml
  - dnsendpoint.sops.yaml
  - ciliumlocalredirectpolicy.yaml

secretGenerator:
  - name: cloudflared
    files:
      - 163f32fb-e910-4a18-9ef0-9c5bfe635f33.json=config/163f32fb-e910-4a18-9ef0-9c5bfe635f33.sops.json
      - config/config.yaml
