cluster:
  network:
    cni:
      name: none
machine:
  install:
    disk: /dev/mmcblk0
    extraKernelArgs:
      - cma=512M
  kubelet:
    extraMounts:
      - destination: /var/lib/longhorn
        type: bind
        source: /var/lib/longhorn
        options:
          - bind
          - rshared
          - rw
  nodeLabels:
    topology.kubernetes.io/region: ng
    topology.kubernetes.io/zone: ng-east-1
  network:
    hostname: sophons-alpha
    interfaces:
      - interface: lo
        addresses:
          - fdf6:9420:fade:67::3/128
      - interface: end0
        dhcp: false
        vlans:
          - vlanId: 42
            dhcp: true
            dhcpOptions:
              ipv4: false
              ipv6: true
            addresses:
              - 10.42.69.4/16
            routes:
              - network: 0.0.0.0/0
                gateway: 10.42.0.1
              - network: ::/0
                gateway: fe80::1
                #   metric: 200
          - vlanId: 69
            dhcp: false
            addresses:
              - 10.69.0.4/16
            routes:
              - network: 0.0.0.0/0
                gateway: 10.69.0.1
              - network: ::/0
                gateway: fe80::1
                # metric: 200
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyB5c0M4
        YlJYeU50ejJyblFIa2VBNmZuQ25zM2d0YU9sTnpwTjVEN05NZmgwClE2Y2ZGTitE
        RThZM3JCMGs1VWZkcjlscExvSzcrMGR3RnhpbjZPaWpUL3cKLS0tIDkydkM1dk1N
        Rm8rYSt4ajNqaUdSU0pwaTh4MUV0dUg1YzBPM0g2Y2xwcncKvo63UOEpNM19eolo
        dOizXlufqmkJHNoEB5qUmk2ZWQJ3wZcWLxR6EK3zwfm5tIKDPIB6fbdykgjh3zE3
        jgOwMg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFU1BNbm1HRlZKbEM0dFNz
        WC9hTEpPN3hrWnJKcVhYbUhUeExsU1ZLM3hRClNmZVQvZkVxdE5EYmN1c0dLcVBo
        dGVid0ZURUlUSFl3cEJYelZBNCtlUk0KLS0tIDJPZHR3OTRwQ1hvcENUVWlUcGhZ
        WTkrdGdYVU9XUlZtNFJlcVNoeUg0YlkKyWxX4hheQBsffub8FnPo9Yg51M1e0jhw
        eZIK3rp7GcTto1I0endePKdEHLZUcS8nRQdEp8mbNGAYc2V17SdG0Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-24T13:31:16Z"
  mac: ENC[AES256_GCM,data:3J9EqtBG9WXD1nOQ3G/KKJntpR3aZGt97nfZsyME+ppZivajMezpnLhLZis5pjYQv6eMOmgpxICmCq8GnYX7FljMaCfEgyJ1EFFb+t6sy3zf+u0wZxugGFLTv0u8ZbSrgnKnPSak/A3U5czuywP6ZRyGe+K1ukG5/xiBHW0fnuw=,iv:NDJUPbD9Rq5rlXbgHeUJaW5s2zCXAojoyd+PQxpkUz4=,tag:0VpZZ32bhLkvvnzQm6cXZQ==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  diskSelector:
    match: '''/dev/disk/by-id/usb-SanDisk_Extreme_55AE_323530333653343035343633-0:0'' in disk.symlinks'
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyB5c0M4
        YlJYeU50ejJyblFIa2VBNmZuQ25zM2d0YU9sTnpwTjVEN05NZmgwClE2Y2ZGTitE
        RThZM3JCMGs1VWZkcjlscExvSzcrMGR3RnhpbjZPaWpUL3cKLS0tIDkydkM1dk1N
        Rm8rYSt4ajNqaUdSU0pwaTh4MUV0dUg1YzBPM0g2Y2xwcncKvo63UOEpNM19eolo
        dOizXlufqmkJHNoEB5qUmk2ZWQJ3wZcWLxR6EK3zwfm5tIKDPIB6fbdykgjh3zE3
        jgOwMg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFU1BNbm1HRlZKbEM0dFNz
        WC9hTEpPN3hrWnJKcVhYbUhUeExsU1ZLM3hRClNmZVQvZkVxdE5EYmN1c0dLcVBo
        dGVid0ZURUlUSFl3cEJYelZBNCtlUk0KLS0tIDJPZHR3OTRwQ1hvcENUVWlUcGhZ
        WTkrdGdYVU9XUlZtNFJlcVNoeUg0YlkKyWxX4hheQBsffub8FnPo9Yg51M1e0jhw
        eZIK3rp7GcTto1I0endePKdEHLZUcS8nRQdEp8mbNGAYc2V17SdG0Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-24T13:31:16Z"
  mac: ENC[AES256_GCM,data:3J9EqtBG9WXD1nOQ3G/KKJntpR3aZGt97nfZsyME+ppZivajMezpnLhLZis5pjYQv6eMOmgpxICmCq8GnYX7FljMaCfEgyJ1EFFb+t6sy3zf+u0wZxugGFLTv0u8ZbSrgnKnPSak/A3U5czuywP6ZRyGe+K1ukG5/xiBHW0fnuw=,iv:NDJUPbD9Rq5rlXbgHeUJaW5s2zCXAojoyd+PQxpkUz4=,tag:0VpZZ32bhLkvvnzQm6cXZQ==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: ExtensionServiceConfig
name: tailscale
environment:
  - TS_ROUTES=10.41.3.0/24,2001:cafe:41:3::/64,fdf6:9420:fade:67::3/128
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyB5c0M4
        YlJYeU50ejJyblFIa2VBNmZuQ25zM2d0YU9sTnpwTjVEN05NZmgwClE2Y2ZGTitE
        RThZM3JCMGs1VWZkcjlscExvSzcrMGR3RnhpbjZPaWpUL3cKLS0tIDkydkM1dk1N
        Rm8rYSt4ajNqaUdSU0pwaTh4MUV0dUg1YzBPM0g2Y2xwcncKvo63UOEpNM19eolo
        dOizXlufqmkJHNoEB5qUmk2ZWQJ3wZcWLxR6EK3zwfm5tIKDPIB6fbdykgjh3zE3
        jgOwMg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFU1BNbm1HRlZKbEM0dFNz
        WC9hTEpPN3hrWnJKcVhYbUhUeExsU1ZLM3hRClNmZVQvZkVxdE5EYmN1c0dLcVBo
        dGVid0ZURUlUSFl3cEJYelZBNCtlUk0KLS0tIDJPZHR3OTRwQ1hvcENUVWlUcGhZ
        WTkrdGdYVU9XUlZtNFJlcVNoeUg0YlkKyWxX4hheQBsffub8FnPo9Yg51M1e0jhw
        eZIK3rp7GcTto1I0endePKdEHLZUcS8nRQdEp8mbNGAYc2V17SdG0Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-24T13:31:16Z"
  mac: ENC[AES256_GCM,data:3J9EqtBG9WXD1nOQ3G/KKJntpR3aZGt97nfZsyME+ppZivajMezpnLhLZis5pjYQv6eMOmgpxICmCq8GnYX7FljMaCfEgyJ1EFFb+t6sy3zf+u0wZxugGFLTv0u8ZbSrgnKnPSak/A3U5czuywP6ZRyGe+K1ukG5/xiBHW0fnuw=,iv:NDJUPbD9Rq5rlXbgHeUJaW5s2zCXAojoyd+PQxpkUz4=,tag:0VpZZ32bhLkvvnzQm6cXZQ==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
