apiVersion: v1alpha1
kind: HostnameConfig
auto: "off"
hostname: sophons-alpha
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBlU1dv
        cVlLdDdGY25aR1k3YkQ2NXN0SGZvVGdYT1JzMzNacGxRZ3ZCOEZBClQ1MmtBcHdF
        UnJJNVprM2UzQnRaU1U3SzdsTHRBMTkrcnRGN29aOWUrR1kKLS0tIG5BRHFKV3pT
        ODd6Nk8yVWdYYUZQUis4RWdGTHZtdVRnVmpoU2xSNWc1VEkKxtKxhqSweFVHVWbI
        Hd9K6PHvwrSeejuo9C7Q4ipaUh9djEVbJCw0a9rxIBvLoKMUhTuctBCGQA6zLX92
        scLfLQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBad3RVUWFHbG1NRzRPSnhY
        MlNWb1hUQkxIZGhJTkNyVUkwR1ByVHo2UUJNCm9nOGZRYnBiYnFjTU05bVZWRjFy
        SkJKbGZBQ3RGNUo0NElpb0drZ2hzR00KLS0tICtBWERZU0JObFNsczhOZmFNd0h1
        M0NEYWZYNHhPUWM5aEpXOEp4Q1YvdlEK08Rlj+d9TXRQWoeNCZSENa1CA8KMjTt8
        w/vlIX6bChhFo3wjD6v89FQvrywExdZTP1vN14KMXONkvJyJWBjUoQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-10T13:17:52Z"
  mac: ENC[AES256_GCM,data:jDivAY4S8jIQ8RzZgRx7LpVJDEjD6PIEK2ihkXL1QK8AhBjJ91jbNRM8qh/4nVRZ27WHnvw+QyWX06FiLHlbwXrvB3ThcCoNWB/lqkfDJaCOT1QWAjx/KEHveT9C8ngqPh0gNNtRlvL3xWoKAIxqMozHdegVEU2foCGvsnnNppw=,iv:RY9Hlye54PJxWF+bss+nqsRnoagu7N+dso1sjtLqyv0=,tag:KVPli4YoYpgpZOwiW9ZrhA==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
cluster:
  network:
    cni:
      name: none
machine:
  install:
    disk: /dev/mmcblk0
  kubelet:
    extraMounts:
      - destination: /var/lib/longhorn
        type: bind
        source: /var/lib/longhorn
        options:
          - bind
          - rshared
          - rw
  nodeLabels:
    topology.kubernetes.io/region: ng
    topology.kubernetes.io/zone: ng-east-1
  network:
    interfaces:
      - interface: end0
        dhcp: false
        vlans:
          - vlanId: 42
            dhcp: true
            dhcpOptions:
              ipv4: false
              ipv6: true
            addresses:
              - 10.42.69.4/16
            routes:
              - network: 0.0.0.0/0
                gateway: 10.42.0.1
              - network: ::/0
                gateway: fe80::1
                #   metric: 200
          - vlanId: 69
            dhcp: false
            addresses:
              - 10.69.0.4/16
            routes:
              - network: 0.0.0.0/0
                gateway: 10.69.0.1
              - network: ::/0
                gateway: fe80::1
                # metric: 200
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBlU1dv
        cVlLdDdGY25aR1k3YkQ2NXN0SGZvVGdYT1JzMzNacGxRZ3ZCOEZBClQ1MmtBcHdF
        UnJJNVprM2UzQnRaU1U3SzdsTHRBMTkrcnRGN29aOWUrR1kKLS0tIG5BRHFKV3pT
        ODd6Nk8yVWdYYUZQUis4RWdGTHZtdVRnVmpoU2xSNWc1VEkKxtKxhqSweFVHVWbI
        Hd9K6PHvwrSeejuo9C7Q4ipaUh9djEVbJCw0a9rxIBvLoKMUhTuctBCGQA6zLX92
        scLfLQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBad3RVUWFHbG1NRzRPSnhY
        MlNWb1hUQkxIZGhJTkNyVUkwR1ByVHo2UUJNCm9nOGZRYnBiYnFjTU05bVZWRjFy
        SkJKbGZBQ3RGNUo0NElpb0drZ2hzR00KLS0tICtBWERZU0JObFNsczhOZmFNd0h1
        M0NEYWZYNHhPUWM5aEpXOEp4Q1YvdlEK08Rlj+d9TXRQWoeNCZSENa1CA8KMjTt8
        w/vlIX6bChhFo3wjD6v89FQvrywExdZTP1vN14KMXONkvJyJWBjUoQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-10T13:17:52Z"
  mac: ENC[AES256_GCM,data:jDivAY4S8jIQ8RzZgRx7LpVJDEjD6PIEK2ihkXL1QK8AhBjJ91jbNRM8qh/4nVRZ27WHnvw+QyWX06FiLHlbwXrvB3ThcCoNWB/lqkfDJaCOT1QWAjx/KEHveT9C8ngqPh0gNNtRlvL3xWoKAIxqMozHdegVEU2foCGvsnnNppw=,iv:RY9Hlye54PJxWF+bss+nqsRnoagu7N+dso1sjtLqyv0=,tag:KVPli4YoYpgpZOwiW9ZrhA==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
# https://tailscale.com/docs/reference/best-practices/performance#linux-optimizations-for-subnet-routers-and-exit-nodes
apiVersion: v1alpha1
kind: EthernetConfig
name: end0
features:
  rx-gro-list: "off"
  rx-udp-gro-forwarding: "on"
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBlU1dv
        cVlLdDdGY25aR1k3YkQ2NXN0SGZvVGdYT1JzMzNacGxRZ3ZCOEZBClQ1MmtBcHdF
        UnJJNVprM2UzQnRaU1U3SzdsTHRBMTkrcnRGN29aOWUrR1kKLS0tIG5BRHFKV3pT
        ODd6Nk8yVWdYYUZQUis4RWdGTHZtdVRnVmpoU2xSNWc1VEkKxtKxhqSweFVHVWbI
        Hd9K6PHvwrSeejuo9C7Q4ipaUh9djEVbJCw0a9rxIBvLoKMUhTuctBCGQA6zLX92
        scLfLQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBad3RVUWFHbG1NRzRPSnhY
        MlNWb1hUQkxIZGhJTkNyVUkwR1ByVHo2UUJNCm9nOGZRYnBiYnFjTU05bVZWRjFy
        SkJKbGZBQ3RGNUo0NElpb0drZ2hzR00KLS0tICtBWERZU0JObFNsczhOZmFNd0h1
        M0NEYWZYNHhPUWM5aEpXOEp4Q1YvdlEK08Rlj+d9TXRQWoeNCZSENa1CA8KMjTt8
        w/vlIX6bChhFo3wjD6v89FQvrywExdZTP1vN14KMXONkvJyJWBjUoQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-10T13:17:52Z"
  mac: ENC[AES256_GCM,data:jDivAY4S8jIQ8RzZgRx7LpVJDEjD6PIEK2ihkXL1QK8AhBjJ91jbNRM8qh/4nVRZ27WHnvw+QyWX06FiLHlbwXrvB3ThcCoNWB/lqkfDJaCOT1QWAjx/KEHveT9C8ngqPh0gNNtRlvL3xWoKAIxqMozHdegVEU2foCGvsnnNppw=,iv:RY9Hlye54PJxWF+bss+nqsRnoagu7N+dso1sjtLqyv0=,tag:KVPli4YoYpgpZOwiW9ZrhA==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  diskSelector:
    match: '''/dev/disk/by-id/usb-SanDisk_Extreme_55AE_323530333653343035343633-0:0'' in disk.symlinks'
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBlU1dv
        cVlLdDdGY25aR1k3YkQ2NXN0SGZvVGdYT1JzMzNacGxRZ3ZCOEZBClQ1MmtBcHdF
        UnJJNVprM2UzQnRaU1U3SzdsTHRBMTkrcnRGN29aOWUrR1kKLS0tIG5BRHFKV3pT
        ODd6Nk8yVWdYYUZQUis4RWdGTHZtdVRnVmpoU2xSNWc1VEkKxtKxhqSweFVHVWbI
        Hd9K6PHvwrSeejuo9C7Q4ipaUh9djEVbJCw0a9rxIBvLoKMUhTuctBCGQA6zLX92
        scLfLQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBad3RVUWFHbG1NRzRPSnhY
        MlNWb1hUQkxIZGhJTkNyVUkwR1ByVHo2UUJNCm9nOGZRYnBiYnFjTU05bVZWRjFy
        SkJKbGZBQ3RGNUo0NElpb0drZ2hzR00KLS0tICtBWERZU0JObFNsczhOZmFNd0h1
        M0NEYWZYNHhPUWM5aEpXOEp4Q1YvdlEK08Rlj+d9TXRQWoeNCZSENa1CA8KMjTt8
        w/vlIX6bChhFo3wjD6v89FQvrywExdZTP1vN14KMXONkvJyJWBjUoQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-10T13:17:52Z"
  mac: ENC[AES256_GCM,data:jDivAY4S8jIQ8RzZgRx7LpVJDEjD6PIEK2ihkXL1QK8AhBjJ91jbNRM8qh/4nVRZ27WHnvw+QyWX06FiLHlbwXrvB3ThcCoNWB/lqkfDJaCOT1QWAjx/KEHveT9C8ngqPh0gNNtRlvL3xWoKAIxqMozHdegVEU2foCGvsnnNppw=,iv:RY9Hlye54PJxWF+bss+nqsRnoagu7N+dso1sjtLqyv0=,tag:KVPli4YoYpgpZOwiW9ZrhA==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: WireguardConfig
name: wg.kluster
# publicKey: C/tFptmbSV+HBQYxzsTKUFW4LsPVcQyCNEfr8esvQ3w=
# enc!
privateKey: ENC[AES256_GCM,data:1qRUQcZH54mwy/PvWW+M75T1z2dKsQMCEtEc9+7shhHZ/MihbQhFSEzoo3E=,iv:MdDJdXwOIrXUhd1/Q5DuAJw3ZIBwn076mUBVhr2+ldE=,tag:V1S99Ue2Yd4AZFZz3ZJlGQ==,type:str]
listenPort: 51869
peers:
  # voltzahl
  - publicKey: hVSo5per13c8V9b5wUTAOGp0/W32rkKfSVZSctlqujU=
    allowedIPs:
      - 10.41.6.0/24
      - 2001:cafe:41:6::/64
      - 10.67.0.100/32
      - fdf6:9420:fade:67::5/128
      - fdf6:9420:fade:67::100/128
    # enc!
    endpoint: ENC[AES256_GCM,data:0aQ4MzeHqBd5InlM1Ie20WY=,iv:nSTne/WsRkPpIIpPz1D1h6yWs9XiA5eos3G8iSCiIfk=,tag:vB1gcZTrF2H4ftwnSa8+vg==,type:str]
    persistentKeepaliveInterval: 5s
  # theta
  - publicKey: bg+Z4libGo+HGAC9UrWbooWkOI4+eZ5OAqw+8rPn9AA=
    allowedIPs:
      - 10.41.2.0/24
      - 2001:cafe:41:2::/64
      - 10.67.0.101/32
      - fdf6:9420:fade:67::4/128
      - fdf6:9420:fade:67::101/128
    # enc!
    endpoint: ENC[AES256_GCM,data:Gb2hG5pTxq8S8p0uPFCsf9B3TQ==,iv:b+wIEKSxUywO26TDU0VEfKMBZ+MsG8NCordSgfCr38c=,tag:b0Gxnvi8e+6BQA95zHQogg==,type:str]
    persistentKeepaliveInterval: 5s
  # beta
  - publicKey: mmTxsL60iWtsBx6+aMkxx2Of7g/exHTU9pXrinc1wlQ=
    allowedIPs:
      - 10.41.1.0/24
      - 2001:cafe:41:1::/64
      - 10.67.0.102/32
      - fdf6:9420:fade:67::2/128
      - fdf6:9420:fade:67::102/128
    endpoint: 10.69.0.3:51869
  # oduduwa
  - publicKey: gobYpIEfo5paRPdkJ+Jnqcm9TyD+J2I4+Ry5AU0UhAQ=
    allowedIPs:
      - 10.41.4.0/24
      - 2001:cafe:41:4::/64
      - 10.67.0.104/32
      - fdf6:9420:fade:67::104/128
    # enc!
    endpoint: ENC[AES256_GCM,data:LK7/u7hod81iVhApLpZPXLduew0=,iv:dcgI5gqDl2Jrm6Ly4g/AmKRvip4mF1HtvX9ygSDrJ2U=,tag:LKG88qkyCkuO0fUgJMhFUQ==,type:str]
    persistentKeepaliveInterval: 5s
  # caeneus
  - publicKey: l43bJSBEBDAc9vn+v9z2Zt/vsJRimWwyOwvHfHJrWkQ=
    allowedIPs:
      - 10.41.5.0/24
      - 2001:cafe:41:5::/64
      - 10.67.0.105/32
      - fdf6:9420:fade:67::105/128
    endpoint: 10.42.42.5:51869
    persistentKeepaliveInterval: 5s
  # prime
  - publicKey: 2jXr8tfBYrc3tBSvDweM2mJGAsPp6Sd/T2wCBss2fGU=
    allowedIPs:
      - 10.41.0.0/24
      - 2001:cafe:41::/64
      - 10.67.0.106/32
      - fdf6:9420:fade:67::106/128
    endpoint: 10.42.42.2:51869
    persistentKeepaliveInterval: 5s
up: true
addresses:
  - address: 10.67.0.103/32
  - address: fdf6:9420:fade:67::103/128
routes:
  # voltzahl
  - destination: 10.41.6.0/24
  - destination: 2001:cafe:41:6::/64
  - destination: 10.67.0.100/32
  - destination: fdf6:9420:fade:67::5/128
  - destination: fdf6:9420:fade:67::100/128
  # theta
  - destination: 10.41.2.0/24
  - destination: 2001:cafe:41:2::/64
  - destination: 10.67.0.101/32
  - destination: fdf6:9420:fade:67::4/128
  - destination: fdf6:9420:fade:67::101/128
  # beta
  - destination: 10.41.1.0/24
  - destination: 2001:cafe:41:1::/64
  - destination: 10.67.0.102/32
  - destination: fdf6:9420:fade:67::2/128
  - destination: fdf6:9420:fade:67::102/128
  # oduduwa
  - destination: 10.41.4.0/24
  - destination: 2001:cafe:41:4::/64
  - destination: 10.67.0.104/32
  - destination: fdf6:9420:fade:67::104/128
  # caeneus
  - destination: 10.41.5.0/24
  - destination: 2001:cafe:41:5::/64
  - destination: 10.67.0.105/32
  - destination: fdf6:9420:fade:67::105/128
  # prime
  - destination: 10.41.0.0/24
  - destination: 2001:cafe:41::/64
  - destination: 10.67.0.106/32
  - destination: fdf6:9420:fade:67::106/128
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBlU1dv
        cVlLdDdGY25aR1k3YkQ2NXN0SGZvVGdYT1JzMzNacGxRZ3ZCOEZBClQ1MmtBcHdF
        UnJJNVprM2UzQnRaU1U3SzdsTHRBMTkrcnRGN29aOWUrR1kKLS0tIG5BRHFKV3pT
        ODd6Nk8yVWdYYUZQUis4RWdGTHZtdVRnVmpoU2xSNWc1VEkKxtKxhqSweFVHVWbI
        Hd9K6PHvwrSeejuo9C7Q4ipaUh9djEVbJCw0a9rxIBvLoKMUhTuctBCGQA6zLX92
        scLfLQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBad3RVUWFHbG1NRzRPSnhY
        MlNWb1hUQkxIZGhJTkNyVUkwR1ByVHo2UUJNCm9nOGZRYnBiYnFjTU05bVZWRjFy
        SkJKbGZBQ3RGNUo0NElpb0drZ2hzR00KLS0tICtBWERZU0JObFNsczhOZmFNd0h1
        M0NEYWZYNHhPUWM5aEpXOEp4Q1YvdlEK08Rlj+d9TXRQWoeNCZSENa1CA8KMjTt8
        w/vlIX6bChhFo3wjD6v89FQvrywExdZTP1vN14KMXONkvJyJWBjUoQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-10T13:17:52Z"
  mac: ENC[AES256_GCM,data:jDivAY4S8jIQ8RzZgRx7LpVJDEjD6PIEK2ihkXL1QK8AhBjJ91jbNRM8qh/4nVRZ27WHnvw+QyWX06FiLHlbwXrvB3ThcCoNWB/lqkfDJaCOT1QWAjx/KEHveT9C8ngqPh0gNNtRlvL3xWoKAIxqMozHdegVEU2foCGvsnnNppw=,iv:RY9Hlye54PJxWF+bss+nqsRnoagu7N+dso1sjtLqyv0=,tag:KVPli4YoYpgpZOwiW9ZrhA==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
