apiVersion: v1alpha1
kind: HostnameConfig
auto: "off"
hostname: sophons-beta
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBHSDdG
        N0RSTTlHdlMyb2lHSnRPQlJsK0JGVHdtUUV1d2ViTFJJakZXL2hZClROZXZ2V1Q1
        RHBiQmEvS2hOc0VTTGQ3Qlo2dGtmekJPUnRUdTdVYk1FMm8KLS0tIEV3dmRjMlJS
        N05PZnA5U204RCttQkl6Vjl5Mm9kaTlEL1FER0lPUUQxdDgKqYIC7zIbaQYcYnqI
        5qYwi5kWYxfH0U6ROPew6vW45nAQkie8VjRpaNBOZCtq/oxzUVYQ5IFTWsK7aG9s
        8YlnuA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZjVHK0tOZ3pyNHRDMWdL
        eWY3b0lLaktHc0ZDT0Z6Q3FjMWRnZ3k5UVRVClE0VlFrWlcxWWprSjBIQ3ZvN291
        dktxdUY4azJrR28yNzZNTDdyODVqQjAKLS0tIHJPVUViTjVMZkpQLzR5aG8vNnVn
        clZTeGt0NzBUYmJ0dnozbGx3TnlXT28K5uiBlHC2LizLwlQV/9qiMF1g4WHY626j
        8qIfZCWJyJBuU8gu3SOgHxTqnK1W1i9If/bsQMU2C2tz4m6o+tgF3A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T09:18:08Z"
  mac: ENC[AES256_GCM,data:/p1zYeVpK3DKkxmE5DSgkr7+4VHI0irwhiZcdKvs7Lm1ovQVBnLBLNKMMnPUR1AJNlmVSIP5u+q8AwfvrLPlTDPBN/FUoVwvZhFycWorJn0srXe7SK2c2UtCQglwHAuXZf4Se4XwJagihEf6jRBjvalTyqyFxF37RdW8jaUPJjg=,iv:WjuPvasqStuKyo89nApjN4PwA1xkrBiikC+4rFbeGFI=,tag:XDplRN8YcBoZa868rKsxqg==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
cluster:
  network:
    cni:
      name: none
machine:
  install:
    disk: /dev/mmcblk0
    extraKernelArgs:
      - cma=512M
  kubelet:
    extraMounts:
      - destination: /var/lib/longhorn
        type: bind
        source: /var/lib/longhorn
        options:
          - bind
          - rshared
          - rw
  nodeLabels:
    topology.kubernetes.io/region: ng
    topology.kubernetes.io/zone: ng-east-1
  network:
    interfaces:
      - interface: end0
        dhcp: false
        vlans:
          - vlanId: 42
            dhcp: true
            dhcpOptions:
              ipv4: false
              ipv6: true
            addresses:
              - 10.42.69.3/16
            routes:
              - network: 0.0.0.0/0
                gateway: 10.42.0.1
              - network: ::/0
                gateway: fe80::1
                #   metric: 200
          - vlanId: 69
            dhcp: false
            addresses:
              - 10.69.0.3/16
            routes:
              - network: 0.0.0.0/0
                gateway: 10.69.0.1
              - network: ::/0
                gateway: fe80::1
                # metric: 200
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBHSDdG
        N0RSTTlHdlMyb2lHSnRPQlJsK0JGVHdtUUV1d2ViTFJJakZXL2hZClROZXZ2V1Q1
        RHBiQmEvS2hOc0VTTGQ3Qlo2dGtmekJPUnRUdTdVYk1FMm8KLS0tIEV3dmRjMlJS
        N05PZnA5U204RCttQkl6Vjl5Mm9kaTlEL1FER0lPUUQxdDgKqYIC7zIbaQYcYnqI
        5qYwi5kWYxfH0U6ROPew6vW45nAQkie8VjRpaNBOZCtq/oxzUVYQ5IFTWsK7aG9s
        8YlnuA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZjVHK0tOZ3pyNHRDMWdL
        eWY3b0lLaktHc0ZDT0Z6Q3FjMWRnZ3k5UVRVClE0VlFrWlcxWWprSjBIQ3ZvN291
        dktxdUY4azJrR28yNzZNTDdyODVqQjAKLS0tIHJPVUViTjVMZkpQLzR5aG8vNnVn
        clZTeGt0NzBUYmJ0dnozbGx3TnlXT28K5uiBlHC2LizLwlQV/9qiMF1g4WHY626j
        8qIfZCWJyJBuU8gu3SOgHxTqnK1W1i9If/bsQMU2C2tz4m6o+tgF3A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T09:18:08Z"
  mac: ENC[AES256_GCM,data:/p1zYeVpK3DKkxmE5DSgkr7+4VHI0irwhiZcdKvs7Lm1ovQVBnLBLNKMMnPUR1AJNlmVSIP5u+q8AwfvrLPlTDPBN/FUoVwvZhFycWorJn0srXe7SK2c2UtCQglwHAuXZf4Se4XwJagihEf6jRBjvalTyqyFxF37RdW8jaUPJjg=,iv:WjuPvasqStuKyo89nApjN4PwA1xkrBiikC+4rFbeGFI=,tag:XDplRN8YcBoZa868rKsxqg==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
# https://tailscale.com/docs/reference/best-practices/performance#linux-optimizations-for-subnet-routers-and-exit-nodes
apiVersion: v1alpha1
kind: EthernetConfig
name: end0
features:
  rx-gro-list: "off"
  rx-udp-gro-forwarding: "on"
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBHSDdG
        N0RSTTlHdlMyb2lHSnRPQlJsK0JGVHdtUUV1d2ViTFJJakZXL2hZClROZXZ2V1Q1
        RHBiQmEvS2hOc0VTTGQ3Qlo2dGtmekJPUnRUdTdVYk1FMm8KLS0tIEV3dmRjMlJS
        N05PZnA5U204RCttQkl6Vjl5Mm9kaTlEL1FER0lPUUQxdDgKqYIC7zIbaQYcYnqI
        5qYwi5kWYxfH0U6ROPew6vW45nAQkie8VjRpaNBOZCtq/oxzUVYQ5IFTWsK7aG9s
        8YlnuA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZjVHK0tOZ3pyNHRDMWdL
        eWY3b0lLaktHc0ZDT0Z6Q3FjMWRnZ3k5UVRVClE0VlFrWlcxWWprSjBIQ3ZvN291
        dktxdUY4azJrR28yNzZNTDdyODVqQjAKLS0tIHJPVUViTjVMZkpQLzR5aG8vNnVn
        clZTeGt0NzBUYmJ0dnozbGx3TnlXT28K5uiBlHC2LizLwlQV/9qiMF1g4WHY626j
        8qIfZCWJyJBuU8gu3SOgHxTqnK1W1i9If/bsQMU2C2tz4m6o+tgF3A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T09:18:08Z"
  mac: ENC[AES256_GCM,data:/p1zYeVpK3DKkxmE5DSgkr7+4VHI0irwhiZcdKvs7Lm1ovQVBnLBLNKMMnPUR1AJNlmVSIP5u+q8AwfvrLPlTDPBN/FUoVwvZhFycWorJn0srXe7SK2c2UtCQglwHAuXZf4Se4XwJagihEf6jRBjvalTyqyFxF37RdW8jaUPJjg=,iv:WjuPvasqStuKyo89nApjN4PwA1xkrBiikC+4rFbeGFI=,tag:XDplRN8YcBoZa868rKsxqg==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  diskSelector:
    match: '''/dev/disk/by-id/ata-SSD_512GB_202312010062'' in disk.symlinks'
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBHSDdG
        N0RSTTlHdlMyb2lHSnRPQlJsK0JGVHdtUUV1d2ViTFJJakZXL2hZClROZXZ2V1Q1
        RHBiQmEvS2hOc0VTTGQ3Qlo2dGtmekJPUnRUdTdVYk1FMm8KLS0tIEV3dmRjMlJS
        N05PZnA5U204RCttQkl6Vjl5Mm9kaTlEL1FER0lPUUQxdDgKqYIC7zIbaQYcYnqI
        5qYwi5kWYxfH0U6ROPew6vW45nAQkie8VjRpaNBOZCtq/oxzUVYQ5IFTWsK7aG9s
        8YlnuA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZjVHK0tOZ3pyNHRDMWdL
        eWY3b0lLaktHc0ZDT0Z6Q3FjMWRnZ3k5UVRVClE0VlFrWlcxWWprSjBIQ3ZvN291
        dktxdUY4azJrR28yNzZNTDdyODVqQjAKLS0tIHJPVUViTjVMZkpQLzR5aG8vNnVn
        clZTeGt0NzBUYmJ0dnozbGx3TnlXT28K5uiBlHC2LizLwlQV/9qiMF1g4WHY626j
        8qIfZCWJyJBuU8gu3SOgHxTqnK1W1i9If/bsQMU2C2tz4m6o+tgF3A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T09:18:08Z"
  mac: ENC[AES256_GCM,data:/p1zYeVpK3DKkxmE5DSgkr7+4VHI0irwhiZcdKvs7Lm1ovQVBnLBLNKMMnPUR1AJNlmVSIP5u+q8AwfvrLPlTDPBN/FUoVwvZhFycWorJn0srXe7SK2c2UtCQglwHAuXZf4Se4XwJagihEf6jRBjvalTyqyFxF37RdW8jaUPJjg=,iv:WjuPvasqStuKyo89nApjN4PwA1xkrBiikC+4rFbeGFI=,tag:XDplRN8YcBoZa868rKsxqg==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: WireguardConfig
name: wg.kluster
# publicKey: mmTxsL60iWtsBx6+aMkxx2Of7g/exHTU9pXrinc1wlQ=
# enc!
privateKey: ENC[AES256_GCM,data:MIZRfnVsl9Tm4rpRjNdNkMeXa4aMvHbXFL1plkfnv8xkrol5io3vZZ0WRRQ=,iv:2lvJC3FHprcHrlcwpxZ9Kmm3K/7iBuFAMELzIRMnYhA=,tag:quH4e8hdrNGmFdyO792bUw==,type:str]
listenPort: 51869
up: true
peers:
  # voltzahl
  - publicKey: hVSo5per13c8V9b5wUTAOGp0/W32rkKfSVZSctlqujU=
    allowedIPs:
      - 10.41.6.0/24
      - 2001:cafe:41:6::/64
      - 10.67.0.100/32
      - fdf6:9420:fade:67::5/128
      - fdf6:9420:fade:67::100/128
    # enc!
    endpoint: ENC[AES256_GCM,data:gA46PwNRWpTuadZ/YSg7fLc=,iv:+MHEv8AdXJz2nsiZNplD7QwvP9yAvsJZP+NwY8RxMrU=,tag:YJniPqoOTeIvswYylfY4+Q==,type:str]
    persistentKeepaliveInterval: 5s
  # theta
  - publicKey: bg+Z4libGo+HGAC9UrWbooWkOI4+eZ5OAqw+8rPn9AA=
    allowedIPs:
      - 10.41.2.0/24
      - 2001:cafe:41:2::/64
      - 10.67.0.101/32
      - fdf6:9420:fade:67::4/128
      - fdf6:9420:fade:67::101/128
    # enc!
    endpoint: ENC[AES256_GCM,data:q2CW4pyRGRH3e0LTAuO5Hhuxuw==,iv:PTw7aSNxRxnUU03T2Lg5Q5ftrrsaqY7p1YYxv16Vi/8=,tag:q7LAKal08RwaQVBzPsr/bg==,type:str]
    persistentKeepaliveInterval: 5s
  # alpha
  - publicKey: C/tFptmbSV+HBQYxzsTKUFW4LsPVcQyCNEfr8esvQ3w=
    allowedIPs:
      - 10.41.3.0/24
      - 2001:cafe:41:3::/64
      - 10.67.0.103/32
      - fdf6:9420:fade:67::103/128
    endpoint: 10.69.0.4:51869
  # oduduwa
  - publicKey: gobYpIEfo5paRPdkJ+Jnqcm9TyD+J2I4+Ry5AU0UhAQ=
    allowedIPs:
      - 10.41.4.0/24
      - 2001:cafe:41:4::/64
      - 10.67.0.104/32
      - fdf6:9420:fade:67::104/128
    # enc!
    endpoint: ENC[AES256_GCM,data:ao6OirfUNxoB5nODiJIj+XEfkZQ=,iv:PhHASXh6L/6EYxtLpl+OLJwmpZsAZjwmbhZZbr927+k=,tag:TCJo2RNa+saSoWXZ4pvNXw==,type:str]
    persistentKeepaliveInterval: 5s
  # caeneus
  - publicKey: l43bJSBEBDAc9vn+v9z2Zt/vsJRimWwyOwvHfHJrWkQ=
    allowedIPs:
      - 10.41.5.0/24
      - 2001:cafe:41:5::/64
      - 10.67.0.105/32
      - fdf6:9420:fade:67::105/128
    endpoint: 10.42.42.5:51869
    persistentKeepaliveInterval: 5s
  # prime
  - publicKey: 2jXr8tfBYrc3tBSvDweM2mJGAsPp6Sd/T2wCBss2fGU=
    allowedIPs:
      - 10.41.0.0/24
      - 2001:cafe:41::/64
      - 10.67.0.106/32
      - fdf6:9420:fade:67::106/128
    endpoint: 10.42.42.2:51869
    persistentKeepaliveInterval: 5s
addresses:
  - address: 10.67.0.102/32
  - address: fdf6:9420:fade:67::2/128
  - address: fdf6:9420:fade:67::102/128
routes:
  # voltzahl
  - destination: 10.41.6.0/24
  - destination: 2001:cafe:41:6::/64
  - destination: 10.67.0.100/32
  - destination: fdf6:9420:fade:67::5/128
  - destination: fdf6:9420:fade:67::100/128
  # theta
  - destination: 10.41.2.0/24
  - destination: 2001:cafe:41:2::/64
  - destination: 10.67.0.101/32
  - destination: fdf6:9420:fade:67::4/128
  - destination: fdf6:9420:fade:67::101/128
  # alpha
  - destination: 10.41.3.0/24
  - destination: 2001:cafe:41:3::/64
  - destination: 10.67.0.103/32
  - destination: fdf6:9420:fade:67::103/128
  # oduduwa
  - destination: 10.41.4.0/24
  - destination: 2001:cafe:41:4::/64
  - destination: 10.67.0.104/32
  - destination: fdf6:9420:fade:67::104/128
  # caeneus
  - destination: 10.41.5.0/24
  - destination: 2001:cafe:41:5::/64
  - destination: 10.67.0.105/32
  - destination: fdf6:9420:fade:67::105/128
  # prime
  - destination: 10.41.0.0/24
  - destination: 2001:cafe:41::/64
  - destination: 10.67.0.106/32
  - destination: fdf6:9420:fade:67::106/128
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBHSDdG
        N0RSTTlHdlMyb2lHSnRPQlJsK0JGVHdtUUV1d2ViTFJJakZXL2hZClROZXZ2V1Q1
        RHBiQmEvS2hOc0VTTGQ3Qlo2dGtmekJPUnRUdTdVYk1FMm8KLS0tIEV3dmRjMlJS
        N05PZnA5U204RCttQkl6Vjl5Mm9kaTlEL1FER0lPUUQxdDgKqYIC7zIbaQYcYnqI
        5qYwi5kWYxfH0U6ROPew6vW45nAQkie8VjRpaNBOZCtq/oxzUVYQ5IFTWsK7aG9s
        8YlnuA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZjVHK0tOZ3pyNHRDMWdL
        eWY3b0lLaktHc0ZDT0Z6Q3FjMWRnZ3k5UVRVClE0VlFrWlcxWWprSjBIQ3ZvN291
        dktxdUY4azJrR28yNzZNTDdyODVqQjAKLS0tIHJPVUViTjVMZkpQLzR5aG8vNnVn
        clZTeGt0NzBUYmJ0dnozbGx3TnlXT28K5uiBlHC2LizLwlQV/9qiMF1g4WHY626j
        8qIfZCWJyJBuU8gu3SOgHxTqnK1W1i9If/bsQMU2C2tz4m6o+tgF3A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T09:18:08Z"
  mac: ENC[AES256_GCM,data:/p1zYeVpK3DKkxmE5DSgkr7+4VHI0irwhiZcdKvs7Lm1ovQVBnLBLNKMMnPUR1AJNlmVSIP5u+q8AwfvrLPlTDPBN/FUoVwvZhFycWorJn0srXe7SK2c2UtCQglwHAuXZf4Se4XwJagihEf6jRBjvalTyqyFxF37RdW8jaUPJjg=,iv:WjuPvasqStuKyo89nApjN4PwA1xkrBiikC+4rFbeGFI=,tag:XDplRN8YcBoZa868rKsxqg==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
