apiVersion: v1alpha1
kind: HostnameConfig
auto: "off"
hostname: sophons-beta
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBTdFQz
        Y0lWZkZ4VlhscVZ4NzA1SVAwMzl2L2RtOEh2QTQwZE5jYTdBN3gwClNtcUpWdE9a
        UEcxUlFoQ2owSERQQnphV2ZpVnFLWVpLb0VnWGlTR200VzQKLS0tIEhUaFUvQUc1
        OFZaRWdUMDcwakxRN0c3QlZIRjhqdXAwNlRWUzMrS2trdFUKNkIpFpnKqAPHnaZU
        wPqoqaYB67bN/0PeUuJXmg4w0NhlrQ1Xvwdpk6GXJwC7ghGDJffQAiGf9bw2FoOO
        Kst04Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDR2pyZE1ka0VrMFNGblhG
        TGh5QnFJMGk0bTBuREl0ZlU3cGN1OGliMHowClI3eUZpWnVZZTAySEJCTW4rMExU
        S21NSTlYZUN3ZUI2SmlsRm15S2ptTzgKLS0tIDJrZTZDSnZ1V0R2eWI2NEFUK0tn
        SmM4OHdLOGgxVCtaTTd6clBKZ3NyOTQKEd7F3FqhNQk3rpRG8ObEDY468feZs8Hf
        pnHePMRONAulKnzyJIoRvz4LN3yh3dgFJuTchyAk/v+mvsqTCRUS9w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-31T18:34:50Z"
  mac: ENC[AES256_GCM,data:44zAXenR88O7yn9yhJ2OkrGP3gchqFICTzDG4F38rqwvJwHELjhNTETQ0KbA1pY7zXJiXEIM085JbAE+9mH8Kr5Z58qiJgGM1d4sSsnKzImuPbFqf6IX/sME718BOOSvLpeZQ17IdgZlhhEhBVRi3WvP4Y3gSAiOnKYJSyNua10=,iv:sf6VvgftWY92bvVz9X7RmGjhZ8NRZEvIvulfsWENGmw=,tag:HHgnaIjaEvCHvgA2U6tSQA==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
cluster:
  network:
    cni:
      name: none
machine:
  install:
    disk: /dev/mmcblk0
  kubelet:
    extraMounts:
      - destination: /var/lib/longhorn
        type: bind
        source: /var/lib/longhorn
        options:
          - bind
          - rshared
          - rw
  nodeLabels:
    topology.kubernetes.io/region: ng
    topology.kubernetes.io/zone: ng-east-1
  network:
    interfaces:
      - interface: end0
        dhcp: false
        vlans:
          - vlanId: 42
            dhcp: true
            dhcpOptions:
              ipv4: false
              ipv6: true
            addresses:
              - 10.42.69.3/16
            routes:
              - network: 0.0.0.0/0
                gateway: 10.42.0.1
              - network: ::/0
                gateway: fe80::1
                #   metric: 200
          - vlanId: 69
            dhcp: false
            addresses:
              - 10.69.0.3/16
            routes:
              - network: 0.0.0.0/0
                gateway: 10.69.0.1
              - network: ::/0
                gateway: fe80::1
                # metric: 200
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBTdFQz
        Y0lWZkZ4VlhscVZ4NzA1SVAwMzl2L2RtOEh2QTQwZE5jYTdBN3gwClNtcUpWdE9a
        UEcxUlFoQ2owSERQQnphV2ZpVnFLWVpLb0VnWGlTR200VzQKLS0tIEhUaFUvQUc1
        OFZaRWdUMDcwakxRN0c3QlZIRjhqdXAwNlRWUzMrS2trdFUKNkIpFpnKqAPHnaZU
        wPqoqaYB67bN/0PeUuJXmg4w0NhlrQ1Xvwdpk6GXJwC7ghGDJffQAiGf9bw2FoOO
        Kst04Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDR2pyZE1ka0VrMFNGblhG
        TGh5QnFJMGk0bTBuREl0ZlU3cGN1OGliMHowClI3eUZpWnVZZTAySEJCTW4rMExU
        S21NSTlYZUN3ZUI2SmlsRm15S2ptTzgKLS0tIDJrZTZDSnZ1V0R2eWI2NEFUK0tn
        SmM4OHdLOGgxVCtaTTd6clBKZ3NyOTQKEd7F3FqhNQk3rpRG8ObEDY468feZs8Hf
        pnHePMRONAulKnzyJIoRvz4LN3yh3dgFJuTchyAk/v+mvsqTCRUS9w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-31T18:34:50Z"
  mac: ENC[AES256_GCM,data:44zAXenR88O7yn9yhJ2OkrGP3gchqFICTzDG4F38rqwvJwHELjhNTETQ0KbA1pY7zXJiXEIM085JbAE+9mH8Kr5Z58qiJgGM1d4sSsnKzImuPbFqf6IX/sME718BOOSvLpeZQ17IdgZlhhEhBVRi3WvP4Y3gSAiOnKYJSyNua10=,iv:sf6VvgftWY92bvVz9X7RmGjhZ8NRZEvIvulfsWENGmw=,tag:HHgnaIjaEvCHvgA2U6tSQA==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
# https://tailscale.com/docs/reference/best-practices/performance#linux-optimizations-for-subnet-routers-and-exit-nodes
apiVersion: v1alpha1
kind: EthernetConfig
name: end0
features:
  rx-gro-list: "off"
  rx-udp-gro-forwarding: "on"
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBTdFQz
        Y0lWZkZ4VlhscVZ4NzA1SVAwMzl2L2RtOEh2QTQwZE5jYTdBN3gwClNtcUpWdE9a
        UEcxUlFoQ2owSERQQnphV2ZpVnFLWVpLb0VnWGlTR200VzQKLS0tIEhUaFUvQUc1
        OFZaRWdUMDcwakxRN0c3QlZIRjhqdXAwNlRWUzMrS2trdFUKNkIpFpnKqAPHnaZU
        wPqoqaYB67bN/0PeUuJXmg4w0NhlrQ1Xvwdpk6GXJwC7ghGDJffQAiGf9bw2FoOO
        Kst04Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDR2pyZE1ka0VrMFNGblhG
        TGh5QnFJMGk0bTBuREl0ZlU3cGN1OGliMHowClI3eUZpWnVZZTAySEJCTW4rMExU
        S21NSTlYZUN3ZUI2SmlsRm15S2ptTzgKLS0tIDJrZTZDSnZ1V0R2eWI2NEFUK0tn
        SmM4OHdLOGgxVCtaTTd6clBKZ3NyOTQKEd7F3FqhNQk3rpRG8ObEDY468feZs8Hf
        pnHePMRONAulKnzyJIoRvz4LN3yh3dgFJuTchyAk/v+mvsqTCRUS9w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-31T18:34:50Z"
  mac: ENC[AES256_GCM,data:44zAXenR88O7yn9yhJ2OkrGP3gchqFICTzDG4F38rqwvJwHELjhNTETQ0KbA1pY7zXJiXEIM085JbAE+9mH8Kr5Z58qiJgGM1d4sSsnKzImuPbFqf6IX/sME718BOOSvLpeZQ17IdgZlhhEhBVRi3WvP4Y3gSAiOnKYJSyNua10=,iv:sf6VvgftWY92bvVz9X7RmGjhZ8NRZEvIvulfsWENGmw=,tag:HHgnaIjaEvCHvgA2U6tSQA==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  diskSelector:
    match: '''/dev/disk/by-id/ata-SSD_512GB_202312010062'' in disk.symlinks'
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBTdFQz
        Y0lWZkZ4VlhscVZ4NzA1SVAwMzl2L2RtOEh2QTQwZE5jYTdBN3gwClNtcUpWdE9a
        UEcxUlFoQ2owSERQQnphV2ZpVnFLWVpLb0VnWGlTR200VzQKLS0tIEhUaFUvQUc1
        OFZaRWdUMDcwakxRN0c3QlZIRjhqdXAwNlRWUzMrS2trdFUKNkIpFpnKqAPHnaZU
        wPqoqaYB67bN/0PeUuJXmg4w0NhlrQ1Xvwdpk6GXJwC7ghGDJffQAiGf9bw2FoOO
        Kst04Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDR2pyZE1ka0VrMFNGblhG
        TGh5QnFJMGk0bTBuREl0ZlU3cGN1OGliMHowClI3eUZpWnVZZTAySEJCTW4rMExU
        S21NSTlYZUN3ZUI2SmlsRm15S2ptTzgKLS0tIDJrZTZDSnZ1V0R2eWI2NEFUK0tn
        SmM4OHdLOGgxVCtaTTd6clBKZ3NyOTQKEd7F3FqhNQk3rpRG8ObEDY468feZs8Hf
        pnHePMRONAulKnzyJIoRvz4LN3yh3dgFJuTchyAk/v+mvsqTCRUS9w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-31T18:34:50Z"
  mac: ENC[AES256_GCM,data:44zAXenR88O7yn9yhJ2OkrGP3gchqFICTzDG4F38rqwvJwHELjhNTETQ0KbA1pY7zXJiXEIM085JbAE+9mH8Kr5Z58qiJgGM1d4sSsnKzImuPbFqf6IX/sME718BOOSvLpeZQ17IdgZlhhEhBVRi3WvP4Y3gSAiOnKYJSyNua10=,iv:sf6VvgftWY92bvVz9X7RmGjhZ8NRZEvIvulfsWENGmw=,tag:HHgnaIjaEvCHvgA2U6tSQA==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: WireguardConfig
name: wg.kluster
# publicKey: mmTxsL60iWtsBx6+aMkxx2Of7g/exHTU9pXrinc1wlQ=
# enc!
privateKey: ENC[AES256_GCM,data:ecCcWWR5SPUHUqF3n26AgQz0j+lW2GzUsevMSgLxiB5QwX5lDQ3l/NI/h6Q=,iv:IGZG89N8enXvHOXSaPeKxIHq5caGE8YnNA/RTVdVAvo=,tag:NTPheWZRhkIqKtkWFEYnLg==,type:str]
listenPort: 51869
up: true
peers:
  # voltzahl
  - publicKey: hVSo5per13c8V9b5wUTAOGp0/W32rkKfSVZSctlqujU=
    allowedIPs:
      - 10.41.6.0/24
      - 2001:cafe:41:6::/64
      - 10.67.0.100/32
      - fdf6:9420:fade:67::5/128
      - fdf6:9420:fade:67::100/128
    # enc!
    endpoint: ENC[AES256_GCM,data:ihdVv1qtuyuvbYKbhNVOnB3zbQEnaW5IdLIu,iv:VULJWKnv3ouQOUEEwigfBAULJJ2RGE5F6JjmcH34Kjg=,tag:HY4k0sA6DpHzGuJ1XrPgcg==,type:str]
    # enc!
    #ENC[AES256_GCM,data:P06739o+KQSw6Ulz/8lEFUF3Oe40SlEM9umgQST6,iv:8hmfAO6sfp2pvIw5ntEVGCW6FjSTsr2izNCG5ruy/mQ=,tag:kRTkgkBXEJNrDURWpavxrQ==,type:comment]
    persistentKeepaliveInterval: ENC[AES256_GCM,data:0Gw=,iv:yNhpssEX5HeLMlrXlPXgmbJTFhCiXDdQAHRYnfQPir0=,tag:j5fV9AZmUu+HfAKchX10zQ==,type:str]
  # theta
  - publicKey: bg+Z4libGo+HGAC9UrWbooWkOI4+eZ5OAqw+8rPn9AA=
    allowedIPs:
      - 10.41.2.0/24
      - 2001:cafe:41:2::/64
      - 10.67.0.101/32
      - fdf6:9420:fade:67::4/128
      - fdf6:9420:fade:67::101/128
    # enc!
    endpoint: ENC[AES256_GCM,data:1OKJr2ly0kIhUCxJEBqRaSOHrHQhcgRE3ZJuWw==,iv:k9luCrz1EsipcC125ERBJvqJDBxP33RhgwbCJGLXNRI=,tag:ywI+M9aq6JJq3evoQlls6A==,type:str]
    # enc!
    #ENC[AES256_GCM,data:ufZrmdv+E80N6sdPxzYGXUFZyhTJh78T2p8Wpz7m58Q=,iv:wRk+G/DGCGFa9aEhAVEQotH+Bz+255oyNdl+ispdb+w=,tag:16sKPEjXYb52fNjG3ofDVQ==,type:comment]
    persistentKeepaliveInterval: ENC[AES256_GCM,data:hD8=,iv:/udhgYmf/NChLHSRuZYrs4cO/MxOnEu17gNQklkMc7o=,tag:Y26BBJZo1v4D5kPtyivyQA==,type:str]
  # alpha
  - publicKey: C/tFptmbSV+HBQYxzsTKUFW4LsPVcQyCNEfr8esvQ3w=
    allowedIPs:
      - 10.41.3.0/24
      - 2001:cafe:41:3::/64
      - 10.67.0.103/32
      - fdf6:9420:fade:67::103/128
    endpoint: 10.69.0.4:51869
  # oduduwa
  - publicKey: gobYpIEfo5paRPdkJ+Jnqcm9TyD+J2I4+Ry5AU0UhAQ=
    allowedIPs:
      - 10.41.4.0/24
      - 2001:cafe:41:4::/64
      - 10.67.0.104/32
      - fdf6:9420:fade:67::104/128
    # enc!
    endpoint: ENC[AES256_GCM,data:KtcpsyA8OXgGlNGX0/LpoQGWjWE=,iv:c6ZiZGpvet9X2vqHeTbQOoWnRzbqye9Bo+z8cvj33Mc=,tag:SNPI3u79GABhtxU7DvDNVA==,type:str]
    persistentKeepaliveInterval: 5s
  # caeneus
  - publicKey: l43bJSBEBDAc9vn+v9z2Zt/vsJRimWwyOwvHfHJrWkQ=
    allowedIPs:
      - 10.41.5.0/24
      - 2001:cafe:41:5::/64
      - 10.67.0.105/32
      - fdf6:9420:fade:67::105/128
    endpoint: 10.42.42.5:51869
    persistentKeepaliveInterval: 5s
  # prime
  - publicKey: 2jXr8tfBYrc3tBSvDweM2mJGAsPp6Sd/T2wCBss2fGU=
    allowedIPs:
      - 10.41.0.0/24
      - 2001:cafe:41::/64
      - 10.67.0.106/32
      - fdf6:9420:fade:67::106/128
    endpoint: 10.42.42.2:51869
    persistentKeepaliveInterval: 5s
addresses:
  - address: 10.67.0.102/32
  - address: fdf6:9420:fade:67::2/128
  - address: fdf6:9420:fade:67::102/128
routes:
  # voltzahl
  - destination: 10.41.6.0/24
  - destination: 2001:cafe:41:6::/64
  - destination: 10.67.0.100/32
  - destination: fdf6:9420:fade:67::5/128
  - destination: fdf6:9420:fade:67::100/128
  # theta
  - destination: 10.41.2.0/24
  - destination: 2001:cafe:41:2::/64
  - destination: 10.67.0.101/32
  - destination: fdf6:9420:fade:67::4/128
  - destination: fdf6:9420:fade:67::101/128
  # alpha
  - destination: 10.41.3.0/24
  - destination: 2001:cafe:41:3::/64
  - destination: 10.67.0.103/32
  - destination: fdf6:9420:fade:67::103/128
  # oduduwa
  - destination: 10.41.4.0/24
  - destination: 2001:cafe:41:4::/64
  - destination: 10.67.0.104/32
  - destination: fdf6:9420:fade:67::104/128
  # caeneus
  - destination: 10.41.5.0/24
  - destination: 2001:cafe:41:5::/64
  - destination: 10.67.0.105/32
  - destination: fdf6:9420:fade:67::105/128
  # prime
  - destination: 10.41.0.0/24
  - destination: 2001:cafe:41::/64
  - destination: 10.67.0.106/32
  - destination: fdf6:9420:fade:67::106/128
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBTdFQz
        Y0lWZkZ4VlhscVZ4NzA1SVAwMzl2L2RtOEh2QTQwZE5jYTdBN3gwClNtcUpWdE9a
        UEcxUlFoQ2owSERQQnphV2ZpVnFLWVpLb0VnWGlTR200VzQKLS0tIEhUaFUvQUc1
        OFZaRWdUMDcwakxRN0c3QlZIRjhqdXAwNlRWUzMrS2trdFUKNkIpFpnKqAPHnaZU
        wPqoqaYB67bN/0PeUuJXmg4w0NhlrQ1Xvwdpk6GXJwC7ghGDJffQAiGf9bw2FoOO
        Kst04Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDR2pyZE1ka0VrMFNGblhG
        TGh5QnFJMGk0bTBuREl0ZlU3cGN1OGliMHowClI3eUZpWnVZZTAySEJCTW4rMExU
        S21NSTlYZUN3ZUI2SmlsRm15S2ptTzgKLS0tIDJrZTZDSnZ1V0R2eWI2NEFUK0tn
        SmM4OHdLOGgxVCtaTTd6clBKZ3NyOTQKEd7F3FqhNQk3rpRG8ObEDY468feZs8Hf
        pnHePMRONAulKnzyJIoRvz4LN3yh3dgFJuTchyAk/v+mvsqTCRUS9w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-31T18:34:50Z"
  mac: ENC[AES256_GCM,data:44zAXenR88O7yn9yhJ2OkrGP3gchqFICTzDG4F38rqwvJwHELjhNTETQ0KbA1pY7zXJiXEIM085JbAE+9mH8Kr5Z58qiJgGM1d4sSsnKzImuPbFqf6IX/sME718BOOSvLpeZQ17IdgZlhhEhBVRi3WvP4Y3gSAiOnKYJSyNua10=,iv:sf6VvgftWY92bvVz9X7RmGjhZ8NRZEvIvulfsWENGmw=,tag:HHgnaIjaEvCHvgA2U6tSQA==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
