apiVersion: v1alpha1
kind: HostnameConfig
auto: "off"
hostname: sophons-beta
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyAyZ1cz
        VjNHcVJXQjdQUTg2M2tQYzM0eE9hRDBaZmpYUTB1UzA3VWIzVWpNCmUvWGtvNDFt
        dlRDYlljQ2NXaWR6cjVBWjBWMkJVVVFBQk5wS2xwZkF6RTAKLS0tIGFPZnZXbTRS
        K0lNWk1aaFA4cy9lcEdXMkplaDdhSHFZbW1lVFNneGpEUjAK/9/2aZQvE+OY4y45
        WHzBDqzMsaGjtQcVb1l5nHT5w5SPacmdfmrTX+796mHyzBiLNyz3RrfrO38MqTrN
        r4+7SQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiSXJvRnVTaDh3bVhNWlEz
        NHdWcFFaNHpkQ2doeW5CeVh3N3YyTlJTaGwwCnBWdzJIL3RsKzE4RFIrc1NhblpQ
        a1JPQjNONnBRYXB1Ym1WbGdOblpCaWcKLS0tICtjUXh1MzFyWEMwTjJrRlRFdW4z
        QlA4UjJSR0c1NkdVaGF4a2ZzUVpXSkUKUQqr0CHwBZq0orNYBRhN6oGS3mti+NVn
        9pgGNdqtNW/lanNVHCozglSFxlO+wJX9j1FkI5szVReeaytFnkvLMA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-10T19:27:24Z"
  mac: ENC[AES256_GCM,data:rvyu9BbOihG+w/DbpC+xS/rMsvgxsjdofNXUpOlOpGWNzJCS2g45PYmLQdYcry9rciG/RW20K3mfW9zQKizLS10lUR5uZutDIQ5KOg21B878IfMsW6KxCmToEJM48ThC9nsxfVcjENi6ubqfYz4cmx020ki4qXZ44vEfghZdz/A=,iv:1A+AUmDl+l24GfGXYVsMrVVgTXUdv/H8t+fSrNM6Cf8=,tag:M83cG7X+mCcBCI0tlEwbgA==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
cluster:
  network:
    cni:
      name: none
machine:
  install:
    disk: /dev/mmcblk0
  nodeLabels:
    topology.kubernetes.io/region: ng
    topology.kubernetes.io/zone: ng-east-1
  network:
    interfaces:
      - interface: end0
        dhcp: false
        vlans:
          - vlanId: 42
            dhcp: false
            # dhcp: true
            # dhcpOptions:
            #   ipv4: false
            #   ipv6: true
            addresses:
              - 10.42.69.3/16
            routes:
              - network: 0.0.0.0/0
                gateway: 10.42.0.1
                # - network: ::/0
                #   gateway: fe80::1
                #   #   metric: 200
          - vlanId: 69
            dhcp: false
            addresses:
              - 10.69.0.3/16
              # routes:
              #   - network: 0.0.0.0/0
              #     gateway: 10.69.0.1
              #   - network: ::/0
              #     gateway: fe80::1
              #     metric: 200
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyAyZ1cz
        VjNHcVJXQjdQUTg2M2tQYzM0eE9hRDBaZmpYUTB1UzA3VWIzVWpNCmUvWGtvNDFt
        dlRDYlljQ2NXaWR6cjVBWjBWMkJVVVFBQk5wS2xwZkF6RTAKLS0tIGFPZnZXbTRS
        K0lNWk1aaFA4cy9lcEdXMkplaDdhSHFZbW1lVFNneGpEUjAK/9/2aZQvE+OY4y45
        WHzBDqzMsaGjtQcVb1l5nHT5w5SPacmdfmrTX+796mHyzBiLNyz3RrfrO38MqTrN
        r4+7SQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiSXJvRnVTaDh3bVhNWlEz
        NHdWcFFaNHpkQ2doeW5CeVh3N3YyTlJTaGwwCnBWdzJIL3RsKzE4RFIrc1NhblpQ
        a1JPQjNONnBRYXB1Ym1WbGdOblpCaWcKLS0tICtjUXh1MzFyWEMwTjJrRlRFdW4z
        QlA4UjJSR0c1NkdVaGF4a2ZzUVpXSkUKUQqr0CHwBZq0orNYBRhN6oGS3mti+NVn
        9pgGNdqtNW/lanNVHCozglSFxlO+wJX9j1FkI5szVReeaytFnkvLMA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-10T19:27:24Z"
  mac: ENC[AES256_GCM,data:rvyu9BbOihG+w/DbpC+xS/rMsvgxsjdofNXUpOlOpGWNzJCS2g45PYmLQdYcry9rciG/RW20K3mfW9zQKizLS10lUR5uZutDIQ5KOg21B878IfMsW6KxCmToEJM48ThC9nsxfVcjENi6ubqfYz4cmx020ki4qXZ44vEfghZdz/A=,iv:1A+AUmDl+l24GfGXYVsMrVVgTXUdv/H8t+fSrNM6Cf8=,tag:M83cG7X+mCcBCI0tlEwbgA==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
# https://tailscale.com/docs/reference/best-practices/performance#linux-optimizations-for-subnet-routers-and-exit-nodes
apiVersion: v1alpha1
kind: EthernetConfig
name: end0
features:
  rx-gro-list: "off"
  rx-udp-gro-forwarding: "on"
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyAyZ1cz
        VjNHcVJXQjdQUTg2M2tQYzM0eE9hRDBaZmpYUTB1UzA3VWIzVWpNCmUvWGtvNDFt
        dlRDYlljQ2NXaWR6cjVBWjBWMkJVVVFBQk5wS2xwZkF6RTAKLS0tIGFPZnZXbTRS
        K0lNWk1aaFA4cy9lcEdXMkplaDdhSHFZbW1lVFNneGpEUjAK/9/2aZQvE+OY4y45
        WHzBDqzMsaGjtQcVb1l5nHT5w5SPacmdfmrTX+796mHyzBiLNyz3RrfrO38MqTrN
        r4+7SQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiSXJvRnVTaDh3bVhNWlEz
        NHdWcFFaNHpkQ2doeW5CeVh3N3YyTlJTaGwwCnBWdzJIL3RsKzE4RFIrc1NhblpQ
        a1JPQjNONnBRYXB1Ym1WbGdOblpCaWcKLS0tICtjUXh1MzFyWEMwTjJrRlRFdW4z
        QlA4UjJSR0c1NkdVaGF4a2ZzUVpXSkUKUQqr0CHwBZq0orNYBRhN6oGS3mti+NVn
        9pgGNdqtNW/lanNVHCozglSFxlO+wJX9j1FkI5szVReeaytFnkvLMA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-10T19:27:24Z"
  mac: ENC[AES256_GCM,data:rvyu9BbOihG+w/DbpC+xS/rMsvgxsjdofNXUpOlOpGWNzJCS2g45PYmLQdYcry9rciG/RW20K3mfW9zQKizLS10lUR5uZutDIQ5KOg21B878IfMsW6KxCmToEJM48ThC9nsxfVcjENi6ubqfYz4cmx020ki4qXZ44vEfghZdz/A=,iv:1A+AUmDl+l24GfGXYVsMrVVgTXUdv/H8t+fSrNM6Cf8=,tag:M83cG7X+mCcBCI0tlEwbgA==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  diskSelector:
    match: '''/dev/disk/by-id/ata-SSD_512GB_202312010062'' in disk.symlinks'
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyAyZ1cz
        VjNHcVJXQjdQUTg2M2tQYzM0eE9hRDBaZmpYUTB1UzA3VWIzVWpNCmUvWGtvNDFt
        dlRDYlljQ2NXaWR6cjVBWjBWMkJVVVFBQk5wS2xwZkF6RTAKLS0tIGFPZnZXbTRS
        K0lNWk1aaFA4cy9lcEdXMkplaDdhSHFZbW1lVFNneGpEUjAK/9/2aZQvE+OY4y45
        WHzBDqzMsaGjtQcVb1l5nHT5w5SPacmdfmrTX+796mHyzBiLNyz3RrfrO38MqTrN
        r4+7SQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiSXJvRnVTaDh3bVhNWlEz
        NHdWcFFaNHpkQ2doeW5CeVh3N3YyTlJTaGwwCnBWdzJIL3RsKzE4RFIrc1NhblpQ
        a1JPQjNONnBRYXB1Ym1WbGdOblpCaWcKLS0tICtjUXh1MzFyWEMwTjJrRlRFdW4z
        QlA4UjJSR0c1NkdVaGF4a2ZzUVpXSkUKUQqr0CHwBZq0orNYBRhN6oGS3mti+NVn
        9pgGNdqtNW/lanNVHCozglSFxlO+wJX9j1FkI5szVReeaytFnkvLMA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-10T19:27:24Z"
  mac: ENC[AES256_GCM,data:rvyu9BbOihG+w/DbpC+xS/rMsvgxsjdofNXUpOlOpGWNzJCS2g45PYmLQdYcry9rciG/RW20K3mfW9zQKizLS10lUR5uZutDIQ5KOg21B878IfMsW6KxCmToEJM48ThC9nsxfVcjENi6ubqfYz4cmx020ki4qXZ44vEfghZdz/A=,iv:1A+AUmDl+l24GfGXYVsMrVVgTXUdv/H8t+fSrNM6Cf8=,tag:M83cG7X+mCcBCI0tlEwbgA==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
