apiVersion: v1alpha1
kind: HostnameConfig
auto: "off"
hostname: sophons-caeneus
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBrQ25I
        SmwzMXo1K3QwQi82S0pXYTM5RkdkYlVBd2s2dklNVU9rSjEyRHprCnVlTkl3UEVB
        NkhyRStWczlkYks4cWUzd2JmRmlzZ3VqdDhPd09JREZxblEKLS0tIDlDc2NFbGwy
        TTRDSFRWMk5vTkx2eTliN3krRENnV1ZySFI4TmZKWDBmS0UKT/flWUVdqCcSgzOu
        I8DdmGE7PHwPvqWhHYgWISmt/HgR0UiptHzmRAlmlFa1DMABM44VH0asV7U3e7mb
        HjxeYA==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSG13UzZLRy9GcmxTWll6
        SDV4eFAwUjVkUlJFcTFWRUwyanNpRTIzN2pzCnhMbXkxSHpoTU5ub2xBL3NUZGtD
        RkJwa2ZzQzNGOVBsZE9laHlMeGNsRlkKLS0tIHhLOTFyazJOWlBMckN6NmJrZlQ4
        R2hSVHhDd1hYQnpXcEdkZlRZUXZjVWMK+dvtevg0HAHMCfWSAx3A/hgbAuNHUGwP
        TM4AxCwjGtylw+p31DnG8xn5POdYxCM4cBpSxOS1IJBgxynlLzk7Eg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-08-28T20:03:06Z"
  mac: ENC[AES256_GCM,data:KQxRTmTPiPjfNGn0MaZ0ih7uEkBqJikpsblcKChxmMZvPAzfOUnbZTZ+l4lKDRWB5O39vAM6XjVMYfbpfhhoodcyGv6zpe3eVy4+7bVmF1Qes599q9llhHPQJ/5uWSmgYBvZgzy/cayZgLkzWRk7DnZgNVM7hhUmRv/OvP7dips=,iv:bgXWyUexuUbUWgk2sPtasxIDYNllv1+BX7KhQUfyOpA=,tag:ytYgByk1HUZQAz7pdYBYGw==,type:str]
  version: 3.13.3
---
cluster:
  network:
    cni:
      name: none
machine:
  sysctls:
    # 64MiB
    vm.min_free_kbytes: 65536
    vm.swappiness: 200
    vm.watermark_scale_factor: 100
    kernel.unprivileged_userns_clone: 1
  kubelet:
    extraMounts:
      - destination: /var/lib/garage/backup/big-boi
        type: bind
        source: /var/lib/garage/backup/big-boi
        options:
          - bind
          - rshared
          - rw
      - destination: /var/lib/garage/backup/less-big-boi
        type: bind
        source: /var/lib/garage/backup/less-big-boi
        options:
          - bind
          - rshared
          - rw
      - destination: /mnt/less-big-boi/media
        type: bind
        source: /mnt/less-big-boi/media
        options:
          - bind
          - rshared
          - rw
      - destination: /mnt/big-boi/time-machine
        type: bind
        source: /mnt/big-boi/time-machine
        options:
          - bind
          - rshared
          - rw
      - destination: /mnt/big-boi/everything-else
        type: bind
        source: /mnt/big-boi/everything-else
        options:
          - bind
          - rshared
          - rw
    extraConfig:
      mergeDefaultEvictionSettings: true
      evictionHard:
        nodefs.available: 0%
        nodefs.inodesFree: 0%
      # kubelet doesn't use cgroups to apply limits, so, hacks!
      systemReserved:
        ephemeral-storage: 1.5Ti
        cpu: 18000m
        memory: 80Gi
  features:
    hostDNS:
      enabled: true
      forwardKubeDNSToHost: true
  nodeLabels:
    egress.sophons.cloud/positron: "true"
    topology.kubernetes.io/region: ng
    topology.kubernetes.io/zone: ng-middle-east
    hugeloads.sophons.cloud/longhorn: "false"
    hugeloads.sophons.cloud/postgres: "false"
  network:
    interfaces:
      - interface: eth0
        dhcp: false
        addresses:
          - 10.42.42.5/16
        routes:
          - network: 0.0.0.0/0
            gateway: 10.42.0.1
          - network: ::/0
            gateway: fe80::1
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBrQ25I
        SmwzMXo1K3QwQi82S0pXYTM5RkdkYlVBd2s2dklNVU9rSjEyRHprCnVlTkl3UEVB
        NkhyRStWczlkYks4cWUzd2JmRmlzZ3VqdDhPd09JREZxblEKLS0tIDlDc2NFbGwy
        TTRDSFRWMk5vTkx2eTliN3krRENnV1ZySFI4TmZKWDBmS0UKT/flWUVdqCcSgzOu
        I8DdmGE7PHwPvqWhHYgWISmt/HgR0UiptHzmRAlmlFa1DMABM44VH0asV7U3e7mb
        HjxeYA==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSG13UzZLRy9GcmxTWll6
        SDV4eFAwUjVkUlJFcTFWRUwyanNpRTIzN2pzCnhMbXkxSHpoTU5ub2xBL3NUZGtD
        RkJwa2ZzQzNGOVBsZE9laHlMeGNsRlkKLS0tIHhLOTFyazJOWlBMckN6NmJrZlQ4
        R2hSVHhDd1hYQnpXcEdkZlRZUXZjVWMK+dvtevg0HAHMCfWSAx3A/hgbAuNHUGwP
        TM4AxCwjGtylw+p31DnG8xn5POdYxCM4cBpSxOS1IJBgxynlLzk7Eg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-08-28T20:03:06Z"
  mac: ENC[AES256_GCM,data:KQxRTmTPiPjfNGn0MaZ0ih7uEkBqJikpsblcKChxmMZvPAzfOUnbZTZ+l4lKDRWB5O39vAM6XjVMYfbpfhhoodcyGv6zpe3eVy4+7bVmF1Qes599q9llhHPQJ/5uWSmgYBvZgzy/cayZgLkzWRk7DnZgNVM7hhUmRv/OvP7dips=,iv:bgXWyUexuUbUWgk2sPtasxIDYNllv1+BX7KhQUfyOpA=,tag:ytYgByk1HUZQAz7pdYBYGw==,type:str]
  version: 3.13.3
