apiVersion: v1alpha1
kind: HostnameConfig
auto: "off"
hostname: sophons-caeneus
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBqcTRQ
        L0NjU3NXYjBDZWgybDUrNkVnSmU4WHNxdTFqWU1qMHhiYkttdlFVCkNCUHU0MjdX
        clhkaDZYUDk1OUhCUzhOeEc3QWc4YWJpL2hLS05EcUc0V28KLS0tIE10dkNjRFRh
        M2M0MHpMUkYrbjJxS2RMVXd6RXVtcWF0eXFDd2hMb3RtWlkK1abIvAg64CfSEUGX
        +a4+T7yMRbWpfmy4/WBN8DcMMxD6IHOx9eT5XsU+mj1L3O8LvN1lGfpYg6QpUJbi
        aml68g==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXdDlBamI3NFppL0VtMUpa
        dWF4Mlp6QWk3cW93L0tJN3I0SGZWV0pmclZjCnRzdmxBWTFCbVlqWFVLdE53Uys2
        enB5MUx2eml6dXZ0L2czMFJCYVQ0QUkKLS0tIFNRbW52a0pMRzF5cUY3eFVDQ2xH
        UzNtZ2ZFc3Q5MTV0RXBiSlRxQkxRYTgKhirkltQjcPuKuHvO596Yx1O4SETjkOk9
        tOPWtsgc2ZeOg0hrhHkwPaO0EMlVCQriRB4ULk9RO+3vesr5rWax5w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-12T18:26:29Z"
  mac: ENC[AES256_GCM,data:fyrBa5dFsEwUseEMZZ7xs9QDNV4mR73xlYpno1Wo25VNQwemr3kKX6V80AomgkcJBidDT0gyqNyihva1E+ZF2MHmqsimeuzxQsJ/cngrM1mL87oRnfv/aF+JBC5btk/n71O6GHT0qSxWCH9kkAjx7bg6JvjgAVPv4hFifnWkL1w=,iv:JKIxtUhQk6CnaKPiDXpZ3zzyz5vxhruAISCsiD46+OM=,tag:l7o6EbWH/X9Haf8iOOpbag==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
cluster:
  network:
    cni:
      name: none
machine:
  sysctls:
    # 64MiB
    vm.min_free_kbytes: 65536
    vm.swappiness: 200
    vm.watermark_scale_factor: 100
    kernel.unprivileged_userns_clone: 1
  kubelet:
    extraMounts:
      - destination: /var/lib/garage/backup/big-boi
        type: bind
        source: /var/lib/garage/backup/big-boi
        options:
          - bind
          - rshared
          - rw
      - destination: /var/lib/garage/backup/less-big-boi
        type: bind
        source: /var/lib/garage/backup/less-big-boi
        options:
          - bind
          - rshared
          - rw
      - destination: /mnt/less-big-boi/media
        type: bind
        source: /mnt/less-big-boi/media
        options:
          - bind
          - rshared
          - rw
      - destination: /mnt/big-boi/time-machine
        type: bind
        source: /mnt/big-boi/time-machine
        options:
          - bind
          - rshared
          - rw
      - destination: /mnt/big-boi/everything-else
        type: bind
        source: /mnt/big-boi/everything-else
        options:
          - bind
          - rshared
          - rw
    extraConfig:
      mergeDefaultEvictionSettings: true
      evictionHard:
        nodefs.available: 0%
        nodefs.inodesFree: 0%
      # kubelet doesn't use cgroups to apply limits, so, hacks!
      systemReserved:
        ephemeral-storage: 1.5Ti
        cpu: 18000m
        memory: 80Gi
  features:
    hostDNS:
      enabled: true
      forwardKubeDNSToHost: true
  nodeLabels:
    egress.sophons.cloud/positron: "true"
    topology.kubernetes.io/region: ng
    topology.kubernetes.io/zone: ng-middle-east
    hugeloads.sophons.cloud/longhorn: "false"
    hugeloads.sophons.cloud/postgres: "false"
  network:
    interfaces:
      - interface: eth0
        dhcp: false
        addresses:
          - 10.42.42.5/16
        routes:
          - network: 0.0.0.0/0
            gateway: 10.42.0.1
            # - network: ::/0
            #   gateway: fe80::1
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBqcTRQ
        L0NjU3NXYjBDZWgybDUrNkVnSmU4WHNxdTFqWU1qMHhiYkttdlFVCkNCUHU0MjdX
        clhkaDZYUDk1OUhCUzhOeEc3QWc4YWJpL2hLS05EcUc0V28KLS0tIE10dkNjRFRh
        M2M0MHpMUkYrbjJxS2RMVXd6RXVtcWF0eXFDd2hMb3RtWlkK1abIvAg64CfSEUGX
        +a4+T7yMRbWpfmy4/WBN8DcMMxD6IHOx9eT5XsU+mj1L3O8LvN1lGfpYg6QpUJbi
        aml68g==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXdDlBamI3NFppL0VtMUpa
        dWF4Mlp6QWk3cW93L0tJN3I0SGZWV0pmclZjCnRzdmxBWTFCbVlqWFVLdE53Uys2
        enB5MUx2eml6dXZ0L2czMFJCYVQ0QUkKLS0tIFNRbW52a0pMRzF5cUY3eFVDQ2xH
        UzNtZ2ZFc3Q5MTV0RXBiSlRxQkxRYTgKhirkltQjcPuKuHvO596Yx1O4SETjkOk9
        tOPWtsgc2ZeOg0hrhHkwPaO0EMlVCQriRB4ULk9RO+3vesr5rWax5w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-12T18:26:29Z"
  mac: ENC[AES256_GCM,data:fyrBa5dFsEwUseEMZZ7xs9QDNV4mR73xlYpno1Wo25VNQwemr3kKX6V80AomgkcJBidDT0gyqNyihva1E+ZF2MHmqsimeuzxQsJ/cngrM1mL87oRnfv/aF+JBC5btk/n71O6GHT0qSxWCH9kkAjx7bg6JvjgAVPv4hFifnWkL1w=,iv:JKIxtUhQk6CnaKPiDXpZ3zzyz5vxhruAISCsiD46+OM=,tag:l7o6EbWH/X9Haf8iOOpbag==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
