apiVersion: v1alpha1
kind: HostnameConfig
auto: "off"
hostname: sophons-caeneus
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBaVEtu
        ejVNSXFFS01zRXhpaEZzSDdzbWYrcW5waWtHVkdVMDZpUjhwcjNBCjRhRDZ2bjNG
        V3J5OUgwL3lHVUhtQ1NyVGtIdUFNaUlabEg4SVlLYXZyL00KLS0tIFBwa3ZJZFpm
        TUNXOURhQnBodGtKMStpREdQTTJuSkd3ZEJ0VEFMUWJwRGcKxYv9TGQr9ZqrYSTi
        7mXCl4huvdg5Zh11tFWVmaDEfIt4PzwiqNRhHA3eNJeZXN1OZHFngyQdsyCKT/0+
        d9193Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZlVEc3lKZFEzc1lFL00v
        Tm4rajhHVXFQN0x3OHgxZ3BoMVJZalF2andjCkJQaG5TZDlpbGNiQmx1R2F4UkFs
        TXgzL05IUm5jb1dBWmMxRTVCdmxPa3MKLS0tIEgvZWx4ellRWnhyNGcwVmY0RWIv
        Q3NDNW1GcmZVV1pwK0tNc2thcmwzWWsKMCz/fxF1XIrg79QUB0VXOiESGY90gVGd
        Gk1PZBifibH9Yx5n9P+D2sFdjHosUHgxDWhlBoF2KxfxDziDtDWKKw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-08T16:47:51Z"
  mac: ENC[AES256_GCM,data:zcrU/4SdyNovpJefS1q2I5OFzADlpMPA5jvk0zX5fWTg6tpVBMVxLByUnETb2mdsSokR567aS8H2v+U3OIiSyEa64SNpiO1cTNqkLVXiX38dlXWIYh7AGAD2BqCCxIaiNERDIupIQzvzLDeioQT1SdS0rvsarytjPO4ZMR9yE3w=,iv:R+GOXwzEP/2z4Vn4dmiLg3+Qkqr5/Z84E+qdMPgpIto=,tag:XaLdf/dAaBY0eud8w1X67g==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
cluster:
  network:
    cni:
      name: none
machine:
  sysctls:
    # 64MiB
    vm.min_free_kbytes: 65536
    vm.swappiness: 200
    vm.watermark_scale_factor: 100
    kernel.unprivileged_userns_clone: 1
  kubelet:
    extraMounts:
      - destination: /var/lib/garage/backup/big-boi
        type: bind
        source: /var/lib/garage/backup/big-boi
        options:
          - bind
          - rshared
          - rw
      - destination: /var/lib/garage/backup/less-big-boi
        type: bind
        source: /var/lib/garage/backup/less-big-boi
        options:
          - bind
          - rshared
          - rw
      - destination: /mnt/less-big-boi/media
        type: bind
        source: /mnt/less-big-boi/media
        options:
          - bind
          - rshared
          - rw
      - destination: /mnt/big-boi/time-machine
        type: bind
        source: /mnt/big-boi/time-machine
        options:
          - bind
          - rshared
          - rw
      - destination: /mnt/big-boi/everything-else
        type: bind
        source: /mnt/big-boi/everything-else
        options:
          - bind
          - rshared
          - rw
    extraConfig:
      mergeDefaultEvictionSettings: true
      evictionHard:
        nodefs.available: 0%
        nodefs.inodesFree: 0%
      # kubelet doesn't use cgroups to apply limits, so, hacks!
      systemReserved:
        ephemeral-storage: 1.5Ti
        cpu: 16000m
        memory: 80Gi
  features:
    hostDNS:
      enabled: true
      forwardKubeDNSToHost: true
  nodeLabels:
    topology.kubernetes.io/region: ng
    topology.kubernetes.io/zone: ng-middle-east
    hugeloads.sophons.cloud/longhorn: "false"
    hugeloads.sophons.cloud/postgres: "false"
  network:
    interfaces:
      - interface: eth0
        dhcp: false
        addresses:
          - 10.42.42.5/16
        routes:
          - network: 0.0.0.0/0
            gateway: 10.42.0.1
            # - network: ::/0
            #   gateway: fe80::1
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBaVEtu
        ejVNSXFFS01zRXhpaEZzSDdzbWYrcW5waWtHVkdVMDZpUjhwcjNBCjRhRDZ2bjNG
        V3J5OUgwL3lHVUhtQ1NyVGtIdUFNaUlabEg4SVlLYXZyL00KLS0tIFBwa3ZJZFpm
        TUNXOURhQnBodGtKMStpREdQTTJuSkd3ZEJ0VEFMUWJwRGcKxYv9TGQr9ZqrYSTi
        7mXCl4huvdg5Zh11tFWVmaDEfIt4PzwiqNRhHA3eNJeZXN1OZHFngyQdsyCKT/0+
        d9193Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZlVEc3lKZFEzc1lFL00v
        Tm4rajhHVXFQN0x3OHgxZ3BoMVJZalF2andjCkJQaG5TZDlpbGNiQmx1R2F4UkFs
        TXgzL05IUm5jb1dBWmMxRTVCdmxPa3MKLS0tIEgvZWx4ellRWnhyNGcwVmY0RWIv
        Q3NDNW1GcmZVV1pwK0tNc2thcmwzWWsKMCz/fxF1XIrg79QUB0VXOiESGY90gVGd
        Gk1PZBifibH9Yx5n9P+D2sFdjHosUHgxDWhlBoF2KxfxDziDtDWKKw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-08T16:47:51Z"
  mac: ENC[AES256_GCM,data:zcrU/4SdyNovpJefS1q2I5OFzADlpMPA5jvk0zX5fWTg6tpVBMVxLByUnETb2mdsSokR567aS8H2v+U3OIiSyEa64SNpiO1cTNqkLVXiX38dlXWIYh7AGAD2BqCCxIaiNERDIupIQzvzLDeioQT1SdS0rvsarytjPO4ZMR9yE3w=,iv:R+GOXwzEP/2z4Vn4dmiLg3+Qkqr5/Z84E+qdMPgpIto=,tag:XaLdf/dAaBY0eud8w1X67g==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
