cluster:
  discovery:
    enabled: true
    registries:
      # Kubernetes registry is problematic with KubeSpan, if the control plane endpoint is routeable itself via KubeSpan.
      kubernetes:
        disabled: true
      service: {}
  network:
    podSubnets:
      - 10.41.0.0/16
      - 2001:cafe:41::/56
    serviceSubnets:
      - 10.43.0.0/16
      - 2001:cafe:43::/112
  proxy:
    disabled: true
machine:
  network:
    kubespan:
      enabled: true
    # enc!
    extraHostEntries:
      - ip: ENC[AES256_GCM,data:AjgVb1PtJJQ7TJZxEnn/Pha0keU=,iv:mjK3vuJ5ulVrYSO4IKtQLwLOWPvPzLRqAavoyv5hYfA=,tag:pqMV1CV1gOdJXmRFwXApuQ==,type:str]
        aliases:
          - ENC[AES256_GCM,data:yWzzIZCISCqG3XOyACsf9/NlXh0RmvEBi7Q=,iv:5eNxpYTqHcZ9UbvuX8XoNkqP2HWCYC3fl/3HSGeo/7o=,tag:zjvnHdoijTAgJ2H//Ra2zw==,type:str]
      - ip: ENC[AES256_GCM,data:I2HeMngrxSBE0fjfpKYitwSe4ypvIIVv,iv:SGfFe/J7pWN0bum8kT2fCOfV0m8R5Y5NPc12UXSywDk=,tag:givMceMwk+g/rGsByHVu/Q==,type:str]
        aliases:
          - ENC[AES256_GCM,data:Fg2LI4s0F85X9NKLRH5hA5FkmcET/+Ip7s4=,iv:5DD44KJeKtBMSK70BpJQVoYIiBojI7k3Sdh0YWTHdAY=,tag:saZ5AkKrLVe0ifUM3ASbWQ==,type:str]
      - ip: ENC[AES256_GCM,data:fXbVa3ufOOsRjuhGc7U8kXn8BGgzNZce,iv:p4pjLKhp7n/X2SXAh+RZ0Z6viwTFGlfGkA//sOdHbtw=,tag:wdpdrfD1uxEYp2yC7Jc3tw==,type:str]
        aliases:
          - ENC[AES256_GCM,data:O3oCLfvrXRTUgB5cXuCBHQTLRuyBLBH6Msc=,iv:OMdnxwOl6axBW5amxHAL6Gm77a8EM7J5Jx3+3YlV5es=,tag:pvMtZqXuDuigdqCH7nY7WQ==,type:str]
      - ip: ENC[AES256_GCM,data:UUWpppGCo4F0,iv:cN6PYsEWRK3cpmgndo8UOiEs5sKanCQYJVk+wo+Whb0=,tag:CerZxmOVZEp+3Y9rM9i0kA==,type:str]
        aliases:
          - ENC[AES256_GCM,data:5wzbjm4yYgQu59I2/ihseG18UsEHQ+JxSOw=,iv:JAJYF5vOX7NwTmSyMa76ATshLrzFZTUuUm4mi/dx82g=,tag:7ahXOktv1T6SwAhc626zWQ==,type:str]
      - ip: ENC[AES256_GCM,data:OnZMlJn2iVoV,iv:vivAFVBFMfJBqYhIfxNP9xuIGMaezlFNlJBQeEOp9Rc=,tag:VYv6f/Z9utpRLw08gTqk2w==,type:str]
        aliases:
          - ENC[AES256_GCM,data:PjoOojszTuO+teU+Jijx6qunQ9gx/n+owx8=,iv:+ks0VWHYgZGj45EqJXoUPNqF0SCu/HznZaLJns2HaTQ=,tag:iyFja4BJM9UQAWetwRpWag==,type:str]
      - ip: ENC[AES256_GCM,data:wBp+rmKrOM3cdB35Cw==,iv:IoECLabNOxa6dfVwj3kzlsCdbN2AthviHGcmEAirvvI=,tag:kfaG+ryRZf1ucNEuYmgctQ==,type:str]
        aliases:
          - ENC[AES256_GCM,data:szYRrR/x0s+L4a+yrkQoliB7Alzy4t5t1Bw=,iv:xDG0KKAaUcAlztKqTyKGtvExm2CSPWJSS+9sp9mnSmw=,tag:pJ3ei8CpneJMBCmUu27ToQ==,type:str]
  sysctls:
    # 128MiB
    vm.min_free_kbytes: 131072
    vm.watermark_scale_factor: 50
    fs.inotify.max_user_watches: 4194304
    fs.inotify.max_user_instances: 65536
    user.max_user_namespaces: 65536
  kubelet:
    extraArgs:
      rotate-server-certificates: true
    extraMounts:
      - destination: /var/lib/longhorn
        type: bind
        source: /var/lib/longhorn
        options:
          - bind
          - rshared
          - rw
    extraConfig:
      # kubelet serving certs
      serverTLSBootstrap: true
      memorySwap:
        swapBehavior: LimitedSwap
  features:
    hostDNS:
      resolveMemberNames: true
  nodeLabels:
    hugeloads.sophons.cloud/longhorn: "true"
    hugeloads.sophons.cloud/postgres: "true"
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyA1K2k3
        SzVLcmY4OSt1bytmYXdYL21Lc2trNnRsKzFJRFRiN3VmTjVGSm53Cmd0QVV3aHVX
        ejNoNWZBMU5qVFRKeTFCTkk3VUVPbVRhS1k3amUxcUEyREkKLS0tIHViSHpNR2Jn
        RTdpZnlVdmI0aWhLc3FDdXVmT0RKQnIzT0E0R0xCeWpwYjAKeuQsWz0tsm9+WRQt
        afDSlC3uPGai6ac7E1nJYVpiN00a7v4VaKH/Q8+oc4E8doEgKyHAgED56jelkotY
        oa2tYg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqamR6d2lvK1pJaXRXUzhS
        T2p3SU9sWTVRbUMxK2w4Smx0d2xXZEZOZmprClJHVHZ4RzYvMzVnSGIwNi96cm1N
        eXp5RDNLM3pxNW1tVWcxNkpnamdiTTgKLS0tIExOdWIwMFhZODYxSGptTDcvOXM1
        V3BZMlgwWWQyUWl0cGhpRCtGenRyeHcKcG2rNMHG1F6qI2cniaWXKF/R1S+NHIPU
        WuKmO0zykmJ9c+jxYgkrBcdwlhU/9yxU5hkURaUErIwSW/OfU/L1TA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-17T16:22:07Z"
  mac: ENC[AES256_GCM,data:H43QAM14oJs4RH8LKXTQpfJKxpGT1Xz2Yz4dmyvCMRDupYNd2Qjhu4PUWOEFO96nUNr+ZIsS8VCIPJpnggo5Y0m2DM/t86rJeL5Qyb5L03K+uGct/Aw/vBq6x+efNrcgkTjviiCNVb84BeEbjFwQXKBG2WrXXAePVQ49RkA0F7k=,iv:8bf5a1Ns8s9lGs42jXYsZ2LYwO0w7dLCOiJR823lVqE=,tag:z+qS3W424RasyP3MgSNtfQ==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: ZswapConfig
# The maximum percent of memory that zswap can use.
maxPoolPercent: 25
# Enable the shrinker feature: kernel might move
shrinkerEnabled: true
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyA1K2k3
        SzVLcmY4OSt1bytmYXdYL21Lc2trNnRsKzFJRFRiN3VmTjVGSm53Cmd0QVV3aHVX
        ejNoNWZBMU5qVFRKeTFCTkk3VUVPbVRhS1k3amUxcUEyREkKLS0tIHViSHpNR2Jn
        RTdpZnlVdmI0aWhLc3FDdXVmT0RKQnIzT0E0R0xCeWpwYjAKeuQsWz0tsm9+WRQt
        afDSlC3uPGai6ac7E1nJYVpiN00a7v4VaKH/Q8+oc4E8doEgKyHAgED56jelkotY
        oa2tYg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqamR6d2lvK1pJaXRXUzhS
        T2p3SU9sWTVRbUMxK2w4Smx0d2xXZEZOZmprClJHVHZ4RzYvMzVnSGIwNi96cm1N
        eXp5RDNLM3pxNW1tVWcxNkpnamdiTTgKLS0tIExOdWIwMFhZODYxSGptTDcvOXM1
        V3BZMlgwWWQyUWl0cGhpRCtGenRyeHcKcG2rNMHG1F6qI2cniaWXKF/R1S+NHIPU
        WuKmO0zykmJ9c+jxYgkrBcdwlhU/9yxU5hkURaUErIwSW/OfU/L1TA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-17T16:22:07Z"
  mac: ENC[AES256_GCM,data:H43QAM14oJs4RH8LKXTQpfJKxpGT1Xz2Yz4dmyvCMRDupYNd2Qjhu4PUWOEFO96nUNr+ZIsS8VCIPJpnggo5Y0m2DM/t86rJeL5Qyb5L03K+uGct/Aw/vBq6x+efNrcgkTjviiCNVb84BeEbjFwQXKBG2WrXXAePVQ49RkA0F7k=,iv:8bf5a1Ns8s9lGs42jXYsZ2LYwO0w7dLCOiJR823lVqE=,tag:z+qS3W424RasyP3MgSNtfQ==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: ExtensionServiceConfig
name: cloudflared
environment:
  # enc!
  - ENC[AES256_GCM,data:HMH0dR+BWsKPpZqaEw7kvWaCHpG8R218R+aJmVtXAJWuswpx/P057lq2b7nE6jv/K1YdTe8VqQmpSiHj3eVU1AXKFIsUNPycAf+oSHZGkb6R72EeZZZJk8KHorq5YqVNon9gX0KdfhCBwhv5bincttTLqoF+Eq0yMBWiQ2F1MwI1+L691gAMn3JcVWpBeL7eOpThvfrEwqErmIzHdHT6iAP5W1MoA+uyXFqwU9tla3bSNtEx1YNNpxLKu9jtZIvhRFHvdkg=,iv:lLWgWVAldmF1pZTfuUZZT/Z/hnUIKE1se+qOYfYcTyg=,tag:5KUhZX0Ok1e5mA10ImSpqg==,type:str]
  - TUNNEL_METRICS=localhost:2000
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyA1K2k3
        SzVLcmY4OSt1bytmYXdYL21Lc2trNnRsKzFJRFRiN3VmTjVGSm53Cmd0QVV3aHVX
        ejNoNWZBMU5qVFRKeTFCTkk3VUVPbVRhS1k3amUxcUEyREkKLS0tIHViSHpNR2Jn
        RTdpZnlVdmI0aWhLc3FDdXVmT0RKQnIzT0E0R0xCeWpwYjAKeuQsWz0tsm9+WRQt
        afDSlC3uPGai6ac7E1nJYVpiN00a7v4VaKH/Q8+oc4E8doEgKyHAgED56jelkotY
        oa2tYg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqamR6d2lvK1pJaXRXUzhS
        T2p3SU9sWTVRbUMxK2w4Smx0d2xXZEZOZmprClJHVHZ4RzYvMzVnSGIwNi96cm1N
        eXp5RDNLM3pxNW1tVWcxNkpnamdiTTgKLS0tIExOdWIwMFhZODYxSGptTDcvOXM1
        V3BZMlgwWWQyUWl0cGhpRCtGenRyeHcKcG2rNMHG1F6qI2cniaWXKF/R1S+NHIPU
        WuKmO0zykmJ9c+jxYgkrBcdwlhU/9yxU5hkURaUErIwSW/OfU/L1TA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-17T16:22:07Z"
  mac: ENC[AES256_GCM,data:H43QAM14oJs4RH8LKXTQpfJKxpGT1Xz2Yz4dmyvCMRDupYNd2Qjhu4PUWOEFO96nUNr+ZIsS8VCIPJpnggo5Y0m2DM/t86rJeL5Qyb5L03K+uGct/Aw/vBq6x+efNrcgkTjviiCNVb84BeEbjFwQXKBG2WrXXAePVQ49RkA0F7k=,iv:8bf5a1Ns8s9lGs42jXYsZ2LYwO0w7dLCOiJR823lVqE=,tag:z+qS3W424RasyP3MgSNtfQ==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
