# ULA subnet: fdf6:9420:fade::/48
cluster:
  network:
    podSubnets:
      - 10.41.0.0/16
      - 2001:cafe:41::/56
    serviceSubnets:
      - 10.43.0.0/16
      - 2001:cafe:43::/112
  proxy:
    disabled: true
machine:
  network:
    # interfaces:
    #   - interface: lo
    #     addresses:
    #       # Workaround to allow CoreDNS to continue to work with hostDNS & BPF masquerading
    #       # https://github.com/siderolabs/talos/pull/9200#issuecomment-2805269653
    #       - 169.254.116.108/32
    nameservers:
      - 1.1.1.1
      - 9.9.9.9
    kubespan:
      enabled: false
    # enc!
    extraHostEntries:
      - ENC[AES256_GCM,data:mPcAM8nokp/7,iv:IxKDnM64MjlM9Ke/004FPZlNqOxeP45JLuOnxE3gKhk=,tag:61Qp0MJNf0raeuZ2oY5CeA==,type:comment]
      - ip: ENC[AES256_GCM,data:WADmwi6zpw9ZqeSsF3TkU2yIBE1PXQ==,iv:BaTjSORLlKBmlbnnATA2D1SYm6oRnTKvRoAoPF/20y4=,tag:9swX2PFxgbH4mzgqVzFp1A==,type:str]
        aliases:
          - ENC[AES256_GCM,data:vkVe4rQaFw1DPyEPI5U8bsNibSKN8QywNHo=,iv:EyMD21+ekcCM6RBwoRr/Fk/qPyASMS2kpSk+CKxURuA=,tag:LIN49Su3c2OAlK9py1TO2A==,type:str]
      - ip: ENC[AES256_GCM,data:wbjnv1cY6t99XttT,iv:WEau+dXDcRKZ42raT/WWV7OSyiwkQbYPWAJIN25rjvc=,tag:kZWESETPEs5JerkjMQRkpg==,type:str]
        aliases:
          - ENC[AES256_GCM,data:ChNYYdMpg71rIHl+ukLzpIwKHN8efhw2AQI=,iv:+emcW4USqxScBHcURADx5GQpScpO7aRL5n38vrpeyXw=,tag:GNgkJ/1XPOLTHLmhPZAdtQ==,type:str]
      - ip: ENC[AES256_GCM,data:/S5NICnHn3bhGhrb/egLwxtZMQ==,iv:HlpE8rm39K3nHBOi+wJ5i9a0OR4wt7ypQK7YAW8Nc0s=,tag:77nV3FWwMSI9MxCmxH2DoA==,type:str]
        aliases:
          - ENC[AES256_GCM,data:vvZ7ftmK+1yQNHO7363k8frYN3ulWxbZfWQ=,iv:jGT5j596q8wEvzvKDYBHBM8m8Chic7dVMmDczs6mTS8=,tag:h22YWd8oVZJuIF8GvjFXWw==,type:str]
          - ENC[AES256_GCM,data:5XJf5XS/OBh8fjuU8CdaGllqLQ==,iv:b6VhNFnlQiUR7GTF49V2qIBqm/EsdnzQft5lcAqeO74=,tag:JEfaaFKDb778ragleEXABA==,type:str]
      - ip: ENC[AES256_GCM,data:SwioiKenlf1mJbo=,iv:YM1Oa7hhEps/eSllSbwKPuqVIWklgdHz5sgbpxP2tsM=,tag:XRVh0afO5yM3qfLuSs63BA==,type:str]
        aliases:
          - ENC[AES256_GCM,data:9AXc4R/jb2rMAtrmgUU3CnD7adA8prXpTzI=,iv:MDnl0eJyhVDdsi/0mAYANNzOaH7GHcPK8n8QFcK07fI=,tag:CkEOr2PbVdBngJKhg1/EKA==,type:str]
          - ENC[AES256_GCM,data:WGjZQs2buhYH8T51t+g1hJsAlw==,iv:7JTwreIH5LX/5R7ULJI2kMkMmIZTyJdx70rMqvvcYvs=,tag:xJ6Ju3BfIDAK2dkJfYgLTA==,type:str]
      - ENC[AES256_GCM,data:ptd4F8Ej,iv:L6YQWhyTmbRaTjXRBd+ll1Z2lhSDYgosQj5pHDEhUk4=,tag:wwnPyVyLloIv8ymHppJNig==,type:comment]
      - ip: ENC[AES256_GCM,data:y3qOp5da+kBhaeRbQgmUYw6IsHqTEA==,iv:xpM1SHKE8v+EZ6r2ABDzcdXns3QZ4NJGeW0W5KlpD9o=,tag:Gx2yqPHCUezmbc38BRxauQ==,type:str]
        aliases:
          - ENC[AES256_GCM,data:XJIVInGylOX3efZdDM41Z82TX5PcBkKyIP0=,iv:XIgVx0Rkv3Vr0HBORdFGWUULoDep6MlHsPV5SHafDjc=,tag:iCoZ7vlm232wMDn0iyw/Sg==,type:str]
      - ip: ENC[AES256_GCM,data:Z5tZyrmh/u9rSTCWwVY=,iv:rReJFmpIrA3FR82Fb0yDxxFgSDIY6GwG8frAqqfGqRY=,tag:sCCNUHiLno0iXTICcTT+4Q==,type:str]
        aliases:
          - ENC[AES256_GCM,data:858pq89cPHm21aN+rs4qE0RsZhha+2AQvOg=,iv:JbURQhkXup0Ugo9OXdjPv34WhRQRmdwwXS2x4KAqyow=,tag:FkKnrcAosbVhpXtd/Ft+pQ==,type:str]
      - ip: ENC[AES256_GCM,data:CVINaduObOLm4KiarBBQbqjLyaQ=,iv:wZO/PQ3tkg5uKP2wHb9hdG+RznQnYUm9ZpqQCgfFuLI=,tag:SoHrbhIeUZZHYx9Vovqcdg==,type:str]
        aliases:
          - ENC[AES256_GCM,data:IM6rN9YDitz/PYv5EgtaPPGBcsE5RWQHPdg=,iv:vCvHyYLZOtwY0vn2gRvXQfVgY0lr8Cv0Dv1f9Um+1Zc=,tag:Rx8FauRpRA8nT3cX4iKmeQ==,type:str]
          - ENC[AES256_GCM,data:mhKVqa8SIzRpVWsWeaW4NA==,iv:NfhzcFHcAJlQT1e8MJj0gWyUY5VIlzakmxcd3a+9LQ0=,tag:VEjtst583mnkQEcl4NHWww==,type:str]
      - ip: ENC[AES256_GCM,data:MNN6bzI2smxAi2UpVA==,iv:6V3lWg1YlSbsxrdyRLaCeCw3YREylSrCoyNGhsTTN3c=,tag:LXgvJ/WyHKczP0lnWpGuaQ==,type:str]
        aliases:
          - ENC[AES256_GCM,data:xrOz7Lo0J37u98Q+6X45YVTYYGCJLytPSHI=,iv:adMYAwQPphOUGRPihc0W3U+GTPfnkuSllCqvsKgV7cI=,tag:xIm06ATYw4ZyNWVjW8pt9g==,type:str]
          - ENC[AES256_GCM,data:9n+6Tc6a1kgc+ZR1veWqtA==,iv:gRkSACKKhzQtJBr3bxXdqWPHpcCh4qrHPjms0eL9dcw=,tag:OU5GSE4RMqNL2L4c5zn+Sw==,type:str]
      - ENC[AES256_GCM,data:S8Qu5a0=,iv:j6tXW9BXTLD4Eg/4AxCRsz7d8ckJInO87e7YxF1mnsQ=,tag:KceF3lwlVUNbXsgTHIQJXQ==,type:comment]
      - ip: ENC[AES256_GCM,data:2ZIchNUtMfFH2MjtxVhKYs1KNvFr1g==,iv:Av0rzG9k5XO8JYCgzuQGXv2F2LeHhBfHc21fMKWzNEE=,tag:KaJyJAqfeDIQaFMYVlgKew==,type:str]
        aliases:
          - ENC[AES256_GCM,data:BoF49Z233RnZpT9Xfax+fcs+R/e16BmqWyI=,iv:0K98gPBbnAeMfe8DT5WbF3P8kKM652yQnfor6x4vNiU=,tag:2FE7cjdMK+MzIxmHB8AQQA==,type:str]
      - ip: ENC[AES256_GCM,data:Tv/ug/i2X4psyn9QmaY=,iv:l6lMy1RyOFsoS4V3DcTgpyIBNJAm8Ibn48bEbTnvVWY=,tag:p3LT5OffwzDn9LRr990aCA==,type:str]
        aliases:
          - ENC[AES256_GCM,data:Q/be5cGyVkk8v3J7yVSfQ4lOtqYq/rAJAGA=,iv:C997UzJ79rZKPx2OuZfcRUC/wvfbtHCRDb2U7B2I0/4=,tag:xXqkQg0FfP+tWVQLBm1KQg==,type:str]
      - ENC[AES256_GCM,data:Uw5pSuzPHEE=,iv:UlFz5VFfnx2jlIfTvYRwCuDGaRNvhEKIyGo7cMa4BBQ=,tag:rOZjeKXW9IkIbac3jVGWLw==,type:comment]
      - ip: ENC[AES256_GCM,data:B6SgSN1aBgNwTXxXk5w=,iv:1aQY4D+kHl9nvt0S2aRlYW1ahDIb2FB3XOGGZZcxGjw=,tag:NamxeSl9NDOWMhDeGJx1Xg==,type:str]
        aliases:
          - ENC[AES256_GCM,data:+1+mR8AAFovqkCUknJum/X8h,iv:edzoF03uxXIMCoaMFHC4DjuKWtqHJqS7JbwAz8UucRk=,tag:Y5VshmQ5HbiHOSjpl3Obiw==,type:str]
  sysctls:
    # 128MiB
    vm.min_free_kbytes: 131072
    vm.watermark_scale_factor: 50
    fs.inotify.max_user_watches: 4194304
    fs.inotify.max_user_instances: 65536
    user.max_user_namespaces: 65536
    net.ipv4.ip_forward: 1
    net.ipv6.conf.all.forwarding: 1
    # https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes
    net.core.rmem_max: 7500000
    net.core.wmem_max: 7500000
  kubelet:
    nodeIP:
      validSubnets:
        - 10.67.0.0/24
        - fdf6:9420:fade:67::/64
    extraArgs:
      rotate-server-certificates: true
    extraMounts:
      - destination: /var/lib/longhorn
        type: bind
        source: /var/lib/longhorn
        options:
          - bind
          - rshared
          - rw
      - destination: /var/lib/garage
        type: bind
        source: /var/lib/garage
        options:
          - bind
          - rshared
          - rw
      - destination: /var/lib/local-path-provisioner
        type: bind
        source: /var/lib/local-path-provisioner
        options:
          - bind
          - rshared
          - rw
    extraConfig:
      # kubelet serving certs
      serverTLSBootstrap: true
      memorySwap:
        swapBehavior: LimitedSwap
  features:
    # rbac: true
    # stableHostname: true
    # apidCheckExtKeyUsage: true
    hostDNS:
      resolveMemberNames: true
  nodeLabels:
    hugeloads.sophons.cloud/longhorn: "true"
    hugeloads.sophons.cloud/postgres: "true"
# ---
# # The default expression is too trigger happy and _causes_ issues by shooting
# # perfectly fine containers in the head
# apiVersion: v1alpha1
# kind: OOMConfig
# triggerExpression: "false"
# cgroupRankingExpression: "0.0"
# sampleInterval: 5s
# ---
# apiVersion: v1alpha1
# kind: ZswapConfig
# # The maximum percent of memory that zswap can use.
# maxPoolPercent: 25
# # Enable the shrinker feature: kernel might move
# shrinkerEnabled: true
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBES0Rl
        L2RiR1hvRjh2Y1VJQmFDazlxc0Q0aWpoWU53SnRmQUxxaHBRdkVzCnpwWStrNGxl
        SHRDdVFWaWJhbGdHSmgvcDlFb3BqdVV1TmFQKzZpU09VeVEKLS0tIEhBVXBRU0xX
        dVZ0TkpGcXd0bjZkWWNiWUJwOE9YczRGVGhLVmhLZDBwamcKt8ZXQFnyOUAbu1ct
        riyVvL03ooT0DTXZMfLxkXn9pGsSsvl+i1Kqwd7woJokLOczP61TcwosKOSVesKW
        2YeSMQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArL0dCdzJFQUd1RUg2dVEv
        bjhCa0t1RklCOTRJY21TM29jQllOMTlMMVRZCjBnZVBNdjU5YzZ2M1FzbTdWR2pS
        bVdBaTJMWXlUOCsrbStEa05SR3J5QVkKLS0tIEQ2cVkyU0pXWEFDNTMyWlNIZE9j
        VmEvVEptZXc2TmRESjFSTW10QkZPMVkKhTa5cdBaD3qYIeZarhJoqEV+NFa/DNLS
        yfT+GT7bKGdpFv56xv+txhQZPpTu8Dg+WJlbCdc+WV82ASnV5LhPiQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T09:18:08Z"
  mac: ENC[AES256_GCM,data:ezMfdgo8UI2qdRwrD33wryf/XNbPm+5o3ofj/c0dK+zBCh4X451SPmzpRhrrrflIXVTcGXcHpBhHyfR9ogTx1AwhE2cknyxh1P2OPZq9rLjgD+c0CBetLfx+KJLTp/rXPoU0fp778R6L7wDAesb02EqvfevWYLvGHYRWT3vQ5RI=,iv:fqxICg1wo/cspcNO9GSEC/jk8ehVCAMOPqb05CPu4R8=,tag:J+mCDk70n72Bvd726aSmPQ==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: ExtensionServiceConfig
name: cloudflared
environment:
  # enc!
  - ENC[AES256_GCM,data:bzzVABN4vek75XO81tnfXgNJ91f+9HdoCaDOQp+x+K8dhQ0Kb6JgwP+CY/1w+U+nfKVv6my0ellJ+3xLrE//UHPEW/UBTLYXaneIq3Fix+Omwmc+XgEMOhZA3n5V0IEWxtBmIsCb7CEaBKhr0llIh7Cyy9YimNP3y0YZy1AkPv5Nv2DrNZlbGa3BqXHXU//FBBMiuf56/m5Mjfgq2c8R5xXmY6k2cnHX+CrrGza0mim0IBC19XgxmU7EngLzzCIHn1EoPN0=,iv:1d6vXch3o+clh3zmUQ2bmFVAIAQS1pnlp86UmnQxrfw=,tag:Mo1CbFU5ezds3PCRlxA3Yg==,type:str]
  - TUNNEL_METRICS=localhost:2000
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBES0Rl
        L2RiR1hvRjh2Y1VJQmFDazlxc0Q0aWpoWU53SnRmQUxxaHBRdkVzCnpwWStrNGxl
        SHRDdVFWaWJhbGdHSmgvcDlFb3BqdVV1TmFQKzZpU09VeVEKLS0tIEhBVXBRU0xX
        dVZ0TkpGcXd0bjZkWWNiWUJwOE9YczRGVGhLVmhLZDBwamcKt8ZXQFnyOUAbu1ct
        riyVvL03ooT0DTXZMfLxkXn9pGsSsvl+i1Kqwd7woJokLOczP61TcwosKOSVesKW
        2YeSMQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArL0dCdzJFQUd1RUg2dVEv
        bjhCa0t1RklCOTRJY21TM29jQllOMTlMMVRZCjBnZVBNdjU5YzZ2M1FzbTdWR2pS
        bVdBaTJMWXlUOCsrbStEa05SR3J5QVkKLS0tIEQ2cVkyU0pXWEFDNTMyWlNIZE9j
        VmEvVEptZXc2TmRESjFSTW10QkZPMVkKhTa5cdBaD3qYIeZarhJoqEV+NFa/DNLS
        yfT+GT7bKGdpFv56xv+txhQZPpTu8Dg+WJlbCdc+WV82ASnV5LhPiQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T09:18:08Z"
  mac: ENC[AES256_GCM,data:ezMfdgo8UI2qdRwrD33wryf/XNbPm+5o3ofj/c0dK+zBCh4X451SPmzpRhrrrflIXVTcGXcHpBhHyfR9ogTx1AwhE2cknyxh1P2OPZq9rLjgD+c0CBetLfx+KJLTp/rXPoU0fp778R6L7wDAesb02EqvfevWYLvGHYRWT3vQ5RI=,iv:fqxICg1wo/cspcNO9GSEC/jk8ehVCAMOPqb05CPu4R8=,tag:J+mCDk70n72Bvd726aSmPQ==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: ExtensionServiceConfig
name: tailscale
environment:
  # enc!
  - ENC[AES256_GCM,data:zAgMb+JWPh04cVPnkQLjsoBH754v/2rvB7Ec1AU1+LeYERfSShFmy7XygGummSoVyGqW9iLofxuUszU=,iv:DsagjZQDdxFP2wMjaoeHUfdBfi+AmyOTFumspx76zGM=,tag:ny+ufTRkxmO0TwLuYKoybQ==,type:str]
  - TS_EXTRA_ARGS=--login-server=https://hs.vrtx.sh --ssh --accept-routes=true --snat-subnet-routes=false
  # need to toggle this to "false" for changes to ^ to apply, containerboot doesn't consider TS_EXTRA_ARGS
  # when running tailscale set:
  # https://github.com/tailscale/tailscale/blob/f36eb81e6105401b814548393cc90673abe24639/cmd/containerboot/tailscaled.go#L149
  - TS_AUTH_ONCE=true
  - TS_ROUTES=
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBES0Rl
        L2RiR1hvRjh2Y1VJQmFDazlxc0Q0aWpoWU53SnRmQUxxaHBRdkVzCnpwWStrNGxl
        SHRDdVFWaWJhbGdHSmgvcDlFb3BqdVV1TmFQKzZpU09VeVEKLS0tIEhBVXBRU0xX
        dVZ0TkpGcXd0bjZkWWNiWUJwOE9YczRGVGhLVmhLZDBwamcKt8ZXQFnyOUAbu1ct
        riyVvL03ooT0DTXZMfLxkXn9pGsSsvl+i1Kqwd7woJokLOczP61TcwosKOSVesKW
        2YeSMQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArL0dCdzJFQUd1RUg2dVEv
        bjhCa0t1RklCOTRJY21TM29jQllOMTlMMVRZCjBnZVBNdjU5YzZ2M1FzbTdWR2pS
        bVdBaTJMWXlUOCsrbStEa05SR3J5QVkKLS0tIEQ2cVkyU0pXWEFDNTMyWlNIZE9j
        VmEvVEptZXc2TmRESjFSTW10QkZPMVkKhTa5cdBaD3qYIeZarhJoqEV+NFa/DNLS
        yfT+GT7bKGdpFv56xv+txhQZPpTu8Dg+WJlbCdc+WV82ASnV5LhPiQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T09:18:08Z"
  mac: ENC[AES256_GCM,data:ezMfdgo8UI2qdRwrD33wryf/XNbPm+5o3ofj/c0dK+zBCh4X451SPmzpRhrrrflIXVTcGXcHpBhHyfR9ogTx1AwhE2cknyxh1P2OPZq9rLjgD+c0CBetLfx+KJLTp/rXPoU0fp778R6L7wDAesb02EqvfevWYLvGHYRWT3vQ5RI=,iv:fqxICg1wo/cspcNO9GSEC/jk8ehVCAMOPqb05CPu4R8=,tag:J+mCDk70n72Bvd726aSmPQ==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: WireguardConfig
name: wg.dbg
# publicKey: HPMKzZDRqD9BJ6pFo7SiT8IybLr3MgJ2bttVxhyJbFY=
# enc!
privateKey: ENC[AES256_GCM,data:epuwunm6baSj7mNNvoxOHig7dL0T46u0W5S0dRyDeahUo4xQh4JUMadfJyk=,iv:HbC1NQZeVCWBFEKYGDZWMJ5b71AnqHVf+XWrjCeiVFE=,tag:H75ZQCONA/yeIFMGgIIogQ==,type:str]
listenPort: 51867
up: true
peers:
  # a single peer can connect over this interface
  - publicKey: sk0z4CeJ0y9Io73y4Ss8gqE31VKzjDl74aursOOz/Us=
    allowedIPs:
      - fdf6:9420:fade:ffff::fffe/128
    persistentKeepaliveInterval: 5s
addresses:
  - address: fdf6:9420:fade:ffff::ffff/128
routes:
  - destination: fdf6:9420:fade:ffff::fffe/128
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBES0Rl
        L2RiR1hvRjh2Y1VJQmFDazlxc0Q0aWpoWU53SnRmQUxxaHBRdkVzCnpwWStrNGxl
        SHRDdVFWaWJhbGdHSmgvcDlFb3BqdVV1TmFQKzZpU09VeVEKLS0tIEhBVXBRU0xX
        dVZ0TkpGcXd0bjZkWWNiWUJwOE9YczRGVGhLVmhLZDBwamcKt8ZXQFnyOUAbu1ct
        riyVvL03ooT0DTXZMfLxkXn9pGsSsvl+i1Kqwd7woJokLOczP61TcwosKOSVesKW
        2YeSMQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArL0dCdzJFQUd1RUg2dVEv
        bjhCa0t1RklCOTRJY21TM29jQllOMTlMMVRZCjBnZVBNdjU5YzZ2M1FzbTdWR2pS
        bVdBaTJMWXlUOCsrbStEa05SR3J5QVkKLS0tIEQ2cVkyU0pXWEFDNTMyWlNIZE9j
        VmEvVEptZXc2TmRESjFSTW10QkZPMVkKhTa5cdBaD3qYIeZarhJoqEV+NFa/DNLS
        yfT+GT7bKGdpFv56xv+txhQZPpTu8Dg+WJlbCdc+WV82ASnV5LhPiQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T09:18:08Z"
  mac: ENC[AES256_GCM,data:ezMfdgo8UI2qdRwrD33wryf/XNbPm+5o3ofj/c0dK+zBCh4X451SPmzpRhrrrflIXVTcGXcHpBhHyfR9ogTx1AwhE2cknyxh1P2OPZq9rLjgD+c0CBetLfx+KJLTp/rXPoU0fp778R6L7wDAesb02EqvfevWYLvGHYRWT3vQ5RI=,iv:fqxICg1wo/cspcNO9GSEC/jk8ehVCAMOPqb05CPu4R8=,tag:J+mCDk70n72Bvd726aSmPQ==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
