cluster:
  discovery:
    enabled: true
    registries:
      # Kubernetes registry is problematic with KubeSpan, if the control plane endpoint is routeable itself via KubeSpan.
      kubernetes:
        disabled: true
      service: {}
  network:
    podSubnets:
      - 10.41.0.0/16
      - 2001:cafe:41::/56
    serviceSubnets:
      - 10.43.0.0/16
      - 2001:cafe:43::/112
  proxy:
    disabled: true
machine:
  network:
    kubespan:
      enabled: true
      advertiseKubernetesNetworks: true
    # enc!
    extraHostEntries:
      - ip: ENC[AES256_GCM,data:htnpX8+339Np7cSKsi6p7xFZpzg=,iv:fhoQ852IEbZcQVwZWfT14x3qtN18d85dP6v0XA/VTLM=,tag:Xzk81InShd7fJrQerLAHWw==,type:str]
        aliases:
          - ENC[AES256_GCM,data:8276h83cD0tLBvPxCd2/ofwBaZreOpyXkLP/gI9NDw==,iv:f/PGheqlcv85WuQ2+c2xBdSWw50IhS28LKaepilu0jQ=,tag:6rNDLR4pwDSi5YV91XfTlg==,type:str]
      - ip: ENC[AES256_GCM,data:Lq8p6CJSTBUaPENgdViX3SFQq6Az3ZRq,iv:NaNun/0/RmK4wrhDua4idB+BD1APQHDYIHCE236Lthw=,tag:gMbyt8x99NbReGpWMr9MJQ==,type:str]
        aliases:
          - ENC[AES256_GCM,data:Cul30Ypgs4RKFb5ShC0tSj5sfbTPM5hLJkt+k9JwlQ==,iv:zboEuNpiF0o9h1v4bME2TUDXzRA6uSO+KELRezB97bs=,tag:+n0IZltfpdw7pHlV7If3Tg==,type:str]
      - ip: ENC[AES256_GCM,data:0KLDid8pb+jFYC/Ukr39C2K5Zq2TmMbc,iv:B+eEDT55hBQNPNnHOfs64t0EoxY71FHN7sIDiO4Uflg=,tag:sFC75MwBImCGZFo62oSBRw==,type:str]
        aliases:
          - ENC[AES256_GCM,data:k7VtuLIS932qvy3U6KGFHJwGUWX0ZDORT5J+Kglfrg==,iv:MpXSz0rndCZNujxJTkkM8Okvkd3cOJAGjkrkika46IA=,tag:t1jQQqIDXLierbUVY8+5EQ==,type:str]
      - ip: ENC[AES256_GCM,data:o/uFywssalos,iv:q4CA3zdSA7mOoiCbVHmeUC5czWaLJjZL3ja8q3EzAw0=,tag:gvMBkvp2aAMMK0/8aZyR7Q==,type:str]
        aliases:
          - ENC[AES256_GCM,data:POKttgx/SLl2nXcn/9zAE68LlQNGo+iwz47rQvoVxg==,iv:yltZgOV1ExJTlxP1m+N8BWnNdtejkiYmUCwJ0tPbWVM=,tag:FBpBWO0/8SnMdrI4c9t03w==,type:str]
      - ip: ENC[AES256_GCM,data:VzU5UqMSPzcW,iv:itWIfBqVJP+PKmlqD1OG39djadi7fPkVGC8yqXpj02Y=,tag:qIv9ltM66l39mI0z1XrmqQ==,type:str]
        aliases:
          - ENC[AES256_GCM,data:DDdZy0Npbm4nQGlY5HgNXwyVXqRVTSm50QnPzoGGPg==,iv:kGiHfsn192CnK+VsgOGE8k5p1PgxgrM+Z1tMw4tTh/U=,tag:4mOhbF+X1W3kqjq4qDJz0w==,type:str]
      - ip: ENC[AES256_GCM,data:1SOA6pbl68L8kqzleA==,iv:T4wfakVghj1vSQ0YVtBDC38ySh7twQQT1SVrWCbOnfE=,tag:wtaESiN7BeofaW5Vcrkcmw==,type:str]
        aliases:
          - ENC[AES256_GCM,data:ke/L5+YIV4Vjmt8D42dkNtqInZ5pvPRkbHubaIaGTQ==,iv:N0zOFYGn8MyWLWnLQ5TEud9jubLRpFJvUS8HA9/AcDg=,tag:AfkmDXmmado0NWVaHksnNg==,type:str]
  sysctls:
    # 128MiB
    vm.min_free_kbytes: 131072
    vm.watermark_scale_factor: 50
    fs.inotify.max_user_watches: 4194304
    fs.inotify.max_user_instances: 65536
  kubelet:
    extraArgs:
      rotate-server-certificates: true
    extraMounts:
      - destination: /var/lib/longhorn
        type: bind
        source: /var/lib/longhorn
        options:
          - bind
          - rshared
          - rw
    extraConfig:
      # kubelet serving certs
      serverTLSBootstrap: true
      memorySwap:
        swapBehavior: LimitedSwap
  features:
    hostDNS:
      resolveMemberNames: true
  nodeLabels:
    hugeloads.sophons.cloud/longhorn: "true"
    hugeloads.sophons.cloud/postgres: "true"
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBlNjJP
        K2FkZjljTnVpaTQ5SFA4WXpNWUpsSzd4Q0RLZFpBWFRkdENZalI4CkVvSXkzd0xV
        aGJsdCt5eVhjVmV6WGc4anZDTnpuemcrc2RvZUpBYWxQbkUKLS0tIEdGZ0Z0VEc4
        TjZ5V1c0blo2SkdpWnh6RXd6SkRJQWJjQU9tMDZ3Vkpmd2sK/gmIWF1YnbV4amyI
        +PJNOY88VkNnu2Tk24y3EKECnmQ+rqv/xakqaBmhuz8qNIA9T2N+il0RvVA24cPs
        0MVmRQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHaXhnbVVud0RlMjRLV1ZQ
        UEZLdTRDcHBHUHNJMUwzZlB5bktIbmI2cG5jCjBPT3lzeW9pUnBrdHlPM3ZxR0h3
        dHg3UEFqTVRFK20yQlR3RmNlVW03Y00KLS0tIDBqYW5FMTZVU1BNU3ZiWml1UGpX
        QUdwWWd3N0JIbHd0eW1zMDZ6L2FoSHMKUTt1L5MiM8+BkfaGH+qOa1qgUevY6ilD
        r3WuoaR9haYE1xgpal53rm2HsQ3eDR21+HD8kSVXzr1wMvvc4lS0gQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-13T02:38:47Z"
  mac: ENC[AES256_GCM,data:KicysaMMA9saoZw8q4Mi3EVAGCgs4FoHoJ/kjTcrlcI+K1JDBHuGlt747ACeWKdvrtW6L41/7jB6pETRdURq4teEZl+fCEOgxmM1YHUzVkxFz5fsQ1DaiKkGDQvCNcqZ9nzwdLzHDdMTuMl1nPOAQiFIs2mf880/RbH7+4ZnWY4=,iv:k3SoG2ewCtXKUhA6XequoiPmeYn/se051iHiK1Lt0Js=,tag:s3hGJ201Yi5YzWHCnI1KFA==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: ZswapConfig
# The maximum percent of memory that zswap can use.
maxPoolPercent: 25
# Enable the shrinker feature: kernel might move
shrinkerEnabled: true
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBlNjJP
        K2FkZjljTnVpaTQ5SFA4WXpNWUpsSzd4Q0RLZFpBWFRkdENZalI4CkVvSXkzd0xV
        aGJsdCt5eVhjVmV6WGc4anZDTnpuemcrc2RvZUpBYWxQbkUKLS0tIEdGZ0Z0VEc4
        TjZ5V1c0blo2SkdpWnh6RXd6SkRJQWJjQU9tMDZ3Vkpmd2sK/gmIWF1YnbV4amyI
        +PJNOY88VkNnu2Tk24y3EKECnmQ+rqv/xakqaBmhuz8qNIA9T2N+il0RvVA24cPs
        0MVmRQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHaXhnbVVud0RlMjRLV1ZQ
        UEZLdTRDcHBHUHNJMUwzZlB5bktIbmI2cG5jCjBPT3lzeW9pUnBrdHlPM3ZxR0h3
        dHg3UEFqTVRFK20yQlR3RmNlVW03Y00KLS0tIDBqYW5FMTZVU1BNU3ZiWml1UGpX
        QUdwWWd3N0JIbHd0eW1zMDZ6L2FoSHMKUTt1L5MiM8+BkfaGH+qOa1qgUevY6ilD
        r3WuoaR9haYE1xgpal53rm2HsQ3eDR21+HD8kSVXzr1wMvvc4lS0gQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-13T02:38:47Z"
  mac: ENC[AES256_GCM,data:KicysaMMA9saoZw8q4Mi3EVAGCgs4FoHoJ/kjTcrlcI+K1JDBHuGlt747ACeWKdvrtW6L41/7jB6pETRdURq4teEZl+fCEOgxmM1YHUzVkxFz5fsQ1DaiKkGDQvCNcqZ9nzwdLzHDdMTuMl1nPOAQiFIs2mf880/RbH7+4ZnWY4=,iv:k3SoG2ewCtXKUhA6XequoiPmeYn/se051iHiK1Lt0Js=,tag:s3hGJ201Yi5YzWHCnI1KFA==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: ExtensionServiceConfig
name: cloudflared
environment:
  # enc!
  - ENC[AES256_GCM,data:Z4aAyOyFDEayCtMlJuTUyULDICL5twzDra+hEPme3tfBoycfynm322s/O2TTThyV2a7bpPElx/1bRsPHw3byp0loRnpVuLgx/R8kvNMLFFkCzsxHWF2YelHT8q1SSGlTbxNbjiczSUPkSKAXV7mTz1PxT5yvCOZI3fYEAmTODONJXrV5P8Y5Zn9CLqNFV58pzqK7XRNMquYzFA/LopHMswt44sohf0tygGhsIkHyOtvdj4/flX9p8MXDhyRP7JD6kbMn/hg=,iv:nZrlxWG1dsWp2/eW6Vy//Gq8Ip0S16sBFOOxQInal3w=,tag:QfNTKdkk1iDrFgYE+CKudA==,type:str]
  - TUNNEL_METRICS=localhost:2000
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBlNjJP
        K2FkZjljTnVpaTQ5SFA4WXpNWUpsSzd4Q0RLZFpBWFRkdENZalI4CkVvSXkzd0xV
        aGJsdCt5eVhjVmV6WGc4anZDTnpuemcrc2RvZUpBYWxQbkUKLS0tIEdGZ0Z0VEc4
        TjZ5V1c0blo2SkdpWnh6RXd6SkRJQWJjQU9tMDZ3Vkpmd2sK/gmIWF1YnbV4amyI
        +PJNOY88VkNnu2Tk24y3EKECnmQ+rqv/xakqaBmhuz8qNIA9T2N+il0RvVA24cPs
        0MVmRQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHaXhnbVVud0RlMjRLV1ZQ
        UEZLdTRDcHBHUHNJMUwzZlB5bktIbmI2cG5jCjBPT3lzeW9pUnBrdHlPM3ZxR0h3
        dHg3UEFqTVRFK20yQlR3RmNlVW03Y00KLS0tIDBqYW5FMTZVU1BNU3ZiWml1UGpX
        QUdwWWd3N0JIbHd0eW1zMDZ6L2FoSHMKUTt1L5MiM8+BkfaGH+qOa1qgUevY6ilD
        r3WuoaR9haYE1xgpal53rm2HsQ3eDR21+HD8kSVXzr1wMvvc4lS0gQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-13T02:38:47Z"
  mac: ENC[AES256_GCM,data:KicysaMMA9saoZw8q4Mi3EVAGCgs4FoHoJ/kjTcrlcI+K1JDBHuGlt747ACeWKdvrtW6L41/7jB6pETRdURq4teEZl+fCEOgxmM1YHUzVkxFz5fsQ1DaiKkGDQvCNcqZ9nzwdLzHDdMTuMl1nPOAQiFIs2mf880/RbH7+4ZnWY4=,iv:k3SoG2ewCtXKUhA6XequoiPmeYn/se051iHiK1Lt0Js=,tag:s3hGJ201Yi5YzWHCnI1KFA==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
