cluster:
  network:
    podSubnets:
      - 10.41.0.0/16
      - 2001:cafe:41::/56
    serviceSubnets:
      - 10.43.0.0/16
      - 2001:cafe:43::/112
  proxy:
    disabled: true
machine:
  network:
    kubespan:
      enabled: false
    # enc!
    extraHostEntries:
      - ENC[AES256_GCM,data:RCOyi/oZ,iv:ZUqn9usdLU6H8dI0Y+pN/JP2dX+FYanSAVwZtkMS53c=,tag:OVeWmhe55WE150UcpV42Dw==,type:comment]
      - ip: ENC[AES256_GCM,data:Wy0Oi8oyZiYd2uwlR44=,iv:EyT1Y4i5QKdpYsNguuS/BI0IYDuvN2wqIJoFqT6P+Fk=,tag:nSP6kaHY0lUclwOVPADQ7A==,type:str]
        aliases:
          - ENC[AES256_GCM,data:UUN4C+9QxlnzKGoumUng6bBII9KxH7I2MBo=,iv:4jKTMNkYBfnyBboBNLwrI5cbesyPc5pCTsiVogt26N4=,tag:0ZthALwT1/gzERauptgM0A==,type:str]
      - ip: ENC[AES256_GCM,data:vOe8oRZLJoNEgq0V8G0T3R7Q3K8=,iv:+ZA7EL5QK9SfM26sRS/mnuXIf1g2zyfw6V8QyOkDbmk=,tag:G9wghQHxT/BIWvuseaQP+g==,type:str]
        aliases:
          - ENC[AES256_GCM,data:+rC/Fimdru9/QpZEc0YEOFHbvc1gsb3qQDE=,iv:c354a2ayYMhN+Rowa0BbBW9WnX+Du6PtcRx5BhbHk8o=,tag:9UzQB+/edmGekq5ai5L/5g==,type:str]
      - ip: ENC[AES256_GCM,data:B5CPfVaFqaeRNZfXKQ==,iv:p9yqlkULFVvhR/qgS3q04jcUWXN4idsDnwPgpeFZyXU=,tag:ZYDnAa5ZW6xo/iJBaTLdlw==,type:str]
        aliases:
          - ENC[AES256_GCM,data:pzRiTlPCrnOAGfoZXivoVhheHT2lkp+Jrlc=,iv:K2ljcGLJUr4LXFj3qqz9SYNQEEx1PAc+WM2wAFDjiNs=,tag:cuZA9XTcYlXaVdOrqXiFuw==,type:str]
      - ENC[AES256_GCM,data:ANkH6C4=,iv:BE9Zpf1EhAny53ksps8o2qRM1K1A1d2apNCnZFxwz5w=,tag:FKw9ZZixcOq5XZ+xxH2dsg==,type:comment]
      - ip: ENC[AES256_GCM,data:yCFFXi4uLY/f3speRzA=,iv:R7I1cFw97xMVJVz6v9X66f+NFtDeCrMA3QXzLaSwfMM=,tag:XaRmHUcZ6RMRMlQST7+WZw==,type:str]
        aliases:
          - ENC[AES256_GCM,data:DVpVgFm4iRXkPY4AFkunegX2/QyqYMUe2mw=,iv:Q5Fd0FOn/V8FYnEH58PC5Q+ABRFT1WOOqhV7JR1Xz9M=,tag:bYJXvGzs0MeXf9kZ+gSizw==,type:str]
      - ip: ENC[AES256_GCM,data:uVi10pYhSLdi3IkAVpZBJ0tWWfhlrtwo,iv:zU0TcRYirhpF9/ODO5Xs7aBpeIurNgg061GIJSEhN20=,tag:4EJcTD+TbCozPbBmsjJEIA==,type:str]
        aliases:
          - ENC[AES256_GCM,data:yrDLXhlrFguJduG/8NZeBOZAEAKr/s/0y4g=,iv:SuIbGyYZhc6y5t4xq1kBuhNM/dfNEOmn1DZyCVhSvkA=,tag:KLThQEkw6be6IW7PhjKUsQ==,type:str]
      - ENC[AES256_GCM,data:+SVkqVI=,iv:V/jhchibf4MDRjizg9BrRsUyIN4+kfETFXw5eTm8/SQ=,tag:w2dipcsoInnupN29tVZkWw==,type:comment]
      - ip: ENC[AES256_GCM,data:qS1Gvii4Y5mjBTWkgQ==,iv:V5GQdTiK5DGh+PwhGo/P15doyRsifg1NLbXRJjrn8II=,tag:DWdypC1MrWTUIyn7t7td6g==,type:str]
        aliases:
          - ENC[AES256_GCM,data:fbqEfh10PGoAhoHHvkZjZj8ggHgbm5YB8zo=,iv:7Nr4qvwH+KdHlooATW5x78k0hc+Av025ynab+MtL5jo=,tag:qgWZeLNZ9zqqL4hEyx+NYA==,type:str]
      - ip: ENC[AES256_GCM,data:hdFt/CCWKR/1nN3jDyq7flGXOT7GcKqx,iv:s1L/Mx6UDxIxqKED1upymJf6KW6AE+4XdXIwksd5pzo=,tag:HNU7A+XheD8bcji5COiMSA==,type:str]
        aliases:
          - ENC[AES256_GCM,data:ONZWbeLZsaB5tVz7DKtNYRrrCVZfsA7skrM=,iv:GYtXaJi8vU+eNmIy314qrLYkrEuxlbm9lZ4k2jCUuns=,tag:jHyCSD2pMKLfeT2aIJaMiA==,type:str]
  sysctls:
    # 128MiB
    vm.min_free_kbytes: 131072
    vm.watermark_scale_factor: 50
    fs.inotify.max_user_watches: 4194304
    fs.inotify.max_user_instances: 65536
    user.max_user_namespaces: 65536
    net.ipv4.ip_forward: 1
    net.ipv6.conf.all.forwarding: 1
  kubelet:
    nodeIP:
      validSubnets:
        - 100.64.0.0/10
        - fd7a:115c:a1e0::/48
    extraArgs:
      rotate-server-certificates: true
    extraMounts:
      - destination: /var/lib/longhorn
        type: bind
        source: /var/lib/longhorn
        options:
          - bind
          - rshared
          - rw
    extraConfig:
      # kubelet serving certs
      serverTLSBootstrap: true
      memorySwap:
        swapBehavior: LimitedSwap
  features:
    hostDNS:
      resolveMemberNames: true
  nodeLabels:
    hugeloads.sophons.cloud/longhorn: "true"
    hugeloads.sophons.cloud/postgres: "true"
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBROHU3
        dUNjNy9wbk5icHV6NmNoMjBiTkdIZEF2bXJaclpSUkVVSFZDT3k4CnNoV01tMERq
        NW1McS81VWJZMkVHSVVmQS8vTU1lL3RBM0hOQzdVaG5DaGsKLS0tIE9pQXlXa2c5
        aTVla3RwUGVZcTBodnpSbHFFRkRUNlhkL1JVaytvL1kxR28KzIJrvKxwCU/7+oll
        oAUGgBjK+/LkZrB1wj8bu1G2s6HEm6PAjkY4e+a+NS0WTz+Gy+m0dDIrVmzVKnc7
        gATS0Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabHNHQ3JoYTNnNUlicVkr
        dUxMdFpFeEdBMysvNE9hb3A5ZXhmd2lMYTJZCjlBSlFYalNHMzhpb0c0aGczTHhM
        VVRKSUNTeGJWYXRsYlhDa2dEMkU2bUkKLS0tICtlUVlvWVZ2cnEzekdvV2cvSnAz
        ZGV1dmJvMWFaSXhZZndwM2djcGFYMU0Kpp8fliMmZhWgpJJXmG2q1uqpaXvRR/j3
        TTxvYaDTMZcAHbGeV06EFE43Y8s0/raKFab/SyQNBwyNHuB7i/xZFA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-29T15:32:59Z"
  mac: ENC[AES256_GCM,data:KOI6daydWBwVMEJ90E3TT92H/pVf47hA0PqEvc/NcVNE66ehBhfeWSwwA0ZuQ4LNZQCDws/FQ9dPQAu9DdSSRgi+U2eSwvbX0r8y23+X5wGhtGt/3ThViyfM+3tg27p7BJrgUhXosD4n4TtTDABGd3FoZ69nlcPUnX9+HRWAtck=,iv:18Dyby46Vtr15JF5yBXwxv06lMdPFa4j6AeHsdwu0Iw=,tag:2pOD6m3IgBBEJzfiPOy6Mw==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: ZswapConfig
# The maximum percent of memory that zswap can use.
maxPoolPercent: 25
# Enable the shrinker feature: kernel might move
shrinkerEnabled: true
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBROHU3
        dUNjNy9wbk5icHV6NmNoMjBiTkdIZEF2bXJaclpSUkVVSFZDT3k4CnNoV01tMERq
        NW1McS81VWJZMkVHSVVmQS8vTU1lL3RBM0hOQzdVaG5DaGsKLS0tIE9pQXlXa2c5
        aTVla3RwUGVZcTBodnpSbHFFRkRUNlhkL1JVaytvL1kxR28KzIJrvKxwCU/7+oll
        oAUGgBjK+/LkZrB1wj8bu1G2s6HEm6PAjkY4e+a+NS0WTz+Gy+m0dDIrVmzVKnc7
        gATS0Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabHNHQ3JoYTNnNUlicVkr
        dUxMdFpFeEdBMysvNE9hb3A5ZXhmd2lMYTJZCjlBSlFYalNHMzhpb0c0aGczTHhM
        VVRKSUNTeGJWYXRsYlhDa2dEMkU2bUkKLS0tICtlUVlvWVZ2cnEzekdvV2cvSnAz
        ZGV1dmJvMWFaSXhZZndwM2djcGFYMU0Kpp8fliMmZhWgpJJXmG2q1uqpaXvRR/j3
        TTxvYaDTMZcAHbGeV06EFE43Y8s0/raKFab/SyQNBwyNHuB7i/xZFA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-29T15:32:59Z"
  mac: ENC[AES256_GCM,data:KOI6daydWBwVMEJ90E3TT92H/pVf47hA0PqEvc/NcVNE66ehBhfeWSwwA0ZuQ4LNZQCDws/FQ9dPQAu9DdSSRgi+U2eSwvbX0r8y23+X5wGhtGt/3ThViyfM+3tg27p7BJrgUhXosD4n4TtTDABGd3FoZ69nlcPUnX9+HRWAtck=,iv:18Dyby46Vtr15JF5yBXwxv06lMdPFa4j6AeHsdwu0Iw=,tag:2pOD6m3IgBBEJzfiPOy6Mw==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: ExtensionServiceConfig
name: cloudflared
environment:
  # enc!
  - ENC[AES256_GCM,data:hCbcvvtkw4kCU9W9QgRk7THnakr9owPPV9zujn2PqI0i3wLhrndwIFNawKs0N4PH32KB+WM8h/GVsJvdf28TU7fAILLJPJ31fRDE8ekguJDUH+fgrFgOzSGNlzyFwodET594vLDXli7za25rCMayuGID3ww6MkIe96L1bDGi+gto3uc5kulNjif5MnRXZUqd0GF9jw9+MuSDk4w2oQAzeKN7WQGP1kIWmXdQnnZKfRL3fnSYRpgUGs2Yf5cut44HvURyhzI=,iv:KxqNGA2gQOZAhnZCeQZYfzThsXm7Et+47FKE0l0JhGE=,tag:GJ+qJaDqGizrVZNDkVyWdA==,type:str]
  - TUNNEL_METRICS=localhost:2000
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBROHU3
        dUNjNy9wbk5icHV6NmNoMjBiTkdIZEF2bXJaclpSUkVVSFZDT3k4CnNoV01tMERq
        NW1McS81VWJZMkVHSVVmQS8vTU1lL3RBM0hOQzdVaG5DaGsKLS0tIE9pQXlXa2c5
        aTVla3RwUGVZcTBodnpSbHFFRkRUNlhkL1JVaytvL1kxR28KzIJrvKxwCU/7+oll
        oAUGgBjK+/LkZrB1wj8bu1G2s6HEm6PAjkY4e+a+NS0WTz+Gy+m0dDIrVmzVKnc7
        gATS0Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabHNHQ3JoYTNnNUlicVkr
        dUxMdFpFeEdBMysvNE9hb3A5ZXhmd2lMYTJZCjlBSlFYalNHMzhpb0c0aGczTHhM
        VVRKSUNTeGJWYXRsYlhDa2dEMkU2bUkKLS0tICtlUVlvWVZ2cnEzekdvV2cvSnAz
        ZGV1dmJvMWFaSXhZZndwM2djcGFYMU0Kpp8fliMmZhWgpJJXmG2q1uqpaXvRR/j3
        TTxvYaDTMZcAHbGeV06EFE43Y8s0/raKFab/SyQNBwyNHuB7i/xZFA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-29T15:32:59Z"
  mac: ENC[AES256_GCM,data:KOI6daydWBwVMEJ90E3TT92H/pVf47hA0PqEvc/NcVNE66ehBhfeWSwwA0ZuQ4LNZQCDws/FQ9dPQAu9DdSSRgi+U2eSwvbX0r8y23+X5wGhtGt/3ThViyfM+3tg27p7BJrgUhXosD4n4TtTDABGd3FoZ69nlcPUnX9+HRWAtck=,iv:18Dyby46Vtr15JF5yBXwxv06lMdPFa4j6AeHsdwu0Iw=,tag:2pOD6m3IgBBEJzfiPOy6Mw==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: ExtensionServiceConfig
name: tailscale
environment:
  # enc!
  - ENC[AES256_GCM,data:wqO5wOYZ69fbRoi2T1GQgMYekAEFykca/rJfHympSUlZmlhy8zNpzF9stjam00Iwbg8csHKe9XSIqns=,iv:s8DePhM1y8nJwi8WfggD5c6+HMMqPmZNjWTjJ45rmxM=,tag:b1Fz3WUt/Kvd1naY+nUd6g==,type:str]
  - TS_EXTRA_ARGS=--login-server=https://hs.vrtx.sh --ssh --accept-routes=true --snat-subnet-routes=false
  # need to toggle this to "false" for changes to ^ to apply, containerboot doesn't consider TS_EXTRA_ARGS
  # when running tailscale set:
  # https://github.com/tailscale/tailscale/blob/f36eb81e6105401b814548393cc90673abe24639/cmd/containerboot/tailscaled.go#L149
  - TS_AUTH_ONCE=true
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBROHU3
        dUNjNy9wbk5icHV6NmNoMjBiTkdIZEF2bXJaclpSUkVVSFZDT3k4CnNoV01tMERq
        NW1McS81VWJZMkVHSVVmQS8vTU1lL3RBM0hOQzdVaG5DaGsKLS0tIE9pQXlXa2c5
        aTVla3RwUGVZcTBodnpSbHFFRkRUNlhkL1JVaytvL1kxR28KzIJrvKxwCU/7+oll
        oAUGgBjK+/LkZrB1wj8bu1G2s6HEm6PAjkY4e+a+NS0WTz+Gy+m0dDIrVmzVKnc7
        gATS0Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabHNHQ3JoYTNnNUlicVkr
        dUxMdFpFeEdBMysvNE9hb3A5ZXhmd2lMYTJZCjlBSlFYalNHMzhpb0c0aGczTHhM
        VVRKSUNTeGJWYXRsYlhDa2dEMkU2bUkKLS0tICtlUVlvWVZ2cnEzekdvV2cvSnAz
        ZGV1dmJvMWFaSXhZZndwM2djcGFYMU0Kpp8fliMmZhWgpJJXmG2q1uqpaXvRR/j3
        TTxvYaDTMZcAHbGeV06EFE43Y8s0/raKFab/SyQNBwyNHuB7i/xZFA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-29T15:32:59Z"
  mac: ENC[AES256_GCM,data:KOI6daydWBwVMEJ90E3TT92H/pVf47hA0PqEvc/NcVNE66ehBhfeWSwwA0ZuQ4LNZQCDws/FQ9dPQAu9DdSSRgi+U2eSwvbX0r8y23+X5wGhtGt/3ThViyfM+3tg27p7BJrgUhXosD4n4TtTDABGd3FoZ69nlcPUnX9+HRWAtck=,iv:18Dyby46Vtr15JF5yBXwxv06lMdPFa4j6AeHsdwu0Iw=,tag:2pOD6m3IgBBEJzfiPOy6Mw==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
