cluster:
  discovery:
    enabled: true
    registries:
      # Kubernetes registry is problematic with KubeSpan, if the control plane endpoint is routeable itself via KubeSpan.
      kubernetes:
        disabled: true
      service: {}
  network:
    podSubnets:
      - 10.41.0.0/16
      - 2001:cafe:41::/56
    serviceSubnets:
      - 10.43.0.0/16
      - 2001:cafe:43::/112
  proxy:
    disabled: true
machine:
  network:
    kubespan:
      enabled: true
    # enc!
    extraHostEntries:
      - ip: ENC[AES256_GCM,data:NsfomUQ36HGUKC8ECzZMJtWGLmM=,iv:XOpXy5m/61s5+yOraKHHgot2gw8CZh3gxParQRkLMNI=,tag:6fH4hB41bcwTCp1VbmL1xw==,type:str]
        aliases:
          - ENC[AES256_GCM,data:rSSPwQS9gi5IxEViwd0l9zGPFZgEvuRB1D4=,iv:VdnvFmH3o6ONvBtnbMayCvzRbJsScSG5MMEvL842xZg=,tag:nmYOZrJe7ER6Cx2Z82sJxw==,type:str]
      - ip: ENC[AES256_GCM,data:EFJbbG/IcQuD/VIsw1MJasP67j4/koiK,iv:OBE4ZRO2TUjpO7uMY3D7DVrSOGa4Zr4H6Rn9+AdmsOI=,tag:IIvAf4kb3BKCZUa5NP+Clg==,type:str]
        aliases:
          - ENC[AES256_GCM,data:vWqXSuHdxE4zTbX0v1jfr39YvgKJbrV7alM=,iv:TFG4msEcf/ilIv26NqkNmfYpYW4xD7CwHgL1cMPR6W8=,tag:sPP8oSwcuXoRS0xOt0Gltw==,type:str]
      - ip: ENC[AES256_GCM,data:2joQ++7LK73qj7gcaIwMI3jxmd1UPfSZ,iv:bOlnpkut1hUKqUMnMiP87M19N18SKpgOXzfsKSaT2/k=,tag:n1YoXzPN3EBttOlQvdg2OA==,type:str]
        aliases:
          - ENC[AES256_GCM,data:AqjyfT31lH4PCkauPcNpWPpjHFXH5605EX0=,iv:YwJkkQA1sIIOG+PaOse7ySeiYhD0jYvF5QsM5joycwM=,tag:1Tzi7fzzxy79b4OyWSlyLQ==,type:str]
      - ip: ENC[AES256_GCM,data:BiDzVDL/ibiH,iv:/oMz89TAeaFqErYl7LunxLuo0RmHf8YhZ0ehPwjLcWc=,tag:hSX1Wk1SpC44R24LJxCSmQ==,type:str]
        aliases:
          - ENC[AES256_GCM,data:5RTIG/kH3S6Af+UV2a5Ehwa+VqD4Kdv3WLc=,iv:UgwQmnjJ+ZOHn08i2E9GLwazhsVnDQGJL8KwhMz5yeY=,tag:0o+g5fxVCiqiUYT46NFiQw==,type:str]
      - ip: ENC[AES256_GCM,data:F7GCpM56iycO,iv:10+Y4yjf01QHyO6MnY9syR5P5YRdXcHTP8Pn/dF9KIE=,tag:WZhb0u6Uzn4JOv6HIr+mpA==,type:str]
        aliases:
          - ENC[AES256_GCM,data:QEupOeUpy1TSMGMJgy4z3AKW3KAgq3JE8rY=,iv:AY7KS4Y//W2C5gEAkF6PhAC/5X+CWLeID7REbo8985E=,tag:J/0lzQ2LBRDT4f6SOVBSqA==,type:str]
      - ip: ENC[AES256_GCM,data:bm/6P8L667IH9D7woA==,iv:SdC6Q+/4oUTAJA1wBSad7dmn3/P0lKaVlfLqbGK5hvo=,tag:6eMCC5crXEkoZjGKsFp+0A==,type:str]
        aliases:
          - ENC[AES256_GCM,data:1+y3osJE0/HOexEV2e2+fykvDim8d9Dv6iw=,iv:Dcuwr1IFyb2Fn5Em1mmaFznc//yi7xGEJe+knNNAU+Y=,tag:yf+4R7DkSOmSo4ODOdlGxw==,type:str]
  sysctls:
    # 128MiB
    vm.min_free_kbytes: 131072
    vm.watermark_scale_factor: 50
    fs.inotify.max_user_watches: 4194304
    fs.inotify.max_user_instances: 65536
  kubelet:
    extraArgs:
      rotate-server-certificates: true
    extraMounts:
      - destination: /var/lib/longhorn
        type: bind
        source: /var/lib/longhorn
        options:
          - bind
          - rshared
          - rw
    extraConfig:
      # kubelet serving certs
      serverTLSBootstrap: true
      memorySwap:
        swapBehavior: LimitedSwap
  features:
    hostDNS:
      resolveMemberNames: true
  nodeLabels:
    hugeloads.sophons.cloud/longhorn: "true"
    hugeloads.sophons.cloud/postgres: "true"
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBCTW1O
        VFhwWGVQODR2ZkxGdTRQMEk3MjF1UVBNcGZiUjNlYlBnNk84Q0dRCjNDVC9ITDMz
        MnVqUUhwcWpEeFBXTDJ1RGZuaDVOVVNhak00QlBvSldNS1UKLS0tIDFiM1ZBU3RG
        a01ZMVUvQUVjN1VsNlVZd3lRWVdBazZoWEVYdndhdWR0ajQKYE1aAm6/QmUZWioE
        7jpkJT5lqVcbxvefuWoYSU4pRUFvEw/4PVU5jJgixrVwkRuZJYT7kxGzP76T3O90
        cDdQnw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCS1REOGwycTdZUXlUTDJ1
        UUdHQmdBQ2F2N0RWRGlGampyeTNUemhkakZjCjVyOWFGYWFoRTMyN0Q5cFF5V2pH
        ZGtxWi9uSzkwckRuZTkyaTFuVG5wL3cKLS0tIFY3LzJmblFzRithMFRUZlBpK1BY
        TURpcGxkVWFuZHFjcWt2TExHazJZMkEK/saLEPBmoGChC/0Yd2bm+vHw2yoduhNq
        +bkENH7qUBRtQu91UPvfGVChOstj+CtQIYv6oVzepYK8RVqwf35X1g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-13T13:12:14Z"
  mac: ENC[AES256_GCM,data:QmqCIpgTV8JhFsP9+0TWeP66fZEDR8u4uI9v+sxNzZD/nUgrePyLAFo2fXdlK+/GeDt19M2Sz5ndl0Qrj1wgyhl/Nq1pXkZz64sP8WC/6EFXqjnEGOO3gGYWv/xKg0YjqYzkOIKCPQVTFdFoc0NRBYvaKY7oMAqRVVDYwRL7t78=,iv:zfDtwOi1DiZtHC/HdnFyJdyIVAMz3xK8JS4o836fFKM=,tag:T6b7+sy6C0VaPiw4X/LrHA==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: ZswapConfig
# The maximum percent of memory that zswap can use.
maxPoolPercent: 25
# Enable the shrinker feature: kernel might move
shrinkerEnabled: true
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBCTW1O
        VFhwWGVQODR2ZkxGdTRQMEk3MjF1UVBNcGZiUjNlYlBnNk84Q0dRCjNDVC9ITDMz
        MnVqUUhwcWpEeFBXTDJ1RGZuaDVOVVNhak00QlBvSldNS1UKLS0tIDFiM1ZBU3RG
        a01ZMVUvQUVjN1VsNlVZd3lRWVdBazZoWEVYdndhdWR0ajQKYE1aAm6/QmUZWioE
        7jpkJT5lqVcbxvefuWoYSU4pRUFvEw/4PVU5jJgixrVwkRuZJYT7kxGzP76T3O90
        cDdQnw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCS1REOGwycTdZUXlUTDJ1
        UUdHQmdBQ2F2N0RWRGlGampyeTNUemhkakZjCjVyOWFGYWFoRTMyN0Q5cFF5V2pH
        ZGtxWi9uSzkwckRuZTkyaTFuVG5wL3cKLS0tIFY3LzJmblFzRithMFRUZlBpK1BY
        TURpcGxkVWFuZHFjcWt2TExHazJZMkEK/saLEPBmoGChC/0Yd2bm+vHw2yoduhNq
        +bkENH7qUBRtQu91UPvfGVChOstj+CtQIYv6oVzepYK8RVqwf35X1g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-13T13:12:14Z"
  mac: ENC[AES256_GCM,data:QmqCIpgTV8JhFsP9+0TWeP66fZEDR8u4uI9v+sxNzZD/nUgrePyLAFo2fXdlK+/GeDt19M2Sz5ndl0Qrj1wgyhl/Nq1pXkZz64sP8WC/6EFXqjnEGOO3gGYWv/xKg0YjqYzkOIKCPQVTFdFoc0NRBYvaKY7oMAqRVVDYwRL7t78=,iv:zfDtwOi1DiZtHC/HdnFyJdyIVAMz3xK8JS4o836fFKM=,tag:T6b7+sy6C0VaPiw4X/LrHA==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: ExtensionServiceConfig
name: cloudflared
environment:
  # enc!
  - ENC[AES256_GCM,data:PZGWJeGFTc6Vo//igM674X/VqbF7B6UaM7kLqf2f62wP05qyR1fcS9elf9lMCUZCbTK9SrWL0FR2tRGixGA7+zRM1jjj8JCqBvROM43uolIvoKPQh/jAQ/2Q3dk0ai099jhhdwWBpt8vSSJ8KgrUei48SVPpF1YwIXgyOb2y+xPhtDZORE0nNo6jSeSDPER5A4TTVudVCDQ6Wf0XRXe1/42k1pwMIuI2tP9V+IdfxY6kxPc5x7kI0JOnyHEa1e+c8yz0OY4=,iv:ZBkqrEpPvMCNtFgOPW9tbFPEKobysDMKGa2UJaWusZQ=,tag:c2vnoE6dDufgXuX092sf7w==,type:str]
  - TUNNEL_METRICS=localhost:2000
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBCTW1O
        VFhwWGVQODR2ZkxGdTRQMEk3MjF1UVBNcGZiUjNlYlBnNk84Q0dRCjNDVC9ITDMz
        MnVqUUhwcWpEeFBXTDJ1RGZuaDVOVVNhak00QlBvSldNS1UKLS0tIDFiM1ZBU3RG
        a01ZMVUvQUVjN1VsNlVZd3lRWVdBazZoWEVYdndhdWR0ajQKYE1aAm6/QmUZWioE
        7jpkJT5lqVcbxvefuWoYSU4pRUFvEw/4PVU5jJgixrVwkRuZJYT7kxGzP76T3O90
        cDdQnw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCS1REOGwycTdZUXlUTDJ1
        UUdHQmdBQ2F2N0RWRGlGampyeTNUemhkakZjCjVyOWFGYWFoRTMyN0Q5cFF5V2pH
        ZGtxWi9uSzkwckRuZTkyaTFuVG5wL3cKLS0tIFY3LzJmblFzRithMFRUZlBpK1BY
        TURpcGxkVWFuZHFjcWt2TExHazJZMkEK/saLEPBmoGChC/0Yd2bm+vHw2yoduhNq
        +bkENH7qUBRtQu91UPvfGVChOstj+CtQIYv6oVzepYK8RVqwf35X1g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-13T13:12:14Z"
  mac: ENC[AES256_GCM,data:QmqCIpgTV8JhFsP9+0TWeP66fZEDR8u4uI9v+sxNzZD/nUgrePyLAFo2fXdlK+/GeDt19M2Sz5ndl0Qrj1wgyhl/Nq1pXkZz64sP8WC/6EFXqjnEGOO3gGYWv/xKg0YjqYzkOIKCPQVTFdFoc0NRBYvaKY7oMAqRVVDYwRL7t78=,iv:zfDtwOi1DiZtHC/HdnFyJdyIVAMz3xK8JS4o836fFKM=,tag:T6b7+sy6C0VaPiw4X/LrHA==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
