cluster:
  discovery:
    enabled: true
    registries:
      # Kubernetes registry is problematic with KubeSpan, if the control plane endpoint is routeable itself via KubeSpan.
      kubernetes:
        disabled: true
      service: {}
  network:
    podSubnets:
      - 10.41.0.0/16
      - 2001:cafe:41::/56
    serviceSubnets:
      - 10.43.0.0/16
      - 2001:cafe:43::/112
  proxy:
    disabled: true
machine:
  network:
    kubespan:
      enabled: true
    # enc!
    extraHostEntries:
      - ip: ENC[AES256_GCM,data:iKMKWuGdchJKMt44h/U50iWPHHY=,iv:lEqECU/7H/XfYQmsmWr71Jrx8m+xpwG2GCscTi+F+r4=,tag:jeUTGFnSi7wfDG+qdwusOw==,type:str]
        aliases:
          - ENC[AES256_GCM,data:x3Le04VNQJy/BUdOY665OgUalJttG05joyY=,iv:FmDLoCX93GshD1vf9yOfnxW1yhsPpiXT2Oihj8B6WDo=,tag:rPPdh8i6X8W0r3hCwSD/pQ==,type:str]
      - ip: ENC[AES256_GCM,data:hPyXrN0qktu+9lY+K7SOrJsddI2Mcv75,iv:rY+MQNApjwWblBzoDAHEfatRZZnpIKtXRmJKbdppIG0=,tag:L529HgrbZCTuiTfRpODJWQ==,type:str]
        aliases:
          - ENC[AES256_GCM,data:tOSXw48954vfMRo+F6wizkKhpCei8s/dwYU=,iv:NnDDwXMyBCDOXP5a4n8Iljk1FpxkPbG7aOTnOZz0qSI=,tag:AW1mLwQ7fAMoB1MkSp+zmg==,type:str]
      - ip: ENC[AES256_GCM,data:r3Df4ofzHp2TNI6vutC/X2eRFnCwEsMU,iv:gol2c/Q8GiRJAggMhgedAMVkLzoLsgU5nLH9qsvnHUQ=,tag:U1tJqbPorGl7rklu4ogQpw==,type:str]
        aliases:
          - ENC[AES256_GCM,data:TX+U1A6lMiUXz27v3IaJeErFE+wESEYAegg=,iv:H8/BcXj7Vj+WELcGs+iScsGpT2ZG2raW/xQXhwzocWQ=,tag:UR4fHl2bC4kgPZlPMS+5zQ==,type:str]
      - ip: ENC[AES256_GCM,data:2EDNCY3/BmiD,iv:Pk4g9uNLieEnxbk6c0YFG91z00Jse7mfQ8gzi/m61BI=,tag:58etFaBSllCpSkp6zN07jA==,type:str]
        aliases:
          - ENC[AES256_GCM,data:1zijjJfboivpzL5sDmiAR64BED3vIyjgWDM=,iv:BV1Cq70A4hDDLcjtZD3mKTyBHkGcx/86VZfiyTqFq0Q=,tag:yxCbLAAVGHsSDF8Shb9Gog==,type:str]
      - ip: ENC[AES256_GCM,data:SdyhRkkeo8te,iv:yHZ8H4tQsHM0YUKlvwYHSkhzL2leMuuRpBY1ZhYsLDk=,tag:sbMge7Wnp/C8hswClom0UA==,type:str]
        aliases:
          - ENC[AES256_GCM,data:cwnKy5kSv62J3FXgiks5M1ho7c+88DQlZb8=,iv:2kf4WYvOARb4lxhRR7FZYr+jDDnU4yaktVk+itPGfMg=,tag:sxQEHFYPslpoDfvfNXGJnQ==,type:str]
      - ip: ENC[AES256_GCM,data:TIMvshErCfXTxR0Krw==,iv:B4cmZmpk0xotCsoQJrJJEIUP28hmA2WWhqeFE+Nm6wU=,tag:4wMkNd6Oq++BHx87qk+MRA==,type:str]
        aliases:
          - ENC[AES256_GCM,data:cCl/6iQg+yTkpC4xpewsh9eRsLJgVlzRlEQ=,iv:cQuHCAjqEC080KTtmeJoVKJlgfOOKm4xGhOeJKYCEXg=,tag:sw/TRQi81hWs+Fzz0Kc/ew==,type:str]
  sysctls:
    # 128MiB
    vm.min_free_kbytes: 131072
    vm.watermark_scale_factor: 50
    fs.inotify.max_user_watches: 4194304
    fs.inotify.max_user_instances: 65536
    user.max_user_namespaces: 65536
  kubelet:
    extraArgs:
      rotate-server-certificates: true
    extraMounts:
      - destination: /var/lib/longhorn
        type: bind
        source: /var/lib/longhorn
        options:
          - bind
          - rshared
          - rw
    extraConfig:
      # kubelet serving certs
      serverTLSBootstrap: true
      memorySwap:
        swapBehavior: LimitedSwap
  features:
    hostDNS:
      resolveMemberNames: true
  nodeLabels:
    hugeloads.sophons.cloud/longhorn: "true"
    hugeloads.sophons.cloud/postgres: "true"
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBrZW42
        RXdLaXV1T0p2TEtEK29ma3pOdFdGUzdrOVgwNEVxdE5FUVozLzNjCkZXQy9uTzVG
        VEhlQ3NaVHdKM001OGZ6amhKZWhKWUl3TysxZHdROTF0WGMKLS0tIHpwVnVyWXVV
        R1hHNkl1eW80UUFOQ1JUM0hwbGdHMStFeXRJZXRCSkNzWWsKHZdNE0ujxHffb6D/
        3HEf6LS5zzOnkAYWNeVyTwxOY61889q6QrZTwRrfcm6KT09NaOjvAmjBMF/EQdgg
        T7tNXQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDaWwzdE9yK3pNK1RDRjB1
        VlBEUVdObDB5VytDRG5BQWVyRkc3NnI0REFrCll2SnFQMlFsQnlIVmhGYUVlUUpk
        eTYyb3N2a3VpbXhjS0JCQTZVYmo4Z1kKLS0tIDNjVXN0UmxuSldpV29KbjlPL093
        d3c3akpXQ0kyK3FEbExHelhLV1YySDQK2kOiFKhj6/2SAz8zoqgBXjHlv/VVe+z1
        0lZjslPzrFiAa3bv3IIAwuH3Z3iKh4H5vM0Jg7ygqrhUi4i/Va1Azg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-20T17:31:40Z"
  mac: ENC[AES256_GCM,data:5rvb5vFv66kBzxL5LFs/4qwVVFI9jHAOFlYrH9VDPm+eqzYp26jwm+zVKUk4z0SNbxxJZLrGD5FcVdBtXbjj5sskN/LWZ2LFiJUPnsCoNS6qn6VMLNPNZAh10ki9HY8d1oIdnHMXPTClRkG2Ke5kzB77NU3LJ5QZoHQ6Jeby/KY=,iv:z5FkuWAylUxSuc0/q6MEebtXoRXxk83ImxlLL6G3KgQ=,tag:Vnrna6f4IOKH58ohSUGtjw==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: ZswapConfig
# The maximum percent of memory that zswap can use.
maxPoolPercent: 25
# Enable the shrinker feature: kernel might move
shrinkerEnabled: true
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBrZW42
        RXdLaXV1T0p2TEtEK29ma3pOdFdGUzdrOVgwNEVxdE5FUVozLzNjCkZXQy9uTzVG
        VEhlQ3NaVHdKM001OGZ6amhKZWhKWUl3TysxZHdROTF0WGMKLS0tIHpwVnVyWXVV
        R1hHNkl1eW80UUFOQ1JUM0hwbGdHMStFeXRJZXRCSkNzWWsKHZdNE0ujxHffb6D/
        3HEf6LS5zzOnkAYWNeVyTwxOY61889q6QrZTwRrfcm6KT09NaOjvAmjBMF/EQdgg
        T7tNXQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDaWwzdE9yK3pNK1RDRjB1
        VlBEUVdObDB5VytDRG5BQWVyRkc3NnI0REFrCll2SnFQMlFsQnlIVmhGYUVlUUpk
        eTYyb3N2a3VpbXhjS0JCQTZVYmo4Z1kKLS0tIDNjVXN0UmxuSldpV29KbjlPL093
        d3c3akpXQ0kyK3FEbExHelhLV1YySDQK2kOiFKhj6/2SAz8zoqgBXjHlv/VVe+z1
        0lZjslPzrFiAa3bv3IIAwuH3Z3iKh4H5vM0Jg7ygqrhUi4i/Va1Azg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-20T17:31:40Z"
  mac: ENC[AES256_GCM,data:5rvb5vFv66kBzxL5LFs/4qwVVFI9jHAOFlYrH9VDPm+eqzYp26jwm+zVKUk4z0SNbxxJZLrGD5FcVdBtXbjj5sskN/LWZ2LFiJUPnsCoNS6qn6VMLNPNZAh10ki9HY8d1oIdnHMXPTClRkG2Ke5kzB77NU3LJ5QZoHQ6Jeby/KY=,iv:z5FkuWAylUxSuc0/q6MEebtXoRXxk83ImxlLL6G3KgQ=,tag:Vnrna6f4IOKH58ohSUGtjw==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: ExtensionServiceConfig
name: cloudflared
environment:
  # enc!
  - ENC[AES256_GCM,data:Y/U5EhxCcjaLMi5Rp7UQc61NBn8JPHb61ciuHPQ0+wIcBkYiNYJya4C4CsBLLU9SvDgaOOQ/yXnl5LeXakPwTZd4WO81xkI1ZwZt77yox+x2J3jQgWkCOhAiU/C2rFigZCIFyvepJG+VkXvIY4rAaEx3CmM3XurBwrWjKGp81pxakklMKSdoTrfNdPFL4QpyU1qC5Ig1rlctcE7B78qqnGHFlJ3I5CRrdpW92rg2UmMqoASCKIjYr+LMfSzCbMBqseB+W6c=,iv:Tww8a2uzwQUi7Ui4mEsODiVF1B1vCxa6D1zCiaeUCBM=,tag:cekHMKspQn9bCiNiqCdMFQ==,type:str]
  - TUNNEL_METRICS=localhost:2000
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBrZW42
        RXdLaXV1T0p2TEtEK29ma3pOdFdGUzdrOVgwNEVxdE5FUVozLzNjCkZXQy9uTzVG
        VEhlQ3NaVHdKM001OGZ6amhKZWhKWUl3TysxZHdROTF0WGMKLS0tIHpwVnVyWXVV
        R1hHNkl1eW80UUFOQ1JUM0hwbGdHMStFeXRJZXRCSkNzWWsKHZdNE0ujxHffb6D/
        3HEf6LS5zzOnkAYWNeVyTwxOY61889q6QrZTwRrfcm6KT09NaOjvAmjBMF/EQdgg
        T7tNXQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDaWwzdE9yK3pNK1RDRjB1
        VlBEUVdObDB5VytDRG5BQWVyRkc3NnI0REFrCll2SnFQMlFsQnlIVmhGYUVlUUpk
        eTYyb3N2a3VpbXhjS0JCQTZVYmo4Z1kKLS0tIDNjVXN0UmxuSldpV29KbjlPL093
        d3c3akpXQ0kyK3FEbExHelhLV1YySDQK2kOiFKhj6/2SAz8zoqgBXjHlv/VVe+z1
        0lZjslPzrFiAa3bv3IIAwuH3Z3iKh4H5vM0Jg7ygqrhUi4i/Va1Azg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-20T17:31:40Z"
  mac: ENC[AES256_GCM,data:5rvb5vFv66kBzxL5LFs/4qwVVFI9jHAOFlYrH9VDPm+eqzYp26jwm+zVKUk4z0SNbxxJZLrGD5FcVdBtXbjj5sskN/LWZ2LFiJUPnsCoNS6qn6VMLNPNZAh10ki9HY8d1oIdnHMXPTClRkG2Ke5kzB77NU3LJ5QZoHQ6Jeby/KY=,iv:z5FkuWAylUxSuc0/q6MEebtXoRXxk83ImxlLL6G3KgQ=,tag:Vnrna6f4IOKH58ohSUGtjw==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
