cluster:
  discovery:
    enabled: true
    registries:
      # Kubernetes registry is problematic with KubeSpan, if the control plane endpoint is routeable itself via KubeSpan.
      kubernetes:
        disabled: true
      service: {}
  network:
    podSubnets:
      - 10.41.0.0/16
      - 2001:cafe:41::/56
    serviceSubnets:
      - 10.43.0.0/16
      - 2001:cafe:43::/112
  proxy:
    disabled: true
machine:
  network:
    kubespan:
      enabled: true
      advertiseKubernetesNetworks: true
  sysctls:
    # 128MiB
    vm.min_free_kbytes: 131072
    vm.watermark_scale_factor: 50
    fs.inotify.max_user_watches: 4194304
    fs.inotify.max_user_instances: 65536
  kubelet:
    extraArgs:
      rotate-server-certificates: true
    extraMounts:
      - destination: /var/lib/longhorn
        type: bind
        source: /var/lib/longhorn
        options:
          - bind
          - rshared
          - rw
    extraConfig:
      # kubelet serving certs
      serverTLSBootstrap: true
      memorySwap:
        swapBehavior: LimitedSwap
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBwemZZ
        RCswZ284WFFpWFJEOWpSZG10Vm9reVJZWGVIR1FUbFBFOTBiM0JBCm5xNVpoS1Y5
        YXpmdFdPMzJwL0RyQUVYM1JnZXZvd05PczByVDQ1ejh0TVUKLS0tIEFwQ2xlUHZm
        ZnYwMEJQWU9FcXY5RUdtK3drSCtFYVNoUXhKR1MvN3NDQ0UKXjmIXK2xDrt93VYc
        pPwd/rmniVgxBwqGHuqm50244aTceKu46UP1ImodKAGzXTJ49uo1sE9hXv+GSIpp
        Nas47w==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3VTZWN0JFMWNmTFVRK3VW
        ZnRhM0FKeHdqbkl6R2N6SWNtMWdUaG5TR0hFCkZtOXlmd2t2Vy81OTBQUmZjV2F2
        MFFCSVM1eWsxRHRlWDB2U2l4bTcvNmMKLS0tIHZZaWM2Z1NQVDYxQXhtRjZsY2pX
        dHpRSi9sMC9XdmRGVWpKNU96TllubjQKO3wABy2NA+vn3DfjNxq2ho2A7tW36aMk
        Z9KSM0OExh78tlWFUCYMQrg8/NZL4D6fxR+VlZxOVnjjg/LTYgqfUA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-08T05:06:21Z"
  mac: ENC[AES256_GCM,data:lgR3AUrnt/im5WBmHwRhESBO8Kqj7DlDqrREM9yHoR5YYudQSG9hAyeLxf3vb8kJqsMHawW2bvmeBRiHCYZoIMKU6EDX/DgTz642BoirkjCpq6VCwqSjdJKqD54EDPnJqsYbY7XC5s5JGJTu5u1QaGxRqqQLktSvUYEcjhrWXmI=,iv:SqMWG9w5dmFahrL0ttmsGECxkZ988puxUIuznaf4aQM=,tag:KOZWJVDftoGazX30OVoJ6w==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: ZswapConfig
# The maximum percent of memory that zswap can use.
maxPoolPercent: 25
# Enable the shrinker feature: kernel might move
shrinkerEnabled: true
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBwemZZ
        RCswZ284WFFpWFJEOWpSZG10Vm9reVJZWGVIR1FUbFBFOTBiM0JBCm5xNVpoS1Y5
        YXpmdFdPMzJwL0RyQUVYM1JnZXZvd05PczByVDQ1ejh0TVUKLS0tIEFwQ2xlUHZm
        ZnYwMEJQWU9FcXY5RUdtK3drSCtFYVNoUXhKR1MvN3NDQ0UKXjmIXK2xDrt93VYc
        pPwd/rmniVgxBwqGHuqm50244aTceKu46UP1ImodKAGzXTJ49uo1sE9hXv+GSIpp
        Nas47w==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3VTZWN0JFMWNmTFVRK3VW
        ZnRhM0FKeHdqbkl6R2N6SWNtMWdUaG5TR0hFCkZtOXlmd2t2Vy81OTBQUmZjV2F2
        MFFCSVM1eWsxRHRlWDB2U2l4bTcvNmMKLS0tIHZZaWM2Z1NQVDYxQXhtRjZsY2pX
        dHpRSi9sMC9XdmRGVWpKNU96TllubjQKO3wABy2NA+vn3DfjNxq2ho2A7tW36aMk
        Z9KSM0OExh78tlWFUCYMQrg8/NZL4D6fxR+VlZxOVnjjg/LTYgqfUA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-08T05:06:21Z"
  mac: ENC[AES256_GCM,data:lgR3AUrnt/im5WBmHwRhESBO8Kqj7DlDqrREM9yHoR5YYudQSG9hAyeLxf3vb8kJqsMHawW2bvmeBRiHCYZoIMKU6EDX/DgTz642BoirkjCpq6VCwqSjdJKqD54EDPnJqsYbY7XC5s5JGJTu5u1QaGxRqqQLktSvUYEcjhrWXmI=,iv:SqMWG9w5dmFahrL0ttmsGECxkZ988puxUIuznaf4aQM=,tag:KOZWJVDftoGazX30OVoJ6w==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: ExtensionServiceConfig
name: cloudflared
environment:
  # enc!
  - ENC[AES256_GCM,data:YZ5cvX0FaD3mNIMUlKJgeTBzYpCiGf6t2S9LATeIT6qd0cdyLNYE89ZXlXBjFCsZFg88yD3iXJFh3saMhbc3D73A9jTi3TMt61iewUKsJ5kXle7kyDRpp/fp1vX/Ti8vBLEW0Zb8pivcRbswWQURbnfd/9upXW55BuQKlfgs4r0DhnNivbHKrYVQ3/BtopDvvI6uhB9mgy9APVy7iPC24vATp9ezkuPqBUF8OAdHP3+yBhnjiZ7z2l5a3cbA5J+QMcUWe7Y=,iv:FqahmliwR04JxXxP514dXF7f+/IXrwbUgjVi7wS5ZxY=,tag:ap6VcKG1fuANhEtZpkOuWQ==,type:str]
  - TUNNEL_METRICS=localhost:2000
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBwemZZ
        RCswZ284WFFpWFJEOWpSZG10Vm9reVJZWGVIR1FUbFBFOTBiM0JBCm5xNVpoS1Y5
        YXpmdFdPMzJwL0RyQUVYM1JnZXZvd05PczByVDQ1ejh0TVUKLS0tIEFwQ2xlUHZm
        ZnYwMEJQWU9FcXY5RUdtK3drSCtFYVNoUXhKR1MvN3NDQ0UKXjmIXK2xDrt93VYc
        pPwd/rmniVgxBwqGHuqm50244aTceKu46UP1ImodKAGzXTJ49uo1sE9hXv+GSIpp
        Nas47w==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3VTZWN0JFMWNmTFVRK3VW
        ZnRhM0FKeHdqbkl6R2N6SWNtMWdUaG5TR0hFCkZtOXlmd2t2Vy81OTBQUmZjV2F2
        MFFCSVM1eWsxRHRlWDB2U2l4bTcvNmMKLS0tIHZZaWM2Z1NQVDYxQXhtRjZsY2pX
        dHpRSi9sMC9XdmRGVWpKNU96TllubjQKO3wABy2NA+vn3DfjNxq2ho2A7tW36aMk
        Z9KSM0OExh78tlWFUCYMQrg8/NZL4D6fxR+VlZxOVnjjg/LTYgqfUA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-08T05:06:21Z"
  mac: ENC[AES256_GCM,data:lgR3AUrnt/im5WBmHwRhESBO8Kqj7DlDqrREM9yHoR5YYudQSG9hAyeLxf3vb8kJqsMHawW2bvmeBRiHCYZoIMKU6EDX/DgTz642BoirkjCpq6VCwqSjdJKqD54EDPnJqsYbY7XC5s5JGJTu5u1QaGxRqqQLktSvUYEcjhrWXmI=,iv:SqMWG9w5dmFahrL0ttmsGECxkZ988puxUIuznaf4aQM=,tag:KOZWJVDftoGazX30OVoJ6w==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
