# ULA subnet: fdf6:9420:fade::/48
cluster:
  network:
    podSubnets:
      - 10.41.0.0/16
      - 2001:cafe:41::/56
    serviceSubnets:
      - 10.43.0.0/16
      - 2001:cafe:43::/112
  proxy:
    disabled: true
machine:
  network:
    # interfaces:
    #   - interface: lo
    #     addresses:
    #       # Workaround to allow CoreDNS to continue to work with hostDNS & BPF masquerading
    #       # https://github.com/siderolabs/talos/pull/9200#issuecomment-2805269653
    #       - 169.254.116.108/32
    nameservers:
      - 1.1.1.1
      - 9.9.9.9
    kubespan:
      enabled: false
    # enc!
    extraHostEntries:
      - ENC[AES256_GCM,data:7AwgOBbEN4B9,iv:SXySJtU5nZjLpkYbHiGfWV+7uCK6Y5dkyzvOF5fXnTM=,tag:nEXHkR1oiRJ0tJnsbojB3A==,type:comment]
      - ip: ENC[AES256_GCM,data:mpmBwsIJY7LldyFp,iv:zXGtZbSn5KhWxIIn2919hmeM4sRf0BaJA2Qh5V8/q9g=,tag:QGtjI8CQ6vua0EMTXiwtdQ==,type:str]
        aliases:
          - ENC[AES256_GCM,data:/9i7f21YxyEcPjI8WM4vu6i6miEkFrAKegE=,iv:CaQdVjOB7JQJr3XKJCZ9gpX9jG0FQiAjaSRMC9TqkEY=,tag:yr55ruvTxkkiQYBYfpI1WA==,type:str]
      - ip: ENC[AES256_GCM,data:S0XjxhKddhEK9IT3Py4VvMjXTg==,iv:GeBmBQVx/gJZKPn1thk7/uD2HW7Rd3/KJXL6u9+Bx/M=,tag:BLB9No8yik9m3ihE8aR7eQ==,type:str]
        aliases:
          - ENC[AES256_GCM,data:9rl7oJKJM/+BR6rcpDOguYkj8VvwtGUdrN4=,iv:YP/o6cEJTN5ktzqhRZYWGDDxfpSxh1wYV3UfHdPG1EI=,tag:79gj4mmruYmXbiTc05HezQ==,type:str]
      - ip: ENC[AES256_GCM,data:VjZMVDxCjdMcSO8=,iv:tjPdQSl9R+6CskSRMXxANmjbyfWUHq9mn21+RkRydh0=,tag:KnFXostzr8DFTG5nhFLU2w==,type:str]
        aliases:
          - ENC[AES256_GCM,data:PBByl2KHlFd2Yeia3dAsVOV1jvCCpeJnbTg=,iv:arjIzfQiky/KLJ9U2uroqWJqkasZTb04QhzMwV4LTgs=,tag:G2wKm5U5EQY3mIYC6Y9FsA==,type:str]
      - ENC[AES256_GCM,data:3E5+y8SO,iv:IdhpXCzmZLdF076KnHqbFAIHyL7tZbLxtYHryNJsJHc=,tag:SDJTfKsTlQX9ee3qv6c/ow==,type:comment]
      - ip: ENC[AES256_GCM,data:puXo2AGVhZsTnIHoUaQ=,iv:Plbm4EPeSDPWiZUluDzWqEK4ifhRvd4gJoOg6Ql8jBA=,tag:vh8o81WUsmKHGkbqscEJbw==,type:str]
        aliases:
          - ENC[AES256_GCM,data:fJcH0sfelfVNwRWETkeOZpdgTN4BOK0vo7E=,iv:n4VI1R+TT+AhxyPy1Wb36rCj5HM/dFpKpqaJ8ISHJcQ=,tag:hIWtnZsOkFK4LAXw/DfUzw==,type:str]
      - ip: ENC[AES256_GCM,data:/7arAC63poWbxp0HmJl/jKNV5X0=,iv:HiWDigWIG/BrEu7VVNigbeM0UUcB4tkANCPtvPsVSj4=,tag:6j0F0B4HFLP8ioffchNA8w==,type:str]
        aliases:
          - ENC[AES256_GCM,data:qHNOyfV/JKIyi7g6r1DJIUlIX617GF+LvHM=,iv:r+BwlGdt8JgnDxBODZdgbBMfXFk7+aP6Bu+WikJH9e4=,tag:yzNB2Arc+/6gPVo9ZyKeuQ==,type:str]
          - ENC[AES256_GCM,data:gCoHtNEHGeQsi4u3rw==,iv:ojjDYiPk4XKBw9k9/V8Wu94keZkwYfzTMtb13MqIDc4=,tag:gZi/xjV6vBAPa7xbfAB8RQ==,type:comment]
      - ip: ENC[AES256_GCM,data:PeASqptAJoQA5QBVIg==,iv:w23VdLeGSrSvKfXttnEVfYA0eF2jbeTbs2Ya2+RQhAI=,tag:+66MTCVs6495ThgbGua0Vg==,type:str]
        aliases:
          - ENC[AES256_GCM,data:cupXN/GuzvjT+4ZE6iCOTxqoQjM19gWBSsA=,iv:r2vDk1xwuQfTa3NSbutzi1L9EET6WWun4+Le+NgJRzc=,tag:R3VHKEkbBDwB4jo81UcRyQ==,type:str]
          - ENC[AES256_GCM,data:tmLbenM+Q3rgANkUNw==,iv:0DB5YqChKIHaS1CNjEgtXBiamoys7oBKx7uyqSTxx6M=,tag:ZvFLcHO4Rq+QSDxPBqMEXw==,type:comment]
      - ENC[AES256_GCM,data:kUf8cIE=,iv:l/CVS1oG7Y63RTzdw5NKOAklJ2rhX4gmUag1wpfx4Yo=,tag:4NM3g/z5Zh2eSaf97E3Www==,type:comment]
      - ip: ENC[AES256_GCM,data:DHBoy2nUmU1QvZr04Ic=,iv:JwDW+9yIvrcV0+BCwI4E/Du6dxKn7VzDUmPc/97y4oQ=,tag:CRr34ncl6w7wX24lHeaJ7Q==,type:str]
        aliases:
          - ENC[AES256_GCM,data:vDnABbyRL2bOT9Aszw17btjSCgPbktSG7JY=,iv:0ht2BWaztbteZMquDHZm6uk6QRYTbZ+ofkOKK0YaBLg=,tag:GY7O4Oe8JNTdMySecQqT9g==,type:str]
  sysctls:
    # 128MiB
    vm.min_free_kbytes: 131072
    vm.watermark_scale_factor: 50
    fs.inotify.max_user_watches: 4194304
    fs.inotify.max_user_instances: 65536
    user.max_user_namespaces: 65536
    net.ipv4.ip_forward: 1
    net.ipv6.conf.all.forwarding: 1
    # https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes
    net.core.rmem_max: 7500000
    net.core.wmem_max: 7500000
  kubelet:
    nodeIP:
      validSubnets:
        - 100.64.0.0/10
        - fd7a:115c:a1e0::/48
    extraArgs:
      rotate-server-certificates: true
    extraMounts:
      - destination: /var/lib/longhorn
        type: bind
        source: /var/lib/longhorn
        options:
          - bind
          - rshared
          - rw
      - destination: /var/lib/garage
        type: bind
        source: /var/lib/garage
        options:
          - bind
          - rshared
          - rw
      - destination: /var/lib/local-path-provisioner
        type: bind
        source: /var/lib/local-path-provisioner
        options:
          - bind
          - rshared
          - rw
    extraConfig:
      # kubelet serving certs
      serverTLSBootstrap: true
      memorySwap:
        swapBehavior: LimitedSwap
  features:
    hostDNS:
      resolveMemberNames: true
  nodeLabels:
    hugeloads.sophons.cloud/longhorn: "true"
    hugeloads.sophons.cloud/postgres: "true"
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyAyY2Ry
        czJiZGt1bEZqOFl5N2VONG5LN1lRYjJrSEtsY2ZPdXkvYVZGdXg4CmJia0FzWWxF
        Vng1eW03YnBwQ0xkS2FIVmV5RzhqSWRRSmw4czVJUlV0cG8KLS0tIFFjcmJJc05z
        T2RoL3dLRS9qalJPUDV1V0tvcVVhZ1pIZElQMlZaVjlGUDAKeQalTyFyj17Xt9tF
        t1ZKZbn25Cm16AzX7LNUQ8q232PNhGa05H6KEO5VTEcS+qW7DVXmamd9Rd13DTd5
        Qrao9w==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVNldPQlY3OUhyK0lXS1c2
        V3VDVEI4TGkwc045TEIzVWlZTTNVOWlHV2hFCmY1M3pSSDFNaHp3OFZSeGsrWmVo
        LzRtYWRtbTNCM211V3pucldTVkZiZVEKLS0tIHo5Q1FZbnpwVXZQNXdvMFZJSU50
        TUtxSW1XZm5xSzFXeUNCbERsVGV6UncKHO2+7aq6VNZ1bMGstolvW+umoe4V67ai
        /q7hFqehlCOFro/RzNT1EEZNPXctQ/ecjuMEe0pZmBBZ8QxS0E5BnA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-26T15:54:57Z"
  mac: ENC[AES256_GCM,data:gx3b3D8VR7QAEfexSM2y8y8tRq2UXnGpYN9AoFokgTIV7FtBx2sAP65rkmqdFKG9FLk9bx3t+UrOrO56hGjtip4kQsO2dUR5QhCcKsk4uYRxd6JrnwViVdWonsScAJFDDzDbQDfNBMhyVNJewiU6zRnkDsw8B6ONrSmTpCwn2N0=,iv:aJ4LEXi6fh1JN2AJasOf8xVwpM0Wq0Pf3x0jd33HoAI=,tag:8Y1gZVYc3qx3llDc01eXng==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: ZswapConfig
# The maximum percent of memory that zswap can use.
maxPoolPercent: 25
# Enable the shrinker feature: kernel might move
shrinkerEnabled: true
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyAyY2Ry
        czJiZGt1bEZqOFl5N2VONG5LN1lRYjJrSEtsY2ZPdXkvYVZGdXg4CmJia0FzWWxF
        Vng1eW03YnBwQ0xkS2FIVmV5RzhqSWRRSmw4czVJUlV0cG8KLS0tIFFjcmJJc05z
        T2RoL3dLRS9qalJPUDV1V0tvcVVhZ1pIZElQMlZaVjlGUDAKeQalTyFyj17Xt9tF
        t1ZKZbn25Cm16AzX7LNUQ8q232PNhGa05H6KEO5VTEcS+qW7DVXmamd9Rd13DTd5
        Qrao9w==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVNldPQlY3OUhyK0lXS1c2
        V3VDVEI4TGkwc045TEIzVWlZTTNVOWlHV2hFCmY1M3pSSDFNaHp3OFZSeGsrWmVo
        LzRtYWRtbTNCM211V3pucldTVkZiZVEKLS0tIHo5Q1FZbnpwVXZQNXdvMFZJSU50
        TUtxSW1XZm5xSzFXeUNCbERsVGV6UncKHO2+7aq6VNZ1bMGstolvW+umoe4V67ai
        /q7hFqehlCOFro/RzNT1EEZNPXctQ/ecjuMEe0pZmBBZ8QxS0E5BnA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-26T15:54:57Z"
  mac: ENC[AES256_GCM,data:gx3b3D8VR7QAEfexSM2y8y8tRq2UXnGpYN9AoFokgTIV7FtBx2sAP65rkmqdFKG9FLk9bx3t+UrOrO56hGjtip4kQsO2dUR5QhCcKsk4uYRxd6JrnwViVdWonsScAJFDDzDbQDfNBMhyVNJewiU6zRnkDsw8B6ONrSmTpCwn2N0=,iv:aJ4LEXi6fh1JN2AJasOf8xVwpM0Wq0Pf3x0jd33HoAI=,tag:8Y1gZVYc3qx3llDc01eXng==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: ExtensionServiceConfig
name: cloudflared
environment:
  # enc!
  - ENC[AES256_GCM,data:arE4QGcZhkcR94YBR4rTBTDhi7dKtR0tmqeRIFQyCV3L37LSYvQCR3Q5qdGmmAuosOaCgn93+LH6RsyONdGy+x3ZJherOs2w7U1fJHiZcvw/E9EcS8tDMld2f+a6PmTNsxyQ9LkzF51qKYIz37MVOZ7liCMhk00jCzQPplOTEBKTOkMvEVSWxUC89lZSVEVDCEn4IJEV7PZMrnFz+1qXq3M2YPDEyHL4cb3JCnsXQ/MPNkjpOMS+/BhtLcAK0XDBbyrOh0Q=,iv:0sIDeJVrY24P510GMkS3u+13awN/3ID+5wgmKTeqTSI=,tag:Jdatj9uiFKElNCQYVGKxmg==,type:str]
  - TUNNEL_METRICS=localhost:2000
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyAyY2Ry
        czJiZGt1bEZqOFl5N2VONG5LN1lRYjJrSEtsY2ZPdXkvYVZGdXg4CmJia0FzWWxF
        Vng1eW03YnBwQ0xkS2FIVmV5RzhqSWRRSmw4czVJUlV0cG8KLS0tIFFjcmJJc05z
        T2RoL3dLRS9qalJPUDV1V0tvcVVhZ1pIZElQMlZaVjlGUDAKeQalTyFyj17Xt9tF
        t1ZKZbn25Cm16AzX7LNUQ8q232PNhGa05H6KEO5VTEcS+qW7DVXmamd9Rd13DTd5
        Qrao9w==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVNldPQlY3OUhyK0lXS1c2
        V3VDVEI4TGkwc045TEIzVWlZTTNVOWlHV2hFCmY1M3pSSDFNaHp3OFZSeGsrWmVo
        LzRtYWRtbTNCM211V3pucldTVkZiZVEKLS0tIHo5Q1FZbnpwVXZQNXdvMFZJSU50
        TUtxSW1XZm5xSzFXeUNCbERsVGV6UncKHO2+7aq6VNZ1bMGstolvW+umoe4V67ai
        /q7hFqehlCOFro/RzNT1EEZNPXctQ/ecjuMEe0pZmBBZ8QxS0E5BnA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-26T15:54:57Z"
  mac: ENC[AES256_GCM,data:gx3b3D8VR7QAEfexSM2y8y8tRq2UXnGpYN9AoFokgTIV7FtBx2sAP65rkmqdFKG9FLk9bx3t+UrOrO56hGjtip4kQsO2dUR5QhCcKsk4uYRxd6JrnwViVdWonsScAJFDDzDbQDfNBMhyVNJewiU6zRnkDsw8B6ONrSmTpCwn2N0=,iv:aJ4LEXi6fh1JN2AJasOf8xVwpM0Wq0Pf3x0jd33HoAI=,tag:8Y1gZVYc3qx3llDc01eXng==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: ExtensionServiceConfig
name: tailscale
environment:
  # enc!
  - ENC[AES256_GCM,data:BBXd5W5BTig8SITmO+bkI0HNCubGaHK2jzchLAdMM3qllgYgr92Uw2Bu3/hkcNn3OrgdvsRJvV0LXlA=,iv:zgT1ZJSXorNu1V0wkezGtQxrbOTICx4/XTOrpu+SqVk=,tag:eiWOJY+xULMJ17GvhU4c/w==,type:str]
  - TS_EXTRA_ARGS=--login-server=https://hs.vrtx.sh --ssh --accept-routes=true --snat-subnet-routes=false
  # need to toggle this to "false" for changes to ^ to apply, containerboot doesn't consider TS_EXTRA_ARGS
  # when running tailscale set:
  # https://github.com/tailscale/tailscale/blob/f36eb81e6105401b814548393cc90673abe24639/cmd/containerboot/tailscaled.go#L149
  - TS_AUTH_ONCE=true
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyAyY2Ry
        czJiZGt1bEZqOFl5N2VONG5LN1lRYjJrSEtsY2ZPdXkvYVZGdXg4CmJia0FzWWxF
        Vng1eW03YnBwQ0xkS2FIVmV5RzhqSWRRSmw4czVJUlV0cG8KLS0tIFFjcmJJc05z
        T2RoL3dLRS9qalJPUDV1V0tvcVVhZ1pIZElQMlZaVjlGUDAKeQalTyFyj17Xt9tF
        t1ZKZbn25Cm16AzX7LNUQ8q232PNhGa05H6KEO5VTEcS+qW7DVXmamd9Rd13DTd5
        Qrao9w==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVNldPQlY3OUhyK0lXS1c2
        V3VDVEI4TGkwc045TEIzVWlZTTNVOWlHV2hFCmY1M3pSSDFNaHp3OFZSeGsrWmVo
        LzRtYWRtbTNCM211V3pucldTVkZiZVEKLS0tIHo5Q1FZbnpwVXZQNXdvMFZJSU50
        TUtxSW1XZm5xSzFXeUNCbERsVGV6UncKHO2+7aq6VNZ1bMGstolvW+umoe4V67ai
        /q7hFqehlCOFro/RzNT1EEZNPXctQ/ecjuMEe0pZmBBZ8QxS0E5BnA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-26T15:54:57Z"
  mac: ENC[AES256_GCM,data:gx3b3D8VR7QAEfexSM2y8y8tRq2UXnGpYN9AoFokgTIV7FtBx2sAP65rkmqdFKG9FLk9bx3t+UrOrO56hGjtip4kQsO2dUR5QhCcKsk4uYRxd6JrnwViVdWonsScAJFDDzDbQDfNBMhyVNJewiU6zRnkDsw8B6ONrSmTpCwn2N0=,iv:aJ4LEXi6fh1JN2AJasOf8xVwpM0Wq0Pf3x0jd33HoAI=,tag:8Y1gZVYc3qx3llDc01eXng==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
