cluster:
  network:
    podSubnets:
      - 10.41.0.0/16
      - 2001:cafe:41::/56
    serviceSubnets:
      - 10.43.0.0/16
      - 2001:cafe:43::/112
  proxy:
    disabled: true
machine:
  network:
    kubespan:
      enabled: false
    # enc!
    extraHostEntries:
      - ENC[AES256_GCM,data:cyQpZnALMtt1p7IGZQ==,iv:lhbU6DzuQN5S7LWfgrUIcRaA7ju1dwrG3ySDFvBF2Q0=,tag:UqBXMXwgwJSjfqxmXFL08A==,type:comment]
      - ip: ENC[AES256_GCM,data:wBTHzAejiGwa0y3U4h7onGh4TLRbfZLt2A==,iv:xnDqnBpwo5LuAZzqxBEu4EMGOU3ri5hbG3UvM6dpSTs=,tag:NVxpcv0fyvKxCzpD0IwupA==,type:str]
        aliases:
          - ENC[AES256_GCM,data:LMqSJAjFdQouZA==,iv:HPkm4noEfKkzVld/wpIAoC2cHb8LHw3lXvImdaIviFY=,tag:Q899BtkyORhvRVsJUCG9pQ==,type:str]
      - ip: ENC[AES256_GCM,data:wO/1Lqc3li5uAQbK2vZ7cRThR8xgxsdejL0=,iv:jdR5/mUThhT+DTiCB1LAx+B0ruWmkHcJzePpP1+Tef8=,tag:XGQN9OVLgkzR+dWob8yn+Q==,type:str]
        aliases:
          - ENC[AES256_GCM,data:T0mkvQ4cldeLow==,iv:X6TSMeakwVzQipK4nabR6bXAdRkKCLpc08eN7bj5XxI=,tag:vFrFOobyan2R1ti9weyyLA==,type:str]
      - ENC[AES256_GCM,data:Fd1V4hTAxok=,iv:DonE66ZZbp2GqeTdMA7CtxwpX5bIuz872XGYI6rtcoI=,tag:1cxseXEyLh8dSAxT8+r5EQ==,type:comment]
      - ip: ENC[AES256_GCM,data:rNhSxX+NmtS8KJzcXV0=,iv:2Y6n4vZL03MEadj4Kd+HyDfBkG3I9N5szTxFFqgeyto=,tag:n20sTgMcUxUV6/A4Okc1Dw==,type:str]
        aliases:
          - ENC[AES256_GCM,data:FqVIyJob0ET1DA==,iv:R3w/PUe4F7LfTHcFjJPRGT4fpkS1WuLMk5NZd37/YOg=,tag:lcDHciSUZnZnS6UZVphPpw==,type:str]
      - ENC[AES256_GCM,data:tpOz5PSz,iv:x9zcZy2E5N+1iVpGpGExOQDZyl7xfrTdk+UpeLDF0AE=,tag:GBjR5f9ciiqTvfQ3l3u83w==,type:comment]
      - ip: ENC[AES256_GCM,data:SAVJUY6cXEgOnRuiLwQ=,iv:qdZJehtd61Ps6+JJc+Lei8zcMc9tTx4lL0tt+Ip2UkY=,tag:OjGbXkokS2Hhg8w7Ubkzsw==,type:str]
        aliases:
          - ENC[AES256_GCM,data:tJkB06a16VU0fe5bHR+QZqGCE3nAUWlmakQ=,iv:wGS5LXpqtN0DwrOepcfg77Vsh+1BUP8pMkL8/Gowr6k=,tag:QXl2u7vYDL1dOAv9swPnSg==,type:str]
      - ip: ENC[AES256_GCM,data:sFQZkV1eoUrDYFK6Bn81rAZ5oRQ=,iv:ag/mANpaIzjQX7O4Fx1WSt0mS5tgcnWn25WrKsiY2VA=,tag:gujjfYknAexvNmIa+mqZrA==,type:str]
        aliases:
          - ENC[AES256_GCM,data:gVBQCqxUdUZsdwwup1SiCZyk4VQ22H9bBlk=,iv:bG/WTJObvGSlSSVeArqv4ior5R42cZh+I92T1n21bmo=,tag:VkMgIYfW5V1ZnnOaK+mqig==,type:str]
          - ENC[AES256_GCM,data:+RKbKZd5kveNvw==,iv:3zI3clbx+biAxby6d6mvY8w+ZyWYd3/njhFLbwRaTx8=,tag:uWNi9mgErSz7Qm1Nq6tIqg==,type:str]
      - ip: ENC[AES256_GCM,data:iAACsIPGVE8KkuGlTg==,iv:1qi12e0wrKTT5+qRX4OaAqzdApg77sZHSjgMeJEIR+s=,tag:YhxruiyV57VvDUlr0lhLOQ==,type:str]
        aliases:
          - ENC[AES256_GCM,data:gydJx42uL8DiyK4f8/BstgCpbqxL6XkA4LU=,iv:60LDv5JD6Et5IXw6mKiFScCBHJR6wfZygmu4O0BJzUc=,tag:LplxjMjWxB0cyosW2baw1A==,type:str]
          - ENC[AES256_GCM,data:qH/RtYIc8O6/uQ==,iv:j/LPZGWBOvAVggQVOY/lP3tNqhaHb7ZssJxwUt2pgNQ=,tag:NvTT+xG3dVtit1FoUmzjgw==,type:str]
      - ENC[AES256_GCM,data:pBOaxeg=,iv:p5ddM8KH6G9h7lThKgGOCBBzNUy7jFKSUkbDySoQIwc=,tag:CaTYSOgDZdY7SVh3tUZsGg==,type:comment]
      - ip: ENC[AES256_GCM,data:LgWQTZM/zxj2V8oTyCc=,iv:7xfpe0jvFE4bFHSIftwtozQRCQRPyOfxYcdWb+qFpwM=,tag:sLPTZ/8LAp9AO7cudPN7Ow==,type:str]
        aliases:
          - ENC[AES256_GCM,data:/7cyOzeGwATsRjL0qrK+7e976PAU+TmNXho=,iv:cjKkrpZACeHY7tsxWDy3iyd0K28sBOLW3y0BJAJef2s=,tag:RFW0Yv3JojfMf/Eonxv2Tw==,type:str]
      - ip: ENC[AES256_GCM,data:whFj37aLM91yfSs8ueuN94mjBEY5B1Ug,iv:6bYXAie/Q/e/EV1qI6vDSTAUHYXKgguW6+WUSCsoxbg=,tag:1LXEVlF4h48DJALl5lsoPQ==,type:str]
        aliases:
          - ENC[AES256_GCM,data:q+QsUGTyL1CW5PlFwKLV6S7REC8vVQtOQgA=,iv:jvNt995kidf3Xkyaet9GqfnF5+dBcBkL/1HZej9725A=,tag:gaf0z3bbDfp5+j/HDbvTkA==,type:str]
      - ip: ENC[AES256_GCM,data:GaV/2vsIQau8cGdz+qyxZULjr0VAjTY9,iv:rcNkyi7bwZUTIShOtVTF18hoZe0L/96Km9HreCq58XI=,tag:MAwAS5pYRrj5zyXHXa7P0A==,type:str]
        aliases:
          - ENC[AES256_GCM,data:EKCoCNPNQzTDHw==,iv:+7VV3g+2ubP1eXEb1yhK92A9N5LXo6wSR5rERJN9vpk=,tag:iyMe7xPO1HnsCqRxWTgQtQ==,type:str]
      - ENC[AES256_GCM,data:dxgyNlw=,iv:9tZjU+yAt6TeF2D5UXH/XB0oIeMLKBljt4daC+xY4gk=,tag:xEv6ggKvZVW95rk/Cnf0Hg==,type:comment]
      - ip: ENC[AES256_GCM,data:fP22u7vxq59vXPS0rw==,iv:GVOtu3LO2fSCylTTDfTYBD64YzMt/iYJYHk8BrWOP+E=,tag:D4Vbq8BU8rD3gKHdGMf5Vw==,type:str]
        aliases:
          - ENC[AES256_GCM,data:5xjt6zqMfgVrB2ATiDSAI3a3iokx/Dg9ApE=,iv:c4JhSVWRDjGU47M43jSFU5zpWJ2XruZwgCgl7buHgPs=,tag:FVCDNbzvH3eti3eIx5othg==,type:str]
      - ip: ENC[AES256_GCM,data:at4HeRTqdXabbX7MUR1H49BGWKBK+7C+,iv:X89r9rm95qXFJhGnYUDimEA3jhewuZN4G+YhwVArtxo=,tag:RFJLj5XFHp+cyPA2fOQNpQ==,type:str]
        aliases:
          - ENC[AES256_GCM,data:SqhsipRZoHvaqJNwbiEuy+pVXQLJPJAV9Gg=,iv:e2u/WI5R+7TMIf40Q5bmmk7ZZtg6ja/anbU4edKhv3s=,tag:sj7O8we2/e/hY8WDKF/0rg==,type:str]
      - ip: ENC[AES256_GCM,data:zV/nO1UOYNWWHuVox2wgToLnYPzrAaYy,iv:wyArXRYSrqLYYfEZSJWEsIpHGuBFZr3a3Yziy+j8mWU=,tag:hs8GEiU99XVkPnoWdAB/UQ==,type:str]
        aliases:
          - ENC[AES256_GCM,data:sAA1fuoB5tC/9A==,iv:Nl5f71hvYlIbD1Lth4vwcQyT4k01Sy0g+qYIEGhgcfg=,tag:7JkKj990UhFRdoFLyayKww==,type:str]
      - ENC[AES256_GCM,data:cEViietQ,iv:qtMhYH0cksePKI+huMNOiIyMY3RIaxzGeEgAje9GfbI=,tag:lm7Y65clHOsJzXcKqXS+Kg==,type:comment]
      - ip: ENC[AES256_GCM,data:E4+3YYWyWAHJOQd8Ai6AAdUrO3YGR0zR,iv:N47usX6CqvV77DRhipGXYpsNSqvtmydsIu1mwPjjOGU=,tag:aUhVI5ag4TG3DU1yrA1yoQ==,type:str]
        aliases:
          - ENC[AES256_GCM,data:PFku4AjzS8ndWQ==,iv:4/20IBvNhYMSKOXqQQUiBXUp50pX5/jzqQmtXJtGFlo=,tag:LIxpR0P8TuR3pJ4AJqnS0Q==,type:str]
      - ENC[AES256_GCM,data:Brynm8PHvIs=,iv:qymeKAQHwoexY/KKND/Sw/pvoVJcl0eBi5ILQLa8WAs=,tag:xR7HdQskbkWRMoivaWovsQ==,type:comment]
      - ip: ENC[AES256_GCM,data:lvlzoyNtewMdphEYDadv63A3Z0HM4hif,iv:baGFC8iwYx4PzOZ5OSQ0pYA6cU24uHqsVyTA2CDeLMQ=,tag:Oiz53M1hflAtZeKA+R9ozQ==,type:str]
        aliases:
          - ENC[AES256_GCM,data:AARkFs4pSUaSEw==,iv:Pl9Gb5bFPEc6MvO1O2tfy9khA0vrLZfEjGlTnZIbWwE=,tag:Ocze9Ol0LhVPhyRuUDDFhQ==,type:str]
  sysctls:
    # 128MiB
    vm.min_free_kbytes: 131072
    vm.watermark_scale_factor: 50
    fs.inotify.max_user_watches: 4194304
    fs.inotify.max_user_instances: 65536
    user.max_user_namespaces: 65536
    net.ipv4.ip_forward: 1
    net.ipv6.conf.all.forwarding: 1
    # https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes
    net.core.rmem_max: 7500000
    net.core.wmem_max: 7500000
  kubelet:
    nodeIP:
      validSubnets:
        - 100.64.0.0/10
        - fd7a:115c:a1e0::/48
    extraArgs:
      rotate-server-certificates: true
    extraMounts:
      - destination: /var/lib/longhorn
        type: bind
        source: /var/lib/longhorn
        options:
          - bind
          - rshared
          - rw
    extraConfig:
      # kubelet serving certs
      serverTLSBootstrap: true
      memorySwap:
        swapBehavior: LimitedSwap
  features:
    hostDNS:
      resolveMemberNames: true
  nodeLabels:
    hugeloads.sophons.cloud/longhorn: "true"
    hugeloads.sophons.cloud/postgres: "true"
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBEd0xW
        b1JnUzJFcnZCOCt0cEErMWVqQWcvUTJIdStoYkVnOG80RlVjTzJ3Cml4ejJxdkZq
        ZFVjVFQ1d3RJSSswemtkZTB0S2gyT0hHUTFnaGMyODg0R1UKLS0tIFNTR3YxRDB5
        emxnWG9tVDFabFhBUmhQY1h6NU5rM01DZkNjNnRTUkFTWmMKXe0hQWU5M/bR7EOB
        agqXoLIq+E2gfGh6Y0H0V0pPtP7v2jrGOd0JB3rrq+lPTRxflvYOWgeMSoSjqBUp
        whYmzQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSYndjb0FURUdpdUgySVRr
        YTMrTEdZV0xTeU1VankrcFFiSWtsSFJVSmgwCmhjc2ZKNFBid0daRmV4OUZRT1lU
        TlhEblFjd3AzR25WYk10U3hSMmNKc1kKLS0tIFhXQWFvY2p1Z1kwaGs3RlFCQUtt
        OFpib1Qxa212NXV5VnRoeUtpYUVVbUkKuW9GluCuel0XjBeiX2fdTDeYUxYrBUy7
        qsZ69WAzeEkQfOvk5V3OcIndNLEIyox7Xc+fna23vBspOPxEo4OVtA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T13:27:54Z"
  mac: ENC[AES256_GCM,data:pQqkOPdS20KH54/iNL25SMRK482gqzCpzBhZWrlS8/KVO4D2DOwCdvGMmcToll4gu1d7sXVEPo+IRlsLBlsoqOFStAwCQjupl/DGyNouiuvKjK6nEjYv1I+5+eOJVfClGBRwe0Vibx484Z9fTda7wZq29u5doA68Xx5ACKbSR70=,iv:AdzQvK5jZxAJr4GZRInOfimtKFDuh0wzOXaCF8kPCNw=,tag:NDYjQreBMPv1ShpDyJzT7A==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: ZswapConfig
# The maximum percent of memory that zswap can use.
maxPoolPercent: 25
# Enable the shrinker feature: kernel might move
shrinkerEnabled: true
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBEd0xW
        b1JnUzJFcnZCOCt0cEErMWVqQWcvUTJIdStoYkVnOG80RlVjTzJ3Cml4ejJxdkZq
        ZFVjVFQ1d3RJSSswemtkZTB0S2gyT0hHUTFnaGMyODg0R1UKLS0tIFNTR3YxRDB5
        emxnWG9tVDFabFhBUmhQY1h6NU5rM01DZkNjNnRTUkFTWmMKXe0hQWU5M/bR7EOB
        agqXoLIq+E2gfGh6Y0H0V0pPtP7v2jrGOd0JB3rrq+lPTRxflvYOWgeMSoSjqBUp
        whYmzQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSYndjb0FURUdpdUgySVRr
        YTMrTEdZV0xTeU1VankrcFFiSWtsSFJVSmgwCmhjc2ZKNFBid0daRmV4OUZRT1lU
        TlhEblFjd3AzR25WYk10U3hSMmNKc1kKLS0tIFhXQWFvY2p1Z1kwaGs3RlFCQUtt
        OFpib1Qxa212NXV5VnRoeUtpYUVVbUkKuW9GluCuel0XjBeiX2fdTDeYUxYrBUy7
        qsZ69WAzeEkQfOvk5V3OcIndNLEIyox7Xc+fna23vBspOPxEo4OVtA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T13:27:54Z"
  mac: ENC[AES256_GCM,data:pQqkOPdS20KH54/iNL25SMRK482gqzCpzBhZWrlS8/KVO4D2DOwCdvGMmcToll4gu1d7sXVEPo+IRlsLBlsoqOFStAwCQjupl/DGyNouiuvKjK6nEjYv1I+5+eOJVfClGBRwe0Vibx484Z9fTda7wZq29u5doA68Xx5ACKbSR70=,iv:AdzQvK5jZxAJr4GZRInOfimtKFDuh0wzOXaCF8kPCNw=,tag:NDYjQreBMPv1ShpDyJzT7A==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: ExtensionServiceConfig
name: cloudflared
environment:
  # enc!
  - ENC[AES256_GCM,data:Q1xHzNlJ2VaBawPUeUzSnNWeSiONiwhscdG0dfPaJBH+IHo6vA16G9U3xaAR/4sDIPtsN0kPwD7s1KOFlh7y0M7nRD2G37Ft3bqP+i69kw8NJMzbIOop+tyT6eiztTewsxU64LLiwVBY+b1j4X+5okbB88QBlJcKGTvh6zw0SwVMFujs1ACUNBSXarCK2ZkD/LrIM7I7ZqA5N05EtenNzWAOaUDaPPMGIOUt4P072c0VVba0XIjiqTa3mtVYq/1SDD5Mrcg=,iv:H9GeoDXzXOAPLGup1qBa46PpXyWtp3Z7qC5a5Xq55lE=,tag:f35GZZZAMkeZwtau0dDUzw==,type:str]
  - TUNNEL_METRICS=localhost:2000
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBEd0xW
        b1JnUzJFcnZCOCt0cEErMWVqQWcvUTJIdStoYkVnOG80RlVjTzJ3Cml4ejJxdkZq
        ZFVjVFQ1d3RJSSswemtkZTB0S2gyT0hHUTFnaGMyODg0R1UKLS0tIFNTR3YxRDB5
        emxnWG9tVDFabFhBUmhQY1h6NU5rM01DZkNjNnRTUkFTWmMKXe0hQWU5M/bR7EOB
        agqXoLIq+E2gfGh6Y0H0V0pPtP7v2jrGOd0JB3rrq+lPTRxflvYOWgeMSoSjqBUp
        whYmzQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSYndjb0FURUdpdUgySVRr
        YTMrTEdZV0xTeU1VankrcFFiSWtsSFJVSmgwCmhjc2ZKNFBid0daRmV4OUZRT1lU
        TlhEblFjd3AzR25WYk10U3hSMmNKc1kKLS0tIFhXQWFvY2p1Z1kwaGs3RlFCQUtt
        OFpib1Qxa212NXV5VnRoeUtpYUVVbUkKuW9GluCuel0XjBeiX2fdTDeYUxYrBUy7
        qsZ69WAzeEkQfOvk5V3OcIndNLEIyox7Xc+fna23vBspOPxEo4OVtA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T13:27:54Z"
  mac: ENC[AES256_GCM,data:pQqkOPdS20KH54/iNL25SMRK482gqzCpzBhZWrlS8/KVO4D2DOwCdvGMmcToll4gu1d7sXVEPo+IRlsLBlsoqOFStAwCQjupl/DGyNouiuvKjK6nEjYv1I+5+eOJVfClGBRwe0Vibx484Z9fTda7wZq29u5doA68Xx5ACKbSR70=,iv:AdzQvK5jZxAJr4GZRInOfimtKFDuh0wzOXaCF8kPCNw=,tag:NDYjQreBMPv1ShpDyJzT7A==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: ExtensionServiceConfig
name: tailscale
environment:
  # enc!
  - ENC[AES256_GCM,data:qPwhDbDDizynihHXxvUB8n0iPcZmp2aqti5S34IiynnsSpjBvBXLwsPU7nQspN/Nkcp+wb0duoyR/GU=,iv:mlXYtYzMnEnfFteSXCUyYNQCbVj/FeeW6QFwv7uUo3E=,tag:/3yhCJ+sGSyt3G2x3ZyVCw==,type:str]
  - TS_EXTRA_ARGS=--login-server=https://hs.vrtx.sh --ssh --accept-routes=true --snat-subnet-routes=false
  # need to toggle this to "false" for changes to ^ to apply, containerboot doesn't consider TS_EXTRA_ARGS
  # when running tailscale set:
  # https://github.com/tailscale/tailscale/blob/f36eb81e6105401b814548393cc90673abe24639/cmd/containerboot/tailscaled.go#L149
  - TS_AUTH_ONCE=true
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBEd0xW
        b1JnUzJFcnZCOCt0cEErMWVqQWcvUTJIdStoYkVnOG80RlVjTzJ3Cml4ejJxdkZq
        ZFVjVFQ1d3RJSSswemtkZTB0S2gyT0hHUTFnaGMyODg0R1UKLS0tIFNTR3YxRDB5
        emxnWG9tVDFabFhBUmhQY1h6NU5rM01DZkNjNnRTUkFTWmMKXe0hQWU5M/bR7EOB
        agqXoLIq+E2gfGh6Y0H0V0pPtP7v2jrGOd0JB3rrq+lPTRxflvYOWgeMSoSjqBUp
        whYmzQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSYndjb0FURUdpdUgySVRr
        YTMrTEdZV0xTeU1VankrcFFiSWtsSFJVSmgwCmhjc2ZKNFBid0daRmV4OUZRT1lU
        TlhEblFjd3AzR25WYk10U3hSMmNKc1kKLS0tIFhXQWFvY2p1Z1kwaGs3RlFCQUtt
        OFpib1Qxa212NXV5VnRoeUtpYUVVbUkKuW9GluCuel0XjBeiX2fdTDeYUxYrBUy7
        qsZ69WAzeEkQfOvk5V3OcIndNLEIyox7Xc+fna23vBspOPxEo4OVtA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T13:27:54Z"
  mac: ENC[AES256_GCM,data:pQqkOPdS20KH54/iNL25SMRK482gqzCpzBhZWrlS8/KVO4D2DOwCdvGMmcToll4gu1d7sXVEPo+IRlsLBlsoqOFStAwCQjupl/DGyNouiuvKjK6nEjYv1I+5+eOJVfClGBRwe0Vibx484Z9fTda7wZq29u5doA68Xx5ACKbSR70=,iv:AdzQvK5jZxAJr4GZRInOfimtKFDuh0wzOXaCF8kPCNw=,tag:NDYjQreBMPv1ShpDyJzT7A==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
