cluster:
  network:
    cni:
      name: none
machine:
  install:
    disk: /dev/vda
  nodeLabels:
    topology.kubernetes.io/region: ng
    topology.kubernetes.io/zone: ng-middle-east
  network:
    hostname: sophons-kaos
    interfaces:
      - interface: lo
        addresses:
          # enc!
          - ENC[AES256_GCM,data:WZU2ndkv6mqwj0sQNZ7FaDvttSEqrYBsiQdbow==,iv:y6rXbuW7XGVJfBBRPpUigC2IjVp2JHlbsKgIe4K+CAo=,tag:i8OkfcNsvMSBN4ixd6XYhg==,type:str]
          # enc!
          - ENC[AES256_GCM,data:OpSyx/KDGzr8RPWf4SLcZax7kQd9zh2IevVQ2g==,iv:lfPAzwo7xIEYlD5iAyKqzJDavi4ionEb1l6Bev679u4=,tag:HYFF4k9fO6ZRqHtqY9IcBA==,type:str]
          - fdf6:9420:fade:67::3/128
      - interface: enp1s0
        dhcp: true
        dhcpOptions:
          ipv4: false
          ipv6: true
        addresses:
          - 10.42.69.4/16
          # enc!
          - ENC[AES256_GCM,data:obMM9l+GqfAU/iD/WGFCpKdOBsOcmWVDb2prlJ2MyQ==,iv:3mvo9yciLBFBCq7C+iK0TErDc0NNvLPGlO1yaNOBUzk=,tag:NafypK0a/QtknsVqLkLX1w==,type:comment]
        routes:
          - network: 0.0.0.0/0
            gateway: 10.42.0.1
          - network: ::/0
            gateway: fe80::9c05:d6ff:fe69:64b7
            metric: 200
      - interface: enp2s0
        dhcp: false
        addresses:
          - 10.69.0.4/16
          # enc!
          - ENC[AES256_GCM,data:v9wxiBA+RXLCkKZCLGFp0/ldtxwYrSfMYiUwBcOL5A==,iv:9vNCGmpiN1l8nDxWNQlgFO/a9kps9yEZwEERjBTxtcc=,tag:VPl6pt3b9QnWxvmEXPosxg==,type:comment]
        routes:
          - network: 0.0.0.0/0
            gateway: 10.69.0.1
          - network: ::/0
            gateway: fe80::9c05:d6ff:fe69:64b7
            metric: 200
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyB6TFl4
        Q3ZLbXh2cmIzekpPdjZwSzJ5d0djMEdGZVBSeEJIWnc4RFRUY1JnClBMeVlDV3N5
        Yk9VTVNlNC8zM2pzQzFYRlY4MzRPVEJPNGJ5WHlyL1FmSjAKLS0tICtCa1Brbmhr
        U2g3Y2NGeE44YVpkTGV4cWNQVXI0QzQreFZSKytTVHFwWlEK1KwNobE+dEQV6f9M
        jmP3L5UNVI2/4iFrz5yXNHvMMPJRa711KGPiSmguHevdwyqby5d4SNrhQDDXdtEr
        BXY4Ag==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvR1ZTNlVlT3kySFFGK3JM
        N01KWXd1dXNTUXN3aEU3Rks0SE5qdEV5bUJVCllqWjFLaEEvS1dWN0xKbXZQV0dD
        OWp2QUFVcG1LY05obmpzMFV5WFRacWcKLS0tIFdYMnl2TmhoU0ZMWEF0SHY5Ynh3
        a1dNY29CR2JWaUpGVFpVcEZ1b3h4UXMKPEJmBybWMZ5Jcv76CNSEGw/7YPKa11QD
        bQ0914tpEGP2niAQTMykSxJGy9grgFt69dLhE9titMrBkVGhhNiJpg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-03T05:46:08Z"
  mac: ENC[AES256_GCM,data:95OMNpBIxIkZTIZ0ZvuXs/1eTH7OK9625SfRhVIeQQcT0s9VsoXZtLuarjirRuyeGkCSLZetZ+B7H65cFQJK0P3WchLo22toOrPp9P6IXYHvo2zZltYQX7RqIQJgYmK1XQk2k6Pg+i1kWfWOwLw0x2zLIdjFk5GGz98vGrGTGcs=,iv:AeymS126GhQofIhMSqtvxRm/Yb/lXvtMUROHBD+yiS8=,tag:qEljcUaThSzDiX/kMQrIiA==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: ExtensionServiceConfig
name: tailscale
environment:
  #enc!
  - ENC[AES256_GCM,data:A3BrbbKSw/4In96z72PG8tHMqKWF0QPypi++eMVSRAXy3KiDR5fy5BviXlB8PqHp0LydcMrvt65gm4wjgJHy1SlMYFHIp9uMhnkDefuEAw7laMN1Uga+3bg1n5gWuhbVMThIrrN0RfaVZFYQy7VCkU8ZnDortR+fSvyYdljLKfNDZzJfJil4hk5Aq9ATYjwdnPFfYPRARbdlZudVrCGjC7pHcJw=,iv:rNGIR4g5T4j5x4cRN8zUI5f8Vp/K1y7WqQBQ+kewLog=,tag:wjLs/y4HtISFlfmSU9xU+Q==,type:str]
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyB6TFl4
        Q3ZLbXh2cmIzekpPdjZwSzJ5d0djMEdGZVBSeEJIWnc4RFRUY1JnClBMeVlDV3N5
        Yk9VTVNlNC8zM2pzQzFYRlY4MzRPVEJPNGJ5WHlyL1FmSjAKLS0tICtCa1Brbmhr
        U2g3Y2NGeE44YVpkTGV4cWNQVXI0QzQreFZSKytTVHFwWlEK1KwNobE+dEQV6f9M
        jmP3L5UNVI2/4iFrz5yXNHvMMPJRa711KGPiSmguHevdwyqby5d4SNrhQDDXdtEr
        BXY4Ag==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvR1ZTNlVlT3kySFFGK3JM
        N01KWXd1dXNTUXN3aEU3Rks0SE5qdEV5bUJVCllqWjFLaEEvS1dWN0xKbXZQV0dD
        OWp2QUFVcG1LY05obmpzMFV5WFRacWcKLS0tIFdYMnl2TmhoU0ZMWEF0SHY5Ynh3
        a1dNY29CR2JWaUpGVFpVcEZ1b3h4UXMKPEJmBybWMZ5Jcv76CNSEGw/7YPKa11QD
        bQ0914tpEGP2niAQTMykSxJGy9grgFt69dLhE9titMrBkVGhhNiJpg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-03T05:46:08Z"
  mac: ENC[AES256_GCM,data:95OMNpBIxIkZTIZ0ZvuXs/1eTH7OK9625SfRhVIeQQcT0s9VsoXZtLuarjirRuyeGkCSLZetZ+B7H65cFQJK0P3WchLo22toOrPp9P6IXYHvo2zZltYQX7RqIQJgYmK1XQk2k6Pg+i1kWfWOwLw0x2zLIdjFk5GGz98vGrGTGcs=,iv:AeymS126GhQofIhMSqtvxRm/Yb/lXvtMUROHBD+yiS8=,tag:qEljcUaThSzDiX/kMQrIiA==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
