apiVersion: v1alpha1
kind: HostnameConfig
auto: "off"
hostname: sophons-leistung
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBQQmlK
        dlJQaXpzcis4UVFja3l1SDFHemV1MU5tZFlkSjZZN08zRE1RbjEwCjZwVXIzMTNk
        cWpCYWdqNG1xVnZNOVNUdDNydkNFMXIySWZ0M0p2VVNsMG8KLS0tIFc3NkVFcE5X
        Y1BzZEYwMG9wUG5kU0diMTQzN2hRV0ljMXBOTjh6SFlWYXcKdP/zCMo7/v8TJza9
        ItYV2WStmb7nxrLug1f6iiaDJqLMD+FRJ8DqvpcHRCn4o5Zcnpmo6bU/2IrvDjbY
        GbI48w==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcUV0L3l3YzI5SHEvR2Rt
        ZGtpNTgyR0pDUHppWlZZREZZODdPZjh3dlZrCmQwT3FlK3oxSzFWdFhmc0d5QXpQ
        MERtMk1YbFBGbGoxODlERHJhVHJNSGcKLS0tIHV0akFOZmJTYzg0SXNrbVJzWThO
        WWYzODdwMDhaYnFkWjdkMnM4SEx1TE0K+zelc9cDoVOAkCk1zRDeYKmrnXLhCcNJ
        Vn5+UTaJP0dAHosPz6WlfZYPojxQ5IRCGpJ25HT6pVmUHFE5ur9sQw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-08-28T20:03:06Z"
  mac: ENC[AES256_GCM,data:H6R33TQ4EawfZy6UloqHdz9Aw6pY21OjD1/Xk5EdY3Hcf6fYDLpzNevL9IBpG+DlO/LUP06H0Ujq3gEu5RUnYDlstwvDT9bc4lea53Bw04OSeV1SwmphE5fYZTuaisITYum4mYHd5zy33FTZeXJmyIQg3CrYuPTw1HrBQyKGD4g=,iv:W7Vt+5aA34BFviL32357E4oh0h3tmhH4BcTb2E0I49w=,tag:wsZr8f53WsZO9AN1rZvAhQ==,type:str]
  version: 3.13.3
---
cluster:
  network:
    cni:
      name: none
machine:
  install:
    disk: /dev/vda
  nodeLabels:
    egress.sophons.cloud/ci-ipv6: "true"
    topology.kubernetes.io/region: de
    topology.kubernetes.io/zone: de-east-2
    hugeloads.sophons.cloud/garage: "true"
    cluster.garage.sophons.cloud/global: "true"
    weed.sophons.cloud/cluster: global
    weed.sophons.cloud/master: "true"
    weed.sophons.cloud/volume: "true"
    weed.sophons.cloud/filer: "true"
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBQQmlK
        dlJQaXpzcis4UVFja3l1SDFHemV1MU5tZFlkSjZZN08zRE1RbjEwCjZwVXIzMTNk
        cWpCYWdqNG1xVnZNOVNUdDNydkNFMXIySWZ0M0p2VVNsMG8KLS0tIFc3NkVFcE5X
        Y1BzZEYwMG9wUG5kU0diMTQzN2hRV0ljMXBOTjh6SFlWYXcKdP/zCMo7/v8TJza9
        ItYV2WStmb7nxrLug1f6iiaDJqLMD+FRJ8DqvpcHRCn4o5Zcnpmo6bU/2IrvDjbY
        GbI48w==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcUV0L3l3YzI5SHEvR2Rt
        ZGtpNTgyR0pDUHppWlZZREZZODdPZjh3dlZrCmQwT3FlK3oxSzFWdFhmc0d5QXpQ
        MERtMk1YbFBGbGoxODlERHJhVHJNSGcKLS0tIHV0akFOZmJTYzg0SXNrbVJzWThO
        WWYzODdwMDhaYnFkWjdkMnM4SEx1TE0K+zelc9cDoVOAkCk1zRDeYKmrnXLhCcNJ
        Vn5+UTaJP0dAHosPz6WlfZYPojxQ5IRCGpJ25HT6pVmUHFE5ur9sQw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-08-28T20:03:06Z"
  mac: ENC[AES256_GCM,data:H6R33TQ4EawfZy6UloqHdz9Aw6pY21OjD1/Xk5EdY3Hcf6fYDLpzNevL9IBpG+DlO/LUP06H0Ujq3gEu5RUnYDlstwvDT9bc4lea53Bw04OSeV1SwmphE5fYZTuaisITYum4mYHd5zy33FTZeXJmyIQg3CrYuPTw1HrBQyKGD4g=,iv:W7Vt+5aA34BFviL32357E4oh0h3tmhH4BcTb2E0I49w=,tag:wsZr8f53WsZO9AN1rZvAhQ==,type:str]
  version: 3.13.3
---
# https://tailscale.com/docs/reference/best-practices/performance#linux-optimizations-for-subnet-routers-and-exit-nodes
apiVersion: v1alpha1
kind: EthernetConfig
name: ens3
features:
  rx-gro-list: "off"
  rx-udp-gro-forwarding: "on"
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBQQmlK
        dlJQaXpzcis4UVFja3l1SDFHemV1MU5tZFlkSjZZN08zRE1RbjEwCjZwVXIzMTNk
        cWpCYWdqNG1xVnZNOVNUdDNydkNFMXIySWZ0M0p2VVNsMG8KLS0tIFc3NkVFcE5X
        Y1BzZEYwMG9wUG5kU0diMTQzN2hRV0ljMXBOTjh6SFlWYXcKdP/zCMo7/v8TJza9
        ItYV2WStmb7nxrLug1f6iiaDJqLMD+FRJ8DqvpcHRCn4o5Zcnpmo6bU/2IrvDjbY
        GbI48w==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcUV0L3l3YzI5SHEvR2Rt
        ZGtpNTgyR0pDUHppWlZZREZZODdPZjh3dlZrCmQwT3FlK3oxSzFWdFhmc0d5QXpQ
        MERtMk1YbFBGbGoxODlERHJhVHJNSGcKLS0tIHV0akFOZmJTYzg0SXNrbVJzWThO
        WWYzODdwMDhaYnFkWjdkMnM4SEx1TE0K+zelc9cDoVOAkCk1zRDeYKmrnXLhCcNJ
        Vn5+UTaJP0dAHosPz6WlfZYPojxQ5IRCGpJ25HT6pVmUHFE5ur9sQw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-08-28T20:03:06Z"
  mac: ENC[AES256_GCM,data:H6R33TQ4EawfZy6UloqHdz9Aw6pY21OjD1/Xk5EdY3Hcf6fYDLpzNevL9IBpG+DlO/LUP06H0Ujq3gEu5RUnYDlstwvDT9bc4lea53Bw04OSeV1SwmphE5fYZTuaisITYum4mYHd5zy33FTZeXJmyIQg3CrYuPTw1HrBQyKGD4g=,iv:W7Vt+5aA34BFviL32357E4oh0h3tmhH4BcTb2E0I49w=,tag:wsZr8f53WsZO9AN1rZvAhQ==,type:str]
  version: 3.13.3
---
apiVersion: v1alpha1
kind: LinkConfig
name: ens3
addresses:
  # enc!
  - address: ENC[AES256_GCM,data:Qj1RnUuaAzGCqULyG1k++BDp,iv:dkQfvhVsRbsaF5qiBHW2WfRem5F8TAuCasQMDM9ed0M=,tag:uAoLUzovXLJnnmJHPA30Ig==,type:str]
  # enc!
  - address: ENC[AES256_GCM,data:ImSiP0iMLi5QP32N0sUVmU0bb+vx,iv:yq/bvH0BJoktjecocAXf20EdBUowClCSBQ0+kAdi6H8=,tag:90bzWklXHVTwAHllUzIPEg==,type:str]
routes:
  - metric: 150
    # enc!
    gateway: ENC[AES256_GCM,data:K7zl33osiFJuCAtAUA==,iv:DqH2DBTXnSz3it/aaN7s4UVegbM9ihLQ8fKOaCB/rcg=,tag:kQp9NYmLC2E2hI4kgm9BEA==,type:str]
  - gateway: fe80::1
    metric: 100
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBQQmlK
        dlJQaXpzcis4UVFja3l1SDFHemV1MU5tZFlkSjZZN08zRE1RbjEwCjZwVXIzMTNk
        cWpCYWdqNG1xVnZNOVNUdDNydkNFMXIySWZ0M0p2VVNsMG8KLS0tIFc3NkVFcE5X
        Y1BzZEYwMG9wUG5kU0diMTQzN2hRV0ljMXBOTjh6SFlWYXcKdP/zCMo7/v8TJza9
        ItYV2WStmb7nxrLug1f6iiaDJqLMD+FRJ8DqvpcHRCn4o5Zcnpmo6bU/2IrvDjbY
        GbI48w==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcUV0L3l3YzI5SHEvR2Rt
        ZGtpNTgyR0pDUHppWlZZREZZODdPZjh3dlZrCmQwT3FlK3oxSzFWdFhmc0d5QXpQ
        MERtMk1YbFBGbGoxODlERHJhVHJNSGcKLS0tIHV0akFOZmJTYzg0SXNrbVJzWThO
        WWYzODdwMDhaYnFkWjdkMnM4SEx1TE0K+zelc9cDoVOAkCk1zRDeYKmrnXLhCcNJ
        Vn5+UTaJP0dAHosPz6WlfZYPojxQ5IRCGpJ25HT6pVmUHFE5ur9sQw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-08-28T20:03:06Z"
  mac: ENC[AES256_GCM,data:H6R33TQ4EawfZy6UloqHdz9Aw6pY21OjD1/Xk5EdY3Hcf6fYDLpzNevL9IBpG+DlO/LUP06H0Ujq3gEu5RUnYDlstwvDT9bc4lea53Bw04OSeV1SwmphE5fYZTuaisITYum4mYHd5zy33FTZeXJmyIQg3CrYuPTw1HrBQyKGD4g=,iv:W7Vt+5aA34BFviL32357E4oh0h3tmhH4BcTb2E0I49w=,tag:wsZr8f53WsZO9AN1rZvAhQ==,type:str]
  version: 3.13.3
