apiVersion: v1alpha1
kind: HostnameConfig
auto: "off"
hostname: sophons-oduduwa
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBNeXp6
        RkU2aFBpSHQ2SXZ0NWZzdEpqMkJOMHAxSmxIeFJUNDliTkhtSnpRCkd6MjlwZzRY
        dHZIZVNOd1lTT3JKbWNST3NjMnVzc1c4UkhlcmNZTEZEeXMKLS0tIDMxWk1aemQv
        WThHQjd5bUQ5R3d4dlhNZitFYUVHOWswbjA4ZndvTU0wQXMKMMtW23HioKCCOfy2
        lTw3zjfxp5hC4v1vn2QY64SGuQKhxbO9hOR0JXBuUuttdygqh9DzL/9WzG/ZrELT
        F3egOg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVXF1ZUovMjE0eThOenZV
        NXpPVHIzemxNeFl2N2lpd0FYYjBWN1BScEhZCjVucjNJajcvUWRpMkFIUlU5cTdu
        WHZOVEtreW5hYTgxRmFwMTlaZjgvNEkKLS0tIG5uM0hTdnN4YVJ0MnlNbllnYW9x
        OUN2alBDUmJLa0xNRk5iRElIWVJ3VFUKMIk1nBP2bM8XxK4iaiHUACydIEq0gvLb
        Ir+3ryunzHBR7dBxW2vhHny5i8v59ufN6PXGc0M1ce1jVFR0O6+Q3w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-27T19:40:45Z"
  mac: ENC[AES256_GCM,data:e2AoE6n10mJyTsNSBCAH9XpDaq5WEAA3j+3IDwg+9I6egzUDwhQ8jtMNzhXJVv2XVnFQcy8WHKIc9Ci+YVqfCxT19Qb4X9I5O1xUeEdE818iIdNOsmMb+YXm/8LRDGdVzrSbveIl8H84WLoogflKgzQCj/65yNSldj3ogyoWQws=,iv:oJBug9nB/UEM/YEBSbJDP79UTYP+dTrMbgXt1xQT3bQ=,tag:0AaMYaaLGXEsarj3ysyYGQ==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
cluster:
  network:
    cni:
      name: none
machine:
  install:
    disk: /dev/sda
  # sysctls:
  #   # 64MiB
  #   vm.min_free_kbytes: 65536
  #   # vm.swappiness: 200
  #   vm.watermark_scale_factor: 50
  kubelet:
    extraConfig:
      mergeDefaultEvictionSettings: true
      evictionSoft:
        memory.available: 256Mi
      evictionSoftGracePeriod:
        memory.available: 15s
      evictionHard:
        memory.available: 100Mi
  nodeLabels:
    topology.kubernetes.io/region: ng
    topology.kubernetes.io/zone: ng-west-1
    hugeloads.sophons.cloud/longhorn: "false"
    hugeloads.sophons.cloud/postgres: "false"
    hugeloads.sophons.cloud/garage: "true"
    cluster.garage.sophons.cloud/global: "true"
    weed.sophons.cloud/cluster: global
    weed.sophons.cloud/volume: "true"
  network:
    interfaces:
      - interface: ens18
        dhcp: false
        # enc!
        addresses:
          - ENC[AES256_GCM,data:UXaNXxGBIY5O1JEzME964B4=,iv:+Lrt4Wr2gaI0VXfVU5OUKgUbtB5kP7bLZBDBM/rESAY=,tag:F4NncnNWZgs8o13hLNalaA==,type:str]
        routes:
          - network: 0.0.0.0/0
            # enc!
            gateway: ENC[AES256_GCM,data:mjYg5e06n3rcvaZtHYM=,iv:KJus6iwA/P9hbK3lk1DSDVCPEu69DHxvdCI7CbxusGg=,tag:+bEX9f03srzBnx4EvOh8zA==,type:str]
  pods:
    - apiVersion: v1
      kind: Pod
      metadata:
        name: tunnelbroker-configurer
        namespace: kube-system
      spec:
        hostNetwork: true
        containers:
          - name: tunnelbroker
            image: docker.io/library/alpine:3.23.3
            env:
              - name: TUN_IPSUBNET
                # enc!
                value: ENC[AES256_GCM,data:JKJtt3fHzsLnCLQO1AbEqCZJ2QonUQ==,iv:UDdwaAyxmugaYspFvDW2LbtF26k0pK8KkUNlRNCM4/4=,tag:DwACc03XU3InangNAeQm5A==,type:str]
              - name: REMOTE_IP
                # enc!
                value: ENC[AES256_GCM,data:jk1dx07yk/VLuhP07A==,iv:FDX4o4koiOM/c7H/JRT26FDWFv+9k/LxVu732kJ1S18=,tag:vuxWtfRS2jbKu7b87Yr3Qw==,type:str]
              - name: LOCAL_IP
                # enc!
                value: ENC[AES256_GCM,data:640+N/9b2VAosrvh5Nc=,iv:2ro+l5+L+q8BLE0CkhfQTGQgdM75pWTbFVNGijyaIgk=,tag:24h7au4EBuueVGJHTk6hug==,type:str]
            command:
              - ash
              - -c
              - |
                set -xeuo pipefail

                if test -z "$(ip tunnel show he-ipv6)"; then
                  ip tunnel add he-ipv6 mode sit remote $REMOTE_IP local $LOCAL_IP ttl 255
                fi
                ip link set he-ipv6 up

                if test -z "$(ip addr show dev he-ipv6 to $TUN_IPSUBNET)"; then
                  ip addr add $TUN_IPSUBNET dev he-ipv6
                fi

                mkfifo /pause
                </pause
            securityContext:
              capabilities:
                drop:
                  - ALL
                add:
                  - NET_ADMIN
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBNeXp6
        RkU2aFBpSHQ2SXZ0NWZzdEpqMkJOMHAxSmxIeFJUNDliTkhtSnpRCkd6MjlwZzRY
        dHZIZVNOd1lTT3JKbWNST3NjMnVzc1c4UkhlcmNZTEZEeXMKLS0tIDMxWk1aemQv
        WThHQjd5bUQ5R3d4dlhNZitFYUVHOWswbjA4ZndvTU0wQXMKMMtW23HioKCCOfy2
        lTw3zjfxp5hC4v1vn2QY64SGuQKhxbO9hOR0JXBuUuttdygqh9DzL/9WzG/ZrELT
        F3egOg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVXF1ZUovMjE0eThOenZV
        NXpPVHIzemxNeFl2N2lpd0FYYjBWN1BScEhZCjVucjNJajcvUWRpMkFIUlU5cTdu
        WHZOVEtreW5hYTgxRmFwMTlaZjgvNEkKLS0tIG5uM0hTdnN4YVJ0MnlNbllnYW9x
        OUN2alBDUmJLa0xNRk5iRElIWVJ3VFUKMIk1nBP2bM8XxK4iaiHUACydIEq0gvLb
        Ir+3ryunzHBR7dBxW2vhHny5i8v59ufN6PXGc0M1ce1jVFR0O6+Q3w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-27T19:40:45Z"
  mac: ENC[AES256_GCM,data:e2AoE6n10mJyTsNSBCAH9XpDaq5WEAA3j+3IDwg+9I6egzUDwhQ8jtMNzhXJVv2XVnFQcy8WHKIc9Ci+YVqfCxT19Qb4X9I5O1xUeEdE818iIdNOsmMb+YXm/8LRDGdVzrSbveIl8H84WLoogflKgzQCj/65yNSldj3ogyoWQws=,iv:oJBug9nB/UEM/YEBSbJDP79UTYP+dTrMbgXt1xQT3bQ=,tag:0AaMYaaLGXEsarj3ysyYGQ==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
# https://tailscale.com/docs/reference/best-practices/performance#linux-optimizations-for-subnet-routers-and-exit-nodes
apiVersion: v1alpha1
kind: EthernetConfig
name: ens18
features:
  rx-gro-list: "off"
  rx-udp-gro-forwarding: "on"
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBNeXp6
        RkU2aFBpSHQ2SXZ0NWZzdEpqMkJOMHAxSmxIeFJUNDliTkhtSnpRCkd6MjlwZzRY
        dHZIZVNOd1lTT3JKbWNST3NjMnVzc1c4UkhlcmNZTEZEeXMKLS0tIDMxWk1aemQv
        WThHQjd5bUQ5R3d4dlhNZitFYUVHOWswbjA4ZndvTU0wQXMKMMtW23HioKCCOfy2
        lTw3zjfxp5hC4v1vn2QY64SGuQKhxbO9hOR0JXBuUuttdygqh9DzL/9WzG/ZrELT
        F3egOg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVXF1ZUovMjE0eThOenZV
        NXpPVHIzemxNeFl2N2lpd0FYYjBWN1BScEhZCjVucjNJajcvUWRpMkFIUlU5cTdu
        WHZOVEtreW5hYTgxRmFwMTlaZjgvNEkKLS0tIG5uM0hTdnN4YVJ0MnlNbllnYW9x
        OUN2alBDUmJLa0xNRk5iRElIWVJ3VFUKMIk1nBP2bM8XxK4iaiHUACydIEq0gvLb
        Ir+3ryunzHBR7dBxW2vhHny5i8v59ufN6PXGc0M1ce1jVFR0O6+Q3w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-27T19:40:45Z"
  mac: ENC[AES256_GCM,data:e2AoE6n10mJyTsNSBCAH9XpDaq5WEAA3j+3IDwg+9I6egzUDwhQ8jtMNzhXJVv2XVnFQcy8WHKIc9Ci+YVqfCxT19Qb4X9I5O1xUeEdE818iIdNOsmMb+YXm/8LRDGdVzrSbveIl8H84WLoogflKgzQCj/65yNSldj3ogyoWQws=,iv:oJBug9nB/UEM/YEBSbJDP79UTYP+dTrMbgXt1xQT3bQ=,tag:0AaMYaaLGXEsarj3ysyYGQ==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  maxSize: 200GiB
  # TODO: this casually grew past maxSize so idek what maxSize exists for :))
  grow: true
# ---
# apiVersion: v1alpha1
# kind: SwapVolumeConfig
# name: swap
# provisioning:
#   diskSelector:
#     match: system_disk
#   minSize: 1GiB
#   maxSize: 1GiB
#   grow: false
# ---
# apiVersion: v1alpha1
# kind: ZswapConfig
# # The maximum percent of memory that zswap can use.
# maxPoolPercent: 69
# # Enable the shrinker feature: kernel might move
# shrinkerEnabled: true
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBNeXp6
        RkU2aFBpSHQ2SXZ0NWZzdEpqMkJOMHAxSmxIeFJUNDliTkhtSnpRCkd6MjlwZzRY
        dHZIZVNOd1lTT3JKbWNST3NjMnVzc1c4UkhlcmNZTEZEeXMKLS0tIDMxWk1aemQv
        WThHQjd5bUQ5R3d4dlhNZitFYUVHOWswbjA4ZndvTU0wQXMKMMtW23HioKCCOfy2
        lTw3zjfxp5hC4v1vn2QY64SGuQKhxbO9hOR0JXBuUuttdygqh9DzL/9WzG/ZrELT
        F3egOg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVXF1ZUovMjE0eThOenZV
        NXpPVHIzemxNeFl2N2lpd0FYYjBWN1BScEhZCjVucjNJajcvUWRpMkFIUlU5cTdu
        WHZOVEtreW5hYTgxRmFwMTlaZjgvNEkKLS0tIG5uM0hTdnN4YVJ0MnlNbllnYW9x
        OUN2alBDUmJLa0xNRk5iRElIWVJ3VFUKMIk1nBP2bM8XxK4iaiHUACydIEq0gvLb
        Ir+3ryunzHBR7dBxW2vhHny5i8v59ufN6PXGc0M1ce1jVFR0O6+Q3w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-27T19:40:45Z"
  mac: ENC[AES256_GCM,data:e2AoE6n10mJyTsNSBCAH9XpDaq5WEAA3j+3IDwg+9I6egzUDwhQ8jtMNzhXJVv2XVnFQcy8WHKIc9Ci+YVqfCxT19Qb4X9I5O1xUeEdE818iIdNOsmMb+YXm/8LRDGdVzrSbveIl8H84WLoogflKgzQCj/65yNSldj3ogyoWQws=,iv:oJBug9nB/UEM/YEBSbJDP79UTYP+dTrMbgXt1xQT3bQ=,tag:0AaMYaaLGXEsarj3ysyYGQ==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
