apiVersion: v1alpha1
kind: HostnameConfig
auto: "off"
hostname: sophons-oduduwa
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBhRzAr
        SFRDVmlra2pYTnZ3cWRpcVgwQmJaU2Y3NTdwQS9qd2pDSEJreWd3CjJkRmpmYmdC
        MURXd2NhS0NMU3VwR29zNytyQUZPcTBqM0ZQTzdkVHNrWXMKLS0tIEdkUmpmTkV3
        cGcybG16MFB6U2oyNlYwUm9GanhwTlgvSE9NbDNMNlpvRUUKxKRVm3s+MHwdezFj
        mk1JZw3/o5yhVR+FEUDAlZTmX/Ll16X+QdSkZaIShIYXtYC5pDtZu0kqsFjqD6YA
        0vc7gA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bHh1bERqRldYTGhlaHoy
        OE1LSmhXYVluWGNmRVJ3UzA2enJ3YmhtZVJRCmlYRG5KUTVvMVhEb0ZrM1FHN0d1
        K1B5ZnV6SThwWkN2RXJndWlMcTJUTUUKLS0tIFM3T3JUTk9lUjJRSmRzS3NDcDN3
        Mk9EUCtBdW13UGM0M2tGeldpWFI1M0EKjQLORQuCHSeGKlz88cemoBGoP8n8LXyY
        Tc8WOMsNI3FrzsQhcHuseBnNqt7J9O1egO0sb9YpwiBMpzePHkQEpA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-15T19:29:12Z"
  mac: ENC[AES256_GCM,data:d7oVX0ZNkmjb+ynRgYnLKPPMPryVT917JR10EPagaC+KUWAhyaWR+hhyIRezSCYVR2J5rBhYolPDlT6wUFOHmvUNLwf5uFkzMVZAfsBW2/ZQGoSQ5P/R88gdGWqVwtLoMLc79UkLgLdoMfudQEvNBviIWSdscDMcX5CfwYEi4a8=,iv:WtVRUFgHumE9zlGOQ2wrhWX6JQgWhtwOL417xmtjnVo=,tag:GyfQTpsnX6wArKg4xAfoZQ==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
cluster:
  network:
    cni:
      name: none
machine:
  install:
    disk: /dev/sda
  # sysctls:
  #   # 64MiB
  #   vm.min_free_kbytes: 65536
  #   # vm.swappiness: 200
  #   vm.watermark_scale_factor: 50
  kubelet:
    extraConfig:
      mergeDefaultEvictionSettings: true
      evictionSoft:
        memory.available: 256Mi
      evictionSoftGracePeriod:
        memory.available: 15s
      evictionHard:
        memory.available: 100Mi
  nodeLabels:
    topology.kubernetes.io/region: ng
    topology.kubernetes.io/zone: ng-west-1
    hugeloads.sophons.cloud/longhorn: "false"
    hugeloads.sophons.cloud/postgres: "false"
    hugeloads.sophons.cloud/garage: "true"
    cluster.garage.sophons.cloud/global: "true"
    weed.sophons.cloud/cluster: global
    weed.sophons.cloud/volume: "true"
  network:
    interfaces:
      - interface: ens18
        dhcp: false
        # enc!
        addresses:
          - ENC[AES256_GCM,data:s2iI7l25kKw3QArEeuV1eNY=,iv:wpxv0sBDJsRvG3DidehDOrAENS4YReW9JmKcYg+ihjA=,tag:vqFy9/thvT+5ajY+5x/xFA==,type:str]
        routes:
          - network: 0.0.0.0/0
            # enc!
            gateway: ENC[AES256_GCM,data:ksgd5eFO+3jUh3oZg4c=,iv:aNPsR/iH3Ryonk17wgWG4cs5E/3OQwZBhxbeXXIhPLE=,tag:+8Vi5+hfl/kijYX8Y+dbhA==,type:str]
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBhRzAr
        SFRDVmlra2pYTnZ3cWRpcVgwQmJaU2Y3NTdwQS9qd2pDSEJreWd3CjJkRmpmYmdC
        MURXd2NhS0NMU3VwR29zNytyQUZPcTBqM0ZQTzdkVHNrWXMKLS0tIEdkUmpmTkV3
        cGcybG16MFB6U2oyNlYwUm9GanhwTlgvSE9NbDNMNlpvRUUKxKRVm3s+MHwdezFj
        mk1JZw3/o5yhVR+FEUDAlZTmX/Ll16X+QdSkZaIShIYXtYC5pDtZu0kqsFjqD6YA
        0vc7gA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bHh1bERqRldYTGhlaHoy
        OE1LSmhXYVluWGNmRVJ3UzA2enJ3YmhtZVJRCmlYRG5KUTVvMVhEb0ZrM1FHN0d1
        K1B5ZnV6SThwWkN2RXJndWlMcTJUTUUKLS0tIFM3T3JUTk9lUjJRSmRzS3NDcDN3
        Mk9EUCtBdW13UGM0M2tGeldpWFI1M0EKjQLORQuCHSeGKlz88cemoBGoP8n8LXyY
        Tc8WOMsNI3FrzsQhcHuseBnNqt7J9O1egO0sb9YpwiBMpzePHkQEpA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-15T19:29:12Z"
  mac: ENC[AES256_GCM,data:d7oVX0ZNkmjb+ynRgYnLKPPMPryVT917JR10EPagaC+KUWAhyaWR+hhyIRezSCYVR2J5rBhYolPDlT6wUFOHmvUNLwf5uFkzMVZAfsBW2/ZQGoSQ5P/R88gdGWqVwtLoMLc79UkLgLdoMfudQEvNBviIWSdscDMcX5CfwYEi4a8=,iv:WtVRUFgHumE9zlGOQ2wrhWX6JQgWhtwOL417xmtjnVo=,tag:GyfQTpsnX6wArKg4xAfoZQ==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
# https://tailscale.com/docs/reference/best-practices/performance#linux-optimizations-for-subnet-routers-and-exit-nodes
apiVersion: v1alpha1
kind: EthernetConfig
name: ens18
features:
  rx-gro-list: "off"
  rx-udp-gro-forwarding: "on"
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBhRzAr
        SFRDVmlra2pYTnZ3cWRpcVgwQmJaU2Y3NTdwQS9qd2pDSEJreWd3CjJkRmpmYmdC
        MURXd2NhS0NMU3VwR29zNytyQUZPcTBqM0ZQTzdkVHNrWXMKLS0tIEdkUmpmTkV3
        cGcybG16MFB6U2oyNlYwUm9GanhwTlgvSE9NbDNMNlpvRUUKxKRVm3s+MHwdezFj
        mk1JZw3/o5yhVR+FEUDAlZTmX/Ll16X+QdSkZaIShIYXtYC5pDtZu0kqsFjqD6YA
        0vc7gA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bHh1bERqRldYTGhlaHoy
        OE1LSmhXYVluWGNmRVJ3UzA2enJ3YmhtZVJRCmlYRG5KUTVvMVhEb0ZrM1FHN0d1
        K1B5ZnV6SThwWkN2RXJndWlMcTJUTUUKLS0tIFM3T3JUTk9lUjJRSmRzS3NDcDN3
        Mk9EUCtBdW13UGM0M2tGeldpWFI1M0EKjQLORQuCHSeGKlz88cemoBGoP8n8LXyY
        Tc8WOMsNI3FrzsQhcHuseBnNqt7J9O1egO0sb9YpwiBMpzePHkQEpA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-15T19:29:12Z"
  mac: ENC[AES256_GCM,data:d7oVX0ZNkmjb+ynRgYnLKPPMPryVT917JR10EPagaC+KUWAhyaWR+hhyIRezSCYVR2J5rBhYolPDlT6wUFOHmvUNLwf5uFkzMVZAfsBW2/ZQGoSQ5P/R88gdGWqVwtLoMLc79UkLgLdoMfudQEvNBviIWSdscDMcX5CfwYEi4a8=,iv:WtVRUFgHumE9zlGOQ2wrhWX6JQgWhtwOL417xmtjnVo=,tag:GyfQTpsnX6wArKg4xAfoZQ==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  maxSize: 200GiB
  # TODO: this casually grew past maxSize so idek what maxSize exists for :))
  grow: true
# ---
# apiVersion: v1alpha1
# kind: SwapVolumeConfig
# name: swap
# provisioning:
#   diskSelector:
#     match: system_disk
#   minSize: 1GiB
#   maxSize: 1GiB
#   grow: false
# ---
# apiVersion: v1alpha1
# kind: ZswapConfig
# # The maximum percent of memory that zswap can use.
# maxPoolPercent: 69
# # Enable the shrinker feature: kernel might move
# shrinkerEnabled: true
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBhRzAr
        SFRDVmlra2pYTnZ3cWRpcVgwQmJaU2Y3NTdwQS9qd2pDSEJreWd3CjJkRmpmYmdC
        MURXd2NhS0NMU3VwR29zNytyQUZPcTBqM0ZQTzdkVHNrWXMKLS0tIEdkUmpmTkV3
        cGcybG16MFB6U2oyNlYwUm9GanhwTlgvSE9NbDNMNlpvRUUKxKRVm3s+MHwdezFj
        mk1JZw3/o5yhVR+FEUDAlZTmX/Ll16X+QdSkZaIShIYXtYC5pDtZu0kqsFjqD6YA
        0vc7gA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bHh1bERqRldYTGhlaHoy
        OE1LSmhXYVluWGNmRVJ3UzA2enJ3YmhtZVJRCmlYRG5KUTVvMVhEb0ZrM1FHN0d1
        K1B5ZnV6SThwWkN2RXJndWlMcTJUTUUKLS0tIFM3T3JUTk9lUjJRSmRzS3NDcDN3
        Mk9EUCtBdW13UGM0M2tGeldpWFI1M0EKjQLORQuCHSeGKlz88cemoBGoP8n8LXyY
        Tc8WOMsNI3FrzsQhcHuseBnNqt7J9O1egO0sb9YpwiBMpzePHkQEpA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-15T19:29:12Z"
  mac: ENC[AES256_GCM,data:d7oVX0ZNkmjb+ynRgYnLKPPMPryVT917JR10EPagaC+KUWAhyaWR+hhyIRezSCYVR2J5rBhYolPDlT6wUFOHmvUNLwf5uFkzMVZAfsBW2/ZQGoSQ5P/R88gdGWqVwtLoMLc79UkLgLdoMfudQEvNBviIWSdscDMcX5CfwYEi4a8=,iv:WtVRUFgHumE9zlGOQ2wrhWX6JQgWhtwOL417xmtjnVo=,tag:GyfQTpsnX6wArKg4xAfoZQ==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: WireguardConfig
name: wg.kluster
# publicKey: gobYpIEfo5paRPdkJ+Jnqcm9TyD+J2I4+Ry5AU0UhAQ=
# enc!
privateKey: ENC[AES256_GCM,data:+h8yw6SnOf6pO4tWPrfyvOCjW3wQTSwmn7we9RBa98nz2d57XBeDnXoITpw=,iv:ouAyB/hxz6AbVCJiQTgKs/rSYBK7kCcl9JyICLqUo3M=,tag:4r6wHE39JrzVcmxwKPQMUQ==,type:str]
listenPort: 51869
peers:
  # voltzahl
  - publicKey: hVSo5per13c8V9b5wUTAOGp0/W32rkKfSVZSctlqujU=
    allowedIPs:
      - 10.41.6.0/24
      - 2001:cafe:41:6::/64
      - 10.67.0.100/32
      - fdf6:9420:fade:67::5/128
      - fdf6:9420:fade:67::100/128
    # enc!
    endpoint: ENC[AES256_GCM,data:iHuhRZjw77DWAjb2UDABTYw=,iv:Ld5icRb2VXpvv45jTCBx2/Rds0VRMfjmVUZCJBwyQFA=,tag:ZBZQYKY5C159WLhkU/FV8w==,type:str]
    persistentKeepaliveInterval: 30s
  # theta
  - publicKey: bg+Z4libGo+HGAC9UrWbooWkOI4+eZ5OAqw+8rPn9AA=
    allowedIPs:
      - 10.41.2.0/24
      - 2001:cafe:41:2::/64
      - 10.67.0.101/32
      - fdf6:9420:fade:67::4/128
      - fdf6:9420:fade:67::101/128
    # enc!
    endpoint: ENC[AES256_GCM,data:iPlC4GoyTRbYLvQca8s//QYaYA==,iv:Q2IdqZTFwiO107YKHQ04G3JHIak0GUeTDDrdidOwd9U=,tag:tbmZpsAV9d6hsLg2iHDyyg==,type:str]
    persistentKeepaliveInterval: 30s
  # beta
  - publicKey: mmTxsL60iWtsBx6+aMkxx2Of7g/exHTU9pXrinc1wlQ=
    allowedIPs:
      - 10.41.1.0/24
      - 2001:cafe:41:1::/64
      - 10.67.0.102/32
      - fdf6:9420:fade:67::2/128
      - fdf6:9420:fade:67::102/128
    persistentKeepaliveInterval: 5s
  # alpha
  - publicKey: C/tFptmbSV+HBQYxzsTKUFW4LsPVcQyCNEfr8esvQ3w=
    allowedIPs:
      - 10.41.3.0/24
      - 2001:cafe:41:3::/64
      - 10.67.0.103/32
      - fdf6:9420:fade:67::103/128
    persistentKeepaliveInterval: 5s
  # caeneus
  - publicKey: l43bJSBEBDAc9vn+v9z2Zt/vsJRimWwyOwvHfHJrWkQ=
    allowedIPs:
      - 10.41.5.0/24
      - 2001:cafe:41:5::/64
      - 10.67.0.105/32
      - fdf6:9420:fade:67::105/128
    persistentKeepaliveInterval: 5s
  # prime
  - publicKey: 2jXr8tfBYrc3tBSvDweM2mJGAsPp6Sd/T2wCBss2fGU=
    allowedIPs:
      - 10.41.0.0/24
      - 2001:cafe:41::/64
      - 10.67.0.106/32
      - fdf6:9420:fade:67::106/128
    persistentKeepaliveInterval: 5s
up: true
addresses:
  - address: 10.67.0.104/32
  - address: fdf6:9420:fade:67::104/128
routes:
  # voltzahl
  - destination: 10.41.6.0/24
  - destination: 2001:cafe:41:6::/64
  - destination: 10.67.0.100/32
  - destination: fdf6:9420:fade:67::5/128
  - destination: fdf6:9420:fade:67::100/128
  # theta
  - destination: 10.41.2.0/24
  - destination: 2001:cafe:41:2::/64
  - destination: 10.67.0.101/32
  - destination: fdf6:9420:fade:67::4/128
  - destination: fdf6:9420:fade:67::101/128
  # beta
  - destination: 10.41.1.0/24
  - destination: 2001:cafe:41:1::/64
  - destination: 10.67.0.102/32
  - destination: fdf6:9420:fade:67::2/128
  - destination: fdf6:9420:fade:67::102/128
  # alpha
  - destination: 10.41.3.0/24
  - destination: 2001:cafe:41:3::/64
  - destination: 10.67.0.103/32
  - destination: fdf6:9420:fade:67::103/128
  # caeneus
  - destination: 10.41.5.0/24
  - destination: 2001:cafe:41:5::/64
  - destination: 10.67.0.105/32
  - destination: fdf6:9420:fade:67::105/128
  # prime
  - destination: 10.41.0.0/24
  - destination: 2001:cafe:41::/64
  - destination: 10.67.0.106/32
  - destination: fdf6:9420:fade:67::106/128
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBhRzAr
        SFRDVmlra2pYTnZ3cWRpcVgwQmJaU2Y3NTdwQS9qd2pDSEJreWd3CjJkRmpmYmdC
        MURXd2NhS0NMU3VwR29zNytyQUZPcTBqM0ZQTzdkVHNrWXMKLS0tIEdkUmpmTkV3
        cGcybG16MFB6U2oyNlYwUm9GanhwTlgvSE9NbDNMNlpvRUUKxKRVm3s+MHwdezFj
        mk1JZw3/o5yhVR+FEUDAlZTmX/Ll16X+QdSkZaIShIYXtYC5pDtZu0kqsFjqD6YA
        0vc7gA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bHh1bERqRldYTGhlaHoy
        OE1LSmhXYVluWGNmRVJ3UzA2enJ3YmhtZVJRCmlYRG5KUTVvMVhEb0ZrM1FHN0d1
        K1B5ZnV6SThwWkN2RXJndWlMcTJUTUUKLS0tIFM3T3JUTk9lUjJRSmRzS3NDcDN3
        Mk9EUCtBdW13UGM0M2tGeldpWFI1M0EKjQLORQuCHSeGKlz88cemoBGoP8n8LXyY
        Tc8WOMsNI3FrzsQhcHuseBnNqt7J9O1egO0sb9YpwiBMpzePHkQEpA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-15T19:29:12Z"
  mac: ENC[AES256_GCM,data:d7oVX0ZNkmjb+ynRgYnLKPPMPryVT917JR10EPagaC+KUWAhyaWR+hhyIRezSCYVR2J5rBhYolPDlT6wUFOHmvUNLwf5uFkzMVZAfsBW2/ZQGoSQ5P/R88gdGWqVwtLoMLc79UkLgLdoMfudQEvNBviIWSdscDMcX5CfwYEi4a8=,iv:WtVRUFgHumE9zlGOQ2wrhWX6JQgWhtwOL417xmtjnVo=,tag:GyfQTpsnX6wArKg4xAfoZQ==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
