cluster:
  network:
    cni:
      name: none
machine:
  install:
    disk: /dev/sda
  sysctls:
    # 64MiB
    vm.min_free_kbytes: 65536
    vm.swappiness: 200
    vm.watermark_scale_factor: 250
  kubelet:
    extraMounts:
      - destination: /var/lib/longhorn
        type: bind
        source: /var/lib/longhorn
        options:
          - bind
          - rshared
          - rw
    extraConfig:
      mergeDefaultEvictionSettings: true
      evictionSoft:
        memory.available: 200Mi
      evictionSoftGracePeriod:
        memory.available: 15s
      evictionHard:
        memory.available: 128Mi
  nodeLabels:
    topology.kubernetes.io/region: ng
    topology.kubernetes.io/zone: ng-west-1
  network:
    hostname: sophons-oduduwa
    interfaces:
      - interface: ens18
        dhcp: false
        # enc!
        addresses:
          - ENC[AES256_GCM,data:OXoYRE33ZWKcCIFLslyR/zE=,iv:bREttkI5KN0OQHhRqt/qYBBEglZuZVWU/4ovPQFhctg=,tag:WvY0THVlixxBn/ivEFyIZg==,type:str]
        routes:
          - network: 0.0.0.0/0
            # enc!
            gateway: ENC[AES256_GCM,data:mFPkuLEzG/HrQGHq118=,iv:3kYowG51KqEeiMu3Gdr6pltk55v3f7gDDlc0CG5gYLQ=,tag:RHmt4F+rXBKjDSTQg0bULg==,type:str]
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBRbUtZ
        T0lsclNxZDBxR2lVNmoyYzdVQlMzOGtzQVRmdXA1ODJQTXNtMDFvCkFkYnR1clE3
        SXR4ZXg3KzYxVUQrTUo2cjNVcExBcE1XdFJGMHdGVHAxd2cKLS0tIEU1UGJwOGVZ
        K3oxUUtJNzdIVTlxRktQVE1TeVpNSXM1M293aUwyNDFjREUKpZ9CqLciq844xOiX
        zEfzuQY+WNnwLF/mzi5iY53bqjxDcaBz9z/3jnhb8PV3Hx4MZ3Xt8IOVe4VaKupb
        32kJhg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRekRoVm1OaFdkTklwMmF6
        L0phSTlRaVQyQVZmN3g4aDFqbVNzZk8wMjJZCm1xNEhjUSthN3dmNlVPd2xJQmV6
        blNNdE5UYk9TeW8xMUdzc3BQZVgvSm8KLS0tIEkyaGcybkVFdVpkS0luYmJ6TDV5
        UUNHRW9VSmhRTEovWW8zeGRmdG95UGcKNQXjKlxXN2USJHuWDgd7Vm9slL+K8/Cf
        TSQj9i6gV3El1EXI2QGlbw5wPR3YGLL+v3VjIPSZd+luODofaLlS/A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T16:14:44Z"
  mac: ENC[AES256_GCM,data:zSta5yt7lGrsDDVuHB0xXJxuz/IWph3UKjjjl/U3nb33cgfIhxg9VDcjdbdtX4ofbBqLvNTYRfMjn1Zlav8AADX1ge0AYxpwkEr1dQDLevxUiuQgsvvRQnEAavNUmRcNsQ3oAoTsQ3YIBIWx3Ye/QLuHm7PMlu1MohGOshzOdNs=,iv:+Jq+q8PD+UaONpoT/cD60FOVoQ6POVzEo+aEVp/Xbrc=,tag:AFufWyj/Qm+QYRziW/JpcQ==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  maxSize: 17GiB
  grow: false
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBRbUtZ
        T0lsclNxZDBxR2lVNmoyYzdVQlMzOGtzQVRmdXA1ODJQTXNtMDFvCkFkYnR1clE3
        SXR4ZXg3KzYxVUQrTUo2cjNVcExBcE1XdFJGMHdGVHAxd2cKLS0tIEU1UGJwOGVZ
        K3oxUUtJNzdIVTlxRktQVE1TeVpNSXM1M293aUwyNDFjREUKpZ9CqLciq844xOiX
        zEfzuQY+WNnwLF/mzi5iY53bqjxDcaBz9z/3jnhb8PV3Hx4MZ3Xt8IOVe4VaKupb
        32kJhg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRekRoVm1OaFdkTklwMmF6
        L0phSTlRaVQyQVZmN3g4aDFqbVNzZk8wMjJZCm1xNEhjUSthN3dmNlVPd2xJQmV6
        blNNdE5UYk9TeW8xMUdzc3BQZVgvSm8KLS0tIEkyaGcybkVFdVpkS0luYmJ6TDV5
        UUNHRW9VSmhRTEovWW8zeGRmdG95UGcKNQXjKlxXN2USJHuWDgd7Vm9slL+K8/Cf
        TSQj9i6gV3El1EXI2QGlbw5wPR3YGLL+v3VjIPSZd+luODofaLlS/A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T16:14:44Z"
  mac: ENC[AES256_GCM,data:zSta5yt7lGrsDDVuHB0xXJxuz/IWph3UKjjjl/U3nb33cgfIhxg9VDcjdbdtX4ofbBqLvNTYRfMjn1Zlav8AADX1ge0AYxpwkEr1dQDLevxUiuQgsvvRQnEAavNUmRcNsQ3oAoTsQ3YIBIWx3Ye/QLuHm7PMlu1MohGOshzOdNs=,iv:+Jq+q8PD+UaONpoT/cD60FOVoQ6POVzEo+aEVp/Xbrc=,tag:AFufWyj/Qm+QYRziW/JpcQ==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: SwapVolumeConfig
name: swap
provisioning:
  diskSelector:
    match: system_disk
  minSize: 1GiB
  maxSize: 1GiB
  grow: false
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBRbUtZ
        T0lsclNxZDBxR2lVNmoyYzdVQlMzOGtzQVRmdXA1ODJQTXNtMDFvCkFkYnR1clE3
        SXR4ZXg3KzYxVUQrTUo2cjNVcExBcE1XdFJGMHdGVHAxd2cKLS0tIEU1UGJwOGVZ
        K3oxUUtJNzdIVTlxRktQVE1TeVpNSXM1M293aUwyNDFjREUKpZ9CqLciq844xOiX
        zEfzuQY+WNnwLF/mzi5iY53bqjxDcaBz9z/3jnhb8PV3Hx4MZ3Xt8IOVe4VaKupb
        32kJhg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRekRoVm1OaFdkTklwMmF6
        L0phSTlRaVQyQVZmN3g4aDFqbVNzZk8wMjJZCm1xNEhjUSthN3dmNlVPd2xJQmV6
        blNNdE5UYk9TeW8xMUdzc3BQZVgvSm8KLS0tIEkyaGcybkVFdVpkS0luYmJ6TDV5
        UUNHRW9VSmhRTEovWW8zeGRmdG95UGcKNQXjKlxXN2USJHuWDgd7Vm9slL+K8/Cf
        TSQj9i6gV3El1EXI2QGlbw5wPR3YGLL+v3VjIPSZd+luODofaLlS/A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T16:14:44Z"
  mac: ENC[AES256_GCM,data:zSta5yt7lGrsDDVuHB0xXJxuz/IWph3UKjjjl/U3nb33cgfIhxg9VDcjdbdtX4ofbBqLvNTYRfMjn1Zlav8AADX1ge0AYxpwkEr1dQDLevxUiuQgsvvRQnEAavNUmRcNsQ3oAoTsQ3YIBIWx3Ye/QLuHm7PMlu1MohGOshzOdNs=,iv:+Jq+q8PD+UaONpoT/cD60FOVoQ6POVzEo+aEVp/Xbrc=,tag:AFufWyj/Qm+QYRziW/JpcQ==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: ZswapConfig
# The maximum percent of memory that zswap can use.
maxPoolPercent: 69
# Enable the shrinker feature: kernel might move
shrinkerEnabled: true
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBRbUtZ
        T0lsclNxZDBxR2lVNmoyYzdVQlMzOGtzQVRmdXA1ODJQTXNtMDFvCkFkYnR1clE3
        SXR4ZXg3KzYxVUQrTUo2cjNVcExBcE1XdFJGMHdGVHAxd2cKLS0tIEU1UGJwOGVZ
        K3oxUUtJNzdIVTlxRktQVE1TeVpNSXM1M293aUwyNDFjREUKpZ9CqLciq844xOiX
        zEfzuQY+WNnwLF/mzi5iY53bqjxDcaBz9z/3jnhb8PV3Hx4MZ3Xt8IOVe4VaKupb
        32kJhg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRekRoVm1OaFdkTklwMmF6
        L0phSTlRaVQyQVZmN3g4aDFqbVNzZk8wMjJZCm1xNEhjUSthN3dmNlVPd2xJQmV6
        blNNdE5UYk9TeW8xMUdzc3BQZVgvSm8KLS0tIEkyaGcybkVFdVpkS0luYmJ6TDV5
        UUNHRW9VSmhRTEovWW8zeGRmdG95UGcKNQXjKlxXN2USJHuWDgd7Vm9slL+K8/Cf
        TSQj9i6gV3El1EXI2QGlbw5wPR3YGLL+v3VjIPSZd+luODofaLlS/A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T16:14:44Z"
  mac: ENC[AES256_GCM,data:zSta5yt7lGrsDDVuHB0xXJxuz/IWph3UKjjjl/U3nb33cgfIhxg9VDcjdbdtX4ofbBqLvNTYRfMjn1Zlav8AADX1ge0AYxpwkEr1dQDLevxUiuQgsvvRQnEAavNUmRcNsQ3oAoTsQ3YIBIWx3Ye/QLuHm7PMlu1MohGOshzOdNs=,iv:+Jq+q8PD+UaONpoT/cD60FOVoQ6POVzEo+aEVp/Xbrc=,tag:AFufWyj/Qm+QYRziW/JpcQ==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: ExtensionServiceConfig
name: tailscale
environment:
  - TS_ROUTES=10.41.4.0/24,2001:cafe:41:4::/64
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBRbUtZ
        T0lsclNxZDBxR2lVNmoyYzdVQlMzOGtzQVRmdXA1ODJQTXNtMDFvCkFkYnR1clE3
        SXR4ZXg3KzYxVUQrTUo2cjNVcExBcE1XdFJGMHdGVHAxd2cKLS0tIEU1UGJwOGVZ
        K3oxUUtJNzdIVTlxRktQVE1TeVpNSXM1M293aUwyNDFjREUKpZ9CqLciq844xOiX
        zEfzuQY+WNnwLF/mzi5iY53bqjxDcaBz9z/3jnhb8PV3Hx4MZ3Xt8IOVe4VaKupb
        32kJhg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRekRoVm1OaFdkTklwMmF6
        L0phSTlRaVQyQVZmN3g4aDFqbVNzZk8wMjJZCm1xNEhjUSthN3dmNlVPd2xJQmV6
        blNNdE5UYk9TeW8xMUdzc3BQZVgvSm8KLS0tIEkyaGcybkVFdVpkS0luYmJ6TDV5
        UUNHRW9VSmhRTEovWW8zeGRmdG95UGcKNQXjKlxXN2USJHuWDgd7Vm9slL+K8/Cf
        TSQj9i6gV3El1EXI2QGlbw5wPR3YGLL+v3VjIPSZd+luODofaLlS/A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T16:14:44Z"
  mac: ENC[AES256_GCM,data:zSta5yt7lGrsDDVuHB0xXJxuz/IWph3UKjjjl/U3nb33cgfIhxg9VDcjdbdtX4ofbBqLvNTYRfMjn1Zlav8AADX1ge0AYxpwkEr1dQDLevxUiuQgsvvRQnEAavNUmRcNsQ3oAoTsQ3YIBIWx3Ye/QLuHm7PMlu1MohGOshzOdNs=,iv:+Jq+q8PD+UaONpoT/cD60FOVoQ6POVzEo+aEVp/Xbrc=,tag:AFufWyj/Qm+QYRziW/JpcQ==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
