cluster:
  network:
    cni:
      name: none
machine:
  install:
    disk: /dev/sda
  sysctls:
    # 64MiB
    vm.min_free_kbytes: 65536
    vm.swappiness: 200
    vm.watermark_scale_factor: 100
  kubelet:
    extraMounts:
      - destination: /var/lib/longhorn
        type: bind
        source: /var/lib/longhorn
        options:
          - bind
          - rshared
          - rw
    extraConfig:
      mergeDefaultEvictionSettings: true
      evictionSoft:
        memory.available: 128Mi
      evictionSoftGracePeriod:
        memory.available: 15s
      evictionHard:
        memory.available: 100Mi
  nodeLabels:
    topology.kubernetes.io/region: ng
    topology.kubernetes.io/zone: ng-west-1
  network:
    hostname: sophons-oduduwa
    interfaces:
      - interface: ens18
        dhcp: false
        # enc!
        addresses:
          - ENC[AES256_GCM,data:DwMrkxg+cHTvIvEZ8C3I/j4=,iv:oOdHNUsbN/Oj/ZJHjV6f/fWhhY6g5NrVeOzRvimavu8=,tag:23xi/3of4ur9eE8Qg3BaLQ==,type:str]
        routes:
          - network: 0.0.0.0/0
            # enc!
            gateway: ENC[AES256_GCM,data:fbFgQ1iBo8eZXfpJcLs=,iv:wSLjCR1xqZ6ic6+1/dhCb/gt9z1dRDD4ITJ1c3iYZ5s=,tag:s1nHmrhfgUDdvpEiZM+UHw==,type:str]
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyB1cXJK
        Zkp1NXdWRXNEemY1V3Q5Mm1lc2djeC95a1QrejQ3QzlKbVpIenlVCmJJWXR4S2gr
        R0VXS3B0Sm5NcE05OUZNQVZDR25nUkxJT2x2Y1ZtZXU5ZDQKLS0tIEZFZVNENGNB
        RU5YT2FYMTNTSWY5WFVPRzZYTW9lZWhPZEdEdXlyYWtEeDAKUrhiOL8SsnsjFQdy
        pQdELByod07iE5HNbVmyDvl4jfEo/i/YOY+R9MOcDsMLo98sVhMhmHgkZrJMS+KZ
        Zr9rfw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUE5aci9VSFdEVGdCaXZW
        WVR4MklWeENLWFJ5T2ZkaUtlb25JSWJqUTJnCnEzSzRGUUt4NnhxNzZvSDh3aHF3
        a2s1d1NCenVIWUZKWWFHdVNNMGF2a00KLS0tIERlUDQwSFBmYmliMjNycnlaeXlO
        ajUzRjFBRlB6WEFJQ1NPTXdRVkViRncKTt4I4zQ4kAtZgLxA7WrWx5ha0EfEY0XP
        XJIPwQ32IZYNYoSsUUYj0xQhOnaMyF/kQMfZRtcj8sdXFDSNy8kQ0g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-23T20:23:31Z"
  mac: ENC[AES256_GCM,data:A5T3IF0wj1N3G0qG7aHHgh67850D5n9QsNZ+4VwkexY/mTYOpK8ysxQ2oChn0agTB2EF+f+EYpPn8ymp2815q8jNQmqMZTwSvVsDIk3NTWllf0zqvtS0tG2c4xro8w4eneSzxIVWwXIWM4XWylz2t/Xne5nXUVAVl2/I6WRjYiQ=,iv:6qwS5eVf/HtNHbljOcU9Ye1QfA6TYLT2RSizG32UHRk=,tag:knp2JuDt299W1ylPRkivUg==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  maxSize: 17GiB
  grow: false
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyB1cXJK
        Zkp1NXdWRXNEemY1V3Q5Mm1lc2djeC95a1QrejQ3QzlKbVpIenlVCmJJWXR4S2gr
        R0VXS3B0Sm5NcE05OUZNQVZDR25nUkxJT2x2Y1ZtZXU5ZDQKLS0tIEZFZVNENGNB
        RU5YT2FYMTNTSWY5WFVPRzZYTW9lZWhPZEdEdXlyYWtEeDAKUrhiOL8SsnsjFQdy
        pQdELByod07iE5HNbVmyDvl4jfEo/i/YOY+R9MOcDsMLo98sVhMhmHgkZrJMS+KZ
        Zr9rfw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUE5aci9VSFdEVGdCaXZW
        WVR4MklWeENLWFJ5T2ZkaUtlb25JSWJqUTJnCnEzSzRGUUt4NnhxNzZvSDh3aHF3
        a2s1d1NCenVIWUZKWWFHdVNNMGF2a00KLS0tIERlUDQwSFBmYmliMjNycnlaeXlO
        ajUzRjFBRlB6WEFJQ1NPTXdRVkViRncKTt4I4zQ4kAtZgLxA7WrWx5ha0EfEY0XP
        XJIPwQ32IZYNYoSsUUYj0xQhOnaMyF/kQMfZRtcj8sdXFDSNy8kQ0g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-23T20:23:31Z"
  mac: ENC[AES256_GCM,data:A5T3IF0wj1N3G0qG7aHHgh67850D5n9QsNZ+4VwkexY/mTYOpK8ysxQ2oChn0agTB2EF+f+EYpPn8ymp2815q8jNQmqMZTwSvVsDIk3NTWllf0zqvtS0tG2c4xro8w4eneSzxIVWwXIWM4XWylz2t/Xne5nXUVAVl2/I6WRjYiQ=,iv:6qwS5eVf/HtNHbljOcU9Ye1QfA6TYLT2RSizG32UHRk=,tag:knp2JuDt299W1ylPRkivUg==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: SwapVolumeConfig
name: swap
provisioning:
  diskSelector:
    match: system_disk
  minSize: 1GiB
  maxSize: 1GiB
  grow: false
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyB1cXJK
        Zkp1NXdWRXNEemY1V3Q5Mm1lc2djeC95a1QrejQ3QzlKbVpIenlVCmJJWXR4S2gr
        R0VXS3B0Sm5NcE05OUZNQVZDR25nUkxJT2x2Y1ZtZXU5ZDQKLS0tIEZFZVNENGNB
        RU5YT2FYMTNTSWY5WFVPRzZYTW9lZWhPZEdEdXlyYWtEeDAKUrhiOL8SsnsjFQdy
        pQdELByod07iE5HNbVmyDvl4jfEo/i/YOY+R9MOcDsMLo98sVhMhmHgkZrJMS+KZ
        Zr9rfw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUE5aci9VSFdEVGdCaXZW
        WVR4MklWeENLWFJ5T2ZkaUtlb25JSWJqUTJnCnEzSzRGUUt4NnhxNzZvSDh3aHF3
        a2s1d1NCenVIWUZKWWFHdVNNMGF2a00KLS0tIERlUDQwSFBmYmliMjNycnlaeXlO
        ajUzRjFBRlB6WEFJQ1NPTXdRVkViRncKTt4I4zQ4kAtZgLxA7WrWx5ha0EfEY0XP
        XJIPwQ32IZYNYoSsUUYj0xQhOnaMyF/kQMfZRtcj8sdXFDSNy8kQ0g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-23T20:23:31Z"
  mac: ENC[AES256_GCM,data:A5T3IF0wj1N3G0qG7aHHgh67850D5n9QsNZ+4VwkexY/mTYOpK8ysxQ2oChn0agTB2EF+f+EYpPn8ymp2815q8jNQmqMZTwSvVsDIk3NTWllf0zqvtS0tG2c4xro8w4eneSzxIVWwXIWM4XWylz2t/Xne5nXUVAVl2/I6WRjYiQ=,iv:6qwS5eVf/HtNHbljOcU9Ye1QfA6TYLT2RSizG32UHRk=,tag:knp2JuDt299W1ylPRkivUg==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: ZswapConfig
# The maximum percent of memory that zswap can use.
maxPoolPercent: 69
# Enable the shrinker feature: kernel might move
shrinkerEnabled: true
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyB1cXJK
        Zkp1NXdWRXNEemY1V3Q5Mm1lc2djeC95a1QrejQ3QzlKbVpIenlVCmJJWXR4S2gr
        R0VXS3B0Sm5NcE05OUZNQVZDR25nUkxJT2x2Y1ZtZXU5ZDQKLS0tIEZFZVNENGNB
        RU5YT2FYMTNTSWY5WFVPRzZYTW9lZWhPZEdEdXlyYWtEeDAKUrhiOL8SsnsjFQdy
        pQdELByod07iE5HNbVmyDvl4jfEo/i/YOY+R9MOcDsMLo98sVhMhmHgkZrJMS+KZ
        Zr9rfw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUE5aci9VSFdEVGdCaXZW
        WVR4MklWeENLWFJ5T2ZkaUtlb25JSWJqUTJnCnEzSzRGUUt4NnhxNzZvSDh3aHF3
        a2s1d1NCenVIWUZKWWFHdVNNMGF2a00KLS0tIERlUDQwSFBmYmliMjNycnlaeXlO
        ajUzRjFBRlB6WEFJQ1NPTXdRVkViRncKTt4I4zQ4kAtZgLxA7WrWx5ha0EfEY0XP
        XJIPwQ32IZYNYoSsUUYj0xQhOnaMyF/kQMfZRtcj8sdXFDSNy8kQ0g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-23T20:23:31Z"
  mac: ENC[AES256_GCM,data:A5T3IF0wj1N3G0qG7aHHgh67850D5n9QsNZ+4VwkexY/mTYOpK8ysxQ2oChn0agTB2EF+f+EYpPn8ymp2815q8jNQmqMZTwSvVsDIk3NTWllf0zqvtS0tG2c4xro8w4eneSzxIVWwXIWM4XWylz2t/Xne5nXUVAVl2/I6WRjYiQ=,iv:6qwS5eVf/HtNHbljOcU9Ye1QfA6TYLT2RSizG32UHRk=,tag:knp2JuDt299W1ylPRkivUg==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: ExtensionServiceConfig
name: tailscale
environment:
  - TS_ROUTES=10.41.4.0/24,2001:cafe:41:4::/64
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyB1cXJK
        Zkp1NXdWRXNEemY1V3Q5Mm1lc2djeC95a1QrejQ3QzlKbVpIenlVCmJJWXR4S2gr
        R0VXS3B0Sm5NcE05OUZNQVZDR25nUkxJT2x2Y1ZtZXU5ZDQKLS0tIEZFZVNENGNB
        RU5YT2FYMTNTSWY5WFVPRzZYTW9lZWhPZEdEdXlyYWtEeDAKUrhiOL8SsnsjFQdy
        pQdELByod07iE5HNbVmyDvl4jfEo/i/YOY+R9MOcDsMLo98sVhMhmHgkZrJMS+KZ
        Zr9rfw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUE5aci9VSFdEVGdCaXZW
        WVR4MklWeENLWFJ5T2ZkaUtlb25JSWJqUTJnCnEzSzRGUUt4NnhxNzZvSDh3aHF3
        a2s1d1NCenVIWUZKWWFHdVNNMGF2a00KLS0tIERlUDQwSFBmYmliMjNycnlaeXlO
        ajUzRjFBRlB6WEFJQ1NPTXdRVkViRncKTt4I4zQ4kAtZgLxA7WrWx5ha0EfEY0XP
        XJIPwQ32IZYNYoSsUUYj0xQhOnaMyF/kQMfZRtcj8sdXFDSNy8kQ0g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-23T20:23:31Z"
  mac: ENC[AES256_GCM,data:A5T3IF0wj1N3G0qG7aHHgh67850D5n9QsNZ+4VwkexY/mTYOpK8ysxQ2oChn0agTB2EF+f+EYpPn8ymp2815q8jNQmqMZTwSvVsDIk3NTWllf0zqvtS0tG2c4xro8w4eneSzxIVWwXIWM4XWylz2t/Xne5nXUVAVl2/I6WRjYiQ=,iv:6qwS5eVf/HtNHbljOcU9Ye1QfA6TYLT2RSizG32UHRk=,tag:knp2JuDt299W1ylPRkivUg==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
