apiVersion: v1alpha1
kind: HostnameConfig
auto: "off"
hostname: sophons-oduduwa
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyB3NC9l
        d2wzeGZ2UlZSNDkzQURkdEpNWXk2Q3RnZ3RxY1AxMVVkLzVVRHlBCnhiaGw5bC81
        TitKbDkvNzJlZDZMb2NEUXpTNHJCMDdCMDM4bmJEMGQxaTQKLS0tIDUrdnpKK3Va
        Qno2MDZPTzRmbHhrWXkxaHBxN0FTeWVJRUhoZ21HSGVoSVkKhFu48b6YnGRBlTBK
        nf+J33ABLqSy2+LeqqnuaFfVEC+TypgwiUHoS2HCu2ivsY+Aa9e9NQfCvr4R8q4k
        /Zdr0Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UjJIbHhtU28vUG1GVmJk
        SXpQQ1dRSFdzSEFIMDdSVCtSeGxpVGVjOXlJCmVCMmZKbUp1VG83UTBmaGlmMTc2
        d1loakJCc2FVZ1ZMZU5aY3VPT05FNEkKLS0tIEhPYzFJUHBvRFMxMFhEbDJxZHZ0
        VW9xRWhQa1E4UElTSXhvWm9tTFRTWEUKuLxdUJR7ajUW+R2A6RkkvL+ClwXL4qvo
        Z7HzWmPFnhhx7C081oVjgpZN0DWxZ4heaepvEenT3Dfi/FlMCdj+YA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-10T16:45:25Z"
  mac: ENC[AES256_GCM,data:eou4OxWhKH/aAhRkkBaiUIVTI2WJ+vWuQU/JJupfCAKy7BpmlPsHfZSw9eGb/PvW427oV4JngRDhn5voEMyzRvX7NZhyej0qOoGdLgkvlTySy9c3B/4mEl+p+QgqZSCjwQiGoIRRhQGBxY0BFRVZYo5IcQegzB9eqUXRYGYks20=,iv:DEC+sy/W0H4LtTFqQTIVZo01iGDLMQZX8MSKHR/mEv0=,tag:eclov7cgygdBSXMPjtAgnA==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
cluster:
  network:
    cni:
      name: none
machine:
  install:
    disk: /dev/sda
  # sysctls:
  #   # 64MiB
  #   vm.min_free_kbytes: 65536
  #   # vm.swappiness: 200
  #   vm.watermark_scale_factor: 50
  kubelet:
    extraMounts:
      - destination: /var/lib/longhorn
        type: bind
        source: /var/lib/longhorn
        options:
          - bind
          - rshared
          - rw
    extraConfig:
      mergeDefaultEvictionSettings: true
      evictionSoft:
        memory.available: 256Mi
      evictionSoftGracePeriod:
        memory.available: 15s
      evictionHard:
        memory.available: 100Mi
  nodeLabels:
    topology.kubernetes.io/region: ng
    topology.kubernetes.io/zone: ng-west-1
    hugeloads.sophons.cloud/longhorn: "false"
    hugeloads.sophons.cloud/postgres: "false"
    hugeloads.sophons.cloud/garage: "true"
    cluster.garage.sophons.cloud/global: "true"
    weed.sophons.cloud/cluster: global
    weed.sophons.cloud/volume: "true"
  network:
    interfaces:
      - interface: ens18
        dhcp: false
        # enc!
        addresses:
          - ENC[AES256_GCM,data:osSa7k9q6E9YCRovn5RhCMA=,iv:YBaAMUaeVk2kqNCmPjJQAgPeS2hi0O3063degaOgfRU=,tag:rxZqbY3sISDbwT0Ytqdb4g==,type:str]
        routes:
          - network: 0.0.0.0/0
            # enc!
            gateway: ENC[AES256_GCM,data:iGmnkFEcfZ4kKR+XUh8=,iv:PC+wmxPvpqvrXXsq9kOTJ2xasdV5fW0ux3fF0hdshwg=,tag:k/cWq63fHpiI9pz+6JRdmg==,type:str]
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyB3NC9l
        d2wzeGZ2UlZSNDkzQURkdEpNWXk2Q3RnZ3RxY1AxMVVkLzVVRHlBCnhiaGw5bC81
        TitKbDkvNzJlZDZMb2NEUXpTNHJCMDdCMDM4bmJEMGQxaTQKLS0tIDUrdnpKK3Va
        Qno2MDZPTzRmbHhrWXkxaHBxN0FTeWVJRUhoZ21HSGVoSVkKhFu48b6YnGRBlTBK
        nf+J33ABLqSy2+LeqqnuaFfVEC+TypgwiUHoS2HCu2ivsY+Aa9e9NQfCvr4R8q4k
        /Zdr0Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UjJIbHhtU28vUG1GVmJk
        SXpQQ1dRSFdzSEFIMDdSVCtSeGxpVGVjOXlJCmVCMmZKbUp1VG83UTBmaGlmMTc2
        d1loakJCc2FVZ1ZMZU5aY3VPT05FNEkKLS0tIEhPYzFJUHBvRFMxMFhEbDJxZHZ0
        VW9xRWhQa1E4UElTSXhvWm9tTFRTWEUKuLxdUJR7ajUW+R2A6RkkvL+ClwXL4qvo
        Z7HzWmPFnhhx7C081oVjgpZN0DWxZ4heaepvEenT3Dfi/FlMCdj+YA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-10T16:45:25Z"
  mac: ENC[AES256_GCM,data:eou4OxWhKH/aAhRkkBaiUIVTI2WJ+vWuQU/JJupfCAKy7BpmlPsHfZSw9eGb/PvW427oV4JngRDhn5voEMyzRvX7NZhyej0qOoGdLgkvlTySy9c3B/4mEl+p+QgqZSCjwQiGoIRRhQGBxY0BFRVZYo5IcQegzB9eqUXRYGYks20=,iv:DEC+sy/W0H4LtTFqQTIVZo01iGDLMQZX8MSKHR/mEv0=,tag:eclov7cgygdBSXMPjtAgnA==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
# https://tailscale.com/docs/reference/best-practices/performance#linux-optimizations-for-subnet-routers-and-exit-nodes
apiVersion: v1alpha1
kind: EthernetConfig
name: ens18
features:
  rx-gro-list: "off"
  rx-udp-gro-forwarding: "on"
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyB3NC9l
        d2wzeGZ2UlZSNDkzQURkdEpNWXk2Q3RnZ3RxY1AxMVVkLzVVRHlBCnhiaGw5bC81
        TitKbDkvNzJlZDZMb2NEUXpTNHJCMDdCMDM4bmJEMGQxaTQKLS0tIDUrdnpKK3Va
        Qno2MDZPTzRmbHhrWXkxaHBxN0FTeWVJRUhoZ21HSGVoSVkKhFu48b6YnGRBlTBK
        nf+J33ABLqSy2+LeqqnuaFfVEC+TypgwiUHoS2HCu2ivsY+Aa9e9NQfCvr4R8q4k
        /Zdr0Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UjJIbHhtU28vUG1GVmJk
        SXpQQ1dRSFdzSEFIMDdSVCtSeGxpVGVjOXlJCmVCMmZKbUp1VG83UTBmaGlmMTc2
        d1loakJCc2FVZ1ZMZU5aY3VPT05FNEkKLS0tIEhPYzFJUHBvRFMxMFhEbDJxZHZ0
        VW9xRWhQa1E4UElTSXhvWm9tTFRTWEUKuLxdUJR7ajUW+R2A6RkkvL+ClwXL4qvo
        Z7HzWmPFnhhx7C081oVjgpZN0DWxZ4heaepvEenT3Dfi/FlMCdj+YA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-10T16:45:25Z"
  mac: ENC[AES256_GCM,data:eou4OxWhKH/aAhRkkBaiUIVTI2WJ+vWuQU/JJupfCAKy7BpmlPsHfZSw9eGb/PvW427oV4JngRDhn5voEMyzRvX7NZhyej0qOoGdLgkvlTySy9c3B/4mEl+p+QgqZSCjwQiGoIRRhQGBxY0BFRVZYo5IcQegzB9eqUXRYGYks20=,iv:DEC+sy/W0H4LtTFqQTIVZo01iGDLMQZX8MSKHR/mEv0=,tag:eclov7cgygdBSXMPjtAgnA==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  maxSize: 80GiB
  # TODO: this casually grew past maxSize so idek what maxSize exists for :))
  grow: true
# ---
# apiVersion: v1alpha1
# kind: SwapVolumeConfig
# name: swap
# provisioning:
#   diskSelector:
#     match: system_disk
#   minSize: 1GiB
#   maxSize: 1GiB
#   grow: false
# ---
# apiVersion: v1alpha1
# kind: ZswapConfig
# # The maximum percent of memory that zswap can use.
# maxPoolPercent: 69
# # Enable the shrinker feature: kernel might move
# shrinkerEnabled: true
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyB3NC9l
        d2wzeGZ2UlZSNDkzQURkdEpNWXk2Q3RnZ3RxY1AxMVVkLzVVRHlBCnhiaGw5bC81
        TitKbDkvNzJlZDZMb2NEUXpTNHJCMDdCMDM4bmJEMGQxaTQKLS0tIDUrdnpKK3Va
        Qno2MDZPTzRmbHhrWXkxaHBxN0FTeWVJRUhoZ21HSGVoSVkKhFu48b6YnGRBlTBK
        nf+J33ABLqSy2+LeqqnuaFfVEC+TypgwiUHoS2HCu2ivsY+Aa9e9NQfCvr4R8q4k
        /Zdr0Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UjJIbHhtU28vUG1GVmJk
        SXpQQ1dRSFdzSEFIMDdSVCtSeGxpVGVjOXlJCmVCMmZKbUp1VG83UTBmaGlmMTc2
        d1loakJCc2FVZ1ZMZU5aY3VPT05FNEkKLS0tIEhPYzFJUHBvRFMxMFhEbDJxZHZ0
        VW9xRWhQa1E4UElTSXhvWm9tTFRTWEUKuLxdUJR7ajUW+R2A6RkkvL+ClwXL4qvo
        Z7HzWmPFnhhx7C081oVjgpZN0DWxZ4heaepvEenT3Dfi/FlMCdj+YA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-10T16:45:25Z"
  mac: ENC[AES256_GCM,data:eou4OxWhKH/aAhRkkBaiUIVTI2WJ+vWuQU/JJupfCAKy7BpmlPsHfZSw9eGb/PvW427oV4JngRDhn5voEMyzRvX7NZhyej0qOoGdLgkvlTySy9c3B/4mEl+p+QgqZSCjwQiGoIRRhQGBxY0BFRVZYo5IcQegzB9eqUXRYGYks20=,iv:DEC+sy/W0H4LtTFqQTIVZo01iGDLMQZX8MSKHR/mEv0=,tag:eclov7cgygdBSXMPjtAgnA==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: WireguardConfig
name: wg.kluster
# publicKey: gobYpIEfo5paRPdkJ+Jnqcm9TyD+J2I4+Ry5AU0UhAQ=
# enc!
privateKey: ENC[AES256_GCM,data:tOU4jfW5+WBffztEJSN3fWuMQ74Arq5Apn4e62EIMl9mjUmjfw5UZMxqk30=,iv:g6FLeEK3BcaETP5nSkL/kCvWofsPrmBr8/PYcNhpmvU=,tag:tOfAk81P45T0FaW1qkwJfg==,type:str]
listenPort: 51869
peers:
  # voltzahl
  - publicKey: hVSo5per13c8V9b5wUTAOGp0/W32rkKfSVZSctlqujU=
    allowedIPs:
      - 10.41.6.0/24
      - 2001:cafe:41:6::/64
      - 10.67.0.100/32
      - fdf6:9420:fade:67::5/128
      - fdf6:9420:fade:67::100/128
    # enc!
    endpoint: ENC[AES256_GCM,data:oehURWeUwKdUSJppKXu+/WQ=,iv:Lfpe7vr5M2e80GmWzGgPkARHcQx3TkRsRCEMRRSzans=,tag:qr6WQdLvxozAO6pu7Hnycw==,type:str]
    persistentKeepaliveInterval: 30s
  # theta
  - publicKey: bg+Z4libGo+HGAC9UrWbooWkOI4+eZ5OAqw+8rPn9AA=
    allowedIPs:
      - 10.41.2.0/24
      - 2001:cafe:41:2::/64
      - 10.67.0.101/32
      - fdf6:9420:fade:67::4/128
      - fdf6:9420:fade:67::101/128
    # enc!
    endpoint: ENC[AES256_GCM,data:f7d88Wtb5jyi8LlYXYFXrCvuQg==,iv:r2RQwas/2WWim7CiGSkkZkNO1TENSRioCgJaQ2LVl2E=,tag:RvXY+mrM75y00d45IMoVhg==,type:str]
    persistentKeepaliveInterval: 30s
  # beta
  - publicKey: mmTxsL60iWtsBx6+aMkxx2Of7g/exHTU9pXrinc1wlQ=
    allowedIPs:
      - 10.41.1.0/24
      - 2001:cafe:41:1::/64
      - 10.67.0.102/32
      - fdf6:9420:fade:67::2/128
      - fdf6:9420:fade:67::102/128
    persistentKeepaliveInterval: 5s
  # alpha
  - publicKey: C/tFptmbSV+HBQYxzsTKUFW4LsPVcQyCNEfr8esvQ3w=
    allowedIPs:
      - 10.41.3.0/24
      - 2001:cafe:41:3::/64
      - 10.67.0.103/32
      - fdf6:9420:fade:67::103/128
    persistentKeepaliveInterval: 5s
  # caeneus
  - publicKey: l43bJSBEBDAc9vn+v9z2Zt/vsJRimWwyOwvHfHJrWkQ=
    allowedIPs:
      - 10.41.5.0/24
      - 2001:cafe:41:5::/64
      - 10.67.0.105/32
      - fdf6:9420:fade:67::105/128
    persistentKeepaliveInterval: 5s
  # prime
  - publicKey: 2jXr8tfBYrc3tBSvDweM2mJGAsPp6Sd/T2wCBss2fGU=
    allowedIPs:
      - 10.41.0.0/24
      - 2001:cafe:41::/64
      - 10.67.0.106/32
      - fdf6:9420:fade:67::106/128
    persistentKeepaliveInterval: 5s
up: true
addresses:
  - address: 10.67.0.104/32
  - address: fdf6:9420:fade:67::104/128
routes:
  # voltzahl
  - destination: 10.41.6.0/24
  - destination: 2001:cafe:41:6::/64
  - destination: 10.67.0.100/32
  - destination: fdf6:9420:fade:67::5/128
  - destination: fdf6:9420:fade:67::100/128
  # theta
  - destination: 10.41.2.0/24
  - destination: 2001:cafe:41:2::/64
  - destination: 10.67.0.101/32
  - destination: fdf6:9420:fade:67::4/128
  - destination: fdf6:9420:fade:67::101/128
  # beta
  - destination: 10.41.1.0/24
  - destination: 2001:cafe:41:1::/64
  - destination: 10.67.0.102/32
  - destination: fdf6:9420:fade:67::2/128
  - destination: fdf6:9420:fade:67::102/128
  # alpha
  - destination: 10.41.3.0/24
  - destination: 2001:cafe:41:3::/64
  - destination: 10.67.0.103/32
  - destination: fdf6:9420:fade:67::103/128
  # caeneus
  - destination: 10.41.5.0/24
  - destination: 2001:cafe:41:5::/64
  - destination: 10.67.0.105/32
  - destination: fdf6:9420:fade:67::105/128
  # prime
  - destination: 10.41.0.0/24
  - destination: 2001:cafe:41::/64
  - destination: 10.67.0.106/32
  - destination: fdf6:9420:fade:67::106/128
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyB3NC9l
        d2wzeGZ2UlZSNDkzQURkdEpNWXk2Q3RnZ3RxY1AxMVVkLzVVRHlBCnhiaGw5bC81
        TitKbDkvNzJlZDZMb2NEUXpTNHJCMDdCMDM4bmJEMGQxaTQKLS0tIDUrdnpKK3Va
        Qno2MDZPTzRmbHhrWXkxaHBxN0FTeWVJRUhoZ21HSGVoSVkKhFu48b6YnGRBlTBK
        nf+J33ABLqSy2+LeqqnuaFfVEC+TypgwiUHoS2HCu2ivsY+Aa9e9NQfCvr4R8q4k
        /Zdr0Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UjJIbHhtU28vUG1GVmJk
        SXpQQ1dRSFdzSEFIMDdSVCtSeGxpVGVjOXlJCmVCMmZKbUp1VG83UTBmaGlmMTc2
        d1loakJCc2FVZ1ZMZU5aY3VPT05FNEkKLS0tIEhPYzFJUHBvRFMxMFhEbDJxZHZ0
        VW9xRWhQa1E4UElTSXhvWm9tTFRTWEUKuLxdUJR7ajUW+R2A6RkkvL+ClwXL4qvo
        Z7HzWmPFnhhx7C081oVjgpZN0DWxZ4heaepvEenT3Dfi/FlMCdj+YA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-10T16:45:25Z"
  mac: ENC[AES256_GCM,data:eou4OxWhKH/aAhRkkBaiUIVTI2WJ+vWuQU/JJupfCAKy7BpmlPsHfZSw9eGb/PvW427oV4JngRDhn5voEMyzRvX7NZhyej0qOoGdLgkvlTySy9c3B/4mEl+p+QgqZSCjwQiGoIRRhQGBxY0BFRVZYo5IcQegzB9eqUXRYGYks20=,iv:DEC+sy/W0H4LtTFqQTIVZo01iGDLMQZX8MSKHR/mEv0=,tag:eclov7cgygdBSXMPjtAgnA==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
