cluster:
  network:
    cni:
      name: none
machine:
  install:
    disk: /dev/sda
  sysctls:
    # 64MiB
    vm.min_free_kbytes: 65536
    vm.swappiness: 200
    vm.watermark_scale_factor: 250
  kubelet:
    extraMounts:
      - destination: /var/lib/longhorn
        type: bind
        source: /var/lib/longhorn
        options:
          - bind
          - rshared
          - rw
    extraConfig:
      mergeDefaultEvictionSettings: true
      evictionSoft:
        memory.available: 150Mi
      evictionSoftGracePeriod:
        memory.available: 15s
      evictionHard:
        memory.available: 128Mi
  nodeLabels:
    topology.kubernetes.io/region: ng
    topology.kubernetes.io/zone: ng-west-1
  network:
    hostname: sophons-oduduwa
    interfaces:
      - interface: ens18
        dhcp: false
        # enc!
        addresses:
          - ENC[AES256_GCM,data:OD7k8R2/Z479h+b3sf73WYI=,iv:JMyul9UlRJ4hbFjwRT/L8B0GGFa+xOdiH8YR83CeIO8=,tag:2lsSTwP+AAvm9DG3nVoMmA==,type:str]
        routes:
          - network: 0.0.0.0/0
            # enc!
            gateway: ENC[AES256_GCM,data:DB3G3Tq8v6IZBGmyvng=,iv:EoMi4jrbNSQxjCelqA5qsi0oSPBZZUozL0DpU5NJohA=,tag:uvYKjnx2OxSsaO/1WatDRg==,type:str]
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyArYkdh
        bmhQMFlIUGd0eU1BT21xRjhuK0xVSEIzYmExMW1xbm9UVVdibWhBCmZaamwvK1Vh
        NXVqTW0rdlZEWG9sSzlPK2YyNm8xakYvWFZrVEd2RlB4MG8KLS0tIExmUVBvcWFh
        bmtweVNTNG5CRXhoaG1pMFlKaFhYeTZaUm5XajFvWlFBVE0Kc/OCI/HjeN/EpsDa
        XWPB1K2giTQxKkooLmXmx5Tetx1x+1ShrOc5xJZLpDs4XhcTq280AiD7pwh8zuEy
        I2mhaA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4eFpydHVkc2FPRnVjR3FV
        cUhvT1R6RE0xbmxOd3JQc1ZYUzhHWng4N25vCjF1QUxxa2RKV1hCY3p1QTEzWXBX
        VUt4YzRLQ3E4bFZrcDZRaVNxWGY3UVUKLS0tIFNtTVhVYzhOUTBERWJpVDlNc2pC
        SUkvQ1diR1oyZS9rcVlVTnJGWHBod1UKYf1KI/cbYj66TYW5XJvTRJCHe+HDxbRB
        AyA1UibcvdpLMHTCzuP6P1jIASE9K3OZlLiF4rUvGEt4y1kQa9lz1A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-01T19:54:27Z"
  mac: ENC[AES256_GCM,data:83hf5O6gVCG5NouKvNaChO6FCJHBc93HvdsGIrTN5yWfpvCyKUV5JkOTEw0cYN89FxB84X9FxuvcPO65dmNKibCN3agF+CtpiJ+m8L12G87FhHw3pP03XUdQdqvXDHEcRHwrFBbPUWs/+k9/boOYaV4m4D1OAgTOtUj/sfswUtY=,iv:99vCOhEM+sFrx8mfGY//MIGeT7fCJ+519oNgeHjUU+M=,tag:tX5v7+zwu3UZXSEkM8T3tw==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  maxSize: 17GiB
  grow: false
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyArYkdh
        bmhQMFlIUGd0eU1BT21xRjhuK0xVSEIzYmExMW1xbm9UVVdibWhBCmZaamwvK1Vh
        NXVqTW0rdlZEWG9sSzlPK2YyNm8xakYvWFZrVEd2RlB4MG8KLS0tIExmUVBvcWFh
        bmtweVNTNG5CRXhoaG1pMFlKaFhYeTZaUm5XajFvWlFBVE0Kc/OCI/HjeN/EpsDa
        XWPB1K2giTQxKkooLmXmx5Tetx1x+1ShrOc5xJZLpDs4XhcTq280AiD7pwh8zuEy
        I2mhaA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4eFpydHVkc2FPRnVjR3FV
        cUhvT1R6RE0xbmxOd3JQc1ZYUzhHWng4N25vCjF1QUxxa2RKV1hCY3p1QTEzWXBX
        VUt4YzRLQ3E4bFZrcDZRaVNxWGY3UVUKLS0tIFNtTVhVYzhOUTBERWJpVDlNc2pC
        SUkvQ1diR1oyZS9rcVlVTnJGWHBod1UKYf1KI/cbYj66TYW5XJvTRJCHe+HDxbRB
        AyA1UibcvdpLMHTCzuP6P1jIASE9K3OZlLiF4rUvGEt4y1kQa9lz1A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-01T19:54:27Z"
  mac: ENC[AES256_GCM,data:83hf5O6gVCG5NouKvNaChO6FCJHBc93HvdsGIrTN5yWfpvCyKUV5JkOTEw0cYN89FxB84X9FxuvcPO65dmNKibCN3agF+CtpiJ+m8L12G87FhHw3pP03XUdQdqvXDHEcRHwrFBbPUWs/+k9/boOYaV4m4D1OAgTOtUj/sfswUtY=,iv:99vCOhEM+sFrx8mfGY//MIGeT7fCJ+519oNgeHjUU+M=,tag:tX5v7+zwu3UZXSEkM8T3tw==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: SwapVolumeConfig
name: swap
provisioning:
  diskSelector:
    match: system_disk
  minSize: 1GiB
  maxSize: 1GiB
  grow: false
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyArYkdh
        bmhQMFlIUGd0eU1BT21xRjhuK0xVSEIzYmExMW1xbm9UVVdibWhBCmZaamwvK1Vh
        NXVqTW0rdlZEWG9sSzlPK2YyNm8xakYvWFZrVEd2RlB4MG8KLS0tIExmUVBvcWFh
        bmtweVNTNG5CRXhoaG1pMFlKaFhYeTZaUm5XajFvWlFBVE0Kc/OCI/HjeN/EpsDa
        XWPB1K2giTQxKkooLmXmx5Tetx1x+1ShrOc5xJZLpDs4XhcTq280AiD7pwh8zuEy
        I2mhaA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4eFpydHVkc2FPRnVjR3FV
        cUhvT1R6RE0xbmxOd3JQc1ZYUzhHWng4N25vCjF1QUxxa2RKV1hCY3p1QTEzWXBX
        VUt4YzRLQ3E4bFZrcDZRaVNxWGY3UVUKLS0tIFNtTVhVYzhOUTBERWJpVDlNc2pC
        SUkvQ1diR1oyZS9rcVlVTnJGWHBod1UKYf1KI/cbYj66TYW5XJvTRJCHe+HDxbRB
        AyA1UibcvdpLMHTCzuP6P1jIASE9K3OZlLiF4rUvGEt4y1kQa9lz1A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-01T19:54:27Z"
  mac: ENC[AES256_GCM,data:83hf5O6gVCG5NouKvNaChO6FCJHBc93HvdsGIrTN5yWfpvCyKUV5JkOTEw0cYN89FxB84X9FxuvcPO65dmNKibCN3agF+CtpiJ+m8L12G87FhHw3pP03XUdQdqvXDHEcRHwrFBbPUWs/+k9/boOYaV4m4D1OAgTOtUj/sfswUtY=,iv:99vCOhEM+sFrx8mfGY//MIGeT7fCJ+519oNgeHjUU+M=,tag:tX5v7+zwu3UZXSEkM8T3tw==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: ZswapConfig
# The maximum percent of memory that zswap can use.
maxPoolPercent: 69
# Enable the shrinker feature: kernel might move
shrinkerEnabled: true
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyArYkdh
        bmhQMFlIUGd0eU1BT21xRjhuK0xVSEIzYmExMW1xbm9UVVdibWhBCmZaamwvK1Vh
        NXVqTW0rdlZEWG9sSzlPK2YyNm8xakYvWFZrVEd2RlB4MG8KLS0tIExmUVBvcWFh
        bmtweVNTNG5CRXhoaG1pMFlKaFhYeTZaUm5XajFvWlFBVE0Kc/OCI/HjeN/EpsDa
        XWPB1K2giTQxKkooLmXmx5Tetx1x+1ShrOc5xJZLpDs4XhcTq280AiD7pwh8zuEy
        I2mhaA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4eFpydHVkc2FPRnVjR3FV
        cUhvT1R6RE0xbmxOd3JQc1ZYUzhHWng4N25vCjF1QUxxa2RKV1hCY3p1QTEzWXBX
        VUt4YzRLQ3E4bFZrcDZRaVNxWGY3UVUKLS0tIFNtTVhVYzhOUTBERWJpVDlNc2pC
        SUkvQ1diR1oyZS9rcVlVTnJGWHBod1UKYf1KI/cbYj66TYW5XJvTRJCHe+HDxbRB
        AyA1UibcvdpLMHTCzuP6P1jIASE9K3OZlLiF4rUvGEt4y1kQa9lz1A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-01T19:54:27Z"
  mac: ENC[AES256_GCM,data:83hf5O6gVCG5NouKvNaChO6FCJHBc93HvdsGIrTN5yWfpvCyKUV5JkOTEw0cYN89FxB84X9FxuvcPO65dmNKibCN3agF+CtpiJ+m8L12G87FhHw3pP03XUdQdqvXDHEcRHwrFBbPUWs/+k9/boOYaV4m4D1OAgTOtUj/sfswUtY=,iv:99vCOhEM+sFrx8mfGY//MIGeT7fCJ+519oNgeHjUU+M=,tag:tX5v7+zwu3UZXSEkM8T3tw==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: ExtensionServiceConfig
name: tailscale
environment:
  - TS_ROUTES=10.41.4.0/24,2001:cafe:41:4::/64
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyArYkdh
        bmhQMFlIUGd0eU1BT21xRjhuK0xVSEIzYmExMW1xbm9UVVdibWhBCmZaamwvK1Vh
        NXVqTW0rdlZEWG9sSzlPK2YyNm8xakYvWFZrVEd2RlB4MG8KLS0tIExmUVBvcWFh
        bmtweVNTNG5CRXhoaG1pMFlKaFhYeTZaUm5XajFvWlFBVE0Kc/OCI/HjeN/EpsDa
        XWPB1K2giTQxKkooLmXmx5Tetx1x+1ShrOc5xJZLpDs4XhcTq280AiD7pwh8zuEy
        I2mhaA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4eFpydHVkc2FPRnVjR3FV
        cUhvT1R6RE0xbmxOd3JQc1ZYUzhHWng4N25vCjF1QUxxa2RKV1hCY3p1QTEzWXBX
        VUt4YzRLQ3E4bFZrcDZRaVNxWGY3UVUKLS0tIFNtTVhVYzhOUTBERWJpVDlNc2pC
        SUkvQ1diR1oyZS9rcVlVTnJGWHBod1UKYf1KI/cbYj66TYW5XJvTRJCHe+HDxbRB
        AyA1UibcvdpLMHTCzuP6P1jIASE9K3OZlLiF4rUvGEt4y1kQa9lz1A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-01T19:54:27Z"
  mac: ENC[AES256_GCM,data:83hf5O6gVCG5NouKvNaChO6FCJHBc93HvdsGIrTN5yWfpvCyKUV5JkOTEw0cYN89FxB84X9FxuvcPO65dmNKibCN3agF+CtpiJ+m8L12G87FhHw3pP03XUdQdqvXDHEcRHwrFBbPUWs/+k9/boOYaV4m4D1OAgTOtUj/sfswUtY=,iv:99vCOhEM+sFrx8mfGY//MIGeT7fCJ+519oNgeHjUU+M=,tag:tX5v7+zwu3UZXSEkM8T3tw==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
