cluster:
  network:
    cni:
      name: none
machine:
  install:
    disk: /dev/mmcblk0
    extraKernelArgs:
      - cma=256M
  sysctls:
    # 64MiB
    vm.min_free_kbytes: 65536
    vm.swappiness: 200
    vm.watermark_scale_factor: 250
  kubelet:
    nodeIP:
      validSubnets:
        - 10.42.0.0/16
        # enc!
        - ENC[AES256_GCM,data:6Gd9GfRRRhemixEx0+bJogyY+1UF9EQ=,iv:mzjx7Ee4VodRjR+Oh2SwiwO5QGmPrRXIsKbNOWsozzE=,tag:948MfBcr6N4JDnLqmu8qrA==,type:str]
    extraMounts:
      - destination: /var/lib/longhorn
        type: bind
        source: /var/lib/longhorn
        options:
          - bind
          - rshared
          - rw
    extraConfig:
      mergeDefaultEvictionSettings: true
      evictionSoft:
        memory.available: 256Mi
      evictionSoftGracePeriod:
        memory.available: 30s
      evictionHard:
        memory.available: 100Mi
  nodeLabels:
    topology.kubernetes.io/region: ng
    topology.kubernetes.io/zone: ng-west-1
    hugeloads.sophons.cloud/postgres: "false"
  network:
    hostname: sophons-prime
    interfaces:
      - interface: end0
        dhcp: false
        vlans:
          - vlanId: 42
            dhcp: false
            addresses:
              - 10.42.42.2/16
              # enc!
              - ENC[AES256_GCM,data:qKaMq9TvdEiC40vsxhaPY39xbuTfAsiXWLsE,iv:9qKYgKONqy0lbLM8WGT62BJwjDuHt+PBmDE/AoYGaWE=,tag:FxkbWuY0lsR6e7kt9YWhEA==,type:str]
            routes:
              - network: 0.0.0.0/0
                gateway: 10.42.0.1
              - network: ::/0
                gateway: fe80::9c05:d6ff:fe69:64b7
                metric: 200
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyA4N0or
        WGJyUWJtYUNWY1JBcGJPMEIzcWJtckZ3enZLQVpUV1pJeXVNQWs0CmM2OGY5Rm1H
        WmJFNEs2NVFjdUxIS2NNRnphMFFrT1lpbERJdUNlYnRXRncKLS0tIFVtTHQvNjAv
        eXpaUVRaU3NaY0VNZVY5cURPd2phaHUvemdySGZ1UnNncXcKgjP1kAey0tBW295o
        pZAEUpNsyLKoISJ9YQWf/SXS50fHyZz6W/5zFGG+GJurwF0ifNvm/HyzOnuJehsW
        L30ixQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYanZ5clpaQWxWQndrVGhL
        emd1WTl5czQ4bFhiU0pFYjJxYklnZzB0UVFzCkpFMDFpRTFEN2ZsRjUxbHJEUGRn
        MHBXenlzSDl5a2JyWGpneENmT0hSY28KLS0tIE45UHc1MFNhSU9VSWtyV0xIZGsz
        eFh4NERleTBxRW43RmV3ZXhnWnVYL1EKe/jAJGZceNt+K5CSvy3syEuJvWoKGFO9
        Tvt/Xf033ZOxy+qlJDDO4MTNh7ynLEt/5dEj5l2eq8C3oQ9smod2Aw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-17T16:22:08Z"
  mac: ENC[AES256_GCM,data:XLbMBOxbr9XwBfA6ajEp/gVuv7F91sxgx+sxOTaM1aXDeKDXkIlDnB8QqdZ9x/e391UyJ3dtgHTSMSGIiN1Rz/hqM7SY4a827aEKSeT/2YvXtmd9GC5jAqFJpv+EbuxECmzwabS3GwX5IDKLRDPlEMrsrWrcCG0lxo1euOpNXb4=,iv:r+lB2E8xOuSrO9RyT4jPKxzY75+nZ95AkvX9w//vC+k=,tag:xGFlbZA4XMZdu0OG7WHi7g==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  maxSize: 100GiB
  grow: false
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyA4N0or
        WGJyUWJtYUNWY1JBcGJPMEIzcWJtckZ3enZLQVpUV1pJeXVNQWs0CmM2OGY5Rm1H
        WmJFNEs2NVFjdUxIS2NNRnphMFFrT1lpbERJdUNlYnRXRncKLS0tIFVtTHQvNjAv
        eXpaUVRaU3NaY0VNZVY5cURPd2phaHUvemdySGZ1UnNncXcKgjP1kAey0tBW295o
        pZAEUpNsyLKoISJ9YQWf/SXS50fHyZz6W/5zFGG+GJurwF0ifNvm/HyzOnuJehsW
        L30ixQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYanZ5clpaQWxWQndrVGhL
        emd1WTl5czQ4bFhiU0pFYjJxYklnZzB0UVFzCkpFMDFpRTFEN2ZsRjUxbHJEUGRn
        MHBXenlzSDl5a2JyWGpneENmT0hSY28KLS0tIE45UHc1MFNhSU9VSWtyV0xIZGsz
        eFh4NERleTBxRW43RmV3ZXhnWnVYL1EKe/jAJGZceNt+K5CSvy3syEuJvWoKGFO9
        Tvt/Xf033ZOxy+qlJDDO4MTNh7ynLEt/5dEj5l2eq8C3oQ9smod2Aw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-17T16:22:08Z"
  mac: ENC[AES256_GCM,data:XLbMBOxbr9XwBfA6ajEp/gVuv7F91sxgx+sxOTaM1aXDeKDXkIlDnB8QqdZ9x/e391UyJ3dtgHTSMSGIiN1Rz/hqM7SY4a827aEKSeT/2YvXtmd9GC5jAqFJpv+EbuxECmzwabS3GwX5IDKLRDPlEMrsrWrcCG0lxo1euOpNXb4=,iv:r+lB2E8xOuSrO9RyT4jPKxzY75+nZ95AkvX9w//vC+k=,tag:xGFlbZA4XMZdu0OG7WHi7g==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: SwapVolumeConfig
name: swap-1GiB
provisioning:
  diskSelector:
    match: system_disk
  minSize: 1GiB
  maxSize: 1GiB
  grow: false
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyA4N0or
        WGJyUWJtYUNWY1JBcGJPMEIzcWJtckZ3enZLQVpUV1pJeXVNQWs0CmM2OGY5Rm1H
        WmJFNEs2NVFjdUxIS2NNRnphMFFrT1lpbERJdUNlYnRXRncKLS0tIFVtTHQvNjAv
        eXpaUVRaU3NaY0VNZVY5cURPd2phaHUvemdySGZ1UnNncXcKgjP1kAey0tBW295o
        pZAEUpNsyLKoISJ9YQWf/SXS50fHyZz6W/5zFGG+GJurwF0ifNvm/HyzOnuJehsW
        L30ixQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYanZ5clpaQWxWQndrVGhL
        emd1WTl5czQ4bFhiU0pFYjJxYklnZzB0UVFzCkpFMDFpRTFEN2ZsRjUxbHJEUGRn
        MHBXenlzSDl5a2JyWGpneENmT0hSY28KLS0tIE45UHc1MFNhSU9VSWtyV0xIZGsz
        eFh4NERleTBxRW43RmV3ZXhnWnVYL1EKe/jAJGZceNt+K5CSvy3syEuJvWoKGFO9
        Tvt/Xf033ZOxy+qlJDDO4MTNh7ynLEt/5dEj5l2eq8C3oQ9smod2Aw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-17T16:22:08Z"
  mac: ENC[AES256_GCM,data:XLbMBOxbr9XwBfA6ajEp/gVuv7F91sxgx+sxOTaM1aXDeKDXkIlDnB8QqdZ9x/e391UyJ3dtgHTSMSGIiN1Rz/hqM7SY4a827aEKSeT/2YvXtmd9GC5jAqFJpv+EbuxECmzwabS3GwX5IDKLRDPlEMrsrWrcCG0lxo1euOpNXb4=,iv:r+lB2E8xOuSrO9RyT4jPKxzY75+nZ95AkvX9w//vC+k=,tag:xGFlbZA4XMZdu0OG7WHi7g==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: ZswapConfig
# The maximum percent of memory that zswap can use.
maxPoolPercent: 69
# Enable the shrinker feature: kernel might move
shrinkerEnabled: true
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyA4N0or
        WGJyUWJtYUNWY1JBcGJPMEIzcWJtckZ3enZLQVpUV1pJeXVNQWs0CmM2OGY5Rm1H
        WmJFNEs2NVFjdUxIS2NNRnphMFFrT1lpbERJdUNlYnRXRncKLS0tIFVtTHQvNjAv
        eXpaUVRaU3NaY0VNZVY5cURPd2phaHUvemdySGZ1UnNncXcKgjP1kAey0tBW295o
        pZAEUpNsyLKoISJ9YQWf/SXS50fHyZz6W/5zFGG+GJurwF0ifNvm/HyzOnuJehsW
        L30ixQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYanZ5clpaQWxWQndrVGhL
        emd1WTl5czQ4bFhiU0pFYjJxYklnZzB0UVFzCkpFMDFpRTFEN2ZsRjUxbHJEUGRn
        MHBXenlzSDl5a2JyWGpneENmT0hSY28KLS0tIE45UHc1MFNhSU9VSWtyV0xIZGsz
        eFh4NERleTBxRW43RmV3ZXhnWnVYL1EKe/jAJGZceNt+K5CSvy3syEuJvWoKGFO9
        Tvt/Xf033ZOxy+qlJDDO4MTNh7ynLEt/5dEj5l2eq8C3oQ9smod2Aw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-17T16:22:08Z"
  mac: ENC[AES256_GCM,data:XLbMBOxbr9XwBfA6ajEp/gVuv7F91sxgx+sxOTaM1aXDeKDXkIlDnB8QqdZ9x/e391UyJ3dtgHTSMSGIiN1Rz/hqM7SY4a827aEKSeT/2YvXtmd9GC5jAqFJpv+EbuxECmzwabS3GwX5IDKLRDPlEMrsrWrcCG0lxo1euOpNXb4=,iv:r+lB2E8xOuSrO9RyT4jPKxzY75+nZ95AkvX9w//vC+k=,tag:xGFlbZA4XMZdu0OG7WHi7g==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
