cluster:
  network:
    cni:
      name: none
machine:
  install:
    disk: /dev/mmcblk0
    extraKernelArgs:
      - cma=256M
  sysctls:
    # 64MiB
    vm.min_free_kbytes: 65536
    vm.swappiness: 200
    vm.watermark_scale_factor: 250
  kubelet:
    nodeIP:
      validSubnets:
        - 10.42.0.0/16
        # enc!
        - ENC[AES256_GCM,data:E6yXwp0iah/oqY8OTSTPgFNWUgVLdOs=,iv:ZjG4J4+n1pry9S9WxW3uh3neNn8nkRVr3DJp+DLtpg4=,tag:1eyUAYxNZQFTnbrmHDPtHQ==,type:str]
    extraMounts:
      - destination: /var/lib/longhorn
        type: bind
        source: /var/lib/longhorn
        options:
          - bind
          - rshared
          - rw
    extraConfig:
      mergeDefaultEvictionSettings: true
      evictionSoft:
        memory.available: 150Mi
      evictionSoftGracePeriod:
        memory.available: 30s
      evictionHard:
        memory.available: 100Mi
  nodeLabels:
    topology.kubernetes.io/region: ng
    topology.kubernetes.io/zone: ng-west-1
    hugeloads.sophons.cloud/postgres: "false"
  network:
    hostname: sophons-prime
    interfaces:
      - interface: end0
        dhcp: false
        vlans:
          - vlanId: 42
            dhcp: false
            addresses:
              - 10.42.42.2/16
              # enc!
              - ENC[AES256_GCM,data:jvBhBuiMKK0ZU75PNtlMzJn9aKe3x9i9D5u5,iv:6L83W1IUAYj8PEzvyQfbBKUYOkplzj+Dmq/OkdUYW/g=,tag:RtPvHXAWu9fGeNDJWwD4Wg==,type:str]
            routes:
              - network: 0.0.0.0/0
                gateway: 10.42.0.1
              - network: ::/0
                gateway: fe80::9c05:d6ff:fe69:64b7
                metric: 200
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBKLzl3
        WHY0cTBDQ3RlRlVJZUJWN0lLL1ovTUEreE9TRUJjbmJhb0tkdmpZClQwNVM2U0xm
        cHBEMlQvWEZlQVlQOE0wSERETWlqQXZNZUdTVWxIRVNRVEEKLS0tIEd3THpHb2Nu
        UjZnNFljcnYxWUw3emNqSVplbnpSeVpaVHRaMlA0dTF5S1kK3g3V/92R80J4e/Y1
        nAku64GiY7y2dwUeSLx5hfaTRG8BI41YEyipj7u7+wZF/vXUQXyGusTnKFh/+Hmd
        uCgT3g==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsckJHYlEwVnorRkhXQUlW
        Y3lQQTJyMHkwdUJxazFPVTgvU3E5UklGZnhBCjY4ODAwODFCOHgranVwajZIdEsv
        ZVp6S3F6YjVBYnlPMllYYk14Qzh0bWcKLS0tIHBmRXNxNFNuTVQ1OUxlaWZGd2Zl
        aUpQUks1d004MXFHUE1XaHJYWmNjckUK7G93rsfN5aGk3uxueNjCi5hs1cy9u7jb
        viG7z5yiHBLsyds4g0enaNPoa7S3H1WPzv6RSLQ+IWDLbsLOrLryfQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-18T18:44:59Z"
  mac: ENC[AES256_GCM,data:13OIeWfoJu1H7YMCg3S22K2tA9VYXobzlRNIuqMVGnNBruZEtCVMMaBK4+I/cwrgfgtCr1bzO6zM3mqIqbVOMCrv/0+JnVXc/mdiTVa8Yu+HPD1j7RELaLE8yk0TA4kGYVcXmmML3zZFi2AiTSb2aF4oQdObGmCVHGruO99jFOA=,iv:ccq6w9XtmFLBIB1xFfmr1vZp+tyA1lcafa12bw6QXbI=,tag:BPtKVUmHmR/xebCH9Ad0WQ==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  maxSize: 100GiB
  grow: false
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBKLzl3
        WHY0cTBDQ3RlRlVJZUJWN0lLL1ovTUEreE9TRUJjbmJhb0tkdmpZClQwNVM2U0xm
        cHBEMlQvWEZlQVlQOE0wSERETWlqQXZNZUdTVWxIRVNRVEEKLS0tIEd3THpHb2Nu
        UjZnNFljcnYxWUw3emNqSVplbnpSeVpaVHRaMlA0dTF5S1kK3g3V/92R80J4e/Y1
        nAku64GiY7y2dwUeSLx5hfaTRG8BI41YEyipj7u7+wZF/vXUQXyGusTnKFh/+Hmd
        uCgT3g==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsckJHYlEwVnorRkhXQUlW
        Y3lQQTJyMHkwdUJxazFPVTgvU3E5UklGZnhBCjY4ODAwODFCOHgranVwajZIdEsv
        ZVp6S3F6YjVBYnlPMllYYk14Qzh0bWcKLS0tIHBmRXNxNFNuTVQ1OUxlaWZGd2Zl
        aUpQUks1d004MXFHUE1XaHJYWmNjckUK7G93rsfN5aGk3uxueNjCi5hs1cy9u7jb
        viG7z5yiHBLsyds4g0enaNPoa7S3H1WPzv6RSLQ+IWDLbsLOrLryfQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-18T18:44:59Z"
  mac: ENC[AES256_GCM,data:13OIeWfoJu1H7YMCg3S22K2tA9VYXobzlRNIuqMVGnNBruZEtCVMMaBK4+I/cwrgfgtCr1bzO6zM3mqIqbVOMCrv/0+JnVXc/mdiTVa8Yu+HPD1j7RELaLE8yk0TA4kGYVcXmmML3zZFi2AiTSb2aF4oQdObGmCVHGruO99jFOA=,iv:ccq6w9XtmFLBIB1xFfmr1vZp+tyA1lcafa12bw6QXbI=,tag:BPtKVUmHmR/xebCH9Ad0WQ==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: SwapVolumeConfig
name: swap-1GiB
provisioning:
  diskSelector:
    match: system_disk
  minSize: 1GiB
  maxSize: 1GiB
  grow: false
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBKLzl3
        WHY0cTBDQ3RlRlVJZUJWN0lLL1ovTUEreE9TRUJjbmJhb0tkdmpZClQwNVM2U0xm
        cHBEMlQvWEZlQVlQOE0wSERETWlqQXZNZUdTVWxIRVNRVEEKLS0tIEd3THpHb2Nu
        UjZnNFljcnYxWUw3emNqSVplbnpSeVpaVHRaMlA0dTF5S1kK3g3V/92R80J4e/Y1
        nAku64GiY7y2dwUeSLx5hfaTRG8BI41YEyipj7u7+wZF/vXUQXyGusTnKFh/+Hmd
        uCgT3g==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsckJHYlEwVnorRkhXQUlW
        Y3lQQTJyMHkwdUJxazFPVTgvU3E5UklGZnhBCjY4ODAwODFCOHgranVwajZIdEsv
        ZVp6S3F6YjVBYnlPMllYYk14Qzh0bWcKLS0tIHBmRXNxNFNuTVQ1OUxlaWZGd2Zl
        aUpQUks1d004MXFHUE1XaHJYWmNjckUK7G93rsfN5aGk3uxueNjCi5hs1cy9u7jb
        viG7z5yiHBLsyds4g0enaNPoa7S3H1WPzv6RSLQ+IWDLbsLOrLryfQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-18T18:44:59Z"
  mac: ENC[AES256_GCM,data:13OIeWfoJu1H7YMCg3S22K2tA9VYXobzlRNIuqMVGnNBruZEtCVMMaBK4+I/cwrgfgtCr1bzO6zM3mqIqbVOMCrv/0+JnVXc/mdiTVa8Yu+HPD1j7RELaLE8yk0TA4kGYVcXmmML3zZFi2AiTSb2aF4oQdObGmCVHGruO99jFOA=,iv:ccq6w9XtmFLBIB1xFfmr1vZp+tyA1lcafa12bw6QXbI=,tag:BPtKVUmHmR/xebCH9Ad0WQ==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: ZswapConfig
# The maximum percent of memory that zswap can use.
maxPoolPercent: 69
# Enable the shrinker feature: kernel might move
shrinkerEnabled: true
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBKLzl3
        WHY0cTBDQ3RlRlVJZUJWN0lLL1ovTUEreE9TRUJjbmJhb0tkdmpZClQwNVM2U0xm
        cHBEMlQvWEZlQVlQOE0wSERETWlqQXZNZUdTVWxIRVNRVEEKLS0tIEd3THpHb2Nu
        UjZnNFljcnYxWUw3emNqSVplbnpSeVpaVHRaMlA0dTF5S1kK3g3V/92R80J4e/Y1
        nAku64GiY7y2dwUeSLx5hfaTRG8BI41YEyipj7u7+wZF/vXUQXyGusTnKFh/+Hmd
        uCgT3g==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsckJHYlEwVnorRkhXQUlW
        Y3lQQTJyMHkwdUJxazFPVTgvU3E5UklGZnhBCjY4ODAwODFCOHgranVwajZIdEsv
        ZVp6S3F6YjVBYnlPMllYYk14Qzh0bWcKLS0tIHBmRXNxNFNuTVQ1OUxlaWZGd2Zl
        aUpQUks1d004MXFHUE1XaHJYWmNjckUK7G93rsfN5aGk3uxueNjCi5hs1cy9u7jb
        viG7z5yiHBLsyds4g0enaNPoa7S3H1WPzv6RSLQ+IWDLbsLOrLryfQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-18T18:44:59Z"
  mac: ENC[AES256_GCM,data:13OIeWfoJu1H7YMCg3S22K2tA9VYXobzlRNIuqMVGnNBruZEtCVMMaBK4+I/cwrgfgtCr1bzO6zM3mqIqbVOMCrv/0+JnVXc/mdiTVa8Yu+HPD1j7RELaLE8yk0TA4kGYVcXmmML3zZFi2AiTSb2aF4oQdObGmCVHGruO99jFOA=,iv:ccq6w9XtmFLBIB1xFfmr1vZp+tyA1lcafa12bw6QXbI=,tag:BPtKVUmHmR/xebCH9Ad0WQ==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
