cluster:
  network:
    cni:
      name: none
machine:
  install:
    disk: /dev/mmcblk0
    extraKernelArgs:
      - cma=256M
  sysctls:
    # 64MiB
    vm.min_free_kbytes: 65536
    vm.swappiness: 200
    vm.watermark_scale_factor: 250
  kubelet:
    nodeIP:
      validSubnets:
        - 10.42.0.0/16
        # enc!
        - ENC[AES256_GCM,data:UYCFVE+staHmJzYmLRM7/jg0hO2QK3Y=,iv:5hXBAv5bJChc2DagFcGDgcrrn6qPPa+DW1vCD/AXFco=,tag:PxdbQDMEOQ1FGg6tvintpA==,type:str]
    extraMounts:
      - destination: /var/lib/longhorn
        type: bind
        source: /var/lib/longhorn
        options:
          - bind
          - rshared
          - rw
    extraConfig:
      mergeDefaultEvictionSettings: true
      evictionSoft:
        memory.available: 150Mi
      evictionSoftGracePeriod:
        memory.available: 30s
      evictionHard:
        memory.available: 100Mi
  nodeLabels:
    topology.kubernetes.io/region: ng
    topology.kubernetes.io/zone: ng-east-2
    hugeloads.sophons.cloud/postgres: "false"
  network:
    hostname: sophons-prime
    interfaces:
      - interface: end0
        dhcp: false
        vlans:
          - vlanId: 42
            dhcp: false
            addresses:
              - 10.42.42.2/16
              # enc!
              - ENC[AES256_GCM,data:LHB8KXRUioogkb2lffWwWtwLJtZh3Xf9vIbb,iv:tLjvd4diTTcFHIi6PnrF5rzSoCBpyWZsKMPrCleBAVE=,tag:jAv65Ad/890lX4ideI5bJw==,type:str]
            routes:
              - network: 0.0.0.0/0
                gateway: 10.42.0.1
              - network: ::/0
                gateway: fe80::9c05:d6ff:fe69:64b7
                metric: 200
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBvMkYw
        WTE3V1lmRGNNZ3BudVR0a08rdDlnMVk4enl4b1ZaVVg2NXV3VVhZCi9PYXh1aDg3
        OEltV21vRHBZYy9oWGlXcndWRjBLSEhUTFB0d0h3dHUvRkkKLS0tIDM2cXdicnNX
        YlR5SVErK1JEMTY4NUc4WVVsdGt0WllIamV0VkhjTnB0VFUKsFPQ9W7vbW8YtPea
        6jtyrnQuouAqS2rMGZnsUfQMxbVoxwE40mo77BANV1bRA6ck409XImC3j9/UZOYF
        p3pvlw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUzZaV0VRbktRT3FSMVJM
        MTlnUmh6WG5YOW13ckVoOVN3NEpwTGF1UFNzCnB5cnBzRkljY3d5QWdRWFIrL2JB
        NThQY3JxVlJHSWJYNXE3alArTHVSaTQKLS0tIHJjNi8ycWo0OGZObS9URmpwd0c4
        d2RycXpLWDRWcmhDQnB0bHZaNHpiUzAKr+AjOr4TEqdAtXcBngULL1/TyeEBbLbI
        i0GIW9JS5cW5jz1y82Pea5Zg4gQWcqb/vLDHGhIHQ96SF7iINgd3Iw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-20T00:47:41Z"
  mac: ENC[AES256_GCM,data:yoLR9aIZmbmdH7hv/frM0wC2NQNh62RZkVCi/Or6Czj4USQo0R973gq2p6a0xT/jEnXmL0wHdRiS/2SpGTgr3UjopBkr22torLtlEweYkRLhQhqQczLGW4BXYel0rtu5FFdC8bwpCwn1Ucq+nEyeQzALsxLWO0PAZ2qZIuPykEQ=,iv:9Dm6vWbhq5An5QZauD8riMU5OHpOltIfbvIYRqWv/6c=,tag:DayazK3wlxkSkuIvJ/xWsA==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  maxSize: 100GiB
  grow: false
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBvMkYw
        WTE3V1lmRGNNZ3BudVR0a08rdDlnMVk4enl4b1ZaVVg2NXV3VVhZCi9PYXh1aDg3
        OEltV21vRHBZYy9oWGlXcndWRjBLSEhUTFB0d0h3dHUvRkkKLS0tIDM2cXdicnNX
        YlR5SVErK1JEMTY4NUc4WVVsdGt0WllIamV0VkhjTnB0VFUKsFPQ9W7vbW8YtPea
        6jtyrnQuouAqS2rMGZnsUfQMxbVoxwE40mo77BANV1bRA6ck409XImC3j9/UZOYF
        p3pvlw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUzZaV0VRbktRT3FSMVJM
        MTlnUmh6WG5YOW13ckVoOVN3NEpwTGF1UFNzCnB5cnBzRkljY3d5QWdRWFIrL2JB
        NThQY3JxVlJHSWJYNXE3alArTHVSaTQKLS0tIHJjNi8ycWo0OGZObS9URmpwd0c4
        d2RycXpLWDRWcmhDQnB0bHZaNHpiUzAKr+AjOr4TEqdAtXcBngULL1/TyeEBbLbI
        i0GIW9JS5cW5jz1y82Pea5Zg4gQWcqb/vLDHGhIHQ96SF7iINgd3Iw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-20T00:47:41Z"
  mac: ENC[AES256_GCM,data:yoLR9aIZmbmdH7hv/frM0wC2NQNh62RZkVCi/Or6Czj4USQo0R973gq2p6a0xT/jEnXmL0wHdRiS/2SpGTgr3UjopBkr22torLtlEweYkRLhQhqQczLGW4BXYel0rtu5FFdC8bwpCwn1Ucq+nEyeQzALsxLWO0PAZ2qZIuPykEQ=,iv:9Dm6vWbhq5An5QZauD8riMU5OHpOltIfbvIYRqWv/6c=,tag:DayazK3wlxkSkuIvJ/xWsA==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: SwapVolumeConfig
name: swap-1GiB
provisioning:
  diskSelector:
    match: system_disk
  minSize: 1GiB
  maxSize: 1GiB
  grow: false
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBvMkYw
        WTE3V1lmRGNNZ3BudVR0a08rdDlnMVk4enl4b1ZaVVg2NXV3VVhZCi9PYXh1aDg3
        OEltV21vRHBZYy9oWGlXcndWRjBLSEhUTFB0d0h3dHUvRkkKLS0tIDM2cXdicnNX
        YlR5SVErK1JEMTY4NUc4WVVsdGt0WllIamV0VkhjTnB0VFUKsFPQ9W7vbW8YtPea
        6jtyrnQuouAqS2rMGZnsUfQMxbVoxwE40mo77BANV1bRA6ck409XImC3j9/UZOYF
        p3pvlw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUzZaV0VRbktRT3FSMVJM
        MTlnUmh6WG5YOW13ckVoOVN3NEpwTGF1UFNzCnB5cnBzRkljY3d5QWdRWFIrL2JB
        NThQY3JxVlJHSWJYNXE3alArTHVSaTQKLS0tIHJjNi8ycWo0OGZObS9URmpwd0c4
        d2RycXpLWDRWcmhDQnB0bHZaNHpiUzAKr+AjOr4TEqdAtXcBngULL1/TyeEBbLbI
        i0GIW9JS5cW5jz1y82Pea5Zg4gQWcqb/vLDHGhIHQ96SF7iINgd3Iw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-20T00:47:41Z"
  mac: ENC[AES256_GCM,data:yoLR9aIZmbmdH7hv/frM0wC2NQNh62RZkVCi/Or6Czj4USQo0R973gq2p6a0xT/jEnXmL0wHdRiS/2SpGTgr3UjopBkr22torLtlEweYkRLhQhqQczLGW4BXYel0rtu5FFdC8bwpCwn1Ucq+nEyeQzALsxLWO0PAZ2qZIuPykEQ=,iv:9Dm6vWbhq5An5QZauD8riMU5OHpOltIfbvIYRqWv/6c=,tag:DayazK3wlxkSkuIvJ/xWsA==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: ZswapConfig
# The maximum percent of memory that zswap can use.
maxPoolPercent: 69
# Enable the shrinker feature: kernel might move
shrinkerEnabled: true
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBvMkYw
        WTE3V1lmRGNNZ3BudVR0a08rdDlnMVk4enl4b1ZaVVg2NXV3VVhZCi9PYXh1aDg3
        OEltV21vRHBZYy9oWGlXcndWRjBLSEhUTFB0d0h3dHUvRkkKLS0tIDM2cXdicnNX
        YlR5SVErK1JEMTY4NUc4WVVsdGt0WllIamV0VkhjTnB0VFUKsFPQ9W7vbW8YtPea
        6jtyrnQuouAqS2rMGZnsUfQMxbVoxwE40mo77BANV1bRA6ck409XImC3j9/UZOYF
        p3pvlw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUzZaV0VRbktRT3FSMVJM
        MTlnUmh6WG5YOW13ckVoOVN3NEpwTGF1UFNzCnB5cnBzRkljY3d5QWdRWFIrL2JB
        NThQY3JxVlJHSWJYNXE3alArTHVSaTQKLS0tIHJjNi8ycWo0OGZObS9URmpwd0c4
        d2RycXpLWDRWcmhDQnB0bHZaNHpiUzAKr+AjOr4TEqdAtXcBngULL1/TyeEBbLbI
        i0GIW9JS5cW5jz1y82Pea5Zg4gQWcqb/vLDHGhIHQ96SF7iINgd3Iw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-20T00:47:41Z"
  mac: ENC[AES256_GCM,data:yoLR9aIZmbmdH7hv/frM0wC2NQNh62RZkVCi/Or6Czj4USQo0R973gq2p6a0xT/jEnXmL0wHdRiS/2SpGTgr3UjopBkr22torLtlEweYkRLhQhqQczLGW4BXYel0rtu5FFdC8bwpCwn1Ucq+nEyeQzALsxLWO0PAZ2qZIuPykEQ=,iv:9Dm6vWbhq5An5QZauD8riMU5OHpOltIfbvIYRqWv/6c=,tag:DayazK3wlxkSkuIvJ/xWsA==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
