apiVersion: v1alpha1
kind: HostnameConfig
auto: "off"
hostname: sophons-prime
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBSeEZQ
        cWk0UmJSQ0R2Nk1RR0FIaXRxQk1FTDIwWVJsYUtFblU1bU9xZlQwCkhXU1ZzSmhl
        N2hnRlRQQjZKdGhWVzh0VnUzclVjRjA0YjRhY3BBdGZQMGMKLS0tIG15ZGpJWW9r
        WWRFMnJ0Mk91eU9zdlV5SWRNRnhzM2RhbVU5b1VVMnUzUWcKV/4tZTcSSDUc0zyk
        pMPFGfodbwCHqeiohyzHEeHGvepTaLMRllRleDmCkiciUDOjh4cQ/Qtjzp9q8aRC
        i3Zl/Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5cGtKcUs1VzFSYXd5Wk1o
        UkZxcWkzYmgzYldGdHMzS2dJWXR5WGM1SkZFCklZVnFhQUJ0SEdqUDU4TFQ2dlE2
        N3ZQY0lxU3JZWVRYSTRobEhiTUIrVGsKLS0tIEtuNEJTNmFVVmpuc2RlbzJLelAz
        QlFjOVM2MlpTTEdBT3lndGxhdHQzWEUKo52AuXT3+aBTZhor5M/DEEPQI8XzetW7
        1C2pw4jUTDmTG6zkDqVvAT16ZG/3eqivAxCVBtEgRJJfSSg2W43nrg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-09-03T10:59:14Z"
  mac: ENC[AES256_GCM,data:DEHZjNrZIFBWa9/0MVNrwq2acGuK0hODqYPZ6Z7XCDwMmGZcfVxqtFd2e8y2iK2otUMqGtAAKH40YC1w2k4kXSbC/phHY4p8oaTKXWJtnYDXUrqSss0cX+rKhbONB0a5JSpvCSGp0WwD+V9BFp8v9wmq6eUX2GrhH+uqfCb/3ds=,iv:hlb/tpGCrGVJaZpHviZpZUMVsvS1xkgU06wgWI7J80s=,tag:wUfPTP46M9SRONyh8WUhPw==,type:str]
  version: 3.13.3
---
cluster:
  network:
    cni:
      name: none
machine:
  install:
    disk: /dev/mmcblk0
  kernel:
    modules:
      - name: snd-usb-audio
  sysctls:
    # 64MiB
    vm.min_free_kbytes: 65536
    vm.swappiness: 200
    vm.watermark_scale_factor: 250
  kubelet:
    extraConfig:
      mergeDefaultEvictionSettings: true
      evictionSoft:
        memory.available: 150Mi
      evictionSoftGracePeriod:
        memory.available: 30s
      evictionHard:
        memory.available: 100Mi
  nodeLabels:
    egress.sophons.cloud/positron: "true"
    topology.kubernetes.io/region: ng
    # TODO: fully merge all of NG into one zone
    topology.kubernetes.io/zone: ng-east-1
    hugeloads.sophons.cloud/postgres: "false"
  network:
    interfaces:
      - interface: end0
        dhcp: false
        vlans:
          - vlanId: 42
            dhcp: false
            # dhcp: true
            # dhcpOptions:
            #   ipv4: false
            #   ipv6: true
            addresses:
              - 10.42.42.2/16
            routes:
              - network: 0.0.0.0/0
                gateway: 10.42.0.1
                # - network: ::/0
                #   gateway: fe80::9c05:d6ff:fe69:64b7
                #   metric: 200
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBSeEZQ
        cWk0UmJSQ0R2Nk1RR0FIaXRxQk1FTDIwWVJsYUtFblU1bU9xZlQwCkhXU1ZzSmhl
        N2hnRlRQQjZKdGhWVzh0VnUzclVjRjA0YjRhY3BBdGZQMGMKLS0tIG15ZGpJWW9r
        WWRFMnJ0Mk91eU9zdlV5SWRNRnhzM2RhbVU5b1VVMnUzUWcKV/4tZTcSSDUc0zyk
        pMPFGfodbwCHqeiohyzHEeHGvepTaLMRllRleDmCkiciUDOjh4cQ/Qtjzp9q8aRC
        i3Zl/Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5cGtKcUs1VzFSYXd5Wk1o
        UkZxcWkzYmgzYldGdHMzS2dJWXR5WGM1SkZFCklZVnFhQUJ0SEdqUDU4TFQ2dlE2
        N3ZQY0lxU3JZWVRYSTRobEhiTUIrVGsKLS0tIEtuNEJTNmFVVmpuc2RlbzJLelAz
        QlFjOVM2MlpTTEdBT3lndGxhdHQzWEUKo52AuXT3+aBTZhor5M/DEEPQI8XzetW7
        1C2pw4jUTDmTG6zkDqVvAT16ZG/3eqivAxCVBtEgRJJfSSg2W43nrg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-09-03T10:59:14Z"
  mac: ENC[AES256_GCM,data:DEHZjNrZIFBWa9/0MVNrwq2acGuK0hODqYPZ6Z7XCDwMmGZcfVxqtFd2e8y2iK2otUMqGtAAKH40YC1w2k4kXSbC/phHY4p8oaTKXWJtnYDXUrqSss0cX+rKhbONB0a5JSpvCSGp0WwD+V9BFp8v9wmq6eUX2GrhH+uqfCb/3ds=,iv:hlb/tpGCrGVJaZpHviZpZUMVsvS1xkgU06wgWI7J80s=,tag:wUfPTP46M9SRONyh8WUhPw==,type:str]
  version: 3.13.3
---
# https://tailscale.com/docs/reference/best-practices/performance#linux-optimizations-for-subnet-routers-and-exit-nodes
apiVersion: v1alpha1
kind: EthernetConfig
name: end0
features:
  rx-gro-list: "off"
  rx-udp-gro-forwarding: "on"
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBSeEZQ
        cWk0UmJSQ0R2Nk1RR0FIaXRxQk1FTDIwWVJsYUtFblU1bU9xZlQwCkhXU1ZzSmhl
        N2hnRlRQQjZKdGhWVzh0VnUzclVjRjA0YjRhY3BBdGZQMGMKLS0tIG15ZGpJWW9r
        WWRFMnJ0Mk91eU9zdlV5SWRNRnhzM2RhbVU5b1VVMnUzUWcKV/4tZTcSSDUc0zyk
        pMPFGfodbwCHqeiohyzHEeHGvepTaLMRllRleDmCkiciUDOjh4cQ/Qtjzp9q8aRC
        i3Zl/Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5cGtKcUs1VzFSYXd5Wk1o
        UkZxcWkzYmgzYldGdHMzS2dJWXR5WGM1SkZFCklZVnFhQUJ0SEdqUDU4TFQ2dlE2
        N3ZQY0lxU3JZWVRYSTRobEhiTUIrVGsKLS0tIEtuNEJTNmFVVmpuc2RlbzJLelAz
        QlFjOVM2MlpTTEdBT3lndGxhdHQzWEUKo52AuXT3+aBTZhor5M/DEEPQI8XzetW7
        1C2pw4jUTDmTG6zkDqVvAT16ZG/3eqivAxCVBtEgRJJfSSg2W43nrg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-09-03T10:59:14Z"
  mac: ENC[AES256_GCM,data:DEHZjNrZIFBWa9/0MVNrwq2acGuK0hODqYPZ6Z7XCDwMmGZcfVxqtFd2e8y2iK2otUMqGtAAKH40YC1w2k4kXSbC/phHY4p8oaTKXWJtnYDXUrqSss0cX+rKhbONB0a5JSpvCSGp0WwD+V9BFp8v9wmq6eUX2GrhH+uqfCb/3ds=,iv:hlb/tpGCrGVJaZpHviZpZUMVsvS1xkgU06wgWI7J80s=,tag:wUfPTP46M9SRONyh8WUhPw==,type:str]
  version: 3.13.3
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  maxSize: 100GiB
  grow: false
# ---
# apiVersion: v1alpha1
# kind: SwapVolumeConfig
# name: swap-1GiB
# provisioning:
#   diskSelector:
#     match: system_disk
#   minSize: 1GiB
#   maxSize: 1GiB
#   grow: false
# ---
# apiVersion: v1alpha1
# kind: ZswapConfig
# # The maximum percent of memory that zswap can use.
# maxPoolPercent: 69
# # Enable the shrinker feature: kernel might move
# shrinkerEnabled: true
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBSeEZQ
        cWk0UmJSQ0R2Nk1RR0FIaXRxQk1FTDIwWVJsYUtFblU1bU9xZlQwCkhXU1ZzSmhl
        N2hnRlRQQjZKdGhWVzh0VnUzclVjRjA0YjRhY3BBdGZQMGMKLS0tIG15ZGpJWW9r
        WWRFMnJ0Mk91eU9zdlV5SWRNRnhzM2RhbVU5b1VVMnUzUWcKV/4tZTcSSDUc0zyk
        pMPFGfodbwCHqeiohyzHEeHGvepTaLMRllRleDmCkiciUDOjh4cQ/Qtjzp9q8aRC
        i3Zl/Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5cGtKcUs1VzFSYXd5Wk1o
        UkZxcWkzYmgzYldGdHMzS2dJWXR5WGM1SkZFCklZVnFhQUJ0SEdqUDU4TFQ2dlE2
        N3ZQY0lxU3JZWVRYSTRobEhiTUIrVGsKLS0tIEtuNEJTNmFVVmpuc2RlbzJLelAz
        QlFjOVM2MlpTTEdBT3lndGxhdHQzWEUKo52AuXT3+aBTZhor5M/DEEPQI8XzetW7
        1C2pw4jUTDmTG6zkDqVvAT16ZG/3eqivAxCVBtEgRJJfSSg2W43nrg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
  encrypted_comment_regex: enc!
  lastmodified: "2026-09-03T10:59:14Z"
  mac: ENC[AES256_GCM,data:DEHZjNrZIFBWa9/0MVNrwq2acGuK0hODqYPZ6Z7XCDwMmGZcfVxqtFd2e8y2iK2otUMqGtAAKH40YC1w2k4kXSbC/phHY4p8oaTKXWJtnYDXUrqSss0cX+rKhbONB0a5JSpvCSGp0WwD+V9BFp8v9wmq6eUX2GrhH+uqfCb/3ds=,iv:hlb/tpGCrGVJaZpHviZpZUMVsvS1xkgU06wgWI7J80s=,tag:wUfPTP46M9SRONyh8WUhPw==,type:str]
  version: 3.13.3
