cluster:
  # allowSchedulingOnControlPlanes: false
  network:
    cni:
      name: none
machine:
  install:
    disk: /dev/mmcblk0
    extraKernelArgs:
      - cma=256M
  sysctls:
    # 64MiB
    vm.min_free_kbytes: 65536
    vm.swappiness: 200
    vm.watermark_scale_factor: 100
  kubelet:
    nodeIP:
      validSubnets:
        - 10.42.0.0/16
        # enc!
        - ENC[AES256_GCM,data:L56SjTEewetno54+T/OUNOuRTJyHnNs=,iv:liFbW0xO0VybiBcpKDZj6IsBofUupuUxkPL6M4+JlgY=,tag:mCfFwmHKeo4h5E3a3XAtcA==,type:str]
    extraMounts:
      - destination: /var/lib/longhorn
        type: bind
        source: /var/lib/longhorn
        options:
          - bind
          - rshared
          - rw
    extraConfig:
      mergeDefaultEvictionSettings: true
      evictionSoft:
        memory.available: 128Mi
      evictionSoftGracePeriod:
        memory.available: 30s
      evictionHard:
        memory.available: 64Mi
  nodeLabels:
    topology.kubernetes.io/region: ng
    topology.kubernetes.io/zone: ng-east-1
    loads.kaos.nexus/postgres: "false"
  network:
    hostname: sophons-prime
    interfaces:
      - interface: end0
        dhcp: false
        vlans:
          - vlanId: 42
            dhcp: false
            addresses:
              - 10.42.42.2/16
              # enc!
              - ENC[AES256_GCM,data:nE5vh1UisC5bco8jfhwIrwc00Tgtzc3n1ByS,iv:DdtOp+xkP75whweZJR1ZLP/CvZZRpiNuN9E3a9ysP3A=,tag:LpJ5z9vkNSmE5x0HuXTK0A==,type:str]
            routes:
              - network: 0.0.0.0/0
                gateway: 10.42.0.1
              - network: ::/0
                gateway: fe80::9c05:d6ff:fe69:64b7
                metric: 200
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyA3d1lM
        cm1KN0pNWGZ3bW1VTFdvR25kOFJYQy8rTDZoU0Q3WFNXZXZ2WlU4CkhIUk13d0dn
        NmxaYWRNQVJ4ZG5HV0UwWjAzRFpDR1FaNjg3LzFpZklVZW8KLS0tIG1nWmo0VXJD
        clhsaDlkRm1SVUQrN0V4Qk50eUVlWVlpUjlBWjZNQkxwVlEKSy08PDxt7dcO/Rdf
        jICzf2A6TRbcpFSUxK13mUIWJbeuNqO7IWkmaFlSv3IH66Xm8uUnbVu8yeC+aZ4S
        HAtTRA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXVWxSelcveGZGM0MwTVN2
        UVIraG9EV2Y3UWNEUmVJa1hnYkw2NWU5RXdNCmFRa2pyZEhmOGVsU2RRR3VCV1Fq
        S3pGTER3SCt5R1M5bUhweTVUVDFmZTgKLS0tIDYvTlB5U09aNXVuU0VkdGhlWmFt
        NFMrYWtxcHI2TFVWMkVIcmxJMVZEOWcK1mnOQbv9g+LFpWkehNOMB59F3V7Q5fbQ
        PlJawXcQuOhhnRJM42E8dCGGBpijiSgn4SWr7TNNU9xZS6SPqhnLew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-12T16:21:46Z"
  mac: ENC[AES256_GCM,data:FeYEEWjc2SnuOTu+EfWAPT3vZLz1LImzg/3Bke52/t/n6aB29/w5HoiD800pxyn5q9pz0QyIn8WiIi+/OTtpQVHRF4+lgh+nF+gHnN3Sn+4/UOY4UefJcWLk394DKtJ0JBvSPMuSRxBg7PXqx8D3SK0ja1DiYDdUEMORo6vuBfM=,iv:PU8bkZJ+LFUYlX5KJBpgL45VCvHlupDNCNZODPWxvTc=,tag:aD3LgyVZ8rMv5FoJgzqCUQ==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  maxSize: 100GiB
  grow: false
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyA3d1lM
        cm1KN0pNWGZ3bW1VTFdvR25kOFJYQy8rTDZoU0Q3WFNXZXZ2WlU4CkhIUk13d0dn
        NmxaYWRNQVJ4ZG5HV0UwWjAzRFpDR1FaNjg3LzFpZklVZW8KLS0tIG1nWmo0VXJD
        clhsaDlkRm1SVUQrN0V4Qk50eUVlWVlpUjlBWjZNQkxwVlEKSy08PDxt7dcO/Rdf
        jICzf2A6TRbcpFSUxK13mUIWJbeuNqO7IWkmaFlSv3IH66Xm8uUnbVu8yeC+aZ4S
        HAtTRA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXVWxSelcveGZGM0MwTVN2
        UVIraG9EV2Y3UWNEUmVJa1hnYkw2NWU5RXdNCmFRa2pyZEhmOGVsU2RRR3VCV1Fq
        S3pGTER3SCt5R1M5bUhweTVUVDFmZTgKLS0tIDYvTlB5U09aNXVuU0VkdGhlWmFt
        NFMrYWtxcHI2TFVWMkVIcmxJMVZEOWcK1mnOQbv9g+LFpWkehNOMB59F3V7Q5fbQ
        PlJawXcQuOhhnRJM42E8dCGGBpijiSgn4SWr7TNNU9xZS6SPqhnLew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-12T16:21:46Z"
  mac: ENC[AES256_GCM,data:FeYEEWjc2SnuOTu+EfWAPT3vZLz1LImzg/3Bke52/t/n6aB29/w5HoiD800pxyn5q9pz0QyIn8WiIi+/OTtpQVHRF4+lgh+nF+gHnN3Sn+4/UOY4UefJcWLk394DKtJ0JBvSPMuSRxBg7PXqx8D3SK0ja1DiYDdUEMORo6vuBfM=,iv:PU8bkZJ+LFUYlX5KJBpgL45VCvHlupDNCNZODPWxvTc=,tag:aD3LgyVZ8rMv5FoJgzqCUQ==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: SwapVolumeConfig
name: swap-1GiB
provisioning:
  diskSelector:
    match: system_disk
  minSize: 1GiB
  maxSize: 1GiB
  grow: false
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyA3d1lM
        cm1KN0pNWGZ3bW1VTFdvR25kOFJYQy8rTDZoU0Q3WFNXZXZ2WlU4CkhIUk13d0dn
        NmxaYWRNQVJ4ZG5HV0UwWjAzRFpDR1FaNjg3LzFpZklVZW8KLS0tIG1nWmo0VXJD
        clhsaDlkRm1SVUQrN0V4Qk50eUVlWVlpUjlBWjZNQkxwVlEKSy08PDxt7dcO/Rdf
        jICzf2A6TRbcpFSUxK13mUIWJbeuNqO7IWkmaFlSv3IH66Xm8uUnbVu8yeC+aZ4S
        HAtTRA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXVWxSelcveGZGM0MwTVN2
        UVIraG9EV2Y3UWNEUmVJa1hnYkw2NWU5RXdNCmFRa2pyZEhmOGVsU2RRR3VCV1Fq
        S3pGTER3SCt5R1M5bUhweTVUVDFmZTgKLS0tIDYvTlB5U09aNXVuU0VkdGhlWmFt
        NFMrYWtxcHI2TFVWMkVIcmxJMVZEOWcK1mnOQbv9g+LFpWkehNOMB59F3V7Q5fbQ
        PlJawXcQuOhhnRJM42E8dCGGBpijiSgn4SWr7TNNU9xZS6SPqhnLew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-12T16:21:46Z"
  mac: ENC[AES256_GCM,data:FeYEEWjc2SnuOTu+EfWAPT3vZLz1LImzg/3Bke52/t/n6aB29/w5HoiD800pxyn5q9pz0QyIn8WiIi+/OTtpQVHRF4+lgh+nF+gHnN3Sn+4/UOY4UefJcWLk394DKtJ0JBvSPMuSRxBg7PXqx8D3SK0ja1DiYDdUEMORo6vuBfM=,iv:PU8bkZJ+LFUYlX5KJBpgL45VCvHlupDNCNZODPWxvTc=,tag:aD3LgyVZ8rMv5FoJgzqCUQ==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: ZswapConfig
# The maximum percent of memory that zswap can use.
maxPoolPercent: 69
# Enable the shrinker feature: kernel might move
shrinkerEnabled: false
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyA3d1lM
        cm1KN0pNWGZ3bW1VTFdvR25kOFJYQy8rTDZoU0Q3WFNXZXZ2WlU4CkhIUk13d0dn
        NmxaYWRNQVJ4ZG5HV0UwWjAzRFpDR1FaNjg3LzFpZklVZW8KLS0tIG1nWmo0VXJD
        clhsaDlkRm1SVUQrN0V4Qk50eUVlWVlpUjlBWjZNQkxwVlEKSy08PDxt7dcO/Rdf
        jICzf2A6TRbcpFSUxK13mUIWJbeuNqO7IWkmaFlSv3IH66Xm8uUnbVu8yeC+aZ4S
        HAtTRA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXVWxSelcveGZGM0MwTVN2
        UVIraG9EV2Y3UWNEUmVJa1hnYkw2NWU5RXdNCmFRa2pyZEhmOGVsU2RRR3VCV1Fq
        S3pGTER3SCt5R1M5bUhweTVUVDFmZTgKLS0tIDYvTlB5U09aNXVuU0VkdGhlWmFt
        NFMrYWtxcHI2TFVWMkVIcmxJMVZEOWcK1mnOQbv9g+LFpWkehNOMB59F3V7Q5fbQ
        PlJawXcQuOhhnRJM42E8dCGGBpijiSgn4SWr7TNNU9xZS6SPqhnLew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-12T16:21:46Z"
  mac: ENC[AES256_GCM,data:FeYEEWjc2SnuOTu+EfWAPT3vZLz1LImzg/3Bke52/t/n6aB29/w5HoiD800pxyn5q9pz0QyIn8WiIi+/OTtpQVHRF4+lgh+nF+gHnN3Sn+4/UOY4UefJcWLk394DKtJ0JBvSPMuSRxBg7PXqx8D3SK0ja1DiYDdUEMORo6vuBfM=,iv:PU8bkZJ+LFUYlX5KJBpgL45VCvHlupDNCNZODPWxvTc=,tag:aD3LgyVZ8rMv5FoJgzqCUQ==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
