apiVersion: v1alpha1
kind: HostnameConfig
auto: "off"
hostname: sophons-prime
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBqWmhT
        dmc0eFFvYzJROGFXT3BCZ3diMHN3eXFCZ1FOVUVESjdmTVUyaHpNClppQXR2aU8r
        RWorZkIrYjZ0TGtTSHJvWkIrTklCblFYVEdEdk1yRktJRTAKLS0tIDBRRVVvbFhK
        eXROajl5dHI3dlBFa0dTcExyZHU5UGRveEV1VEE3VDNPa28KbwAFIueNSVdkH+Pr
        qxWwPUa6Nj9tVY3B4H4pshBmgNKnCHKV6H2fH9ztCsl2iJafQgt3DKSOR0gUsxnR
        R61NDA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzd01SVVFvVFd0TmY2Rys1
        aGJXM3BmS3Z5enRQOFk2NGJNTjZCRFVRc2prCnJlT0k5bUhYaENSTExoV1pnSXZ4
        YWpCeUNSNGhaTUN6YlljaS9aUVkva3MKLS0tIDlDbTB4UTByaUR3c0hRZ3hxa2FS
        bXkzZnlCRDlGY2NEUTl3Mk1Gczg1ejAKvmq91oXMjsXmZbjsfNNcqgawOyiDsHM2
        dbhDVPph82eTHkhx+x6iTmZWZ9KxoESj40wEhYzyddICmOdozVDzlg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-31T18:34:51Z"
  mac: ENC[AES256_GCM,data:Zd597ywrwB9o3jAiq1LeDEbSQJmNiOsOLW8If6DOUmF7mlsMQDtv1DHc+/gALKNWNM4IE36CcObOuqe+bZIXK3KNB+M3PZdICGjUGICLJGQZa8trZWPCNZq1VlgN/KKepqJ+5qohAalB8easA1A2gTMVs4yhrTbqr5IObwvcFiQ=,iv:mNSl8Y0hN2rVIWVMOIR+csrqJS6cMe41UFYCDM9MkCU=,tag:NdIB+9q/tjc6kR5yGA3nkw==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
cluster:
  network:
    cni:
      name: none
machine:
  install:
    disk: /dev/mmcblk0
  kernel:
    modules:
      - name: snd-usb-audio
  sysctls:
    # 64MiB
    vm.min_free_kbytes: 65536
    vm.swappiness: 200
    vm.watermark_scale_factor: 250
  kubelet:
    extraMounts:
      - destination: /var/lib/longhorn
        type: bind
        source: /var/lib/longhorn
        options:
          - bind
          - rshared
          - rw
    extraConfig:
      mergeDefaultEvictionSettings: true
      evictionSoft:
        memory.available: 150Mi
      evictionSoftGracePeriod:
        memory.available: 30s
      evictionHard:
        memory.available: 100Mi
  nodeLabels:
    topology.kubernetes.io/region: ng
    topology.kubernetes.io/zone: ng-east-2
    hugeloads.sophons.cloud/postgres: "false"
  network:
    interfaces:
      - interface: end0
        dhcp: false
        vlans:
          - vlanId: 42
            dhcp: true
            dhcpOptions:
              ipv4: false
              ipv6: true
            addresses:
              - 10.42.42.2/16
            routes:
              - network: 0.0.0.0/0
                gateway: 10.42.0.1
              - network: ::/0
                gateway: fe80::9c05:d6ff:fe69:64b7
                metric: 200
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBqWmhT
        dmc0eFFvYzJROGFXT3BCZ3diMHN3eXFCZ1FOVUVESjdmTVUyaHpNClppQXR2aU8r
        RWorZkIrYjZ0TGtTSHJvWkIrTklCblFYVEdEdk1yRktJRTAKLS0tIDBRRVVvbFhK
        eXROajl5dHI3dlBFa0dTcExyZHU5UGRveEV1VEE3VDNPa28KbwAFIueNSVdkH+Pr
        qxWwPUa6Nj9tVY3B4H4pshBmgNKnCHKV6H2fH9ztCsl2iJafQgt3DKSOR0gUsxnR
        R61NDA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzd01SVVFvVFd0TmY2Rys1
        aGJXM3BmS3Z5enRQOFk2NGJNTjZCRFVRc2prCnJlT0k5bUhYaENSTExoV1pnSXZ4
        YWpCeUNSNGhaTUN6YlljaS9aUVkva3MKLS0tIDlDbTB4UTByaUR3c0hRZ3hxa2FS
        bXkzZnlCRDlGY2NEUTl3Mk1Gczg1ejAKvmq91oXMjsXmZbjsfNNcqgawOyiDsHM2
        dbhDVPph82eTHkhx+x6iTmZWZ9KxoESj40wEhYzyddICmOdozVDzlg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-31T18:34:51Z"
  mac: ENC[AES256_GCM,data:Zd597ywrwB9o3jAiq1LeDEbSQJmNiOsOLW8If6DOUmF7mlsMQDtv1DHc+/gALKNWNM4IE36CcObOuqe+bZIXK3KNB+M3PZdICGjUGICLJGQZa8trZWPCNZq1VlgN/KKepqJ+5qohAalB8easA1A2gTMVs4yhrTbqr5IObwvcFiQ=,iv:mNSl8Y0hN2rVIWVMOIR+csrqJS6cMe41UFYCDM9MkCU=,tag:NdIB+9q/tjc6kR5yGA3nkw==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
# https://tailscale.com/docs/reference/best-practices/performance#linux-optimizations-for-subnet-routers-and-exit-nodes
apiVersion: v1alpha1
kind: EthernetConfig
name: end0
features:
  rx-gro-list: "off"
  rx-udp-gro-forwarding: "on"
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBqWmhT
        dmc0eFFvYzJROGFXT3BCZ3diMHN3eXFCZ1FOVUVESjdmTVUyaHpNClppQXR2aU8r
        RWorZkIrYjZ0TGtTSHJvWkIrTklCblFYVEdEdk1yRktJRTAKLS0tIDBRRVVvbFhK
        eXROajl5dHI3dlBFa0dTcExyZHU5UGRveEV1VEE3VDNPa28KbwAFIueNSVdkH+Pr
        qxWwPUa6Nj9tVY3B4H4pshBmgNKnCHKV6H2fH9ztCsl2iJafQgt3DKSOR0gUsxnR
        R61NDA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzd01SVVFvVFd0TmY2Rys1
        aGJXM3BmS3Z5enRQOFk2NGJNTjZCRFVRc2prCnJlT0k5bUhYaENSTExoV1pnSXZ4
        YWpCeUNSNGhaTUN6YlljaS9aUVkva3MKLS0tIDlDbTB4UTByaUR3c0hRZ3hxa2FS
        bXkzZnlCRDlGY2NEUTl3Mk1Gczg1ejAKvmq91oXMjsXmZbjsfNNcqgawOyiDsHM2
        dbhDVPph82eTHkhx+x6iTmZWZ9KxoESj40wEhYzyddICmOdozVDzlg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-31T18:34:51Z"
  mac: ENC[AES256_GCM,data:Zd597ywrwB9o3jAiq1LeDEbSQJmNiOsOLW8If6DOUmF7mlsMQDtv1DHc+/gALKNWNM4IE36CcObOuqe+bZIXK3KNB+M3PZdICGjUGICLJGQZa8trZWPCNZq1VlgN/KKepqJ+5qohAalB8easA1A2gTMVs4yhrTbqr5IObwvcFiQ=,iv:mNSl8Y0hN2rVIWVMOIR+csrqJS6cMe41UFYCDM9MkCU=,tag:NdIB+9q/tjc6kR5yGA3nkw==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  maxSize: 100GiB
  grow: false
# ---
# apiVersion: v1alpha1
# kind: SwapVolumeConfig
# name: swap-1GiB
# provisioning:
#   diskSelector:
#     match: system_disk
#   minSize: 1GiB
#   maxSize: 1GiB
#   grow: false
# ---
# apiVersion: v1alpha1
# kind: ZswapConfig
# # The maximum percent of memory that zswap can use.
# maxPoolPercent: 69
# # Enable the shrinker feature: kernel might move
# shrinkerEnabled: true
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBqWmhT
        dmc0eFFvYzJROGFXT3BCZ3diMHN3eXFCZ1FOVUVESjdmTVUyaHpNClppQXR2aU8r
        RWorZkIrYjZ0TGtTSHJvWkIrTklCblFYVEdEdk1yRktJRTAKLS0tIDBRRVVvbFhK
        eXROajl5dHI3dlBFa0dTcExyZHU5UGRveEV1VEE3VDNPa28KbwAFIueNSVdkH+Pr
        qxWwPUa6Nj9tVY3B4H4pshBmgNKnCHKV6H2fH9ztCsl2iJafQgt3DKSOR0gUsxnR
        R61NDA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzd01SVVFvVFd0TmY2Rys1
        aGJXM3BmS3Z5enRQOFk2NGJNTjZCRFVRc2prCnJlT0k5bUhYaENSTExoV1pnSXZ4
        YWpCeUNSNGhaTUN6YlljaS9aUVkva3MKLS0tIDlDbTB4UTByaUR3c0hRZ3hxa2FS
        bXkzZnlCRDlGY2NEUTl3Mk1Gczg1ejAKvmq91oXMjsXmZbjsfNNcqgawOyiDsHM2
        dbhDVPph82eTHkhx+x6iTmZWZ9KxoESj40wEhYzyddICmOdozVDzlg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-31T18:34:51Z"
  mac: ENC[AES256_GCM,data:Zd597ywrwB9o3jAiq1LeDEbSQJmNiOsOLW8If6DOUmF7mlsMQDtv1DHc+/gALKNWNM4IE36CcObOuqe+bZIXK3KNB+M3PZdICGjUGICLJGQZa8trZWPCNZq1VlgN/KKepqJ+5qohAalB8easA1A2gTMVs4yhrTbqr5IObwvcFiQ=,iv:mNSl8Y0hN2rVIWVMOIR+csrqJS6cMe41UFYCDM9MkCU=,tag:NdIB+9q/tjc6kR5yGA3nkw==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: WireguardConfig
name: wg.kluster
# publicKey: 2jXr8tfBYrc3tBSvDweM2mJGAsPp6Sd/T2wCBss2fGU=
# enc!
privateKey: ENC[AES256_GCM,data:dljMJchEQrR525R0bbaQHVfFtXKmaafPTGmsVC2c/CfFSCBQc7ZV3v9qL+k=,iv:3hTtySzNoYPuudDhJtH7fnZ6qSVvfDhcTRGfMHcMry0=,tag:oOARgPPm+wWk3NHfO5NQJg==,type:str]
listenPort: 51869
peers:
  # voltzahl
  - publicKey: hVSo5per13c8V9b5wUTAOGp0/W32rkKfSVZSctlqujU=
    allowedIPs:
      - 10.41.6.0/24
      - 2001:cafe:41:6::/64
      - 10.67.0.100/32
      - fdf6:9420:fade:67::5/128
      - fdf6:9420:fade:67::100/128
    # enc!
    endpoint: ENC[AES256_GCM,data:aiRBAg7IoZpqG8GboORBcEc2uoMFLK5d5KC7,iv:Aj4BuigQVxb3MTViosPnqeYFNfJwu4cCLdV0sNUGkpA=,tag:ZFXqtOEtJl/7tE3JkyGq9g==,type:str]
    # enc!
    #ENC[AES256_GCM,data:62o/W+0ySOn6O2LOxstbeQuxNyc0hoSDO7Zj/VM+,iv:Twb9ucKfXjAo/hUj67WpoMlilwOo2YIzr7mP9LU3AR0=,tag:asKyRHeAHVHFw5tOseEnBg==,type:comment]
    persistentKeepaliveInterval: ENC[AES256_GCM,data:JkY=,iv:zHlP5nhzRodh84lxwO4L9e8XHJeI8BlnrNPznyhc6ZY=,tag:bKkC8z4S241x/hdI90OJ+w==,type:str]
  # theta
  - publicKey: bg+Z4libGo+HGAC9UrWbooWkOI4+eZ5OAqw+8rPn9AA=
    allowedIPs:
      - 10.41.2.0/24
      - 2001:cafe:41:2::/64
      - 10.67.0.101/32
      - fdf6:9420:fade:67::4/128
      - fdf6:9420:fade:67::101/128
    # enc!
    endpoint: ENC[AES256_GCM,data:HMjM+vNnJ7vV5geyCqEjYDy9jx+O1jY/c3/Cdg==,iv:QRG8/xG+wbIPLMRqbaUpgmZvp7A/Ic/pwUZDdePr+cQ=,tag:scUvopkavzgEIf3X7yTYMw==,type:str]
    # enc!
    #ENC[AES256_GCM,data:TEEAkMqyCNv5cLNTdvzZ/NFXXYJEbnPSnMTADv1IMGw=,iv:rpDEVajh6XAeOiL5f7ZqwIjH6++yD4etvU+6AsT+4yQ=,tag:2wE8UypQPEzgsyPQpNGZdw==,type:comment]
    persistentKeepaliveInterval: ENC[AES256_GCM,data:Dwc=,iv:PsTXz8j/VemXtAcBh3WkDOyhWZ3IO10Q2b+CLJe0ir0=,tag:+UJ6+5Jowk1Y983IEHR8zA==,type:str]
  # beta
  - publicKey: mmTxsL60iWtsBx6+aMkxx2Of7g/exHTU9pXrinc1wlQ=
    allowedIPs:
      - 10.41.1.0/24
      - 2001:cafe:41:1::/64
      - 10.67.0.102/32
      - fdf6:9420:fade:67::2/128
      - fdf6:9420:fade:67::102/128
    endpoint: 10.69.0.3:51869
  # alpha
  - publicKey: C/tFptmbSV+HBQYxzsTKUFW4LsPVcQyCNEfr8esvQ3w=
    allowedIPs:
      - 10.41.3.0/24
      - 2001:cafe:41:3::/64
      - 10.67.0.103/32
      - fdf6:9420:fade:67::103/128
    endpoint: 10.69.0.4:51869
  # oduduwa
  - publicKey: gobYpIEfo5paRPdkJ+Jnqcm9TyD+J2I4+Ry5AU0UhAQ=
    allowedIPs:
      - 10.41.4.0/24
      - 2001:cafe:41:4::/64
      - 10.67.0.104/32
      - fdf6:9420:fade:67::104/128
    # enc!
    endpoint: ENC[AES256_GCM,data:ir0gAKq6lt2TYcGtZsm2KL397rw=,iv:YA3qGBDLdWQILEjJCPyum2DEsq+XsggxWKTb7uh5csI=,tag:adziWHhQFZO5fWnB493TFg==,type:str]
    persistentKeepaliveInterval: 5s
  # caeneus
  - publicKey: l43bJSBEBDAc9vn+v9z2Zt/vsJRimWwyOwvHfHJrWkQ=
    allowedIPs:
      - 10.41.5.0/24
      - 2001:cafe:41:5::/64
      - 10.67.0.105/32
      - fdf6:9420:fade:67::105/128
    endpoint: 10.42.42.5:51869
    persistentKeepaliveInterval: 5s
up: true
addresses:
  - address: 10.67.0.106/32
  - address: fdf6:9420:fade:67::106/128
routes:
  # voltzahl
  - destination: 10.41.6.0/24
  - destination: 2001:cafe:41:6::/64
  - destination: 10.67.0.100/32
  - destination: fdf6:9420:fade:67::5/128
  - destination: fdf6:9420:fade:67::100/128
  # theta
  - destination: 10.41.2.0/24
  - destination: 2001:cafe:41:2::/64
  - destination: 10.67.0.101/32
  - destination: fdf6:9420:fade:67::4/128
  - destination: fdf6:9420:fade:67::101/128
  # beta
  - destination: 10.41.1.0/24
  - destination: 2001:cafe:41:1::/64
  - destination: 10.67.0.102/32
  - destination: fdf6:9420:fade:67::2/128
  - destination: fdf6:9420:fade:67::102/128
  # alpha
  - destination: 10.41.3.0/24
  - destination: 2001:cafe:41:3::/64
  - destination: 10.67.0.103/32
  - destination: fdf6:9420:fade:67::103/128
  # oduduwa
  - destination: 10.41.4.0/24
  - destination: 2001:cafe:41:4::/64
  - destination: 10.67.0.104/32
  - destination: fdf6:9420:fade:67::104/128
  # caeneus
  - destination: 10.41.5.0/24
  - destination: 2001:cafe:41:5::/64
  - destination: 10.67.0.105/32
  - destination: fdf6:9420:fade:67::105/128
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBqWmhT
        dmc0eFFvYzJROGFXT3BCZ3diMHN3eXFCZ1FOVUVESjdmTVUyaHpNClppQXR2aU8r
        RWorZkIrYjZ0TGtTSHJvWkIrTklCblFYVEdEdk1yRktJRTAKLS0tIDBRRVVvbFhK
        eXROajl5dHI3dlBFa0dTcExyZHU5UGRveEV1VEE3VDNPa28KbwAFIueNSVdkH+Pr
        qxWwPUa6Nj9tVY3B4H4pshBmgNKnCHKV6H2fH9ztCsl2iJafQgt3DKSOR0gUsxnR
        R61NDA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzd01SVVFvVFd0TmY2Rys1
        aGJXM3BmS3Z5enRQOFk2NGJNTjZCRFVRc2prCnJlT0k5bUhYaENSTExoV1pnSXZ4
        YWpCeUNSNGhaTUN6YlljaS9aUVkva3MKLS0tIDlDbTB4UTByaUR3c0hRZ3hxa2FS
        bXkzZnlCRDlGY2NEUTl3Mk1Gczg1ejAKvmq91oXMjsXmZbjsfNNcqgawOyiDsHM2
        dbhDVPph82eTHkhx+x6iTmZWZ9KxoESj40wEhYzyddICmOdozVDzlg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-31T18:34:51Z"
  mac: ENC[AES256_GCM,data:Zd597ywrwB9o3jAiq1LeDEbSQJmNiOsOLW8If6DOUmF7mlsMQDtv1DHc+/gALKNWNM4IE36CcObOuqe+bZIXK3KNB+M3PZdICGjUGICLJGQZa8trZWPCNZq1VlgN/KKepqJ+5qohAalB8easA1A2gTMVs4yhrTbqr5IObwvcFiQ=,iv:mNSl8Y0hN2rVIWVMOIR+csrqJS6cMe41UFYCDM9MkCU=,tag:NdIB+9q/tjc6kR5yGA3nkw==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
