cluster:
  network:
    cni:
      name: none
machine:
  install:
    disk: /dev/mmcblk0
    extraKernelArgs:
      - cma=256M
  sysctls:
    # 64MiB
    vm.min_free_kbytes: 65536
    vm.swappiness: 200
    vm.watermark_scale_factor: 250
  kubelet:
    extraMounts:
      - destination: /var/lib/longhorn
        type: bind
        source: /var/lib/longhorn
        options:
          - bind
          - rshared
          - rw
    extraConfig:
      mergeDefaultEvictionSettings: true
      evictionSoft:
        memory.available: 150Mi
      evictionSoftGracePeriod:
        memory.available: 30s
      evictionHard:
        memory.available: 100Mi
  nodeLabels:
    topology.kubernetes.io/region: ng
    topology.kubernetes.io/zone: ng-east-2
    hugeloads.sophons.cloud/postgres: "false"
  network:
    hostname: sophons-prime
    interfaces:
      - interface: end0
        dhcp: false
        vlans:
          - vlanId: 42
            dhcp: false
            addresses:
              - 10.42.42.2/16
              # enc!
              - ENC[AES256_GCM,data:KLdeCwvjLooLWcHBB1706v6gPvSPUS+hY8X2,iv:DNQwMfKj1x72ZkGh5ss40MhIy5a/0efwHKicGnapwJg=,tag:kVJDF/c6HOMpBTxJQAJMlw==,type:str]
            routes:
              - network: 0.0.0.0/0
                gateway: 10.42.0.1
              - network: ::/0
                gateway: fe80::9c05:d6ff:fe69:64b7
                metric: 200
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBQVm8v
        VjBGQXdLdEpsRC9KWTh1SGhGdnBkdlQwbVdMajlGRXY3YXRqZFRFCnpNalVGdUN2
        NjFnejJ3Q3hFUGN1Sm5OTmw5R28wUzVkVldjNXpkVlc4UUEKLS0tIE1RelVzN0Ny
        Vlgra2VlRlI5alFvTjQyYUUvTXBXRWIrNEtiYithSkgrK3cKaOQvX7Td7821+a+U
        vF7aYnPDDzvR+0HTxa+D4XfGQCVsJfHa0FolnW4iOWPAt3JQ+lxvlO/tjLXu0azb
        BUTSsw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlMEh3bU8yRHdwb25jK2la
        UkRvcGJvZlloNGtyRm1WR0M4aWsrVGRSMHpjCmpjYU5tRzNJRnZQTmZxcjU5S1lO
        ZWRuR1NkSzFXN3hpQUZGMW9QWXNjbXcKLS0tIC84d1NaOVM3azBoanA1bVlmUDhN
        U01XcWF5aTVqeWdHYVVkWEVNN0J5V2sKNS14rxW4NKc7VGUL+UJa0gDZPPiNY2A+
        rarhf32QO7mND7f4e+yCu8+pBK0PXmTcWvcszOM7tSkWKZ8lRT/ntw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-23T20:23:31Z"
  mac: ENC[AES256_GCM,data:3lKhSAR5c1x+/INUkSdbXZsBx5tf9iUieJx4k4gW3VUpduhU22a7YfrudRRD2iDN1TmSOLwHdkCN4i0jU9FkeMLdhW8xwXDhnEtCDoGGMjMSl2dJgVliryAlp4h/kGPSXUmgebbyFHIQWj4sflFBVWZWNY6TeFs7m8MgkxwKcQo=,iv:9BegzVLVp6qcKo1FvKMrJoIceHmg/vVue80KcVe0QG4=,tag:i/v3isxSt0mNB+oCsvRzrg==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  maxSize: 100GiB
  grow: false
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBQVm8v
        VjBGQXdLdEpsRC9KWTh1SGhGdnBkdlQwbVdMajlGRXY3YXRqZFRFCnpNalVGdUN2
        NjFnejJ3Q3hFUGN1Sm5OTmw5R28wUzVkVldjNXpkVlc4UUEKLS0tIE1RelVzN0Ny
        Vlgra2VlRlI5alFvTjQyYUUvTXBXRWIrNEtiYithSkgrK3cKaOQvX7Td7821+a+U
        vF7aYnPDDzvR+0HTxa+D4XfGQCVsJfHa0FolnW4iOWPAt3JQ+lxvlO/tjLXu0azb
        BUTSsw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlMEh3bU8yRHdwb25jK2la
        UkRvcGJvZlloNGtyRm1WR0M4aWsrVGRSMHpjCmpjYU5tRzNJRnZQTmZxcjU5S1lO
        ZWRuR1NkSzFXN3hpQUZGMW9QWXNjbXcKLS0tIC84d1NaOVM3azBoanA1bVlmUDhN
        U01XcWF5aTVqeWdHYVVkWEVNN0J5V2sKNS14rxW4NKc7VGUL+UJa0gDZPPiNY2A+
        rarhf32QO7mND7f4e+yCu8+pBK0PXmTcWvcszOM7tSkWKZ8lRT/ntw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-23T20:23:31Z"
  mac: ENC[AES256_GCM,data:3lKhSAR5c1x+/INUkSdbXZsBx5tf9iUieJx4k4gW3VUpduhU22a7YfrudRRD2iDN1TmSOLwHdkCN4i0jU9FkeMLdhW8xwXDhnEtCDoGGMjMSl2dJgVliryAlp4h/kGPSXUmgebbyFHIQWj4sflFBVWZWNY6TeFs7m8MgkxwKcQo=,iv:9BegzVLVp6qcKo1FvKMrJoIceHmg/vVue80KcVe0QG4=,tag:i/v3isxSt0mNB+oCsvRzrg==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: SwapVolumeConfig
name: swap-1GiB
provisioning:
  diskSelector:
    match: system_disk
  minSize: 1GiB
  maxSize: 1GiB
  grow: false
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBQVm8v
        VjBGQXdLdEpsRC9KWTh1SGhGdnBkdlQwbVdMajlGRXY3YXRqZFRFCnpNalVGdUN2
        NjFnejJ3Q3hFUGN1Sm5OTmw5R28wUzVkVldjNXpkVlc4UUEKLS0tIE1RelVzN0Ny
        Vlgra2VlRlI5alFvTjQyYUUvTXBXRWIrNEtiYithSkgrK3cKaOQvX7Td7821+a+U
        vF7aYnPDDzvR+0HTxa+D4XfGQCVsJfHa0FolnW4iOWPAt3JQ+lxvlO/tjLXu0azb
        BUTSsw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlMEh3bU8yRHdwb25jK2la
        UkRvcGJvZlloNGtyRm1WR0M4aWsrVGRSMHpjCmpjYU5tRzNJRnZQTmZxcjU5S1lO
        ZWRuR1NkSzFXN3hpQUZGMW9QWXNjbXcKLS0tIC84d1NaOVM3azBoanA1bVlmUDhN
        U01XcWF5aTVqeWdHYVVkWEVNN0J5V2sKNS14rxW4NKc7VGUL+UJa0gDZPPiNY2A+
        rarhf32QO7mND7f4e+yCu8+pBK0PXmTcWvcszOM7tSkWKZ8lRT/ntw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-23T20:23:31Z"
  mac: ENC[AES256_GCM,data:3lKhSAR5c1x+/INUkSdbXZsBx5tf9iUieJx4k4gW3VUpduhU22a7YfrudRRD2iDN1TmSOLwHdkCN4i0jU9FkeMLdhW8xwXDhnEtCDoGGMjMSl2dJgVliryAlp4h/kGPSXUmgebbyFHIQWj4sflFBVWZWNY6TeFs7m8MgkxwKcQo=,iv:9BegzVLVp6qcKo1FvKMrJoIceHmg/vVue80KcVe0QG4=,tag:i/v3isxSt0mNB+oCsvRzrg==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: ZswapConfig
# The maximum percent of memory that zswap can use.
maxPoolPercent: 69
# Enable the shrinker feature: kernel might move
shrinkerEnabled: true
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBQVm8v
        VjBGQXdLdEpsRC9KWTh1SGhGdnBkdlQwbVdMajlGRXY3YXRqZFRFCnpNalVGdUN2
        NjFnejJ3Q3hFUGN1Sm5OTmw5R28wUzVkVldjNXpkVlc4UUEKLS0tIE1RelVzN0Ny
        Vlgra2VlRlI5alFvTjQyYUUvTXBXRWIrNEtiYithSkgrK3cKaOQvX7Td7821+a+U
        vF7aYnPDDzvR+0HTxa+D4XfGQCVsJfHa0FolnW4iOWPAt3JQ+lxvlO/tjLXu0azb
        BUTSsw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlMEh3bU8yRHdwb25jK2la
        UkRvcGJvZlloNGtyRm1WR0M4aWsrVGRSMHpjCmpjYU5tRzNJRnZQTmZxcjU5S1lO
        ZWRuR1NkSzFXN3hpQUZGMW9QWXNjbXcKLS0tIC84d1NaOVM3azBoanA1bVlmUDhN
        U01XcWF5aTVqeWdHYVVkWEVNN0J5V2sKNS14rxW4NKc7VGUL+UJa0gDZPPiNY2A+
        rarhf32QO7mND7f4e+yCu8+pBK0PXmTcWvcszOM7tSkWKZ8lRT/ntw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-23T20:23:31Z"
  mac: ENC[AES256_GCM,data:3lKhSAR5c1x+/INUkSdbXZsBx5tf9iUieJx4k4gW3VUpduhU22a7YfrudRRD2iDN1TmSOLwHdkCN4i0jU9FkeMLdhW8xwXDhnEtCDoGGMjMSl2dJgVliryAlp4h/kGPSXUmgebbyFHIQWj4sflFBVWZWNY6TeFs7m8MgkxwKcQo=,iv:9BegzVLVp6qcKo1FvKMrJoIceHmg/vVue80KcVe0QG4=,tag:i/v3isxSt0mNB+oCsvRzrg==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: ExtensionServiceConfig
name: tailscale
environment:
  - TS_ROUTES=10.41.0.0/24,2001:cafe:41::/64
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBQVm8v
        VjBGQXdLdEpsRC9KWTh1SGhGdnBkdlQwbVdMajlGRXY3YXRqZFRFCnpNalVGdUN2
        NjFnejJ3Q3hFUGN1Sm5OTmw5R28wUzVkVldjNXpkVlc4UUEKLS0tIE1RelVzN0Ny
        Vlgra2VlRlI5alFvTjQyYUUvTXBXRWIrNEtiYithSkgrK3cKaOQvX7Td7821+a+U
        vF7aYnPDDzvR+0HTxa+D4XfGQCVsJfHa0FolnW4iOWPAt3JQ+lxvlO/tjLXu0azb
        BUTSsw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlMEh3bU8yRHdwb25jK2la
        UkRvcGJvZlloNGtyRm1WR0M4aWsrVGRSMHpjCmpjYU5tRzNJRnZQTmZxcjU5S1lO
        ZWRuR1NkSzFXN3hpQUZGMW9QWXNjbXcKLS0tIC84d1NaOVM3azBoanA1bVlmUDhN
        U01XcWF5aTVqeWdHYVVkWEVNN0J5V2sKNS14rxW4NKc7VGUL+UJa0gDZPPiNY2A+
        rarhf32QO7mND7f4e+yCu8+pBK0PXmTcWvcszOM7tSkWKZ8lRT/ntw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-23T20:23:31Z"
  mac: ENC[AES256_GCM,data:3lKhSAR5c1x+/INUkSdbXZsBx5tf9iUieJx4k4gW3VUpduhU22a7YfrudRRD2iDN1TmSOLwHdkCN4i0jU9FkeMLdhW8xwXDhnEtCDoGGMjMSl2dJgVliryAlp4h/kGPSXUmgebbyFHIQWj4sflFBVWZWNY6TeFs7m8MgkxwKcQo=,iv:9BegzVLVp6qcKo1FvKMrJoIceHmg/vVue80KcVe0QG4=,tag:i/v3isxSt0mNB+oCsvRzrg==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
