apiVersion: v1alpha1
kind: HostnameConfig
auto: "off"
hostname: sophons-prime
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBkaith
        ekJwNTFndlV1b0ltaDVmUkVVZ3NBUTVJa3g1OUdhWU1LSlRLLzFnClYxMUNHeW5V
        UVNrbDhTYkx6VThLejVHUmZzeUE0WHl1b3NpVmFFUElvKzQKLS0tIFgyWlVTa29C
        aE9UV0ZVUVVZTEZtVHBiUEI3bitLVXdHUU90dHpaekdrbzgKKgfr6ytBvfyZLOQg
        ao86ypV3uoV9sQGsZ+yAG6gEVJBtGSHiNGNrAKfWd5FNPT6T+Hp1FcPEWCAWuCXl
        GQc7Sg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzOTJQMCtLS3FZYkhNdE1z
        WTFQS1dIK1lQaUh1L0s4bjZQRE9IM2hHT1ZBClN1UXEyMEdzWG1EbUhOTkhsUEx6
        d0RnbmFhM1luWTlzckJIN05raTFTbWMKLS0tIFgzVXU2MzZZSUNtempHcXd4Ymwx
        U29hcjZYb2Z5ZW5ubTZMQ1pKbU1qZ1kKnPVdkofPd5ZcG64p+QTCyLi1CHMJ4sT+
        uFZTJxzAhLHXguWMsatJ7CnD6n9OfeeppH9wUwo8Q5dg4tEAd4e5Lw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-10T13:17:53Z"
  mac: ENC[AES256_GCM,data:kenWzwoXt/jU+B6zvfaNfPzkvfjrDZ22WRUYMMGDRk7vfAOSVGdaUb2L4CSM/JS96Sa/ghoglbFWoOoidT4ocanUletIJa1WffHgVECbayhc1halgnmB7Mu4h9ta3AVbMlnpoGxntK2wL8Q43A7wVIsy2HKYblKLGKxbUnj3xpQ=,iv:9aXmAEHGgK7/vANfftXqbCtdtGKRtQLPFBHQw2hQ7hE=,tag:5WdP+Ey8//DGljR/QKuRcg==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
cluster:
  network:
    cni:
      name: none
machine:
  install:
    disk: /dev/mmcblk0
  kernel:
    modules:
      - name: snd-usb-audio
  sysctls:
    # 64MiB
    vm.min_free_kbytes: 65536
    vm.swappiness: 200
    vm.watermark_scale_factor: 250
  kubelet:
    extraMounts:
      - destination: /var/lib/longhorn
        type: bind
        source: /var/lib/longhorn
        options:
          - bind
          - rshared
          - rw
    extraConfig:
      mergeDefaultEvictionSettings: true
      evictionSoft:
        memory.available: 150Mi
      evictionSoftGracePeriod:
        memory.available: 30s
      evictionHard:
        memory.available: 100Mi
  nodeLabels:
    topology.kubernetes.io/region: ng
    topology.kubernetes.io/zone: ng-east-2
    hugeloads.sophons.cloud/postgres: "false"
  network:
    interfaces:
      - interface: end0
        dhcp: false
        vlans:
          - vlanId: 42
            dhcp: true
            dhcpOptions:
              ipv4: false
              ipv6: true
            addresses:
              - 10.42.42.2/16
            routes:
              - network: 0.0.0.0/0
                gateway: 10.42.0.1
              - network: ::/0
                gateway: fe80::9c05:d6ff:fe69:64b7
                metric: 200
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBkaith
        ekJwNTFndlV1b0ltaDVmUkVVZ3NBUTVJa3g1OUdhWU1LSlRLLzFnClYxMUNHeW5V
        UVNrbDhTYkx6VThLejVHUmZzeUE0WHl1b3NpVmFFUElvKzQKLS0tIFgyWlVTa29C
        aE9UV0ZVUVVZTEZtVHBiUEI3bitLVXdHUU90dHpaekdrbzgKKgfr6ytBvfyZLOQg
        ao86ypV3uoV9sQGsZ+yAG6gEVJBtGSHiNGNrAKfWd5FNPT6T+Hp1FcPEWCAWuCXl
        GQc7Sg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzOTJQMCtLS3FZYkhNdE1z
        WTFQS1dIK1lQaUh1L0s4bjZQRE9IM2hHT1ZBClN1UXEyMEdzWG1EbUhOTkhsUEx6
        d0RnbmFhM1luWTlzckJIN05raTFTbWMKLS0tIFgzVXU2MzZZSUNtempHcXd4Ymwx
        U29hcjZYb2Z5ZW5ubTZMQ1pKbU1qZ1kKnPVdkofPd5ZcG64p+QTCyLi1CHMJ4sT+
        uFZTJxzAhLHXguWMsatJ7CnD6n9OfeeppH9wUwo8Q5dg4tEAd4e5Lw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-10T13:17:53Z"
  mac: ENC[AES256_GCM,data:kenWzwoXt/jU+B6zvfaNfPzkvfjrDZ22WRUYMMGDRk7vfAOSVGdaUb2L4CSM/JS96Sa/ghoglbFWoOoidT4ocanUletIJa1WffHgVECbayhc1halgnmB7Mu4h9ta3AVbMlnpoGxntK2wL8Q43A7wVIsy2HKYblKLGKxbUnj3xpQ=,iv:9aXmAEHGgK7/vANfftXqbCtdtGKRtQLPFBHQw2hQ7hE=,tag:5WdP+Ey8//DGljR/QKuRcg==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
# https://tailscale.com/docs/reference/best-practices/performance#linux-optimizations-for-subnet-routers-and-exit-nodes
apiVersion: v1alpha1
kind: EthernetConfig
name: end0
features:
  rx-gro-list: "off"
  rx-udp-gro-forwarding: "on"
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBkaith
        ekJwNTFndlV1b0ltaDVmUkVVZ3NBUTVJa3g1OUdhWU1LSlRLLzFnClYxMUNHeW5V
        UVNrbDhTYkx6VThLejVHUmZzeUE0WHl1b3NpVmFFUElvKzQKLS0tIFgyWlVTa29C
        aE9UV0ZVUVVZTEZtVHBiUEI3bitLVXdHUU90dHpaekdrbzgKKgfr6ytBvfyZLOQg
        ao86ypV3uoV9sQGsZ+yAG6gEVJBtGSHiNGNrAKfWd5FNPT6T+Hp1FcPEWCAWuCXl
        GQc7Sg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzOTJQMCtLS3FZYkhNdE1z
        WTFQS1dIK1lQaUh1L0s4bjZQRE9IM2hHT1ZBClN1UXEyMEdzWG1EbUhOTkhsUEx6
        d0RnbmFhM1luWTlzckJIN05raTFTbWMKLS0tIFgzVXU2MzZZSUNtempHcXd4Ymwx
        U29hcjZYb2Z5ZW5ubTZMQ1pKbU1qZ1kKnPVdkofPd5ZcG64p+QTCyLi1CHMJ4sT+
        uFZTJxzAhLHXguWMsatJ7CnD6n9OfeeppH9wUwo8Q5dg4tEAd4e5Lw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-10T13:17:53Z"
  mac: ENC[AES256_GCM,data:kenWzwoXt/jU+B6zvfaNfPzkvfjrDZ22WRUYMMGDRk7vfAOSVGdaUb2L4CSM/JS96Sa/ghoglbFWoOoidT4ocanUletIJa1WffHgVECbayhc1halgnmB7Mu4h9ta3AVbMlnpoGxntK2wL8Q43A7wVIsy2HKYblKLGKxbUnj3xpQ=,iv:9aXmAEHGgK7/vANfftXqbCtdtGKRtQLPFBHQw2hQ7hE=,tag:5WdP+Ey8//DGljR/QKuRcg==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  maxSize: 100GiB
  grow: false
# ---
# apiVersion: v1alpha1
# kind: SwapVolumeConfig
# name: swap-1GiB
# provisioning:
#   diskSelector:
#     match: system_disk
#   minSize: 1GiB
#   maxSize: 1GiB
#   grow: false
# ---
# apiVersion: v1alpha1
# kind: ZswapConfig
# # The maximum percent of memory that zswap can use.
# maxPoolPercent: 69
# # Enable the shrinker feature: kernel might move
# shrinkerEnabled: true
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBkaith
        ekJwNTFndlV1b0ltaDVmUkVVZ3NBUTVJa3g1OUdhWU1LSlRLLzFnClYxMUNHeW5V
        UVNrbDhTYkx6VThLejVHUmZzeUE0WHl1b3NpVmFFUElvKzQKLS0tIFgyWlVTa29C
        aE9UV0ZVUVVZTEZtVHBiUEI3bitLVXdHUU90dHpaekdrbzgKKgfr6ytBvfyZLOQg
        ao86ypV3uoV9sQGsZ+yAG6gEVJBtGSHiNGNrAKfWd5FNPT6T+Hp1FcPEWCAWuCXl
        GQc7Sg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzOTJQMCtLS3FZYkhNdE1z
        WTFQS1dIK1lQaUh1L0s4bjZQRE9IM2hHT1ZBClN1UXEyMEdzWG1EbUhOTkhsUEx6
        d0RnbmFhM1luWTlzckJIN05raTFTbWMKLS0tIFgzVXU2MzZZSUNtempHcXd4Ymwx
        U29hcjZYb2Z5ZW5ubTZMQ1pKbU1qZ1kKnPVdkofPd5ZcG64p+QTCyLi1CHMJ4sT+
        uFZTJxzAhLHXguWMsatJ7CnD6n9OfeeppH9wUwo8Q5dg4tEAd4e5Lw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-10T13:17:53Z"
  mac: ENC[AES256_GCM,data:kenWzwoXt/jU+B6zvfaNfPzkvfjrDZ22WRUYMMGDRk7vfAOSVGdaUb2L4CSM/JS96Sa/ghoglbFWoOoidT4ocanUletIJa1WffHgVECbayhc1halgnmB7Mu4h9ta3AVbMlnpoGxntK2wL8Q43A7wVIsy2HKYblKLGKxbUnj3xpQ=,iv:9aXmAEHGgK7/vANfftXqbCtdtGKRtQLPFBHQw2hQ7hE=,tag:5WdP+Ey8//DGljR/QKuRcg==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: WireguardConfig
name: wg.kluster
# publicKey: 2jXr8tfBYrc3tBSvDweM2mJGAsPp6Sd/T2wCBss2fGU=
# enc!
privateKey: ENC[AES256_GCM,data:fooBtT/2QoWjF/R/xl/CFszHM31ZpJQDiJrZ/9g2RbviMSjP9oo7nLCMmuQ=,iv:nTKBgBHU+Ya9meVPVJwryv3iyBUQz6pHdIny23yOd1g=,tag:3NNueP1Fh/goF/vxYZaALw==,type:str]
listenPort: 51869
peers:
  # voltzahl
  - publicKey: hVSo5per13c8V9b5wUTAOGp0/W32rkKfSVZSctlqujU=
    allowedIPs:
      - 10.41.6.0/24
      - 2001:cafe:41:6::/64
      - 10.67.0.100/32
      - fdf6:9420:fade:67::5/128
      - fdf6:9420:fade:67::100/128
    # enc!
    endpoint: ENC[AES256_GCM,data:jVux5dtQC9l3VjdA1guvsz8=,iv:fl+bh1tPJXPZ65zr+hrhEvBQeHu1bn4Ql5iz1IslihQ=,tag:fXbq0be0GAhVH7Rvh1kIaw==,type:str]
    persistentKeepaliveInterval: 5s
  # theta
  - publicKey: bg+Z4libGo+HGAC9UrWbooWkOI4+eZ5OAqw+8rPn9AA=
    allowedIPs:
      - 10.41.2.0/24
      - 2001:cafe:41:2::/64
      - 10.67.0.101/32
      - fdf6:9420:fade:67::4/128
      - fdf6:9420:fade:67::101/128
    # enc!
    endpoint: ENC[AES256_GCM,data:5AgdiMblSU6USNJ1TNMkG/t2WA==,iv:9XjDbN0sEuVabGqy39vQb4mZLpeC3hA/WLHpa/FtdeQ=,tag:IEu+v7lfdDcEhsMMtJ3ZMA==,type:str]
    persistentKeepaliveInterval: 5s
  # beta
  - publicKey: mmTxsL60iWtsBx6+aMkxx2Of7g/exHTU9pXrinc1wlQ=
    allowedIPs:
      - 10.41.1.0/24
      - 2001:cafe:41:1::/64
      - 10.67.0.102/32
      - fdf6:9420:fade:67::2/128
      - fdf6:9420:fade:67::102/128
    endpoint: 10.69.0.3:51869
  # alpha
  - publicKey: C/tFptmbSV+HBQYxzsTKUFW4LsPVcQyCNEfr8esvQ3w=
    allowedIPs:
      - 10.41.3.0/24
      - 2001:cafe:41:3::/64
      - 10.67.0.103/32
      - fdf6:9420:fade:67::103/128
    endpoint: 10.69.0.4:51869
  # oduduwa
  - publicKey: gobYpIEfo5paRPdkJ+Jnqcm9TyD+J2I4+Ry5AU0UhAQ=
    allowedIPs:
      - 10.41.4.0/24
      - 2001:cafe:41:4::/64
      - 10.67.0.104/32
      - fdf6:9420:fade:67::104/128
    # enc!
    endpoint: ENC[AES256_GCM,data:4apq7Lmg5XqNniSOjkmKA29dHzg=,iv:NAM9+cAms0Yv5oVnE8vSyj3Gd2MI7Ej8IfqODoRH8ns=,tag:0i622Dky5iuJnsBr0Qu2OQ==,type:str]
    persistentKeepaliveInterval: 5s
  # caeneus
  - publicKey: l43bJSBEBDAc9vn+v9z2Zt/vsJRimWwyOwvHfHJrWkQ=
    allowedIPs:
      - 10.41.5.0/24
      - 2001:cafe:41:5::/64
      - 10.67.0.105/32
      - fdf6:9420:fade:67::105/128
    endpoint: 10.42.42.5:51869
    persistentKeepaliveInterval: 5s
up: true
addresses:
  - address: 10.67.0.106/32
  - address: fdf6:9420:fade:67::106/128
routes:
  # voltzahl
  - destination: 10.41.6.0/24
  - destination: 2001:cafe:41:6::/64
  - destination: 10.67.0.100/32
  - destination: fdf6:9420:fade:67::5/128
  - destination: fdf6:9420:fade:67::100/128
  # theta
  - destination: 10.41.2.0/24
  - destination: 2001:cafe:41:2::/64
  - destination: 10.67.0.101/32
  - destination: fdf6:9420:fade:67::4/128
  - destination: fdf6:9420:fade:67::101/128
  # beta
  - destination: 10.41.1.0/24
  - destination: 2001:cafe:41:1::/64
  - destination: 10.67.0.102/32
  - destination: fdf6:9420:fade:67::2/128
  - destination: fdf6:9420:fade:67::102/128
  # alpha
  - destination: 10.41.3.0/24
  - destination: 2001:cafe:41:3::/64
  - destination: 10.67.0.103/32
  - destination: fdf6:9420:fade:67::103/128
  # oduduwa
  - destination: 10.41.4.0/24
  - destination: 2001:cafe:41:4::/64
  - destination: 10.67.0.104/32
  - destination: fdf6:9420:fade:67::104/128
  # caeneus
  - destination: 10.41.5.0/24
  - destination: 2001:cafe:41:5::/64
  - destination: 10.67.0.105/32
  - destination: fdf6:9420:fade:67::105/128
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBkaith
        ekJwNTFndlV1b0ltaDVmUkVVZ3NBUTVJa3g1OUdhWU1LSlRLLzFnClYxMUNHeW5V
        UVNrbDhTYkx6VThLejVHUmZzeUE0WHl1b3NpVmFFUElvKzQKLS0tIFgyWlVTa29C
        aE9UV0ZVUVVZTEZtVHBiUEI3bitLVXdHUU90dHpaekdrbzgKKgfr6ytBvfyZLOQg
        ao86ypV3uoV9sQGsZ+yAG6gEVJBtGSHiNGNrAKfWd5FNPT6T+Hp1FcPEWCAWuCXl
        GQc7Sg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzOTJQMCtLS3FZYkhNdE1z
        WTFQS1dIK1lQaUh1L0s4bjZQRE9IM2hHT1ZBClN1UXEyMEdzWG1EbUhOTkhsUEx6
        d0RnbmFhM1luWTlzckJIN05raTFTbWMKLS0tIFgzVXU2MzZZSUNtempHcXd4Ymwx
        U29hcjZYb2Z5ZW5ubTZMQ1pKbU1qZ1kKnPVdkofPd5ZcG64p+QTCyLi1CHMJ4sT+
        uFZTJxzAhLHXguWMsatJ7CnD6n9OfeeppH9wUwo8Q5dg4tEAd4e5Lw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-10T13:17:53Z"
  mac: ENC[AES256_GCM,data:kenWzwoXt/jU+B6zvfaNfPzkvfjrDZ22WRUYMMGDRk7vfAOSVGdaUb2L4CSM/JS96Sa/ghoglbFWoOoidT4ocanUletIJa1WffHgVECbayhc1halgnmB7Mu4h9ta3AVbMlnpoGxntK2wL8Q43A7wVIsy2HKYblKLGKxbUnj3xpQ=,iv:9aXmAEHGgK7/vANfftXqbCtdtGKRtQLPFBHQw2hQ7hE=,tag:5WdP+Ey8//DGljR/QKuRcg==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
