apiVersion: v1alpha1
kind: HostnameConfig
auto: "off"
hostname: sophons-theta
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBhMlRJ
        ampqbDhzWXVYY2dyeXB5TFB2U094aU54dzI5VXU1TUVBb1VIRFVJCklyQm1Ia2RZ
        aW5ra3Z5MGU0MytLS0J0bjZ6THZ1Y0dzSWFteWdsS2Z3akEKLS0tIEdaeDBlVkxt
        VGpIODBHOS9ja3B0VXlMVjZzV2xjNmI1eWhNQ21ITkU1QWsK3HQWGHzpU6s4EeTI
        bbH1uG+tl9NzZkUFsElYI3xu/v1jkoz2/BB4MPaaYviv8NE+ObzCM6zo+f52qGav
        szrA/A==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0akkyRkdVaEFwbWxCTEtG
        T3ZCcElLMjFjM1cxK01IUTVLamozSms4MDJRCkhicldVUTlLNXMzT1ZBWWxicHMz
        ZUU0cGN5WmgrUnVvREdKdHd0dHN5ZG8KLS0tIGRIRlcwUzRMS0l3cDRSZHc0NGZh
        Rk5Wbi8waFd5d3NyTGVjQTNJb3dlNDgKjqFY6vkOIwSJXf1CbwiElxqi73YC6aEM
        mtY6nJmlBfn+e6MJyjEbes20kC0UIAXBQ/+P9TEQFkNeUhYb1tXB9g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T09:18:09Z"
  mac: ENC[AES256_GCM,data:ECfDPR/cVbJNItM1F5d46+pVsmF3Gt8wCtrnJRcNcm4wO9gKd+6y7vFV5Oe0/IS+bpup7f2OIXrJ1Od8ehgBF9xJbP0vSAhT7LHNLq/qaBuM+n3bUtuxr5qBB9uDFC329O9SUKgIIoF6dWH9ShP9rpPA6DQT+EK8aFc1JpMX8+Q=,iv:DIcPd9Vm5vSLzrOX/7E5/qlb8nCgOsAgS6ZjErnP3rw=,tag:OCbhQIoF5ljdCf+VkNCJsQ==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
cluster:
  network:
    cni:
      name: none
machine:
  install:
    disk: /dev/vda
  kubelet:
    extraMounts:
      - destination: /var/lib/longhorn
        type: bind
        source: /var/lib/longhorn
        options:
          - bind
          - rshared
          - rw
  nodeLabels:
    topology.kubernetes.io/region: nl
    topology.kubernetes.io/zone: nl-east-1
    hugeloads.sophons.cloud/garage: "true"
    cluster.garage.sophons.cloud/global: "true"
    weed.sophons.cloud/cluster: global
    weed.sophons.cloud/master: "true"
    weed.sophons.cloud/volume: "true"
  network:
    interfaces:
      - interface: enp7s0
        dhcp: false
        addresses:
          # enc!
          - ENC[AES256_GCM,data:Oc+xAZU80gQi2NcznVMsEA==,iv:KJJitO3/C+aNaooXPASAeCrq1wdzfYSgGV7bGfyKKng=,tag:JGSCD+pjv28l1IU3Rzuo5A==,type:str]
          # enc!
          - ENC[AES256_GCM,data:txRSBi0aJyU+u2gBEosC5QeJha7rBKs=,iv:02CZJ8otX5IxQw1d0JLjOHNdf288iAlPOJcun6sV99k=,tag:8mwsingzqn7cNuSq+Fc63Q==,type:str]
        routes:
          - network: 0.0.0.0/0
            # enc!
            gateway: ENC[AES256_GCM,data:Tt6RghAgq9AzLDE=,iv:62mPdngQ/xEiAqhPMXpH3+KZUWs2D5kT+Ob1sj2vaME=,tag:A0Ki6R+wVBPmbWtJaaJ3bQ==,type:str]
            metric: 150
          - network: ::/0
            gateway: fe80::1
            metric: 100
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBhMlRJ
        ampqbDhzWXVYY2dyeXB5TFB2U094aU54dzI5VXU1TUVBb1VIRFVJCklyQm1Ia2RZ
        aW5ra3Z5MGU0MytLS0J0bjZ6THZ1Y0dzSWFteWdsS2Z3akEKLS0tIEdaeDBlVkxt
        VGpIODBHOS9ja3B0VXlMVjZzV2xjNmI1eWhNQ21ITkU1QWsK3HQWGHzpU6s4EeTI
        bbH1uG+tl9NzZkUFsElYI3xu/v1jkoz2/BB4MPaaYviv8NE+ObzCM6zo+f52qGav
        szrA/A==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0akkyRkdVaEFwbWxCTEtG
        T3ZCcElLMjFjM1cxK01IUTVLamozSms4MDJRCkhicldVUTlLNXMzT1ZBWWxicHMz
        ZUU0cGN5WmgrUnVvREdKdHd0dHN5ZG8KLS0tIGRIRlcwUzRMS0l3cDRSZHc0NGZh
        Rk5Wbi8waFd5d3NyTGVjQTNJb3dlNDgKjqFY6vkOIwSJXf1CbwiElxqi73YC6aEM
        mtY6nJmlBfn+e6MJyjEbes20kC0UIAXBQ/+P9TEQFkNeUhYb1tXB9g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T09:18:09Z"
  mac: ENC[AES256_GCM,data:ECfDPR/cVbJNItM1F5d46+pVsmF3Gt8wCtrnJRcNcm4wO9gKd+6y7vFV5Oe0/IS+bpup7f2OIXrJ1Od8ehgBF9xJbP0vSAhT7LHNLq/qaBuM+n3bUtuxr5qBB9uDFC329O9SUKgIIoF6dWH9ShP9rpPA6DQT+EK8aFc1JpMX8+Q=,iv:DIcPd9Vm5vSLzrOX/7E5/qlb8nCgOsAgS6ZjErnP3rw=,tag:OCbhQIoF5ljdCf+VkNCJsQ==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
# https://tailscale.com/docs/reference/best-practices/performance#linux-optimizations-for-subnet-routers-and-exit-nodes
apiVersion: v1alpha1
kind: EthernetConfig
name: enp7s0
features:
  rx-gro-list: "off"
  rx-udp-gro-forwarding: "on"
# ---
# apiVersion: v1alpha1
# kind: VolumeConfig
# name: EPHEMERAL
# provisioning:
#   maxSize: 100GiB
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBhMlRJ
        ampqbDhzWXVYY2dyeXB5TFB2U094aU54dzI5VXU1TUVBb1VIRFVJCklyQm1Ia2RZ
        aW5ra3Z5MGU0MytLS0J0bjZ6THZ1Y0dzSWFteWdsS2Z3akEKLS0tIEdaeDBlVkxt
        VGpIODBHOS9ja3B0VXlMVjZzV2xjNmI1eWhNQ21ITkU1QWsK3HQWGHzpU6s4EeTI
        bbH1uG+tl9NzZkUFsElYI3xu/v1jkoz2/BB4MPaaYviv8NE+ObzCM6zo+f52qGav
        szrA/A==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0akkyRkdVaEFwbWxCTEtG
        T3ZCcElLMjFjM1cxK01IUTVLamozSms4MDJRCkhicldVUTlLNXMzT1ZBWWxicHMz
        ZUU0cGN5WmgrUnVvREdKdHd0dHN5ZG8KLS0tIGRIRlcwUzRMS0l3cDRSZHc0NGZh
        Rk5Wbi8waFd5d3NyTGVjQTNJb3dlNDgKjqFY6vkOIwSJXf1CbwiElxqi73YC6aEM
        mtY6nJmlBfn+e6MJyjEbes20kC0UIAXBQ/+P9TEQFkNeUhYb1tXB9g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T09:18:09Z"
  mac: ENC[AES256_GCM,data:ECfDPR/cVbJNItM1F5d46+pVsmF3Gt8wCtrnJRcNcm4wO9gKd+6y7vFV5Oe0/IS+bpup7f2OIXrJ1Od8ehgBF9xJbP0vSAhT7LHNLq/qaBuM+n3bUtuxr5qBB9uDFC329O9SUKgIIoF6dWH9ShP9rpPA6DQT+EK8aFc1JpMX8+Q=,iv:DIcPd9Vm5vSLzrOX/7E5/qlb8nCgOsAgS6ZjErnP3rw=,tag:OCbhQIoF5ljdCf+VkNCJsQ==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
apiVersion: v1alpha1
kind: WireguardConfig
name: wg.kluster
# publicKey: bg+Z4libGo+HGAC9UrWbooWkOI4+eZ5OAqw+8rPn9AA=
# enc!
privateKey: ENC[AES256_GCM,data:IHA0X8SeJ0hfqFMdg3uufdHJP+0RccfSnwgBs9b1JZDSR0Qs0cqwRHHDB14=,iv:MwtkAdhgaepxgYvjjxlU1NOQsoAV1zmGhKNVZEVypoA=,tag:60dame4NbgVUNFGucFSGww==,type:str]
listenPort: 51869
peers:
  # voltzahl
  - publicKey: hVSo5per13c8V9b5wUTAOGp0/W32rkKfSVZSctlqujU=
    allowedIPs:
      - 10.41.6.0/24
      - 2001:cafe:41:6::/64
      - 10.67.0.100/32
      - fdf6:9420:fade:67::5/128
      - fdf6:9420:fade:67::100/128
    # enc!
    endpoint: ENC[AES256_GCM,data:LDBzgNppsfteMVfjmKDyeKU2CFjfIms1tLUT,iv:xIN+NWVXSRzHqmub4iQUNV50gPTIKViSbfjnwuXXNyc=,tag:/WrVVz0S0JVQJSyNleMCZA==,type:str]
    persistentKeepaliveInterval: 30s
  # beta
  - publicKey: mmTxsL60iWtsBx6+aMkxx2Of7g/exHTU9pXrinc1wlQ=
    allowedIPs:
      - 10.41.1.0/24
      - 2001:cafe:41:1::/64
      - 10.67.0.102/32
      - fdf6:9420:fade:67::2/128
      - fdf6:9420:fade:67::102/128
    persistentKeepaliveInterval: 5s
  # alpha
  - publicKey: C/tFptmbSV+HBQYxzsTKUFW4LsPVcQyCNEfr8esvQ3w=
    allowedIPs:
      - 10.41.3.0/24
      - 2001:cafe:41:3::/64
      - 10.67.0.103/32
      - fdf6:9420:fade:67::103/128
    persistentKeepaliveInterval: 5s
  # oduduwa
  - publicKey: gobYpIEfo5paRPdkJ+Jnqcm9TyD+J2I4+Ry5AU0UhAQ=
    allowedIPs:
      - 10.41.4.0/24
      - 2001:cafe:41:4::/64
      - 10.67.0.104/32
      - fdf6:9420:fade:67::104/128
    # enc!
    endpoint: ENC[AES256_GCM,data:RS+Ue1bpFzEvfzUl3ULU+vEn810=,iv:jFCcMvf57JTWFXysywUYQX9zE32FbpE4kAEgCGgMcxI=,tag:hwC0sByMqGfJmbDfPYWCEg==,type:str]
    persistentKeepaliveInterval: 30s
  # caeneus
  - publicKey: l43bJSBEBDAc9vn+v9z2Zt/vsJRimWwyOwvHfHJrWkQ=
    allowedIPs:
      - 10.41.5.0/24
      - 2001:cafe:41:5::/64
      - 10.67.0.105/32
      - fdf6:9420:fade:67::105/128
    persistentKeepaliveInterval: 5s
  # prime
  - publicKey: 2jXr8tfBYrc3tBSvDweM2mJGAsPp6Sd/T2wCBss2fGU=
    allowedIPs:
      - 10.41.0.0/24
      - 2001:cafe:41::/64
      - 10.67.0.106/32
      - fdf6:9420:fade:67::106/128
    persistentKeepaliveInterval: 5s
up: true
addresses:
  - address: 10.67.0.101/32
  - address: fdf6:9420:fade:67::4/128
  - address: fdf6:9420:fade:67::101/128
routes:
  # voltzahl
  - destination: 10.41.6.0/24
  - destination: 2001:cafe:41:6::/64
  - destination: 10.67.0.100/32
  - destination: fdf6:9420:fade:67::5/128
  - destination: fdf6:9420:fade:67::100/128
  # beta
  - destination: 10.41.1.0/24
  - destination: 2001:cafe:41:1::/64
  - destination: 10.67.0.102/32
  - destination: fdf6:9420:fade:67::2/128
  - destination: fdf6:9420:fade:67::102/128
  # alpha
  - destination: 10.41.3.0/24
  - destination: 2001:cafe:41:3::/64
  - destination: 10.67.0.103/32
  - destination: fdf6:9420:fade:67::103/128
  # oduduwa
  - destination: 10.41.4.0/24
  - destination: 2001:cafe:41:4::/64
  - destination: 10.67.0.104/32
  - destination: fdf6:9420:fade:67::104/128
  # caeneus
  - destination: 10.41.5.0/24
  - destination: 2001:cafe:41:5::/64
  - destination: 10.67.0.105/32
  - destination: fdf6:9420:fade:67::105/128
  # prime
  - destination: 10.41.0.0/24
  - destination: 2001:cafe:41::/64
  - destination: 10.67.0.106/32
  - destination: fdf6:9420:fade:67::106/128
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBhMlRJ
        ampqbDhzWXVYY2dyeXB5TFB2U094aU54dzI5VXU1TUVBb1VIRFVJCklyQm1Ia2RZ
        aW5ra3Z5MGU0MytLS0J0bjZ6THZ1Y0dzSWFteWdsS2Z3akEKLS0tIEdaeDBlVkxt
        VGpIODBHOS9ja3B0VXlMVjZzV2xjNmI1eWhNQ21ITkU1QWsK3HQWGHzpU6s4EeTI
        bbH1uG+tl9NzZkUFsElYI3xu/v1jkoz2/BB4MPaaYviv8NE+ObzCM6zo+f52qGav
        szrA/A==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0akkyRkdVaEFwbWxCTEtG
        T3ZCcElLMjFjM1cxK01IUTVLamozSms4MDJRCkhicldVUTlLNXMzT1ZBWWxicHMz
        ZUU0cGN5WmgrUnVvREdKdHd0dHN5ZG8KLS0tIGRIRlcwUzRMS0l3cDRSZHc0NGZh
        Rk5Wbi8waFd5d3NyTGVjQTNJb3dlNDgKjqFY6vkOIwSJXf1CbwiElxqi73YC6aEM
        mtY6nJmlBfn+e6MJyjEbes20kC0UIAXBQ/+P9TEQFkNeUhYb1tXB9g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T09:18:09Z"
  mac: ENC[AES256_GCM,data:ECfDPR/cVbJNItM1F5d46+pVsmF3Gt8wCtrnJRcNcm4wO9gKd+6y7vFV5Oe0/IS+bpup7f2OIXrJ1Od8ehgBF9xJbP0vSAhT7LHNLq/qaBuM+n3bUtuxr5qBB9uDFC329O9SUKgIIoF6dWH9ShP9rpPA6DQT+EK8aFc1JpMX8+Q=,iv:DIcPd9Vm5vSLzrOX/7E5/qlb8nCgOsAgS6ZjErnP3rw=,tag:OCbhQIoF5ljdCf+VkNCJsQ==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
