apiVersion: v1alpha1
kind: HostnameConfig
auto: "off"
hostname: sophons-theta
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBhYWQz
        SmlURFBqMGZYWS8rb1h5c25mM1RiS2kvNVFDK0xFVGFHcy93SUhRCnV6TXlBL05D
        UDFRR3VQUUNRK1c2VFpNUmZzZEUyT1Q1WjF0SHVLUENHZFkKLS0tIDc4ZVZNazIr
        OXpLYi9aTEJTQ2RZcUNxTmhDRzJoUlVhSjNSVFJ5dFhDZE0KDGvZp79BIk+nN/8H
        pJEBxAo7qJRb6e/pocf4GubI6l6hvd0DJRMxpWcNX/h7yabqvSIfpQYVbNpK9A3R
        bXGOzw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFMTArM3VUb2oxUWJTYTNC
        VnZqUjN0cWhlRXBuOVhQSHRzZUZqdzlFbjJzClVUTWZ0QVRhcXRNcmlHUlY2Ym1L
        ci9WSWZmaFdFZzdhODE4N2dLZ3dGZkkKLS0tIGNBS3djNCs2ZjlqK2hKZ01BV0t3
        NHFac05ybDhNc3lhUW9CT29XdWlQQ3MKpUgc3NZyFjLOd2VHQvRzT9SeGpEJiww2
        byt4k2Sas4TIHqLddNAAlt6HDmVPTuP9NJtTHqFU7f6DyWqwCDMXZA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-16T07:54:54Z"
  mac: ENC[AES256_GCM,data:+ifOmm9Hoql3k6bMK1Bhe6geRRd0YSva7uzPaxG1LfzlKoYV91BZvNYcF+bjiAwv/xbJquAZcdNBZFmkhGCXGdP9R+hYGCOb4XYepZORtzC8UzsUdKcUo8CgD1RGVw8mZZhSZS8SSh6CdU7CUkWHLTRLqim76czU+bMvFOBvna0=,iv:+nzIgDt5F94jv+AKgTywexNa0BaKaT5ZR9tCgNPK4sE=,tag:ayOELTMaDhA5EG9895S+Dw==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
cluster:
  network:
    cni:
      name: none
machine:
  install:
    disk: /dev/vda
  nodeLabels:
    topology.kubernetes.io/region: nl
    topology.kubernetes.io/zone: nl-east-1
    hugeloads.sophons.cloud/garage: "true"
    cluster.garage.sophons.cloud/global: "true"
    weed.sophons.cloud/cluster: global
    weed.sophons.cloud/master: "true"
    weed.sophons.cloud/volume: "true"
  network:
    interfaces:
      - interface: enp7s0
        dhcp: false
        addresses:
          # enc!
          - ENC[AES256_GCM,data:1F7sf3mOZgj/Pip5xu2bMw==,iv:kpmfinEYalTM/Nxp4oYIghLFZOaP1NCTZs+PRskqcxs=,tag:S2B+lhqJ/Fi/xA8xVqwo3g==,type:str]
          # enc!
          - ENC[AES256_GCM,data:ixUkZT2BXAXbU6qZP/OjDQVOAoigJRE=,iv:0m6z1rjIEJplO36NdKIVc2KbJWcC+kBauCokEIHyPfk=,tag:fdQvW5Ovrm49STKYuCz+0A==,type:str]
        routes:
          - network: 0.0.0.0/0
            # enc!
            gateway: ENC[AES256_GCM,data:Cjghexrj3PcNu+I=,iv:6kDHtcDKFXuAdU2i7ljBub8mwhTBTidl22TT6cbM444=,tag:0e/vwEca6/lMC+g2HSsFKw==,type:str]
            metric: 150
          - network: ::/0
            gateway: fe80::1
            metric: 100
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBhYWQz
        SmlURFBqMGZYWS8rb1h5c25mM1RiS2kvNVFDK0xFVGFHcy93SUhRCnV6TXlBL05D
        UDFRR3VQUUNRK1c2VFpNUmZzZEUyT1Q1WjF0SHVLUENHZFkKLS0tIDc4ZVZNazIr
        OXpLYi9aTEJTQ2RZcUNxTmhDRzJoUlVhSjNSVFJ5dFhDZE0KDGvZp79BIk+nN/8H
        pJEBxAo7qJRb6e/pocf4GubI6l6hvd0DJRMxpWcNX/h7yabqvSIfpQYVbNpK9A3R
        bXGOzw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFMTArM3VUb2oxUWJTYTNC
        VnZqUjN0cWhlRXBuOVhQSHRzZUZqdzlFbjJzClVUTWZ0QVRhcXRNcmlHUlY2Ym1L
        ci9WSWZmaFdFZzdhODE4N2dLZ3dGZkkKLS0tIGNBS3djNCs2ZjlqK2hKZ01BV0t3
        NHFac05ybDhNc3lhUW9CT29XdWlQQ3MKpUgc3NZyFjLOd2VHQvRzT9SeGpEJiww2
        byt4k2Sas4TIHqLddNAAlt6HDmVPTuP9NJtTHqFU7f6DyWqwCDMXZA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-16T07:54:54Z"
  mac: ENC[AES256_GCM,data:+ifOmm9Hoql3k6bMK1Bhe6geRRd0YSva7uzPaxG1LfzlKoYV91BZvNYcF+bjiAwv/xbJquAZcdNBZFmkhGCXGdP9R+hYGCOb4XYepZORtzC8UzsUdKcUo8CgD1RGVw8mZZhSZS8SSh6CdU7CUkWHLTRLqim76czU+bMvFOBvna0=,iv:+nzIgDt5F94jv+AKgTywexNa0BaKaT5ZR9tCgNPK4sE=,tag:ayOELTMaDhA5EG9895S+Dw==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
# https://tailscale.com/docs/reference/best-practices/performance#linux-optimizations-for-subnet-routers-and-exit-nodes
apiVersion: v1alpha1
kind: EthernetConfig
name: enp7s0
features:
  rx-gro-list: "off"
  rx-udp-gro-forwarding: "on"
# ---
# apiVersion: v1alpha1
# kind: VolumeConfig
# name: EPHEMERAL
# provisioning:
#   maxSize: 100GiB
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBhYWQz
        SmlURFBqMGZYWS8rb1h5c25mM1RiS2kvNVFDK0xFVGFHcy93SUhRCnV6TXlBL05D
        UDFRR3VQUUNRK1c2VFpNUmZzZEUyT1Q1WjF0SHVLUENHZFkKLS0tIDc4ZVZNazIr
        OXpLYi9aTEJTQ2RZcUNxTmhDRzJoUlVhSjNSVFJ5dFhDZE0KDGvZp79BIk+nN/8H
        pJEBxAo7qJRb6e/pocf4GubI6l6hvd0DJRMxpWcNX/h7yabqvSIfpQYVbNpK9A3R
        bXGOzw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFMTArM3VUb2oxUWJTYTNC
        VnZqUjN0cWhlRXBuOVhQSHRzZUZqdzlFbjJzClVUTWZ0QVRhcXRNcmlHUlY2Ym1L
        ci9WSWZmaFdFZzdhODE4N2dLZ3dGZkkKLS0tIGNBS3djNCs2ZjlqK2hKZ01BV0t3
        NHFac05ybDhNc3lhUW9CT29XdWlQQ3MKpUgc3NZyFjLOd2VHQvRzT9SeGpEJiww2
        byt4k2Sas4TIHqLddNAAlt6HDmVPTuP9NJtTHqFU7f6DyWqwCDMXZA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-16T07:54:54Z"
  mac: ENC[AES256_GCM,data:+ifOmm9Hoql3k6bMK1Bhe6geRRd0YSva7uzPaxG1LfzlKoYV91BZvNYcF+bjiAwv/xbJquAZcdNBZFmkhGCXGdP9R+hYGCOb4XYepZORtzC8UzsUdKcUo8CgD1RGVw8mZZhSZS8SSh6CdU7CUkWHLTRLqim76czU+bMvFOBvna0=,iv:+nzIgDt5F94jv+AKgTywexNa0BaKaT5ZR9tCgNPK4sE=,tag:ayOELTMaDhA5EG9895S+Dw==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
