apiVersion: v1alpha1
kind: HostnameConfig
auto: "off"
hostname: sophons-voltzahl
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBWcXRU
        cnlRVXgramNNTVhQSU1NdkoxNUpHcjJhcWFucWVDMzQvSldZWGowCjRYY0JrQTRZ
        bUdtWHI3enozMXhhbTN3VksrWnZNaWdEeXZjUU1TSThOK2cKLS0tIEpHQVZOTDBK
        OGtQd3VWTXU5WjhEMnNVMk4xYlJCK3pRN3BvY2VWeXl0VW8KcCxvqDQwsRSHCXa1
        Xqpr+a3Bkb0sNvIZw1X52ybpD1E6UOpEa+3dJ10NdP2yrsA9J8ZYYl4HnUFrKPC3
        nd8tgA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dGlGR0JvUlV5NU92MmRs
        QnVjckJ3KzR0NkQ5dFpuOWZVU2xYVFpJZXpNCitlYWhNMmpLRG9WSTAvNUdpVCtm
        T2tTcHQxTlUyRnNJU0RISkh1bVZLQ1EKLS0tIHIvRXY1TjVVRFdxZmFUbjVYaFky
        OVVoV21CQTNlclovdHB4NStBViswMzAKvS/iE8wGugnl2ge2DoOuZoVdbfNgAwHj
        aQD11jmEgzkukMjY0FIvrSbQW89vlMnMaUCUD20kYUsnPVMIo+qNjw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-27T19:40:45Z"
  mac: ENC[AES256_GCM,data:f4sQ2UoVyI5qiH5bWG8Ez4t1jmU+IG5K/ETvl6foZNf5y3Y7j+zXCaC7F+7LZBTAh0pyxgZzss7rcGdsmaEA9iFYgczmfRDoYheqbgxS3Ytc3SRpLPtBGv/raAlfwcE4MJZDH6wfHDfIhBWUXkH2cHajoLX3tDjrircrM6zbOhg=,iv:PX0pkKpsHVRZY93QPBMLPklpLyTqfcWikZozWIzDtDo=,tag:PCBXDAEjwRIPOcfsMMfBrw==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
cluster:
  network:
    cni:
      name: none
  apiServer:
    resources:
      requests:
        # 10 (arm64) CORES WHOOOHOOOOO (my wallet will never recover from this)
        cpu: 1000m
      limits:
        memory: 3Gi
machine:
  install:
    disk: /dev/vda
  nodeLabels:
    topology.kubernetes.io/region: de
    topology.kubernetes.io/zone: de-east-1
    hugeloads.sophons.cloud/garage: "true"
    cluster.garage.sophons.cloud/global: "true"
    weed.sophons.cloud/cluster: global
    weed.sophons.cloud/master: "true"
    weed.sophons.cloud/volume: "true"
  network:
    interfaces:
      - interface: enp7s0
        dhcp: false
        addresses:
          # enc!
          - ENC[AES256_GCM,data:PC8mzGGGXUJAqxXE8VA=,iv:mME2yqKylCa0oS5BBgyyn84iAOwi91Q8WIfiu2SPFBQ=,tag:jsUNU/MPxiHmOKEslHiKpA==,type:str]
          # enc!
          - ENC[AES256_GCM,data:I2Iabuu6VgMygdy5jNZnpCy7qu9l3g==,iv:HR/GUTsbndPsZawAYnEeMlJGeJVP+ZF7GGJzmMqwlPs=,tag:kF+uz+Cyam7DnpY5nCSlUQ==,type:str]
        routes:
          - network: 0.0.0.0/0
            # enc!
            gateway: ENC[AES256_GCM,data:qAkUT+Tq9K0fvQ==,iv:HIRTC7OFCLidFgMBDlQZutZyCKzm3W4hodtSZsZURDg=,tag:PC73F1gkUZMyVdeHyjtTbA==,type:str]
            metric: 150
          - network: ::/0
            gateway: fe80::1
            metric: 100
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBWcXRU
        cnlRVXgramNNTVhQSU1NdkoxNUpHcjJhcWFucWVDMzQvSldZWGowCjRYY0JrQTRZ
        bUdtWHI3enozMXhhbTN3VksrWnZNaWdEeXZjUU1TSThOK2cKLS0tIEpHQVZOTDBK
        OGtQd3VWTXU5WjhEMnNVMk4xYlJCK3pRN3BvY2VWeXl0VW8KcCxvqDQwsRSHCXa1
        Xqpr+a3Bkb0sNvIZw1X52ybpD1E6UOpEa+3dJ10NdP2yrsA9J8ZYYl4HnUFrKPC3
        nd8tgA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dGlGR0JvUlV5NU92MmRs
        QnVjckJ3KzR0NkQ5dFpuOWZVU2xYVFpJZXpNCitlYWhNMmpLRG9WSTAvNUdpVCtm
        T2tTcHQxTlUyRnNJU0RISkh1bVZLQ1EKLS0tIHIvRXY1TjVVRFdxZmFUbjVYaFky
        OVVoV21CQTNlclovdHB4NStBViswMzAKvS/iE8wGugnl2ge2DoOuZoVdbfNgAwHj
        aQD11jmEgzkukMjY0FIvrSbQW89vlMnMaUCUD20kYUsnPVMIo+qNjw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-27T19:40:45Z"
  mac: ENC[AES256_GCM,data:f4sQ2UoVyI5qiH5bWG8Ez4t1jmU+IG5K/ETvl6foZNf5y3Y7j+zXCaC7F+7LZBTAh0pyxgZzss7rcGdsmaEA9iFYgczmfRDoYheqbgxS3Ytc3SRpLPtBGv/raAlfwcE4MJZDH6wfHDfIhBWUXkH2cHajoLX3tDjrircrM6zbOhg=,iv:PX0pkKpsHVRZY93QPBMLPklpLyTqfcWikZozWIzDtDo=,tag:PCBXDAEjwRIPOcfsMMfBrw==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
# https://tailscale.com/docs/reference/best-practices/performance#linux-optimizations-for-subnet-routers-and-exit-nodes
apiVersion: v1alpha1
kind: EthernetConfig
name: enp7s0
features:
  rx-gro-list: "off"
  rx-udp-gro-forwarding: "on"
# ---
# apiVersion: v1alpha1
# kind: VolumeConfig
# name: EPHEMERAL
# provisioning:
#   maxSize: 100GiB
# ---
# apiVersion: v1alpha1
# kind: ExtensionServiceConfig
# name: tailscale
# environment:
#   # - TS_ROUTES=10.41.6.0/24,2001:cafe:41:6::/64,fdf6:9420:fade:67::5/128
#   - TS_ROUTES=10.41.6.0/24,2001:cafe:41:6::/64
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBWcXRU
        cnlRVXgramNNTVhQSU1NdkoxNUpHcjJhcWFucWVDMzQvSldZWGowCjRYY0JrQTRZ
        bUdtWHI3enozMXhhbTN3VksrWnZNaWdEeXZjUU1TSThOK2cKLS0tIEpHQVZOTDBK
        OGtQd3VWTXU5WjhEMnNVMk4xYlJCK3pRN3BvY2VWeXl0VW8KcCxvqDQwsRSHCXa1
        Xqpr+a3Bkb0sNvIZw1X52ybpD1E6UOpEa+3dJ10NdP2yrsA9J8ZYYl4HnUFrKPC3
        nd8tgA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dGlGR0JvUlV5NU92MmRs
        QnVjckJ3KzR0NkQ5dFpuOWZVU2xYVFpJZXpNCitlYWhNMmpLRG9WSTAvNUdpVCtm
        T2tTcHQxTlUyRnNJU0RISkh1bVZLQ1EKLS0tIHIvRXY1TjVVRFdxZmFUbjVYaFky
        OVVoV21CQTNlclovdHB4NStBViswMzAKvS/iE8wGugnl2ge2DoOuZoVdbfNgAwHj
        aQD11jmEgzkukMjY0FIvrSbQW89vlMnMaUCUD20kYUsnPVMIo+qNjw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-27T19:40:45Z"
  mac: ENC[AES256_GCM,data:f4sQ2UoVyI5qiH5bWG8Ez4t1jmU+IG5K/ETvl6foZNf5y3Y7j+zXCaC7F+7LZBTAh0pyxgZzss7rcGdsmaEA9iFYgczmfRDoYheqbgxS3Ytc3SRpLPtBGv/raAlfwcE4MJZDH6wfHDfIhBWUXkH2cHajoLX3tDjrircrM6zbOhg=,iv:PX0pkKpsHVRZY93QPBMLPklpLyTqfcWikZozWIzDtDo=,tag:PCBXDAEjwRIPOcfsMMfBrw==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
