apiVersion: v1alpha1
kind: HostnameConfig
auto: "off"
hostname: sophons-voltzahl
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBsSENN
        NFdmTUJOWStBcTVKRUFQRlI1SHJWaXp4ODhSdUJ3czdUNDFEaWtrCjRCbnVaazhs
        V1F1L0JVSzhuaFhkM2xxUjZncm5hTU1jOGFCL1RkQXhHdUUKLS0tIE1KK0FDa3NK
        bzhWdmw4RzNBeHlkZFdzdmw3enBMKzdHLzd5NEdiV25zNHcKTKWjy1crp630BJo+
        MM9sb+YE/5Fs8RJGB02N0mCBF42Lg8t7EQ21ZbejGz0e52HqAbsGDDtxBtspYVKq
        CW1HhQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3WTJGN2phUVltVXovMC85
        YUpXMmI2QmY3Q0dWRXdqVXM5ZG9EbXNPSERvCjlTa09rVTlBMFZUSSswRXFqYjcw
        aTlKb092N2RXZ2ttQ29HM25JV3pwTm8KLS0tIEhMRnRMWVl4Q2dTb2hLWkNPUEFX
        ZWJISDhwS0c1NXRNNUMrWjVsSTE2d3MK1iK7ChsGNiNWQFKQPnxhtLxzxfiRgAjK
        YCBnkBsOLh1e7biHYhDuhn1BY4B0NvRY9cE3rmk8v1Ku5fZql044Rw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-10T19:27:25Z"
  mac: ENC[AES256_GCM,data:BgAQaF/Fc7JAQXzhirHXbZqu/837eom+Pldy93ViWd2b1vmq62BD+bShyNp6jpUGa7byWzML/9HbbJhArGh103RxVybM7zLvsY9RPyZ/nmAM+LOS/JaMRM+NwetcxRQyKwm5EdDnslQyQ4AjHCmsN2fwy1J+2wc2lz6c511H6LA=,iv:tDIoIvl2Pzrw8FU6YDxxjXG6TNJQcB6REc5fpxW6heo=,tag:fmLtbE5k70WhBGqGJlookg==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
cluster:
  network:
    cni:
      name: none
  apiServer:
    extraArgs:
      # bias to keep more connnections on this guy?
      goaway-chance: ".000001"
    resources:
      requests:
        # 10 (arm64) CORES WHOOOHOOOOO (my wallet will never recover from this)
        cpu: 500m
        memory: 2Gi
      limits:
        memory: 3Gi
machine:
  install:
    disk: /dev/vda
  nodeLabels:
    topology.kubernetes.io/region: de
    topology.kubernetes.io/zone: de-east-1
    hugeloads.sophons.cloud/garage: "true"
    cluster.garage.sophons.cloud/global: "true"
    weed.sophons.cloud/cluster: global
    weed.sophons.cloud/master: "true"
    weed.sophons.cloud/volume: "true"
    weed.sophons.cloud/filer: "true"
  network:
    interfaces:
      - interface: enp7s0
        dhcp: false
        addresses:
          # enc!
          - ENC[AES256_GCM,data:dLrV5a7PxoKqK3+QMRs=,iv:kASCWfQvwoF5hsyA8J1OZRKptiJ/8VMevX8tEOGINDo=,tag:5Ifp74Gee/ulHQcvmgLSvw==,type:str]
          # enc!
          - ENC[AES256_GCM,data:vDAXsuEkiRjO48NAdnUiUjVg8qmwig==,iv:2pypLG4g3Zxux/EnMiBMNCkjPxZ47mRJ1uMCamVUTuw=,tag:94Yi4jfdzzzQ7NkEpTrdZw==,type:str]
        routes:
          - network: 0.0.0.0/0
            # enc!
            gateway: ENC[AES256_GCM,data:OTMSG2XmuUdyXw==,iv:XwrR9//OsaQRc62zjC1/QQLJVpEOnIa2k/ifuKdVwLc=,tag:9Hu0yWyJUtnp8LnupqfESQ==,type:str]
            metric: 150
          - network: ::/0
            gateway: fe80::1
            metric: 100
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBsSENN
        NFdmTUJOWStBcTVKRUFQRlI1SHJWaXp4ODhSdUJ3czdUNDFEaWtrCjRCbnVaazhs
        V1F1L0JVSzhuaFhkM2xxUjZncm5hTU1jOGFCL1RkQXhHdUUKLS0tIE1KK0FDa3NK
        bzhWdmw4RzNBeHlkZFdzdmw3enBMKzdHLzd5NEdiV25zNHcKTKWjy1crp630BJo+
        MM9sb+YE/5Fs8RJGB02N0mCBF42Lg8t7EQ21ZbejGz0e52HqAbsGDDtxBtspYVKq
        CW1HhQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3WTJGN2phUVltVXovMC85
        YUpXMmI2QmY3Q0dWRXdqVXM5ZG9EbXNPSERvCjlTa09rVTlBMFZUSSswRXFqYjcw
        aTlKb092N2RXZ2ttQ29HM25JV3pwTm8KLS0tIEhMRnRMWVl4Q2dTb2hLWkNPUEFX
        ZWJISDhwS0c1NXRNNUMrWjVsSTE2d3MK1iK7ChsGNiNWQFKQPnxhtLxzxfiRgAjK
        YCBnkBsOLh1e7biHYhDuhn1BY4B0NvRY9cE3rmk8v1Ku5fZql044Rw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-10T19:27:25Z"
  mac: ENC[AES256_GCM,data:BgAQaF/Fc7JAQXzhirHXbZqu/837eom+Pldy93ViWd2b1vmq62BD+bShyNp6jpUGa7byWzML/9HbbJhArGh103RxVybM7zLvsY9RPyZ/nmAM+LOS/JaMRM+NwetcxRQyKwm5EdDnslQyQ4AjHCmsN2fwy1J+2wc2lz6c511H6LA=,iv:tDIoIvl2Pzrw8FU6YDxxjXG6TNJQcB6REc5fpxW6heo=,tag:fmLtbE5k70WhBGqGJlookg==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
---
# https://tailscale.com/docs/reference/best-practices/performance#linux-optimizations-for-subnet-routers-and-exit-nodes
apiVersion: v1alpha1
kind: EthernetConfig
name: enp7s0
features:
  rx-gro-list: "off"
  rx-udp-gro-forwarding: "on"
# ---
# apiVersion: v1alpha1
# kind: VolumeConfig
# name: EPHEMERAL
# provisioning:
#   maxSize: 100GiB
# ---
# apiVersion: v1alpha1
# kind: ExtensionServiceConfig
# name: tailscale
# environment:
#   # - TS_ROUTES=10.41.6.0/24,2001:cafe:41:6::/64,fdf6:9420:fade:67::5/128
#   - TS_ROUTES=10.41.6.0/24,2001:cafe:41:6::/64
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBsSENN
        NFdmTUJOWStBcTVKRUFQRlI1SHJWaXp4ODhSdUJ3czdUNDFEaWtrCjRCbnVaazhs
        V1F1L0JVSzhuaFhkM2xxUjZncm5hTU1jOGFCL1RkQXhHdUUKLS0tIE1KK0FDa3NK
        bzhWdmw4RzNBeHlkZFdzdmw3enBMKzdHLzd5NEdiV25zNHcKTKWjy1crp630BJo+
        MM9sb+YE/5Fs8RJGB02N0mCBF42Lg8t7EQ21ZbejGz0e52HqAbsGDDtxBtspYVKq
        CW1HhQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3WTJGN2phUVltVXovMC85
        YUpXMmI2QmY3Q0dWRXdqVXM5ZG9EbXNPSERvCjlTa09rVTlBMFZUSSswRXFqYjcw
        aTlKb092N2RXZ2ttQ29HM25JV3pwTm8KLS0tIEhMRnRMWVl4Q2dTb2hLWkNPUEFX
        ZWJISDhwS0c1NXRNNUMrWjVsSTE2d3MK1iK7ChsGNiNWQFKQPnxhtLxzxfiRgAjK
        YCBnkBsOLh1e7biHYhDuhn1BY4B0NvRY9cE3rmk8v1Ku5fZql044Rw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-10T19:27:25Z"
  mac: ENC[AES256_GCM,data:BgAQaF/Fc7JAQXzhirHXbZqu/837eom+Pldy93ViWd2b1vmq62BD+bShyNp6jpUGa7byWzML/9HbbJhArGh103RxVybM7zLvsY9RPyZ/nmAM+LOS/JaMRM+NwetcxRQyKwm5EdDnslQyQ4AjHCmsN2fwy1J+2wc2lz6c511H6LA=,iv:tDIoIvl2Pzrw8FU6YDxxjXG6TNJQcB6REc5fpxW6heo=,tag:fmLtbE5k70WhBGqGJlookg==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
