http:
  # Add the router
  routers:
    router0:
      entryPoints:
        - web
      service: service-foo
      rule: PathPrefix(`/0`)
    router1:
      entryPoints:
        - web
      service: service-foo
      rule: PathPrefix(`/1`)
    router2:
      entryPoints:
        - web
      service: service-foo
      rule: PathPrefix(`/2`)

  # Add the middleware
  middlewares:
    cilium-trustedips:
      plugin:
        cilium-trustedips:
          logLevel: DEBUG
          staticTrustedCIDRs: ["10.41.0.0/16"]
          endpointLabelSelector:
            app.kubernetes.io/name: cloudflared
          cidrGroupLabelSelector:
            trusted-reverse-proxy: "true"

  # Add the service
  services:
    service-foo:
      loadBalancer:
        servers:
          - url: http://localhost:8080/
