apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gimmich-postgres
  namespace: immich
spec:
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:18.3-1.1.1
  instances: 1

  affinity:
    nodeSelector:
      kubernetes.io/hostname: sophons-caeneus
    tolerations:
      - key: caeneus.sophons.cloud
        operator: Exists

  postgresql:
    parameters:
      shared_buffers: "256MB"
      max_wal_size: "256MB"
      min_wal_size: "64MB"
      wal_keep_size: "512MB"
    shared_preload_libraries:
      - vchord.so

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      memory: 1Gi

  storage:
    storageClass: local-path
    size: 1Ti # ignored

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: pgbooze
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: gimmich-postgres-app
  namespace: immich
spec:
  name: app
  owner: app
  cluster:
    name: gimmich-postgres

  extensions:
    - name: cube
      ensure: present
    - name: vector
      ensure: present
    - name: vchord
      ensure: present
    - name: earthdistance
      ensure: present
