# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.35.2/service.json
apiVersion: v1
kind: Service
metadata:
  name: wgexporter
  namespace: kube-system
spec:
  ports:
    - port: 9069
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: wgexporter
    app.kubernetes.io/instance: klusterexporter
