apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  labels:
    app.kubernetes.io/name: dragonfly
    app.kubernetes.io/instance: dragonfly-zenlesszonezot
    app.kubernetes.io/part-of: dragonfly-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: dragonfly-operator
  name: dragonfly-zenlesszonezot
spec:
  replicas: 1
  args:
    - --s3_endpoint=s3-global.garage.svc.cluster.local:3900
    - --s3_use_https=false
    - --maxmemory=256MiB
    - --proactor_threads=1
    - --cache_mode
  env:
    - name: AWS_REGION
      valueFrom:
        secretKeyRef:
          name: dragoonfly-s3-global-access-key
          key: AWS_REGION
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: dragoonfly-s3-global-access-key
          key: AWS_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: dragoonfly-s3-global-access-key
          key: AWS_SECRET_ACCESS_KEY
  snapshot:
    cron: "*/30 * * * *" # every 30 minutes
    dir: "s3://dragoonfly/zenlesszonezot"

  affinity:
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: zot
                app.kubernetes.io/instance: dragonfly-zenlesszonezot
            topologyKey: topology.kubernetes.io/zone

  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 272Mi
