apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: zenlesszonezot
  namespace: zzzot
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "OCI Registry 2: Electric Boogaloo"
    gethomepage.dev/icon: zot-registry.svg
    gethomepage.dev/name: Zot
    gethomepage.dev/app: zot
    gethomepage.dev/group: Code & Packages
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
      sectionName: websecure

  hostnames:
    - zenlesszonezot.sophons.cloud
    - oci.sophons.cloud
    - z3.sphns.run
    - pz3.sphns.run
    - oci.sphns.run
    - poci.sphns.run

  rules:
    - backendRefs:
        - name: zenlesszonezot
          port: 5000
        # - group: traefik.io
        #   kind: TraefikService
        #   name: zenlesszonezot
