apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: zenlesszonezot
  namespace: zzzot
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: zot
      app.kubernetes.io/instance: zenlesszonezot
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: redis-z3
  namespace: zzzot
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: redis-z3
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: redis-z3-sentinel
  namespace: zzzot
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: redis-z3-sentinel
