apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisReplication
metadata:
  name: redis-z3
  namespace: zzzot
spec:
  clusterSize: 3

  redisExporter:
    enabled: true
    image: quay.io/oliver006/redis_exporter:v1.82.0-alpine
    resources:
      requests:
        cpu: 10m
        memory: 16Mi
      limits:
        cpu: 25m
        memory: 64Mi

  kubernetesConfig:
    image: ghcr.io/valkey-io/valkey:8.1.6-alpine
    resources:
      requests:
        cpu: 10m
        memory: 16Mi
      limits:
        cpu: 100m
        memory: 64Mi

  # affinity:
  #   podAffinity:
  #     preferredDuringSchedulingIgnoredDuringExecution:
  #       - weight: 100
  #         podAffinityTerm:
  #           labelSelector:
  #             matchLabels:
  #               app.kubernetes.io/name: zot
  #               app.kubernetes.io/instance: zenlesszonezot
  #           topologyKey: topology.kubernetes.io/zone

  topologySpreadConstraints:
    - labelSelector:
        matchLabels:
          app: redis-z3
      maxSkew: 1
      minDomains: 3
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
    - labelSelector:
        matchLabels:
          app: redis-z3
      maxSkew: 1
      minDomains: 3
      topologyKey: topology.kubernetes.io/region
      whenUnsatisfiable: DoNotSchedule

  storage:
    volumeClaimTemplate:
      metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 100Mi
