apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisSentinel
metadata:
  name: redis-z3
  namespace: zzzot
spec:
  clusterSize: 3
  redisSentinelConfig:
    redisReplicationName: redis-z3

  redisExporter:
    enabled: true
    image: quay.io/oliver006/redis_exporter:v1.82.0-alpine
    resources:
      requests:
        cpu: 10m
        memory: 16Mi
      limits:
        cpu: 25m
        memory: 64Mi

  kubernetesConfig:
    image: quay.io/opstree/redis-sentinel:v8.6.2
    resources:
      requests:
        cpu: 10m
        memory: 16Mi
      limits:
        cpu: 50m
        memory: 32Mi

  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: redis-z3
          topologyKey: topology.kubernetes.io/zone

  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    fsGroup: 1000
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: [ALL]
