apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-z3
  namespace: zzzot
spec:
  selector:
    matchLabels:
      app: redis-z3
      app.kubernetes.io/component: metrics
  endpoints:
    - port: redis-exporter
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-z3-sentinel
  namespace: zzzot
spec:
  selector:
    matchLabels:
      app: redis-z3-sentinel
      app.kubernetes.io/component: metrics
  endpoints:
    - port: redis-exporter
