apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: zenlesszonezot
  namespace: zzzot
spec:
  weighted:
    services:
      - name: zenlesszonezot
        port: zot
        strategy: leasttime
        nativeLB: false
        scheme: https
        serversTransport: zenlesszonezot
