apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: zenlesszonezot
  namespace: zzzot
spec:
  weighted:
    services:
      - name: zenlesszonezot
        port: 5000
        strategy: leasttime
        nativeLB: false
