image:
  # repository: ghcrd.sphns.run/project-zot/zot
  # repository: docker.io/vrtxdotsh/project-zot--zot
  # tag: main-55b68228dadd603089af8e709009e200505ccd0f
  # repository: ghcrd.sphns.run/tehlordvortex/project-zot/zot
  # pullPolicy: Never
  repository: pz3.sphns.run/project-zot/zot
  tag: dev-fcf89d20-1@sha256:731c4ab34da477b6ff0880ba6435677c3e1b593bec49a1aaefb45fa4ffc8e7cb # 2.1.18 + commits from main

replicaCount: 2
podDisruptionBudget:
  enabled: true
  minAvailable: 1

affinity:
  podAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          namespaces: [alpha-centauri-system]
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: valkey
              app.kubernetes.io/instance: valkeyrie
          topologyKey: topology.kubernetes.io/zone

  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
            - key: kubernetes.io/hostname
              operator: NotIn
              values: [sophons-oduduwa]
        weight: 69
      - preference:
          matchExpressions:
            - key: cluster.garage.sophons.cloud/global
              operator: In
              values: ["true"]
        weight: 68
      - preference:
          matchExpressions:
            - key: topology.kubernetes.io/region
              operator: NotIn
              values: [ng]
        weight: 67

topologySpreadConstraints:
  - labelSelector:
      matchLabels:
        app.kubernetes.io/name: zot
        app.kubernetes.io/instance: zenlesszonezot
    maxSkew: 1
    minDomains: 2
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: DoNotSchedule
    matchLabelKeys: [pod-template-hash]

hostAliases:
  - ip: 10.43.0.69
    hostnames:
      - s3-global.sphns.run
  - ip: 2001:cafe:43::69
    hostnames:
      - s3-global.sphns.run

service:
  type: ClusterIP
  trafficDistribution: PreferClose
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

persistence: false
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    memory: 400Mi
startupProbe:
  failureThreshold: 120

podSecurityContext:
  runAsUser: 65532
  runAsGroup: 65532
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop: [ALL]

env:
  - name: GOGC
    value: "10"
  - name: GOMEMLIMIT
    valueFrom:
      resourceFieldRef:
        resource: limits.memory
externalSecrets:
  - secretName: z3
    mountPath: /secrets/z3
extraVolumeMounts:
  - name: tmp
    subPath: config
    mountPath: /etc/zot
  - name: tmp
    subPath: zot
    mountPath: /tmp

extraVolumes:
  - name: config-templ
    configMap:
      name: zenlesszonezot
  - name: tmp
    emptyDir: {}

initContainers:
  - name: template-config
    # image: ghcrd.sphns.run/tehlordvortex/alpine/envsubst:3.24.1@sha256:9a8e0760a2068d86c0583332a809664c2051d489faa409c079f41a6e888f78ae
    image: pz3.sphns.run/alpine/envsubst:3.24.1@sha256:e54a472f3c276ca68cbb45886b05b61f72b9364b916ed4018c5346304593c887
    # imagePullPolicy: Never
    command:
      - sh
      - -c
      - |
        set -xeuo pipefail
        envsubst '$B2_ACCESS_KEY_ID $B2_SECRET_ACCESS_KEY $GARAGE_ACCESS_KEY_ID $GARAGE_SECRET_ACCESS_KEY' \
          < /etc/zot.templ/config.json > /etc/zot/config.json

    env:
      - name: B2_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: trisolaris-access-key
            key: AWS_ACCESS_KEY_ID
      - name: B2_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: trisolaris-access-key
            key: AWS_SECRET_ACCESS_KEY
      - name: GARAGE_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: z3-access-key
            key: AWS_ACCESS_KEY_ID
      - name: GARAGE_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: z3-access-key
            key: AWS_SECRET_ACCESS_KEY

    volumeMounts:
      - name: config-templ
        mountPath: /etc/zot.templ
      - name: tmp
        subPath: config
        mountPath: /etc/zot

    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop: [ALL]

    resources:
      requests:
        memory: 1Mi
      limits:
        memory: 16Mi

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    basicAuth: null
