image:
  # repository: ghcrd.sphns.run/project-zot/zot
  repository: docker.io/vrtxdotsh/project-zot--zot
  tag: main-55b68228dadd603089af8e709009e200505ccd0f

replicaCount: 3
affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
            - key: cluster.garage.sophons.cloud/global
              operator: In
              values: ["true"]
        weight: 100

  # podAffinity:
  #   preferredDuringSchedulingIgnoredDuringExecution:
  #     - weight: 25
  #       podAffinityTerm:
  #         labelSelector:
  #           matchLabels:
  #             app: redis-z3
  #         topologyKey: topology.kubernetes.io/zone

hostAliases:
  - ip: 10.43.0.69
    hostnames:
      - s3-global.sphns.run
  - ip: 2001:cafe:43::69
    hostnames:
      - s3-global.sphns.run

service:
  type: ClusterIP
  trafficDistribution: PreferClose
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

persistence: false
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    memory: 350Mi
startupProbe:
  initialDelaySeconds: 30
  failureThreshold: 120

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop: [ALL]
  seccompProfile:
    type: RuntimeDefault

env:
  - name: GOGC
    value: "25"
  - name: GOMEMLIMIT
    valueFrom:
      resourceFieldRef:
        resource: limits.memory
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: z3
        key: AWS_ACCESS_KEY_ID
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: z3
        key: AWS_SECRET_ACCESS_KEY
externalSecrets:
  - secretName: z3
    mountPath: /secrets/z3
extraVolumeMounts:
  - name: config
    mountPath: /etc/zot
  - name: tmp
    mountPath: /tmp/zot

extraVolumes:
  - name: config
    configMap:
      name: zenlesszonezot
  - name: tmp
    emptyDir: {}

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    basicAuth: null
