apiVersion: cloudflared-operator.vrtx.sh/v1alpha1
kind: CfdTunnel
metadata:
  name: forge-of-creation
  namespace: forgejo
spec:
  serviceMonitor: {}
  dns:
    externalDNS:
      kind:
        generated:
          endpoints:
            - dnsName: tig.vrtx.sh

  accountId: 93814820f122031e8f5004eb893430f0
  apiToken:
    secretRef:
      name: cf-dns-api-token
      namespace: default
    key: api-token

  serviceRef:
    name: forge-of-creation-forgejo-http
  ingress:
    - service: https://traefik.traefik.svc.cluster.local
  originRequestConfig: |
    matchSNItoHost: true
    http2Origin: true

  containerOverrides:
    name: cloudflared
    resources:
      requests:
        cpu: 25m
        memory: 32Mi
      limits:
        memory: 48Mi
