apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations: [kustomizeconfig.yaml]
namespace: forgejo
resources:
  - middleware.yaml
  - helmrelease.yaml
  - ../garage/access-keys/infinity-and-beyond
components:
  - ../../common/litestream
  - ../../common/litestream/templ-config

secretGenerator:
  - name: forge-of-creation-forgejo-config
    envs: [.env]
  - name: forge-of-creation-forgejo-authelia-config
    envs: [.authelia.oauth.env]

vars:
  - name: LITESTREAM_ENV_CONFIGMAP
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: litestream-env
  - name: LITESTREAM_CONFIG_CONFIGMAP
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: litestream-config
  - name: INFINITY_AND_BEYOND_ACCESS_KEY_SECRET
    objref:
      apiVersion: v1
      kind: Secret
      name: infinity-and-beyond-access-key
  - name: FORGE_OF_CREATION_FORGEJO_CONFIG_SECRET
    objref:
      apiVersion: v1
      kind: Secret
      name: forge-of-creation-forgejo-config
  - name: FORGE_OF_CREATION_FORGEJO_AUTHELIA_CONFIG_SECRET
    objref:
      apiVersion: v1
      kind: Secret
      name: forge-of-creation-forgejo-authelia-config
