# yaml-language-server: $schema=https://code.forgejo.org/forgejo-helm/forgejo-helm/raw/tag/v17.1.1/values.schema.json
valkey-cluster:
  enabled: false
valkey:
  enabled: false
postgresql:
  enabled: false
postgresql-ha:
  enabled: false

image:
  rootless: true

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
            - key: cluster.garage.sophons.cloud/global
              operator: In
              values: ["true"]
        weight: 100

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    memory: 512Mi

persistence:
  enabled: false
  subPath: fs

extraVolumes:
  - name: litestream-config
    configMap:
      name: litestream-config
  - name: juicefs-cache
    hostPath:
      path: /var/lib/garage/juicefs/cache

extraContainerVolumeMounts:
  - name: data
    subPath: db
    mountPath: /db

extraInitVolumeMounts:
  - name: data
    subPath: db
    mountPath: /db
  - name: data
    subPath: forgejo
    mountPath: /tmp

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  fsGroupChangePolicy: "OnRootMismatch"
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

replicaCount: 1
deployment:
  terminationGracePeriodSeconds: 120
  env:
    - name: GOMEMLIMIT
      valueFrom:
        resourceFieldRef:
          resource: limits.memory
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: infinity-and-beyond-access-key
          key: AWS_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: infinity-and-beyond-access-key
          key: AWS_SECRET_ACCESS_KEY

# Prevent the services from being headless
service:
  http:
    clusterIP: null
    ipFamilyPolicy: RequireDualStack
    ipFamilies:
      - IPv4
      - IPv6
  ssh:
    clusterIP: null
    ipFamilyPolicy: RequireDualStack
    ipFamilies:
      - IPv4
      - IPv6

httpRoute:
  enabled: true
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "Git Repository"
    gethomepage.dev/icon: forgejo.svg
    gethomepage.dev/name: Forgejo
    gethomepage.dev/app: forgejo
    gethomepage.dev/group: Code & Packages
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
      sectionName: websecure

  hostnames:
    - tig.vrtx.sh

tcpRoute:
  enabled: true
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
      sectionName: ssh

gitea:
  admin:
    username: vrtx
    email: me@vrtx.sh
    passwordMode: initialOnlyRequireReset

  oauth:
    - name: authelia
      provider: openidConnect
      existingSecret: forge-of-creation-forgejo-authelia-config
      iconUrl: https://auth.sophons.cloud/favicon.ico
      autoDiscoverUrl: https://auth.sophons.cloud/.well-known/openid-configuration
      skipLocal-2fa: true
      scopes: email profile groups sshpubkey
      attributeSshPublicKey: sshpubkey
      groupClaimName: groups

  config:
    log:
      LEVEL: trace

    server:
      DOMAIN: tig.vrtx.sh
      SSH_DOMAIN: ssh.tig.vrtx.sh
      ROOT_URL: https://tig.vrtx.sh/
      OFFLINE_MODE: true
      LFS_START_SERVER: true

    service:
      NO_REPLY_ADDRESS: noreply.tig.vrtx.sh
      DISABLE_REGISTRATION: true

    openid:
      WHITELISTED_URIS: "auth.sophons.cloud"

    cache:
      ADAPTER: redis
    queue:
      TYPE: redis
    session:
      PROVIDER: db

    database:
      DB_TYPE: sqlite3
      SQLITE_TIMEOUT: 15000
      SQLITE_JOURNAL_MODE: wal
      PATH: /db/gitea.v2.db

    storage:
      STORAGE_TYPE: minio
      SERVE_DIRECT: true
      MINIO_ENDPOINT: s3-global.sphns.run
      MINIO_USE_SSL: true
      MINIO_BUCKET: forge-of-creation
      MINIO_LOCATION: global
    "storage.attachments":
      SERVE_DIRECT: true
      MINIO_BASE_PATH: attachments/
    "storage.lfs":
      SERVE_DIRECT: true
      MINIO_BASE_PATH: lfs/
    "storage.avatars":
      MINIO_BASE_PATH: avatars/
    "storage.repo-avatars":
      MINIO_BASE_PATH: repo-avatars/
    "storage.repo-archive":
      SERVE_DIRECT: true
      MINIO_BASE_PATH: repo-archive/
    "storage.packages":
      SERVE_DIRECT: true
      MINIO_BASE_PATH: packages/
    "storage.actions_log":
      SERVE_DIRECT: true
      MINIO_BASE_PATH: actions_log/
    "storage.actions_artifacts":
      SERVE_DIRECT: true
      MINIO_BASE_PATH: actions_artifacts/

    actions:
      ENABLED: false

    packages:
      CHUNKED_UPLOAD_PATH: /tmp/package-upload

    repository:
      TEMP_PATH: /tmp/uploads
    "repository.local":
      LOCAL_COPY_PATH: /tmp/local-repo

    security:
      REVERSE_PROXY_TRUSTED_PROXIES: 10.41.0.0/16,2001:cafe:41::/56

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  additionalConfigSources:
    - secret:
        secretName: forge-of-creation-forgejo-config
