apiVersion: cloudflared-operator.vrtx.sh/v1alpha1
kind: CfdTunnel
metadata:
  name: s3-global
  namespace: garage
spec:
  serviceMonitor: {}
  dns:
    externalDNS:
      kind:
        generated:
          endpoints:
            - dnsName: s3-global.sphns.run
            - dnsName: s3-global.sophons.cloud
            - dnsName: test-s3-web.sphns.run

  accountId: 93814820f122031e8f5004eb893430f0
  apiToken:
    secretRef:
      name: cf-dns-api-token
      namespace: default
    key: api-token

  serviceRef:
    name: global-garage
  ingress:
    - service: https://traefik.traefik.svc.cluster.local
  originRequestConfig: |
    matchSNItoHost: true
    http2Origin: true

  podSpecOverrides:
    priorityClassName: system-cluster-critical
    tolerations:
      - key: orunmila.sophons.cloud/ase-orun
        operator: Exists
  containerOverrides:
    name: cloudflared
    resources:
      requests:
        cpu: 25m
        memory: 48Mi
      limits:
        memory: 48Mi
