apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: s3-global
  namespace: garage
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
      sectionName: websecure

  hostnames:
    - s3-global.sophons.cloud
    - s3-global.sphns.run
    - ps3-global.sphns.run

  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /admin/health
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplaceFullPath
              replaceFullPath: /health
      backendRefs:
        - name: s3-global
          port: 3903
    - backendRefs:
        - name: s3-global
          port: 3900
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: s3ui-global
  namespace: garage
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
      sectionName: websecure

  hostnames:
    - s3ui-global.sophons.cloud
  rules:
    - filters:
        # - type: ExtensionRef
        #   extensionRef:
        #     group: traefik.io
        #     kind: Middleware
        #     name: cache
        - type: ExtensionRef
          extensionRef:
            group: traefik.io
            kind: Middleware
            name: forwardauth-authelia
      backendRefs:
        - name: global-webui
          port: 3909
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: s3web-global
  namespace: garage
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
      sectionName: websecure

  hostnames:
    - test-s3-web.sphns.run

  rules:
    - filters: []
        # - type: ExtensionRef
        #   extensionRef:
        #     group: traefik.io
        #     kind: Middleware
        #     name: cache
      backendRefs:
        - name: s3-global
          port: 3902
