apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: global-garage
  namespace: garage
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: garage
      app.kubernetes.io/instance: global
