# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.34.1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: garage
  namespace: garage
# enc!
stringData:
  rpcSecret: ENC[AES256_GCM,data:Wtks5lBQdSIPqoDxpmAqcGEBM1EE/VQK4tVMLFrGSCiiHjdEUwYCqJVhlyrw7+37+Zh1M+C4WRFb28SGt30rbQ==,iv:Ojk3ltD6l6SQIkgGnQQuBV7t5AneISoaz+YTG+RY6ew=,tag:xc6mhZyg+S04nJudsS/s/w==,type:str]
  adminTokenGlobal: ENC[AES256_GCM,data:tzdpnslz2xW1wIuhvc7tFltP/XOiCCLsupNUn16rbAlmz3SX+M9ZmA8mVhFRVZA9jrVqWpUxzf4bPRzHbdsjOohe/sM=,iv:mAhWYNEvCDORa0ehnuiRFjPBTHkI/+4ZklWhmG4MmtE=,tag:EL/EJ2Ixmhg9OkiKY4qtFg==,type:str]
  adminTokenBackup: ENC[AES256_GCM,data:Ii8Jn1dsMCbIQcDddGrMR3yTCBtMkzuN83O8CnOM1f6F/+/B/H5dRL+YGnhCZ9soSpbmqLREhUd2RQr58NmZivxMohk=,iv:HTVCfFCkiugNMahsycdjmlRSlx83f5FmUH3bmWeCCHs=,tag:DuX7gMJq9asHzrx8G8aqpw==,type:str]
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyB6Mm83
        cHUwWjU1M2M2UVZyU1VoOVNOUWFya2RpOGdMdEdZVmUvRTRXL1hjCnVzYmc1SVNa
        TkRPbUUweGptbVp1U2Z1SlBWSERHZXlkdG9xR2NuSGg4OGsKLS0tIGt1TDBKd0Y3
        TXhGUjdKWVRrWFc1TW1xbXNWKy9kSGZSdSt3YXhvRmRrRlEK6Ol0p5F3n46cV+Bz
        fzGFA20qlbtYT2eoC4ThraHquqiaj7zNrCt7v7xVAXdFOUQEQDDYOX+K1DsvvBh4
        MOcSUQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1czRIWTlNTFFvRWUvbnla
        OWpWazAxU2JUbGF5T2dUSXY5cE94ZXpWaFJjCnBrNEQ1NlpJRGNvRTFDT3dENXlT
        cXdSYVBPZ3NqVEQwOTkyTjlPNEtad1UKLS0tIHRGZXcwVGhyUUZBdlVvOElpQndS
        L3FSMlI1QlRmaFlHaVhjMmZqbjBLUFkK3SDtesKGoKo0g5MQ6ik2tXHr6YOnftSz
        RjgQuOT+5EdKgZrDfNd6J5lHXAqZJL6T5Rdqw5kKOaeBI0M+w6hlTA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T12:11:39Z"
  mac: ENC[AES256_GCM,data:IsKGyWrj44kyJASfQ4Ah74Hw6sfPb829e0K4XoPNw5jOmD1zyCdwlSuSAdSmc91e0eHSKSdrYA0dOY+7QRg7mna2RRITlxt65NDawKgLZfbZ4VZ5uPaLP9VCQiLLXl+hCjAZfQnhO5RIUEgZqLC3wp4BCbPzlY6ObLk/ThjaAN8=,iv:dmARmqhGhmtsNHPGX/WgGBvG9bSv2QftQcwVN+7n2Uo=,tag:7tc5Qky14r0QwpzywRMAeQ==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
