# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.34.1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: garage
  namespace: garage
stringData:
  # enc!
  rpcSecret: ENC[AES256_GCM,data:+KiR8EQZAguA/y71D/dnLe/UTbn83CV6HLw6QqV6a1gFfGNpRXlS2mDbMN0vKYwCxSdc2WkJXwAf4PKEeVI5gw==,iv:qVDmjvuRoD5KZRPpXf2qN4ZzMg0Mbxsxh0CjeEgbIcI=,tag:Zg/XSd8iKShKV9u2e3gQOQ==,type:str]
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBjWWlU
        bkxNNVF4RzM2c254b3BYUUMxc2w4aVEwK0xzb1FPd1dsNjZMRVhJCjlMZG9FVHhK
        byt5OU5Jc3dEczg1eldKc1RoREs0WE9oTUdqbyt1SUZEa2sKLS0tIG5RcDVERVIw
        TDJIT0g0VnJ3Nkk4WUdJUW1JVzFSMy9MOWtJRGU3ZWNUVWcKpb/5IQHUEWZBFICy
        m5eWcDDY+9VA0D7UIvCY+9oRWJ98EHik9p5McI8jyqw6WrkKWjAWeUbAM5i7bvoq
        fJuyPg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBURmJFbnQ0SjI1c0hldjlL
        aW5sU2dSUkhuUEZrY0pLRjR3ekgxTXZGR1NNCmw4bUltLytISEJBYzhCZkhHUmh1
        V1FUOVhKK1NNWElHMHY3SGhibmxRVE0KLS0tIFg5S000cDd4clE5Y2Q1ZnhVNExi
        aWg2SlZCMVoyZGJjdDhqRkVYa3liNGcKtQcp9drkI6Z3I88DTkXIxUpxBeJQT1aO
        0O0BqLXMGRtkZdQzJyzlmj18XQbsPq+/5krFr2fjDK8A8FABBg1QtA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-23T01:18:31Z"
  mac: ENC[AES256_GCM,data:dAD4qnZ6fub4t9tV4BquzsWp1/CLg2E14eoRlHkQw3CVZpF6AKwZcKeuKq/RbUV10s98vrqGhlxjPHw1+Ri6BNOD2/g2neR8wDfxbBKn9iH4mnSPGpl/2U8owpEQapG8VyhKmE5iXVhcuKSd+RbI4c9Lcv0rukwCEAGBnKTUNLs=,iv:kVSnnvBxizHrqUYRHnEj+toCoC6ZeYL1fP0u/ugA2p0=,tag:nPifffL/1MRgUJ65kKvgjA==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
