commonLabels:
  cluster.garage.sophons.cloud: global

garage:
  blockSize: "2097152" # 2MiB
  compressionLevel: "3"
  metadataAutoSnapshotInterval: "1h"
  existingRpcSecret: garage
  s3:
    api:
      region: global

persistence:
  meta:
    storageClass: local-path
    size: 1Ti # ignored
  data:
    storageClass: local-path
    size: 1Ti # ignored

image:
  repository: dxflrs/garage

resources:
  requests:
    cpu: 250m
    memory: 128Mi
  limits:
    memory: 768Mi

nodeSelector:
  hugeloads.sophons.cloud/garage: "true"
  cluster.garage.sophons.cloud/global: "true"

deployment:
  kind: StatefulSet
  replicaCount: 3

tolerations:
  - key: orunmila.sophons.cloud/ase-orun
    operator: Exists
  - key: node.kubernetes.io/not-ready
    operator: Exists
    effect: NoExecute
  - key: node.kubernetes.io/unreachable
    operator: Exists
    effect: NoExecute
  - key: node.kubernetes.io/disk-pressure
    operator: Exists
    effect: NoSchedule
  - key: node.kubernetes.io/memory-pressure
    operator: Exists
    effect: NoSchedule
  - key: node.kubernetes.io/pid-pressure
    operator: Exists
    effect: NoSchedule
  - key: node.kubernetes.io/unschedulable
    operator: Exists
    effect: NoSchedule
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: garage
            app.kubernetes.io/instance: global
        mismatchLabelKeys: [controller-revision-hash]
        topologyKey: topology.kubernetes.io/region

priorityClassName: system-node-critical

securityContext:
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault

monitoring:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  tracing:
    sink: "http://zero-order-alloy.monitoring-system:4317"
