commonLabels:
  cluster.garage.sophons.cloud: global

environment:
  - name: RUST_LOG
    value: warn

garage:
  noClusterRole: true

  blockSize: "2097152" # 2MiB
  compressionLevel: "3"
  metadataAutoSnapshotInterval: "1h"
  existingRpcSecret: garage
  s3:
    api:
      region: global
      bindAddr: "[::]:4900"
    web:
      bindAddr: "[::]:4902"

  additionalTopLevelConfig: |
    block_ram_buffer_max = "768MiB"
    block_max_concurrent_reads = 48
    block_max_concurrent_writes_per_request = 24

persistence:
  meta:
    storageClass: local-path
    size: 1Ti # ignored
  data:
    storageClass: local-path
    size: 1Ti # ignored

extraVolumes:
  - name: traefik-config
    configMap:
      name: traefik-garage-config

image:
  repository: docker.io/dxflrs/garage

resources:
  requests:
    cpu: 75m
    memory: 128Mi
  limits:
    memory: 800Mi

nodeSelector:
  hugeloads.sophons.cloud/garage: "true"
  cluster.garage.sophons.cloud/global: "true"

deployment:
  kind: StatefulSet
  replicaCount: 3

# tolerations:
#   - key: node.kubernetes.io/not-ready
#     operator: Exists
#     effect: NoExecute
#   - key: node.kubernetes.io/unreachable
#     operator: Exists
#     effect: NoExecute
#   - key: node.kubernetes.io/disk-pressure
#     operator: Exists
#     effect: NoSchedule
#   - key: node.kubernetes.io/memory-pressure
#     operator: Exists
#     effect: NoSchedule
#   - key: node.kubernetes.io/pid-pressure
#     operator: Exists
#     effect: NoSchedule
#   - key: node.kubernetes.io/unschedulable
#     operator: Exists
#     effect: NoSchedule
# affinity:
#   podAntiAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#       - labelSelector:
#           matchLabels:
#             app.kubernetes.io/name: garage
#             app.kubernetes.io/instance: global
#         mismatchLabelKeys: [controller-revision-hash]
#         topologyKey: topology.kubernetes.io/zone

priorityClassName: system-node-critical

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault
securityContext:
  allowPrivilegeEscalation: false

monitoring:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
