apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: crowdsec-bouncer
  namespace: crowdsec
spec:
  plugin:
    crowdsec-bouncer-traefik-plugin:
      enabled: true
      updateMaxFailure: -1
      httpTimeoutSeconds: 30
      logLevel: INFO
      crowdsecMode: stream
      crowdsecLapiScheme: http
      crowdsecLapiHost: crowdsec-service.crowdsec.svc.cluster.local:8080
      # crowdsecLapiTlsInsecureVerify: true
      # enc!
      crowdsecLapiKey: ENC[AES256_GCM,data:5/4G83F6h+mEUHOdbh2b9YnJXzMtq1hfnpYvYqNXlX8Ge9duzPNeqZvKC9TSmnGGKOz9gESp03K40kpmj3CL0lvLsVMNUdikafZp0Tv1pZ2DF9lXdznXg6Edzs2dydNhqhJ00+sBzD7yAcY9sMtMEWiD0DYKiy5DKAImc0UNegw=,iv:k/kdafPksJ6B1Xv3FFPqP0KAAOIT3ClmYOeq1iO3bL0=,tag:ihJ9JySCInpf0lr2ySpRSA==,type:str]
      clientTrustedIPs:
        # lokalhost
        - 127.0.0.0/8
        - ::1/128
        # kluster
        - 10.41.0.0/16
        - 2001:cafe:41::/56
      forwardedHeadersTrustedIPs:
        # lokalhost
        - 127.0.0.0/8
        - ::1/128
        # kluster
        - 10.41.0.0/16
        - 2001:cafe:41::/56
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBUZE5k
        RkQ2elltUmN5RUprUWRmNzNpSCtZZGp0cTdyZVdRTDBpRGxhS21RCjdhVGkvWGhV
        RHV6c0gwcEIrNTkxbmVqYmlnMzF1MlUxQmxVNlJZdDArZ2cKLS0tIFE1dHBuT3Vl
        QU5Fc3JQN2N0Tmo4b1VJazBmbVloeDZJcGw2dmdIdTM2eTgKU1sYJM5PUO1/8ekm
        d4DmyrkN01RALA1MB7eUx4mhbUU0zqF6E4jan5UbppeJ4qjyJiMRt7vyPksTxeQf
        AmPHUw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWlIxMm9aQ2diOHN3Tk1M
        WmlKSjBzcTU1R0RaeXU3dEw2amhNc0YzV0h3ClVoVVRGSGRiTkxvd2JwRlAzVUY4
        cHZDVXdqTnQxZC9RUk5na05iLzhmcWcKLS0tIEk0L2Y3U2xrUExPWCtyZWlObkZQ
        UllTNXROYWNkTW9RVUNLZTY1M0MrY2sKyncoTmrNhEbJ2KAsgcRoqgsKJlM5kiwE
        VYRJaXseaCQGg4truXG1zscceaTkGmOfe4rNmQEy3rAAcyMFeDaWZQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-27T06:59:01Z"
  mac: ENC[AES256_GCM,data:GAtYs/SNMBYTMn2jnTqgnEofKw4IeldLA5VUdOKqsKOJqXDR3tdlNWXv/V980szTq28gSJC3THUCIOSSE6v2VIaamDfctm/k3QkGsyZFLiEcrsspgJ/8AwPpJgSKdin4xE9huSR0Thug+91tCkOFQsoemgsUv9hpXSl9AhI6VSo=,iv:j8f0LnUmpJrZgdYYcoIlwe8dwS/iUuAwDZ9HIXrmuLI=,tag:F6zRmeHHhIBhjwshZKXNFA==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
