apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-gateway
spec:
  secretName: gateway-tls

  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: >-
        traefik,headscale,kube-system

  dnsNames:
    - "vrtx.sh"
    - "*.vrtx.sh"
    - "*.tig.vrtx.sh"

    - "vrtx.run"
    - "*.vrtx.run"

    - "sphns.run"
    - "*.sphns.run"

    - "kaos.nexus"
    - "*.kaos.nexus"

    - "sophons.cloud"
    - "*.sophons.cloud"

    - "victorakinyemi.com"
    - "*.victorakinyemi.com"

  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
