configMapGenerator:
  - name: mimir-config
    files:
      - mimir.yaml
  - name: mimir-runtime-config
    options:
      disableNameSuffixHash: true
    files:
      - mimir.yaml=mimir.runtime.yaml
