# Run Mimir in single process mode, with all components running in 1 process.
target: all,alertmanager,overrides-exporter
multitenancy_enabled: false
runtime_config:
  file: /etc/mimir/runtime/mimir.yaml
limits:
  compactor_blocks_retention_period: 3d
  query_ingesters_within: 3h

server:
  log_level: info
  http_listen_port: 9009
  grpc_server_num_workers: 16
  grpc_server_max_concurrent_streams: 25

common:
  storage:
    backend: s3
    s3:
      endpoint: ps3-global.sphns.run
      bucket_name: monitoring
      trace:
        enabled: true
      http:
        tls_handshake_timeout: 30s
        expect_continue_timeout: 30s

# Blocks storage requires a prefix when using a common object storage bucket.
blocks_storage:
  storage_prefix: mimirblocks
  tsdb:
    dir: /data/ingester
    retention_period: 3h
    close_idle_tsdb_timeout: 3h
    stripe_size: 512
    wal_compression_enabled: true
    wal_segment_size_bytes: 16777216 # 16MiB
    wal_replay_concurrency: 8
    ship_interval: 10s
    ship_concurrency: 4
    head_compaction_interval: 15s
    head_chunks_write_buffer_size_bytes: 524288 # 512KiB
    flush_blocks_on_shutdown: true
  bucket_store:
    sync_dir: /tmp/tsdb-sync
    index_cache:
      inmemory:
        max_size_bytes: 134217728 # 128MiB
    series_hash_cache_max_size_bytes: 134217728 # 128MiB
    index_header:
      lazy_loading_idle_timeout: 10m
      lazy_loading_concurrency: 4
    max_concurrent: 8
    ignore_blocks_within: 1h

querier:
  query_store_after: 2h

ruler:
  rule_path: /tmp/data-ruler
ruler_storage:
  storage_prefix: mimirruler

alertmanager:
  data_dir: /tmp/data-alertmanager
  # fallback_config_file: /etc/alertmanager-fallback-config.yaml
  external_url: http://mimir-mirage.monitoring-system:9009/alertmanager
alertmanager_storage:
  storage_prefix: mimiralertmanager

compactor:
  data_dir: /tmp/data-compactor
  cleanup_interval: 5m
  deletion_delay: 4h
distributor:
  reusable_ingester_push_workers: 16
  ring:
    kvstore:
      store: inmemory
ingester:
  ring:
    kvstore:
      store: inmemory
    replication_factor: 1
store_gateway:
  sharding_ring:
    replication_factor: 1

usage_stats:
  enabled: false

activity_tracker:
  filepath: /tmp/metrics-activity.log
