addr: ${LITESTREAM_PROMETHEUS_ADDRESS}
logging:
  level: ${LITESTREAM_LOGGING_LEVEL}

sync-interval: ${LITESTREAM_SYNC_INTERVAL}
validation:
  interval: ${LITESTREAM_VALIDATION_INTERVAL}
snapshot:
  retention: ${LITESTREAM_RETENTION}
  interval: ${LITESTREAM_SNAPSHOT_INTERVAL}

dbs:
  - path: ${LITESTREAM_DB_PATH}
    truncate-page-n: ${LITESTREAM_TRUNCATE_PAGE_N}
    replica:
      url: ${LITESTREAM_REPLICA_URL}
      auto-recover: true
