# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.35.2/cronjob-batch-v1.json
apiVersion: batch/v1
kind: CronJob
metadata:
  name: weedfs-backup-to-rclone-backup
  namespace: backup-system
  labels:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/instance: weedfs
    app.kubernetes.io/component: backup
spec:
  schedule: "0 3 * * *" # 3am daily
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: seaweedfs
        app.kubernetes.io/instance: weedfs
        app.kubernetes.io/component: backup
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: seaweedfs
            app.kubernetes.io/instance: weedfs
            app.kubernetes.io/component: backup
        spec:
          restartPolicy: OnFailure
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            seccompProfile:
              type: RuntimeDefault

          nodeSelector:
            kubernetes.io/hostname: sophons-caeneus
          tolerations:
            - key: caeneus.sophons.cloud
              operator: Exists

          initContainers:
            - name: weed-mount
              image: docker.io/chrislusf/seaweedfs:4.19
              restartPolicy: Always

              env:
                - name: DATA_CENTER
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.labels['topology.kubernetes.io/region']
                - name: GOGC
                  value: "10"
                - name: GOMEMLIMIT
                  value: 300MiB

              command:
                - sh
                - -c
                - |
                  set -xeuo pipefail
                  if mountpoint -q /tmp/weedfs; then
                    umount /tmp/weedfs || umount -f /tmp/weedfs
                  fi

                  exec weed -logtostderr=true mount -umask=000 -asyncDio \
                    -dir=/tmp/weedfs -dirAutoCreate -readOnly -cacheMetaTtlSec=60 -cacheSymlink \
                    -filer=weedfs-seaweedfs-filer-client.weed-system:8888 -filer.path=/ \
                    -concurrentReaders=16 -concurrentWriters=1 -dataCenter=$DATA_CENTER \
                    -volumeServerAccess=publicUrl

              startupProbe:
                exec:
                  command: [mountpoint, -q, /tmp/weedfs]
                initialDelaySeconds: 5
                periodSeconds: 5
                failureThreshold: 5

              volumeMounts:
                - mountPath: /tmp
                  name: tmp
                  mountPropagation: Bidirectional

              resources:
                requests:
                  cpu: 150m
                  memory: 300Mi
                limits:
                  memory: 1Gi # higher limit to avoid getting shot in the head by OOMkilla
                  # prob mem leak

              securityContext:
                runAsUser: 0
                runAsGroup: 0
                runAsNonRoot: false
                privileged: true
                readOnlyRootFilesystem: true
                capabilities:
                  drop: [ALL]
                  add: [SYS_ADMIN]

            - name: restic-forget
              image: ghcr.io/restic/restic:0.18.1
              restartPolicy: OnFailure
              args:
                - forget
                - -v
                - --host=weedfs
                - --group-by=host
                - --prune
                - --keep-within-daily=30d
              envFrom:
                - secretRef:
                    name: restic-password
              env:
                - name: RESTIC_REPOSITORY
                  value: rest:http://rclone-backup:8081/weedfs/
                - name: RESTIC_REST_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: trisolaris-access-key
                      key: AWS_ACCESS_KEY_ID
                - name: RESTIC_REST_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: trisolaris-access-key
                      key: AWS_SECRET_ACCESS_KEY

              volumeMounts:
                - mountPath: /tmp
                  name: tmp
                  subPath: backup-tmp
                - mountPath: /.cache
                  name: tmp
                  subPath: backup-cache

              securityContext:
                privileged: false
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities:
                  drop: [ALL]

          containers:
            - name: restic-backup
              image: ghcr.io/restic/restic:0.18.1
              restartPolicy: OnFailure
              args:
                - backup
                - -vv
                - --host=weedfs
                - --read-concurrency=16
                - /weedfs
              envFrom:
                - secretRef:
                    name: restic-password
              env:
                - name: RESTIC_REPOSITORY
                  value: rest:http://rclone-backup:8081/weedfs/
                - name: RESTIC_REST_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: trisolaris-access-key
                      key: AWS_ACCESS_KEY_ID
                - name: RESTIC_REST_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: trisolaris-access-key
                      key: AWS_SECRET_ACCESS_KEY

              volumeMounts:
                - mountPath: /weedfs
                  name: tmp
                  subPath: weedfs
                  mountPropagation: HostToContainer
                - mountPath: /tmp
                  name: tmp
                  subPath: backup-tmp
                - mountPath: /.cache
                  name: tmp
                  subPath: backup-cache

              securityContext:
                runAsUser: 0
                runAsGroup: 0
                runAsNonRoot: false
                privileged: false
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities:
                  drop: [ALL]

          volumes:
            - name: tmp
              emptyDir: {}
---
# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.35.2/cronjob-batch-v1.json
apiVersion: batch/v1
kind: CronJob
metadata:
  name: weedfs-backup-to-rclone-crypt-b2
  namespace: backup-system
  labels:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/instance: weedfs
    app.kubernetes.io/component: backup-crypt-b2
spec:
  schedule: "0 3 * * *" # 3am daily
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: seaweedfs
        app.kubernetes.io/instance: weedfs
        app.kubernetes.io/component: backup-crypt-b2
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: seaweedfs
            app.kubernetes.io/instance: weedfs
            app.kubernetes.io/component: backup-crypt-b2
        spec:
          restartPolicy: OnFailure
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            seccompProfile:
              type: RuntimeDefault

          affinity:
            podAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - podAffinityTerm:
                    labelSelector:
                      matchLabels:
                        app.kubernetes.io/name: rclone
                        app.kubernetes.io/instance: crypt-b2
                    namespaceSelector:
                      matchLabels:
                        kubernetes.io/metadata.name: default
                    topologyKey: topology.kubernetes.io/zone
                  weight: 100
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - preference:
                    matchExpressions:
                      - key: topology.kubernetes.io/region
                        operator: NotIn
                        values: [ng]
                  weight: 100

          initContainers:
            - name: weed-mount
              image: docker.io/chrislusf/seaweedfs:4.19
              restartPolicy: Always

              env:
                - name: DATA_CENTER
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.labels['topology.kubernetes.io/region']
                - name: GOGC
                  value: "10"
                - name: GOMEMLIMIT
                  value: 300MiB

              command:
                - sh
                - -c
                - |
                  set -xeuo pipefail
                  if mountpoint -q /tmp/weedfs; then
                    umount /tmp/weedfs || umount -f /tmp/weedfs
                  fi

                  exec weed -logtostderr=true mount -umask=000 -asyncDio \
                    -dir=/tmp/weedfs -dirAutoCreate -readOnly -cacheMetaTtlSec=60 -cacheSymlink \
                    -filer=weedfs-seaweedfs-filer-client.weed-system:8888 -filer.path=/ \
                    -concurrentReaders=16 -concurrentWriters=1 -dataCenter=$DATA_CENTER \
                    -volumeServerAccess=publicUrl

              startupProbe:
                exec:
                  command: [mountpoint, -q, /tmp/weedfs]
                initialDelaySeconds: 5
                periodSeconds: 5
                failureThreshold: 5

              volumeMounts:
                - mountPath: /tmp
                  name: tmp
                  mountPropagation: Bidirectional

              resources:
                requests:
                  cpu: 150m
                  memory: 300Mi
                limits:
                  memory: 1Gi # higher limit to avoid getting shot in the head by OOMkilla
                  # prob mem leak

              securityContext:
                runAsUser: 0
                runAsGroup: 0
                runAsNonRoot: false
                privileged: true
                readOnlyRootFilesystem: true
                capabilities:
                  drop: [ALL]
                  add: [SYS_ADMIN]

            - name: restic-forget
              image: ghcr.io/restic/restic:0.18.1
              restartPolicy: OnFailure
              args:
                - forget
                - -v
                - --host=weedfs
                - --group-by=host
                - --prune
                - --keep-within-daily=30d
              envFrom:
                - secretRef:
                    name: restic-password
              env:
                - name: RESTIC_REPOSITORY
                  value: rest:http://rclone-crypt-b2:8081/weedfs/
                - name: RESTIC_REST_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: trisolaris-access-key
                      key: AWS_ACCESS_KEY_ID
                - name: RESTIC_REST_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: trisolaris-access-key
                      key: AWS_SECRET_ACCESS_KEY

              volumeMounts:
                - mountPath: /tmp
                  name: tmp
                  subPath: backup-tmp
                - mountPath: /.cache
                  name: tmp
                  subPath: backup-cache

              securityContext:
                privileged: false
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities:
                  drop: [ALL]

          containers:
            - name: restic-backup
              image: ghcr.io/restic/restic:0.18.1
              restartPolicy: OnFailure
              args:
                - backup
                - -vv
                - --host=weedfs
                - --read-concurrency=16
                - /weedfs
              envFrom:
                - secretRef:
                    name: restic-password
              env:
                - name: RESTIC_REPOSITORY
                  value: rest:http://rclone-crypt-b2:8081/weedfs/
                - name: RESTIC_REST_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: trisolaris-access-key
                      key: AWS_ACCESS_KEY_ID
                - name: RESTIC_REST_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: trisolaris-access-key
                      key: AWS_SECRET_ACCESS_KEY

              volumeMounts:
                - mountPath: /weedfs
                  name: tmp
                  subPath: weedfs
                  mountPropagation: HostToContainer
                - mountPath: /tmp
                  name: tmp
                  subPath: backup-tmp
                - mountPath: /.cache
                  name: tmp
                  subPath: backup-cache

              securityContext:
                runAsUser: 0
                runAsGroup: 0
                runAsNonRoot: false
                privileged: false
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities:
                  drop: [ALL]

          volumes:
            - name: tmp
              emptyDir: {}
