namespace: backup-system
resources:
  - cronjob.yaml
  - ../restic-password
components:
  - ../components/images

configMapGenerator:
  - name: weed-backup
    files:
      - config/b2.replication.toml
      - config/s3.replication.toml
