image:
  tag: "12.0"

httpRoute:
  enabled: true
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Media Server
    gethomepage.dev/group: Media
    gethomepage.dev/icon: jellyfin.svg
    gethomepage.dev/name: Jellyfin
    gethomepage.dev/app: jellyfin

  parentRefs:
    - name: traefik-gateway
      namespace: traefik
      sectionName: websecure

  hostnames:
    - neptune.sophons.cloud

nodeSelector:
  kubernetes.io/hostname: sophons-caeneus
tolerations:
  - key: caeneus.sophons.cloud
    operator: Exists

resources:
  requests:
    cpu: 150m
    memory: 512Mi
  limits:
    memory: 1.5Gi

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  seccompProfile:
    type: RuntimeDefault

securityContext:
  privileged: false
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop: [ALL]
    add: [SYS_ADMIN]

# extraInitContainers:
#   - name: restore-db
#     image: docker.io/library/busybox:1.38
#     command:
#       - sh
#       - -c
#       - |-
#         set -e

#         if [ -f /numedia/jellyfin.rec.db ]; then
#           rm -f /config/data/jellyfin.db-*
#           mv /numedia/jellyfin.rec.db /config/data/jellyfin.db
#         fi

#     volumeMounts:
#       - name: config
#         mountPath: /config
#       - name: numedia
#         mountPath: /numedia

persistence:
  config:
    storageClass: local-path
  media:
    existingClaim: neptune-jellyfin-media
  cache:
    enabled: true
    storageClass: local-path

volumes:
  - name: tmp
    emptyDir: {}
  - name: numedia
    persistentVolumeClaim:
      claimName: neptune-jellyfin-numedia
  - name: hwa-kfd
    hostPath:
      type: CharDevice
      path: /dev/kfd
  - name: hwa-card
    hostPath:
      type: CharDevice
      path: /dev/dri/card2
  - name: hwa-render
    hostPath:
      type: CharDevice
      path: /dev/dri/renderD129

volumeMounts:
  - name: tmp
    mountPath: /tmp
  - name: numedia
    mountPath: /numedia
  - name: hwa-kfd
    mountPath: /dev/kfd
  - name: hwa-card
    mountPath: /dev/dri/card2
  - name: hwa-render
    mountPath: /dev/dri/renderD129
